### ISSUE TITLE
Rendering in Snapshot tests

### ISSUE THREAD

**Issue by PauliusLiekis** [petyosi/react-virtuoso#100]
Hi,

I'm having problems with GroupedVirtuoso in UnitTests. The first issue that I ran into was this:

> Error: Uncaught [Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
>     1. You might have mismatching versions of React and the renderer (such as React DOM)
>     2. You might be breaking the Rules of Hooks
>     3. You might have more than one copy of React in the same app
>     See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.]

This happens when rendering an empty list.
I made sure that the rendering of functional-components and hooks works fine. The issue seems to be specific to GroupedVirtuoso.

I tried to narrow down the issue but run into another problem:

>     TypeError: Cannot read property 'removeEventListener' of null
> 
>       46 |         elRef.current = theRef
>       47 |       } else {
>     > 48 |         elRef.current!.removeEventListener('scroll', onScroll)
>          |                        ^
>       49 |       }
>       50 |     },
>       51 |     [onScroll]
> 
>       at src/VirtuosoScroller.tsx:48:24

The latter issue was reproduced in master of react-virtuoso using the attached test:
[Snapshot.test.tsx.zip](https://github.com/petyosi/react-virtuoso/files/4510151/Snapshot.test.tsx.zip)

You will need to add these two dependencies:

 ```
"@types/react-test-renderer": "^16.9.2",
 "react-test-renderer": "^16.13.1",
```

One of the reasons why we started on this path is that sometimes we get calls to `item` and `group` with out-of-bounds indices. I don't have more details on that yet...

**Comment by petyosi** [comment]
Thanks for the report, I will give this a try.

**Comment by petyosi** [comment]
@PauliusLiekis - can you please test `0.16.1`? Let me know if you discover more issues down the road with the hook usage.

**Comment by PauliusLiekis** [comment]
Sorry for taking forever to respond. I can confirm that I no longer reproduce `removeEventListener` issue with latest code.

However, I still have the other one:
> Error: Uncaught [Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

It has something to do with passing empty array of groups to it. I haven't managed to make a small repro case for it yet :/ I'll let you know once/if I do.
