### ISSUE TITLE
using ReactDom.render occurs 'ResizeObserver loop completed with undelivered notifications.'

### ISSUE THREAD

**Issue by rmstsd** [petyosi/react-virtuoso#1005]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 

**Describe the bug**
console occurs 'ResizeObserver loop completed with undelivered notifications.'

**Reproduction**
https://codesandbox.io/s/cocky-robinson-85fmj8?file=/src/App.js

**To Reproduce**
1. Refresh the page to repeat
2. You can also scroll down and replay it
3. Look at the console to see the error message

**Expected behavior**
 No errors should be reported

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/52687004/accaee8c-c17c-4c34-af54-7bfa2fe48d0d)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows can behave unexpectedly.

**Additional context**
After my testing, I found that this problem occurs when using `ReactDom.render` in `react-dom`, but not when using `createRoot` in `react-dom/client`, which feels strange. I hope I can help you.

**Comment by petyosi** [comment]
https://github.com/petyosi/react-virtuoso/issues?q=is:issue+ResizeObserver
