### ISSUE TITLE
[BUG] Incorrect scrollTo in TableVirtuoso with let top

### ISSUE THREAD

**Issue by alex-nb** [petyosi/react-virtuoso#1007]
**Describe the bug**

```
let top = 0;

tableRef.current.getState(({ scrollTop }) => {
  top = scrollTop;
});

tableRef.current.scrollTo({
  left: 0,
  top,
  behavior: "smooth"
});
```

**scrollTo** doesn't work in that case. It still works without top or without assignment in getState

**Reproduction**
[Codesandbox](https://codesandbox.io/s/runtime-flower-pk4wqq?file=/App.js)

**To Reproduce**
1. Go to https://codesandbox.io/s/runtime-flower-pk4wqq?file=/App.js
2. Scroll right and down 
3. Click on 'Scroll' button
4. Nothing happened

**Expected behavior**
Scroll is working

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by petyosi** [comment]
What are you trying to do here? Reset horizontal scrolling? If so, using the virtuoso API makes no sense, get the element with `scrollerRef` and use the DOM API, I think that you can even omit the top value, and just pass the left one.

**Comment by alex-nb** [comment]
Yes, I already used this solution, but still it can be bug

**Comment by petyosi** [comment]
I see your point. At the moment, the component methods have guards against scrolling to the same vertical location, and don't take the horizontal one into account. 

However, calling getState is fairly expensive operation, so I would not recommend that approach even if it worked.
