### ISSUE TITLE
placeholder for not-yet-loaded rows?

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#101]
Hi, is there any way to render placeholder rows for the ones that have not yet been loaded?

For instance, I have a query that loads the first 10 rows, and tells me how many more rows are available but not yet loaded, and when I reach the bottom it loads 10 more. The problem with this approach is that the user needs to wait for the next chunk to load before they are able to scroll further.

I'd like, instead, to allow them to scroll way down to the last row, even if they are not yet loaded.

**Comment by petyosi** [comment]
I have purposely left data management out of the scope of the component, but this is totally doable. You need to build a data engine wrapper that handles the loading of data pages when scrolled to them, rendering placeholders, and refreshing the component when data arrives.

**Comment by FezVrasta** [comment]
Thanks, but I can’t use the end reached callback in this case, is that correct?

**Comment by petyosi** [comment]
No - I assume that you will use the total amount of items for `totalCount` and then use `rangeChanged` to determine if you need to load more records.

**Comment by FezVrasta** [comment]
I was thinking this library may provide something easier to use, maybe a `totalLoadedCount` property that would tell the `endReached` and `overscan` properties to use this other number rather than `totalCount` to perform their logic?

**Comment by petyosi** [comment]
`endReached` is not a solution in my head - people (and devs) can jump to different locations. using the scrollbars or the API. An external data pager is necessary to make that work.

**Comment by FezVrasta** [comment]
In my case I'm using cursor+limit pagination so the jump to different locations is not really possible, but I get your point. It's just unfortunate I'll need to reimplement most of the built-in logic to get the expected result.
