### ISSUE TITLE
While scrolling down, automatically scrollbar is jumping to the top.

### ISSUE THREAD

**Issue by mohan1140bhonu** [petyosi/react-virtuoso#1014]
**Describe the bug**
While scrolling the items from virtuoso, automatically scrollbar is jumping to top after 3 to 4 scroll attempts. This is happening after using the useWindowScroll. without this key scrollbar was not jumping. But to avoid duel scrollbar i need to use this keyword.

**Reproduction**
I cant share the code since it was a production code.

**To Reproduce**

**Expected behavior**
While scrolling down, it should not jump back to the top of the page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows can behave unexpectedly.

**Additional context**

**Comment by petyosi** [comment]
If you can't share a proper reproduction, then you can sponsor the project with an adequate amount and contact me over email - I will examine your setup and advise you accordingly.
