### ISSUE TITLE
[BUG]How do I make the container auto height

### ISSUE THREAD

**Issue by CaanDoll** [petyosi/react-virtuoso#1016]
For example, when I only have one piece of data, the blank space in the table is very ugly

Is there any way to set the maxHeight of a container? Let him lift himself up

https://codesandbox.io/p/sandbox/crimson-fire-pktqfy?file=%2FApp.js%3A4%2C32

**Comment by petyosi** [comment]
This is not supported, discussed in few other issues. Happy to accept a PR or sponsorship for the development of the feature.
