### ISSUE TITLE
[BUG] GroupedVirtuoso - scrollIntoView doesn't scroll to item under group label

### ISSUE THREAD

**Issue by MikeYermolayev** [petyosi/react-virtuoso#1019]
**Describe the bug**
So I was trying to implement keyboard navigation for grouped list but noticed that item can go under group content and it won't be scrolled into view. 

Here is a video of current behavior

https://github.com/petyosi/react-virtuoso/assets/8783498/e97816ee-41bc-47aa-a11a-3dc6e48231db

**Reproduction**
Here is a [sandbox](https://codesandbox.io/p/sandbox/eloquent-fast-vqxdq7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqo4zmo100063b6brt4vg5uy%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqo4zmo100023b6b3gcrrfhg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqo4zmo100033b6b6f0zwb0j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqo4zmo100053b6bll7mlqab%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqo4zmo100023b6b3gcrrfhg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqo4zmo100013b6bw3ai8bkm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqo4zmo100023b6b3gcrrfhg%2522%252C%2522activeTabId%2522%253A%2522clqo4zmo100013b6bw3ai8bkm%2522%257D%252C%2522clqo4zmo100053b6bll7mlqab%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqo4zmo100043b6byu63s5at%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqo4zmo100053b6bll7mlqab%2522%252C%2522activeTabId%2522%253A%2522clqo4zmo100043b6byu63s5at%2522%257D%252C%2522clqo4zmo100033b6b6f0zwb0j%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqo4zmo100033b6b6f0zwb0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

and a video of how it works on my side

https://github.com/petyosi/react-virtuoso/assets/8783498/96c48c09-208f-4b49-880d-1a403a885c91

**To Reproduce**
1. Navigate down so screen is scrolled
2. Try to navigate up

**Expected behavior**
`scrollIntoView` should take into account height of group content

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Brave

P.S. I've found a couple of similar issues but they all are closed so decided to open a new one

**Comment by petyosi** [comment]
The current implementation of scrollIntoView lets you scroll to items and groups - if I follow what you suggest, then groups would not be reachable - which I consider a valid scenario.

**Comment by MikeYermolayev** [comment]
@petyosi  I think there is some misunderstanding:

What should happen when I do `scrollIntoView({index: 0})`? Should first item of first group become visible? If yes then it's not working for me. Item stays below the group label and I'm stuck

![image](https://github.com/petyosi/react-virtuoso/assets/8783498/37abac1e-626f-4ce0-8c41-faad7f2670e7)


In a contrast when I try `scrollToIndex` I never end in a situation like this. Item to which I scroll is visible

Thanks in advance for your assistance

**Comment by MikeYermolayev** [comment]
Feels like it doesn't take into account groups size when calculating item's top. 

I was able to workaround this by providing adjusted `calculateViewLocation`:
```
const calculateViewLocation: CalculateViewLocation = ({
  itemTop,
  itemBottom,
  viewportTop,
  viewportBottom,
  locationParams: {behavior, align, ...rest},
}) => {
  // where 32 is fixed height of my group content
  if (itemTop - 32 < viewportTop) {
    return {...rest, behavior, align: align != null ? align : "start"};
  }
  if (itemBottom > viewportBottom) {
    return {...rest, behavior, align: align != null ? align : "end"};
  }
  return null;
};
```
