### ISSUE TITLE
Prop to control whether or not to Virtualize

### ISSUE THREAD

**Issue by rowrowrowrow** [petyosi/react-virtuoso#102]
Is it possible given the current props to use Virtuoso without any virtualization? I.e. something like specify a range of [0, list.length] regardless of scrolling/resizing.

For me I would like to choose whether or not to virtualize but still use Virtuoso for it's features and to keep listing things consistent.

Thanks!

**Comment by petyosi** [comment]
You can probably achieve this with a very large overscan property - haven't tested it.

**Comment by rowrowrowrow** [comment]
Yep, that seems to work. In my case I set the overscan to list.length * (expected per row/item height). So now it seems I can either set an arbitrarily high number for the row/item height to account for dynamic sizing or get a more accurate height for dynamic sized items from Virtuoso. Is the latter possible or even worth it?

**Comment by petyosi** [comment]
Not worth it, internal bounds will take care of figuring it out.

**Comment by rowrowrowrow** [comment]
Kk, thanks!
