### ISSUE TITLE
[BUG] Scroll snap prevents programmatic scrolling to items not rendered

### ISSUE THREAD

**Issue by jeffaburt** [petyosi/react-virtuoso#1021]
**Describe the bug**
When [scroll snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap) is enabled (scrollSnapType and scrollSnapAlign), `scrollTo*(...)` methods do not scroll to the right place. Disabling scroll snap restores proper scrollTo behavior.

**Reproduction**

### Scenario 1: TikTok style UI (where each item takes up full screen)
https://codesandbox.io/p/sandbox/react-virtuoso-full-height-cytgrc

- By default, the "Scroll to 1" button does not advance to index 1 when scroll snap is enabled.
- When you manually scroll to index 1 and then back to index 0, "Scroll to 1" all of a sudden works.
- It seems that when scroll snap is enabled, "scroll to" will only advance to items that are already rendered.

https://github.com/petyosi/react-virtuoso/assets/2835199/5fb37900-fb3d-436d-8a4a-db9ccf9d33ae

### Scenario 2: Normal UI where multiple items are shown on the screen
https://codesandbox.io/p/sandbox/react-virtuoso-scroll-snap-normal-height-39mt4x

- By default, the "Scroll to 50" button does not advance to index 50 when scroll snap is enabled.
- It seems that when scroll snap is enabled, "scroll to" will only advance to indexes that are already rendered.

https://github.com/petyosi/react-virtuoso/assets/2835199/8ce01db0-9941-47f4-887a-c7bc721bf706

- When you scroll to a few items past index 0, "Scroll to 0" stops working.
- It seems that when scroll snap is enabled, "scroll to" is unable to return to previous indexes that are no longer rendered.

https://github.com/petyosi/react-virtuoso/assets/2835199/2a8e2337-f836-4643-84b8-3c848d2e61c7

**To Reproduce**

1. Enable CSS scroll snap
2. Call any of the `scrollTo*(...)` methods

**Expected behavior**
The item specified should be visible on screen.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Browser: Chrome Version 120.0.6099.129

**Comment by petyosi** [comment]
While I understand why you may consider this a bug, the library has never claimed supporting scroll snap. If you're interested in exploring the underlying problem, I'm happy to accept a PR on the matters. However, I am not going to work on that by myself, as my own usage of the library has no use case for it.
