### ISSUE TITLE
[BUG] Wrong item position after scroll to index on scaled list

### ISSUE THREAD

**Issue by itwaze** [petyosi/react-virtuoso#1024]
When the list is scaled by `transform: scale()` the size of the list has wrong sizes in order to scroll to specific index. Comparing to scaled list with `font-size: clamp()`, in this way it works properly with no issues and can be scrolled to specific index.

**Reproduction**
[codesandbox](https://codesandbox.io/p/sandbox/quizzical-wind-9grymc?file=%2FApp.js%3A84%2C30)

**To Reproduce**
1) Initially you will see `font-size: clamp` implementation, try `Scroll To 1000`, you will be able to scroll to the last element.
```
fontSize: "1.27em",
// transform: "scale(1.27)",
// transformOrigin: "top center",
```
2) In order to switch to `transform: scale` implementation, comment `fontSize: "1.27em"` in line 84 and uncomment next 2 lines with:
```
// fontSize: "1.27em",
transform: "scale(1.27)",
transformOrigin: "top center",
```
then `Scroll To 1000`, you will see that it wasn't scrolled to the last one.

**Expected behavior**
Scroll to index will work even on scaled (by `transform: scale()`) list.

**Screenshots**
1) scroll to 1000 with `clamp`:
![image](https://github.com/petyosi/react-virtuoso/assets/10471508/c76c89f1-ad2a-479e-9cac-5ee847c9e5b8)

2) scroll to 1000 with 'scale':
![image](https://github.com/petyosi/react-virtuoso/assets/10471508/02342302-f45e-4209-b04f-9cb31b97217a)

**Comment by petyosi** [comment]
Yeah, I see what you're describing, but no, I don't see a way to solve this; the dimensions measured are not affected by the scaling.
