### ISSUE TITLE
[BUG] Width of fit content does not work on virtualized list

### ISSUE THREAD

**Issue by IsaacAbrahamson** [petyosi/react-virtuoso#1027]
**Describe the bug**
Setting `width: 'fit-content'` causes the virtualized list to have no width at all. I want to have a list where the width is based on the width of the largest visible item which is what `fit-content` should do. I'm not really sure this is that valid of a use case, but I don't think there should be no width at all when this is used.

**Reproduction**

[CodeSandbox](https://codesandbox.io/p/sandbox/inspiring-darkness-vn5q7y?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrpc69yu00062e67ntg6iu84%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrpc69yu00022e67f1xnsvh6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrpc69yu00032e67s67394ga%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrpc69yu00052e67ilrpq0he%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.9969150097914%252C53.0030849902086%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrpc69yu00022e67f1xnsvh6%2522%253A%257B%2522id%2522%253A%2522clrpc69yu00022e67f1xnsvh6%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrpc69yu00052e67ilrpq0he%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrpc69yu00042e67ogcq9ln8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrpc69yu00052e67ilrpq0he%2522%252C%2522activeTabId%2522%253A%2522clrpc69yu00042e67ogcq9ln8%2522%257D%252C%2522clrpc69yu00032e67s67394ga%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrpc69yu00032e67s67394ga%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**
1. Go to sandbox
2. Select both checkboxes
3. Press open list button
4. See that list has no width
5. Uncheck "Virtualized" checkbox to see how I expect it to look

**Expected behavior**

I expected the width to be the largest item that is currently visible. In my linked example I have this set to a fixed width for every item.

**Screenshots**

<details>
<summary>Screenshots</summary>

<img width="676" alt="Screenshot 2024-01-22 at 4 07 28 PM" src="https://github.com/petyosi/react-virtuoso/assets/17521691/bc0e0693-8012-47dd-9f94-a2135899f587">

<img width="671" alt="Screenshot 2024-01-22 at 4 07 55 PM" src="https://github.com/petyosi/react-virtuoso/assets/17521691/857d5391-ff73-45f7-a514-9e2bf4e5f0ea">
</details>

**Desktop (please complete the following information):**
 - OS: Mac (silicon)
 - Browser: Chrome

**Comment by petyosi** [comment]
That's not supported due to the styling of the virtualized list - to be more precise, the position: relative.
