### ISSUE TITLE
Dynamic overscan issue

### ISSUE THREAD

**Issue by rowrowrowrow** [petyosi/react-virtuoso#103]
If the overscan changes after mounting Virtuoso, e.g. from 0 to NUMBER, Virtuoso doesn't take that change into account. For me this occurs because I'm calculating the overscan based on the number of items in the list, if the list begins at 0 or changes in length it causes an error.

NOTE: encountered this as a result of https://github.com/petyosi/react-virtuoso/issues/102 but felt it was a separate issue altogether.

**Comment by petyosi** [comment]
I see - quite possible, as I never considered this value to have any reason to change. Does it work if you just put a very large number (something like `15 000 000`)?

**Comment by rowrowrowrow** [comment]
Ya it works as long as the overscan value is constant and correct. In my case, I'd like to virtualize based on the number of items in the list, which can change. But, I can imagine someone wanting to virtualize based on the contents of the list or some other dependency.

One solution for me is to always mount a new Virtuoso when the list changes, allowing me to update the overscan value with each mount... but having an empty list might be part of the usage of Virtuoso. I think a common example might be if you need a list to be empty in order for the infinite scroll to grab more values or similarly if Virtuoso mounts before the list is retrieved.

Simplest solution to me is making the overscan value dynamic, I would be willing to help and contribute as well!

**Comment by petyosi** [comment]
@rowrowrowrow this [works in v1](https://stackblitz.com/edit/react-feqrnp-mpkf92?file=example.js) (currently in beta). See #203 for instructions.
