### ISSUE TITLE
StartReached is not called if there is no modification on firstItemIndex and data

### ISSUE THREAD

**Issue by gustavomahlow** [petyosi/react-virtuoso#1037]
We use the "startReached" callback to fetch more data. What our application does is very similar to the "Prepending Items" example.

If we don't modify "data" and "firstItemIndex" values, "startReached" callback is never called again.

Sometimes we don't modify those values due to an error during request, like network error for example.

I would like to know if there is something we can do to "reset" this behavior and make the callback start being called again.

**Comment by petyosi** [comment]
Hey,

it's great that your company has chosen Virtuoso for your project. I'm happy to look into your case and help you with the integration [in exchange of a sponsorship](https://github.com/sponsors/petyosi?frequency=recurring&sponsor=petyosi).
