### ISSUE TITLE
followOutput doesn't work if total item sizes is smaller than the container size

### ISSUE THREAD

**Issue by joseph1125** [petyosi/react-virtuoso#104]
You can test it with the example of "Stick to Bottom" in https://virtuoso.dev/stick-to-bottom/ and the total and initialTopMostItemIndex as follows

![image](https://user-images.githubusercontent.com/8279406/80559679-f7386700-8a10-11ea-8233-6552627e9524.png)

**Comment by petyosi** [comment]
@joseph1125 I certainly took my time with this one, but it [seems resolved in v1](https://stackblitz.com/edit/react-tab1hw?file=example.js) (currently in beta). Installation instructions and breaking changes are linked in #203
