### ISSUE TITLE
[BUG] ResizeObserver loop completed with undelivered notifications on `Virtuoso` component render

### ISSUE THREAD

**Issue by wilomgfx** [petyosi/react-virtuoso#1043]
**Describe the bug**
When rendering a `Virtuoso` component, the following error is thrown in our dev env (webpack dev server 5.0.3).
This only happens in version [4.7.1](https://github.com/petyosi/react-virtuoso/releases/tag/v4.7.1) and [4.7.0](https://github.com/petyosi/react-virtuoso/releases/tag/v4.7.0), the issue is not present in version [4.6.3](https://github.com/petyosi/react-virtuoso/releases/tag/v4.6.3)

> Uncaught runtime errors:
> ERROR
> ResizeObserver loop completed with undelivered notifications.

**Reproduction**
FYI, I can't reproduce the issue on codesandbox, but it is the minimal amount of code I can put anywhere in our codebase to reproduce the issue.

https://codesandbox.io/p/sandbox/react-virtuoso-bug-resizeobserver-loop-error-rmdfvn?file=%2Fsrc%2FApp.js%3A10%2C15

```jsx
import { Virtuoso as VirtualList } from "react-virtuoso";

export default function MyReactVirtuosoBug() {
  const data = new Array(1000).fill(null).map((_, index) => ({ index }));
  return (
      <div style={{ height: "400px" }}>
        <VirtualList data={data} itemContent={(index) => <div>{index}</div>} />
      </div>
  );
}


```

**To Reproduce**
1. Open page containing the `MyReactVirtuosoBug` component
2. See error

**Expected behavior**
No error is thrown

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/6611491/8b4d824f-ba57-47bc-8eac-04de3bf8f0da)

**Desktop (please complete the following information):**
 - OS: Windows, iOS, Android
 - Browser: Chrome, Safari

**Additional context**
From what I could find online, it's not an actual error, but more of a warning?
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors
I have ignored it in our webpack config `overlay` property of the `client` portion of the dev server configuration.
```js
{
  overlay: {
    runtimeErrors: (error) => {
      if (error.message.includes("ResizeObserver loop completed with undelivered notifications")) {
        return false;
      }
      return true;
    },
  },
}
```

**Comment by petyosi** [comment]
Can you create a minimal sample repo with your setup?

**Comment by petyosi** [comment]
This brings nothing new to the conversation, and #1039 already exists.

**Comment by wilomgfx** [comment]
> Can you create a minimal sample repo with your setup?

Here you go https://github.com/wilomgfx/react-virtuoso-resizeobserver-bug-report

**Comment by petyosi** [comment]
Thank you for the reproduction. 

I believe that [this StackOverflow thread](https://stackoverflow.com/questions/75774800/how-to-stop-resizeobserver-loop-limit-exceeded-error-from-appearing-in-react-a) covers the possible workarounds, including the one you have mentioned (which, I believe, needs an ejection, which might not be very pleasant I guess).
