### ISSUE TITLE
[BUG] Doesn't work with MUI's Dialog

### ISSUE THREAD

**Issue by Hasan-Mir** [petyosi/react-virtuoso#1044]
**Describe the bug**
The Virtuoso component doesn't show (render) the items when rendering the component inside a MUI's `Dialog` component. This issue only happens when we use a `TransitionComponent` that changes the height of the component like `Zoom`. 
The `Grow` transition component causes an issue too and make some empty space at the end of the list when you scroll the list.

**Reproduction**
[Codesandbox](https://codesandbox.io/p/sandbox/lucid-gagarin-ddcffd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltg4nfxs00073j6fbbzpqtmc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltg4nfxs00033j6fnqvibqlc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltg4nfxs00043j6fhxujl2fq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltg4nfxs00063j6f5x6ixbeg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.534573890036754%252C52.465426109963246%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltg4nfxs00033j6fnqvibqlc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltg4nfxs00023j6fcixc7s2z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A81%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltg4nfxs00033j6fnqvibqlc%2522%252C%2522activeTabId%2522%253A%2522cltg4nfxs00023j6fcixc7s2z%2522%257D%252C%2522cltg4nfxs00063j6f5x6ixbeg%2522%253A%257B%2522id%2522%253A%2522cltg4nfxs00063j6f5x6ixbeg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltg4nfxs00053j6frt72xpv2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltg4nfxs00053j6frt72xpv2%2522%257D%252C%2522cltg4nfxs00043j6fhxujl2fq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltg4nfxs00043j6fhxujl2fq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

**To Reproduce**
1. Go to the sandbox.
2. Click on open dialog

**Expected behavior**
The list must be displayed correctly.

**Comment by petyosi** [comment]
https://github.com/petyosi/react-virtuoso/issues/542

**Comment by batu0b** [comment]
Hi @Hasan-Mir , I was having a similar problem, I am using a temporary solution in the following way, I hope it will be useful for you, I wish you a good day.
https://codesandbox.io/p/sandbox/react-virtuoso-mui-dialog-forked-nksqfj
