### ISSUE TITLE
[BUG]: ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by bigint** [petyosi/react-virtuoso#1048]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 

**Describe the bug**

Getting this error `ResizeObserver loop completed with undelivered notifications.`, caught this on Sentry after upgrading to > v4.7.1

<img width="2281" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/69431456/c3013b84-8e0c-43bc-8045-021ecdad7b8f">

**Comment by bigint** [comment]
Seems like more people facing this https://github.com/petyosi/react-virtuoso/issues/875#issuecomment-1972856295

**Comment by bigint** [comment]
The previous issue was closed 🙇🏼

**Comment by bigint** [comment]
https://github.com/petyosi/react-virtuoso/assets/69431456/f8d1d5c8-d29b-408b-95dd-d873f3839b92

@petyosi it would be great for explanation before closing the issue 🙇🏼

**Comment by petyosi** [comment]
@bigint in case you need support from me, sponsor the project.

**Comment by bigint** [comment]
@petyosi are you happy now?

**Comment by bigint** [comment]
@petyosi can you confirm you received your sponsorship?

**Comment by petyosi** [comment]
The error is harmless, so it is safe to ignore it. You can use this:

```tsx
    window.addEventListener('error', e => {
        if(e.message === 'ResizeObserver loop completed with undelivered notifications.' || 
            e.message === 'ResizeObserver loop limit exceeded') {
            e.stopImmediatePropagation();
// depending on your setup, you can also call e.preventDefault();
        }
    })
```

**Comment by bigint** [comment]
I added in the global provider

```
  useEffect(() => {
    window.addEventListener('error', (e) => {
      if (
        e.message ===
          'ResizeObserver loop completed with undelivered notifications.' ||
        e.message === 'ResizeObserver loop limit exceeded'
      ) {
        e.stopImmediatePropagation();
      }
    });
  }, []);
```

still I'm seeing this issue

**Comment by bigint** [comment]
the error is still going to Sentry

**Comment by petyosi** [comment]
I don't know what goes on then. Cancel your sponsorship, and good luck with your project.

**Comment by bigint** [comment]
Cool let me tweet about this!

**Comment by bigint** [comment]
It was a nice rug lol!
