### ISSUE TITLE
[BUG] `TableBody` in components props of `TableVirtuoso` causes rendering issue

### ISSUE THREAD

**Issue by Gumichocopengin8** [petyosi/react-virtuoso#1052]
**Describe the bug**

When `TableBody` in components props of `TableVirtuoso` is defined,  `TableVirtuoso` does not render data properly.

**Reproduction**
Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

[Code Link](https://stackblitz.com/edit/vitejs-vite-zyqdob?file=src%2FApp.tsx,src%2Fmain.tsx&terminal=dev)

Minimum code to reproduce the bug
```tsx
import { TableVirtuoso } from 'react-virtuoso';

export default function App() {
  return (
    <div>
      <TableVirtuoso
        style={{ height: 400 }}
        components={{
          TableBody: (props) => <tbody {...props} />, // comment out or uncomment this line to see the rendering bug
        }}
        data={Array.from({ length: 1000000 }).map((_, i) => ({
          name: `name ${i}`,
        }))}
        fixedHeaderContent={() => (
          <>
            <th style={{ backgroundColor: 'white' }}>Name</th>
          </>
        )}
        itemContent={(_index, user) => (
          <>
            <td>{user.name}</td>
          </>
        )}
      />
    </div>
  );
}

```

**To Reproduce**
1. First comment out `TableBody: (props) => <tbody {...props} />` line to see the expected behavior
2. Uncomment the line and refresh page, then table only renders 1 row even though there are more than 1 data
3. 

**Expected behavior**
It should show all data with `TableBody` in `components` prop.

**Screenshots**

### Unexpected 

<img width="1163" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/34010665/b0db7fed-4db3-4126-8c67-eebb8e28a202">

### Expected 

<img width="1169" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/34010665/7730907f-a56b-4c97-b272-c5d28b996a98">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - macOS
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**

**Comment by petyosi** [comment]
You need to forward the ref to the element. See the material UI table example.
