### ISSUE TITLE
[TYPE ERROR]: GridItem is missing some prop types

### ISSUE THREAD

**Issue by flbn** [petyosi/react-virtuoso#1053]
Not a bug, hence the title change. Just noticed in my project I'm missing some types for `GridItemProps`. wasn't exactly sure if this is done on purpose or not. If it's a bug, I can patch myself, just lmk. I'm type casting since it does log out as existing, and not including it actually results in an error.

Typed as this in the repo:

```
export declare interface GridItemProps {
    'data-index': number;
    className?: string;
}
```

If I log out the item props though, it is there:
<img width="450" alt="Screenshot 2024-03-28 at 12 17 49 AM" src="https://github.com/petyosi/react-virtuoso/assets/55413049/47017ce4-1612-4ca2-b7b3-82aa01fd8add">

[Docs example for VirtuosoGrid](https://virtuoso.dev/grid-responsive-columns/) actually make use of it, so looks like it's prob just been looked over?

**Comment by petyosi** [comment]
That's an omission indeed, happy to accept a PR that fixes it.

**Comment by flbn** [comment]
here's a PR sharing the same node types as the GridListProps: https://github.com/petyosi/react-virtuoso/pull/1054
