### ISSUE TITLE
[BUG] Prepending docs not there anymore

### ISSUE THREAD

**Issue by RobinGiel** [petyosi/react-virtuoso#1056]
Hi,

just wanted to point out that the docs for prepending is not there anymore.

https://virtuoso.dev/prepend-items/

**Comment by petyosi** [comment]
The prepending items was a very awkward API to begin with, as it involved keeping track of firstItemIndex, and then updating two props simultaneously. 

I've just published a new component - Virtuoso Message List, that's targeting the specifics of reverse scrolling through an imperative API. Check the docs above.
