### ISSUE TITLE
[BUG] Table scrolls to top when search params change

### ISSUE THREAD

**Issue by futurliberta** [petyosi/react-virtuoso#1057]
Hi

**Description of the bug**
With react-router-dom, when navigate or setSearchParams is used to update search params, the virtuoso table scrolls back to top.

**Reproduction**
[CodeSandbox](https://codesandbox.io/p/sandbox/determined-mountain-vpm9v8?file=%2Fsrc%2FTestTable.tsx%3A88%2C29)

**Expected behavior**
Keep the scroll position.

**Additional context**
OS: Windows 10
Browsers: Chrome 123, Edge 122

**Comment by petyosi** [comment]
This is not a bug, you're misusing the component. Read the docs.
