### ISSUE TITLE
[BUG] Not unloading no longer visible items

### ISSUE THREAD

**Issue by danielmag** [petyosi/react-virtuoso#1058]
**Describe the bug**
I am trying to migrate from react-virtualized to react-virtuoso and so far found almost everything super straightforward and was actually able to delete a bunch of code that is not longer needed with your library 🎉

One thing that seems to be working differently is that `rangeChanged` does not seem to trigger when previous elements are no longer visible when scrolling down, only when new ones need to be rendered. In virtualized I used `onRowsRendered` for this purpose and it triggered whenever previous elements where no longer visible, removing them from the DOM. Is there any way to have a similar behaviour with virtuoso? I am particularly interested in knowing reliably with is the first visible element on the list.

This especially apparent with variable sized elements (see screenshots below)

**Screenshots**
<img width="1718" alt="Screenshot 2024-04-02 at 16 04 45" src="https://github.com/petyosi/react-virtuoso/assets/6450122/b79b6504-0ca2-4064-8f79-72f2870238a3">
<img width="1714" alt="Screenshot 2024-04-02 at 16 05 42" src="https://github.com/petyosi/react-virtuoso/assets/6450122/67a5d92b-a74c-47f2-ad0e-ce09f5817e13">

**Comment by petyosi** [comment]
This has been discussed previously - search the issues. I think the github issue thread is also mentioned in the docs.

**Comment by danielmag** [comment]
@petyosi could you point me to the issue where this has been already discussed? After a further search I could not find it. Thank you!
