### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server when using Virtuoso with ssr

### ISSUE THREAD

**Issue by mdegrees** [petyosi/react-virtuoso#106]
Using Virtuoso with server side rendering raises the following warning: 

``Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.``

**Comment by petyosi** [comment]
Thanks for that, I will see if I can convert this to useEffect.
