### ISSUE TITLE
[BUG] Zero-sized element, this should not happen 

### ISSUE THREAD

**Issue by mstykow** [petyosi/react-virtuoso#1060]
**Describe the bug**
The error "zero-sized element, this should not happen" appears as of upgrading to v4.7.7. There is also a react-virtuoso internal exception along the lines of "Cannot read properties of null (reading 'dataset')".

This commit seems to have introduced the issue: https://github.com/petyosi/react-virtuoso/commit/1f8c8ee833fe1efafe4879e709316d0c4812bb9c

**Reproduction**
Use virtualized lists and click around so that the underlying data changes, i.e., re-renders/mounts/unmounts occur.

Sorry, I don't have time for a codesandbox. If you don't like that, feel free to close my report. I'm locking my version to 4.7.6.

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/46091730/68c5de96-44ea-49d8-9b47-6853a63581c2)

**Additional context**
This error has been discussed in other issues such as #433 and #206.

**Comment by petyosi** [comment]
I see you are referencing this from another open repository. Any directions on how I can reproduce it there?

**Comment by imansalhi** [comment]
same issue on nextjs 14 :react-virtuoso: Zero-sized element, this should not happen {child: section.pt-4.desktop:pt-6.desktop:first:pt-0}

i have no any other issue like data set or... just getting this error and par of list renders inside other elements of page @petyosi    "react-virtuoso": "^4.8.0",
