### ISSUE TITLE
[BUG] Unable to scroll to absolute bottom if there is a footer with position: sticky

### ISSUE THREAD

**Issue by yelnyafacee** [petyosi/react-virtuoso#1071]
**Describe the bug**
I have setup `virtuoso` with a `position: sticky;` Footer (`<ExpiredNotice />`):

CSS:
```
    "& div.virtuoso": {

        "& section:last-of-type": {

            position: "sticky",
            bottom: "16px",
            paddingLeft: "16px",
            paddingRight: "16px",
            marginTop: "30px",

        },

    }
```

CODE:
```
            <Virtuoso
                ref={ref}
                className={"virtuoso"}
                style={{
                    ....
                }}
                context={{ ... }}
                totalCount={props.messages.length}
                itemContent={
                    (index) => {

                        return (

                            <Message
                                ref={el => (allMessageRefs.current[index] = el)}
                                key={index}
                                index={index}
                                message={props.messages[index]}
                            />

                        )

                    }
                }
                headerFooterTag="section"
                components={{
                    Header: () => (
                        <loadMore />
                    ),
                    Footer: () => (
                        <ExpiredNotice />
                    )

                }}
            />
```

I want the container `<div>` (`<div data-test-id="virtuoso-scroller" ....>`) to scroll to the `absolute bottom` when button is clicked / triggered.
but it seems impossible when the `Footer` `<div>` container itself is `position: sticky;`

ScollToIndex Code:
```
  ref.current?.scrollToIndex({
      index: props.messages.length - 1,
      behavior: "instant",
  })
 ```
 the above scroll the to bottom of the `last` element of the `list`, before the `Footer` `<div>`

**Expected behavior**
To be able to scroll to the absolute bottom of the scrollable `<div>` even when the last child is a `sticky` `Footer`. Looking for a solution or just any workaround that will make it possible

**Screenshots**
![vid2121](https://github.com/petyosi/react-virtuoso/assets/16500322/c4bfb620-5730-461f-ba3f-37dc9ef38dea)

**Comment by petyosi** [comment]
The Virtuoso component does not anticipate a sticky footer element. I see that you're building a chat interface. I strongly recommend you use the VirtuosoMessageList for that purpose - it solves quite a few specifics of the chat interface, including a dedicated sticky footer component.

**Comment by yelnyafacee** [comment]
I see, thanks for the reply, `VirtuosoMessageList` will solve the issues I face above?
is there a monthly subscription pricing instead of a full year subscription? the pricing seems little expensive

**Comment by petyosi** [comment]
Yes, the scrolling API of the message list takes into account the sizing of the sticky elements. 
The pricing is yearly based. A monthly subscription does not make sense for that kind of offering.

**Comment by petyosi** [comment]
[This section of the docs](https://virtuoso.dev/virtuoso-message-list/#imperative-data-management-api) explains it.

> In the case of the message list, an updated data prop may have different underlying reasons - new incoming messages, older messages being loaded, or existing messages being updated (for example, someone liked a message). Reverse-engineering the intent from the data set is not always possible, and it's not always clear how the scroll position should be adjusted. The imperative API gives you the necessary control over the scroll position adjustment that the current data set change should cause.

**Comment by yelnyafacee** [comment]
Then what should I do with the `<VirtuosoMessageList />` `initialData={}` when I clicked the button `load More` button to load older messages? `prepend()` to the `ref`? `append` to the `ref`? does the ref even hold the `initialData`? or do I manually `prepend` / `append` to it?

**Comment by petyosi** [comment]
Follow the tutorial. It covers exactly this - the initial load data and several additional common scenarios.

**Comment by yelnyafacee** [comment]
the complete live example do not even show the complete code, imports etc, why not just use codesandbox instead?

**Comment by petyosi** [comment]
I'm sorry for wasting your time. It looks like the product and my suggestions do not work for you. Good luck finding a solution that fits your requirements.
