### ISSUE TITLE
How to specify a row in Virtuoso List so that it does not unload when scrolling

### ISSUE THREAD

**Issue by linxianxi** [petyosi/react-virtuoso#1072]
How to specify a row in Virtuoso List so that it does not unload when scrolling？
like https://github.com/clauderic/react-tiny-virtual-list?tab=readme-ov-file#prop-types stickyIndices prop

like this? https://github.com/petyosi/react-virtuoso/issues/2

**Comment by petyosi** [comment]
The grouped virtuoso does this.

**Comment by linxianxi** [comment]
@petyosi How to make it sticky after scrolling outside the area?
