### ISSUE TITLE
Prepend optimisation

### ISSUE THREAD

**Issue by uffou** [petyosi/react-virtuoso#108]
Currently, when you prepend there is twice the amount of the rendering of items.  It would be great if there is a way to prepend without any rendering or at least without rendering the old currently visible items. 

I have a case where there are videos and photos so these renders are visible and I wonder how to minimize them.

To see when the item is being rendered I put a console log inside the item function 
https://stackblitz.com/edit/react-hjsvrw?file=ExampleComponents.js

**Comment by petyosi** [comment]
Thank you, 

I think (but not sure) that this is not a problem of the component itself but rather sloppily coded demo which re-renders the component incorrectly. A few `useCallback` should fix it, will examine it and update the issue.

**Comment by uffou** [comment]
I am not sure but my best guess is that the component is rendering because the length changes once then prepending and rendering again.

**Comment by petyosi** [comment]
I was wrong, the demo is not the problem. The `adjustForPrependItems` causes the secondary (correct) render. There is one intermediate (incorrect) cycle when the users are prepended to the array. 

I am not aware of any way to avoid that properly without making the component aware of the data. This is one more use case which is specific for bottom-up scrolling, which I did not have as a use case when designing the component. 

I am leaving the issue open, but I don't have any immediate ideas on how to fix it.

**Comment by petyosi** [comment]
@uffou (sorry if double spamming) - I've done a lot of work in the area with the v1 release (in beta, see #203) - can you please check? I will re-open the issue if necessary. Cheers!
