### ISSUE TITLE
[BUG] When used in MUI's Tooltip component, extra white space will appear.

### ISSUE THREAD

**Issue by Lemonreds** [petyosi/react-virtuoso#1082]
**Describe the bug**
Using react-virtuoso in MUI's Tooltip component, extra white space appears at the bottom and the rendered options do not occupy the entire space

**Reproduction**
https://codesandbox.io/p/sandbox/sleepy-chatelet-kkl7ct

**To Reproduce**
1. Click "Open" with the mouse
2. Scroll the area

**Expected behavior**
No extra white space

**Screenshots**
<img width="339" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/23014238/c0cc1e04-0c51-42cf-b2b8-e18d8edfe52c">

**Comment by petyosi** [comment]
See https://github.com/petyosi/react-virtuoso/issues/542
