### ISSUE TITLE
[BUG] VirtuosoGrid - endReached doesn't call if data set is less then the container

### ISSUE THREAD

**Issue by dinataranis** [petyosi/react-virtuoso#1087]
**Describe the bug**
I am using `VirtuosoGrid` component with `endReached` method and if an initial data set is less then the container the `endReached` is not fired (if I switch to `Virtuoso` component `endReached` is fired)
I have checked the similar issues: 
https://github.com/petyosi/react-virtuoso/issues/919
https://github.com/petyosi/react-virtuoso/issues/924
and as I see `VirtuosoGrid` and `Virtuoso` components behave differently towards `endReached` method if the initial data set is less then the container

**Reproduction**
[Virtuoso with endReached works as expected](https://codesandbox.io/p/sandbox/virtuoso-end-reached-46qzg4)
[VirtuosoGrid with endReached the initial fire doesn't work ](https://codesandbox.io/p/sandbox/virtuoso-grid-end-reached-g2gvp4)

**Expected behavior**
I expect both `Virtuoso` and `VirtuosoGrid` to work the same way and to fire the initial `endReached` if the data set is less then the container (at least one time)

**Comment by erdemdev** [comment]
I ran into this issue too. I'm glad I checked the issues section; otherwise, I would still be struggling with it. For now, I worked around it using the Intersection Observer API.

**Comment by stuartambient** [comment]
i found that endReached doesn't trigger at all even if data is more than container.  There is nothing in the docs that confirms endReached is part of VirtuosoGrid.

**Comment by aderiushev** [comment]
same here

**Comment by prasannamestha** [comment]
+1 facing this issue. Will take a look over the weekend to see if I can raise a fix 👍

**Comment by prasannamestha** [comment]
@petyosi Browsing through the code it seems like this file `gridSystem.ts`  on line 315: `u.withLatestFrom(totalCount, hasScrolled),` uses `hasScrolled` value to trigger `endReached`. 

When the container size is greater than the list size, the `hasScrolled` value is always false and usually there is no scrolling available - hence this function will never be called. Would it be a good idea to omit the `hasScrolled` check here?

**Comment by prasannamestha** [comment]
Raised a PR: https://github.com/petyosi/react-virtuoso/pull/1166 - please take a look

**Comment by say8425** [comment]
In my case, the issue was an over-injected `increaseViewportBy`. Consider reducing the `increaseViewportBy` value or removing it altogether.

**Comment by prasannamestha** [comment]
@petyosi I believe we can close this issue now
