### ISSUE TITLE
[BUG] react-beautiful-dnd + useWindowScroll

### ISSUE THREAD

**Issue by Hodosov** [petyosi/react-virtuoso#1089]
I saw that this problem has already been fixed. but at the moment this example does not work if you use useWindowScroll
Same with hello-pangea/dnd
https://virtuoso.dev/react-beautiful-dnd/

**Comment by petyosi** [comment]
I'm afraid that I have no capacity to support the window scrolling mode integration. You can dig through the commit history, there was an example but it stopped working at some point.
