### ISSUE TITLE
react-sortable-hoc optimisations and docs help

### ISSUE THREAD

**Issue by mitchellwarr** [petyosi/react-virtuoso#109]
I currently have this version of a drag and drop sortable list working with react-virtuoso. My goal is to get this documented either here or on react-sortable-hoc docs.

If i could get some help on if there are better ways to get the index in ItemContainer, and help on whether using ItemContainer and ListContainer are even the best options to accomplish this: Then i will go to react-sortable-hoc and make a PR to add react-virtuoso docs to the ones they have already for react-virtualized, react-infinite, and tiny-react-virtual-list

Alternatively this could be added to the docs in this repo too on how to use drag and drop in the virtual list

```js
import React, { useCallback } from 'react';
import { Virtuoso } from 'react-virtuoso';
import { sortableContainer, sortableElement } from 'react-sortable-hoc';

const ItemContainerSortable = sortableElement(
  props =>  <div {...props}  />
);

const ItemContainer = props => {
  const {
    ['data-index']: index
    // I dont know if theres a better way to do this
    // but ItemContainerSortable requires an index prop to work
  } = props;
  return <ItemContainerSortable index={index} {...props} />;
};

const ListContainerSortable = sortableContainer(
  ({ listRef, children, className, style }) => (
    <div
      ref={listRef}
      className={className}
      style={style}
    >
      {children}
    </div>
  )
);

const List = props => {
  const {
    onSortEnd
  } = props;

  const ListContainer = useCallback(
    (props) => (
      <ListContainerSortable
        {...props}
        onSortEnd={onSortEnd}
      />
    ),
    [onSortEnd]
  );

  return (
    <Virtuoso
      {...props}
      ItemContainer={ItemContainer}
      ListContainer={ListContainer}
    />
  )
}
```

**Comment by petyosi** [comment]
Thank you very much for that! I will add the index to the ItemContainer props, upload an example to the site later today and update the issue. A PR to the react-sortable-hoc docs would be great!

**Comment by petyosi** [comment]
The [example is deployed to the site](https://virtuoso.dev/react-sortable-hoc/).

**Comment by upex** [comment]
Hello @petyosi , could we make this work with VirtuosoGrid?

**Comment by petyosi** [comment]
@upex - give it a try, I am not an expert in the Sortable HOC, but the grid component has the same component props exposed.

**Comment by itrare** [comment]
> I currently have this version of a drag and drop sortable list working with react-virtuoso. My goal is to get this documented either here or on react-sortable-hoc docs.
> 
> If i could get some help on if there are better ways to get the index in ItemContainer, and help on whether using ItemContainer and ListContainer are even the best options to accomplish this: Then i will go to react-sortable-hoc and make a PR to add react-virtuoso docs to the ones they have already for react-virtualized, react-infinite, and tiny-react-virtual-list
> 
> Alternatively this could be added to the docs in this repo too on how to use drag and drop in the virtual list
> 
> ```js
> import React, { useCallback } from 'react';
> import { Virtuoso } from 'react-virtuoso';
> import { sortableContainer, sortableElement } from 'react-sortable-hoc';
> 
> const ItemContainerSortable = sortableElement(
>   props =>  <div {...props}  />
> );
> 
> const ItemContainer = props => {
>   const {
>     ['data-index']: index
>     // I dont know if theres a better way to do this
>     // but ItemContainerSortable requires an index prop to work
>   } = props;
>   return <ItemContainerSortable index={index} {...props} />;
> };
> 
> const ListContainerSortable = sortableContainer(
>   ({ listRef, children, className, style }) => (
>     <div
>       ref={listRef}
>       className={className}
>       style={style}
>     >
>       {children}
>     </div>
>   )
> );
> 
> const List = props => {
>   const {
>     onSortEnd
>   } = props;
> 
>   const ListContainer = useCallback(
>     (props) => (
>       <ListContainerSortable
>         {...props}
>         onSortEnd={onSortEnd}
>       />
>     ),
>     [onSortEnd]
>   );
> 
>   return (
>     <Virtuoso
>       {...props}
>       ItemContainer={ItemContainer}
>       ListContainer={ListContainer}
>     />
>   )
> }
> ```

Hi @petyosi  thanks for such good lib. I am also implementing react sortable hoc with virtuoso, but I am having issue in typescript and don't know to fix it, if typescript example can also be added that would help everyone a lot.

@mitchellwarr if you have any example for typescript please help.

**Comment by petyosi** [comment]
@itrare post your implementation and point towards the problems you are facing.
