### ISSUE TITLE
[BUG] element disappearing when reverse scrolling in the ios

### ISSUE THREAD

**Issue by ros008** [petyosi/react-virtuoso#1094]
**Describe the bug**
There is an issue that the element disappears when reverse scrolling in the ios.
When you scroll up and down again, the element appears.
I only have an issue with ios, and android works fine. It happens with both safari and chrome. (It doesn't happen on desktop.)
I'm attaching the video.

**Reproduction**
[CodeSandbox](https://codesandbox.io/p/sandbox/react-virtuoso-ios-scolling-issue-d7smsq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrhhkjd00063b6o9qo1c7ev%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrhhkjd00023b6ooctmrqfq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrhhkjd00033b6o8nh6os4a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrhhkjd00053b6ocrz22pfs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrhhkjd00023b6ooctmrqfq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrhhkjc00013b6of78dx6ls%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clwrhhkjd00023b6ooctmrqfq%2522%252C%2522activeTabId%2522%253A%2522clwrhhkjc00013b6of78dx6ls%2522%257D%252C%2522clwrhhkjd00053b6ocrz22pfs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrhhkjd00043b6om7fudvfa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwrhhkjd00053b6ocrz22pfs%2522%252C%2522activeTabId%2522%253A%2522clwrhhkjd00043b6om7fudvfa%2522%257D%252C%2522clwrhhkjd00033b6o8nh6os4a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrhhkjd00033b6o8nh6os4a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**
1. scroll to top
2. It happens after a few attempts.

**Screenshots**

https://github.com/petyosi/react-virtuoso/assets/19823020/ae2c5236-222e-453f-ace1-16cd1885aa7a

**Mobile:**
 - IOS: 17.5.1, 16.7.8
 - chrome, safari

**Comment by leeyuchang** [comment]
I have the same problem as well.

**Comment by petyosi** [comment]
This is an inherent problem of the current virtuoso implementation. It is solved in [the MessageList](https://virtuoso.dev/virtuoso-message-list/) - give it a try.

**Comment by ros008** [comment]
So the issue won't be solved forever in Virtuoso?

**Comment by petyosi** [comment]
> So the issue won't be solved forever in Virtuoso?

It is solved in Virtuoso - in the MessageList component.

**Comment by petyosi** [comment]
@raphael-leger I'm sorry that the component and its documentation does not meet your minimal feature set requirements and your standards. This is an open-source, **MIT licensed project** which I have decided to share with the world to use - free of any limitations and obligations on my side. If something does not work for you, then you can contribute a fix, or, alternatively, fork and maintain a version that works for you. You can also build a working solution from scratch or pick any of the popular open source alternatives.
