### ISSUE TITLE
[BUG] `InitialTopMostItemIndex` causes variable height elements to blink/jump when scrolling up.

### ISSUE THREAD

**Issue by KarsonJo** [petyosi/react-virtuoso#1096]
**Describe the bug**
When `InitialTopMostItemIndex` is set to a value greater than 0, all previous elements outside the viewport (of variable height) have a certain probability of causing flickering / jumping when first rendered by scrolling up. The problem only occurs when the following conditions are met:

1. The elements are before the element set by `InitialTopMostItemIndex`.
1. The elements are of variable height.
1. The elements are rendered for the first time.

**Reproduction**
[Stackblitz](https://stackblitz.com/edit/vitejs-vite-vp3p2b?file=src%2FApp.jsx)

**To Reproduce**
1. Scroll up to previous elements.
2. See error.

**Expected behavior**
No flickering / jumping when scrolling up.

**Desktop**
 - Chrome (Windows 11)
 - Firefox (Android)

**Additional context**
This bug first appeared in version **4.7.7**. Earlier versions had no problems.

**Comment by tazaryoot** [comment]
i have the same issue

**Comment by petyosi** [comment]
v4.9.0 introduced a flag to deal with this: https://stackblitz.com/edit/vitejs-vite-sgzjbj?file=package.json,src%2FApp.jsx%3AL21. Keep in mind that you need to take care of #1049 .

**Comment by rik-iso** [comment]
Should it not apply this flag by default when it detects those three conditions? This wasted like an hour of my time before I was able to find this. At the very least, document it?
