### ISSUE TITLE
[BUG] (virtuoso-message-list) strange scrolling on ipad

### ISSUE THREAD

**Issue by septem1997** [petyosi/react-virtuoso#1106]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 

**Describe the bug**
I'm trying to use virtuoso-message-list, it's a great component, I really love it. but it will scroll strangely on iPad, not smoothly, and there may be blanks when loading old messages.

**Reproduction**

https://virtuoso.dev/virtuoso-message-list/examples/messaging/

**To Reproduce**

Just scroll on this page

**Expected behavior**

scroll works well

**Screenshots**

https://github.com/petyosi/react-virtuoso/assets/13849245/fecb19e7-83bd-47b2-8dec-6574ee61385d

**Desktop (please complete the following information):**
 - OS: ios 17 (ipad air M2)
 - Browser Safari

**Additional context**

you can also reproduce this problem by creating an iPad device in the Xcode simulator. If you don't have an iPad

<img width="824" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/13849245/5197f94b-2044-45c9-80af-ac34d50986cb">

**Comment by petyosi** [comment]
@septem1997 I managed to reproduce this on my side, will investigate. Interestingly enough, it does seem to perform better on iPhone.

**Comment by petyosi** [comment]
@septem1997 this is addressed in the latest message-list release. If you need further help with the component or discover any issues with your integration, you can contact me at petyo@virtuoso.dev.
