### ISSUE TITLE
[BUG] Inability to use a flex container as a parent or to customize viewport

### ISSUE THREAD

**Issue by ohnoah** [petyosi/react-virtuoso#1108]
**Describe the bug**
There is no way to customize the position attribute on the viewport div.

**To Reproduce**
1. Place VirtuosoTable in a flex parent. I'm using MUI. You have to set an explicit height for it to show, since the table container uses position:relative.
2. Now, if you want to place an item that is the same height as the table, you can't, because position: relative takes it out of the document flow.

**Expected behavior**
I can set position: static on the table container, and if I would be able to set position: static instead of position: absolute on the viewport (which I tried in devtools), I can fix the issue. However, there is no way customize the CSS on the viewport div.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
I am trying to add a "Add column" div which is the same height as my table and is right-aligned and sticky to the right. This seems impossible with the library as it is.

**Comment by JandenMa** [comment]
I also encountered the same issue when using Virtuoso with MUI. It is unfriendly to set a fixed height for the container, especially when there only a few rows in the table (the actual height is less than the fixed container height), it would display a blank area there.

**Comment by petyosi** [comment]
@JandenMa 
1) This bug report is invalid. All Virtuoso components work as expected in a flex container. 
2) Customizing the viewport is not supposed to be done, The element is there for measurement purposes. 
3) I'm also not sure if you're not looking for something completely unrelated.
