### ISSUE TITLE
[BUG] ScrollSeekPlaceholder in grouping mode create sticky placeholder item on the top of list

### ISSUE THREAD

**Issue by AlexxGlobenko** [petyosi/react-virtuoso#1113]
**Describe the bug**
ScrollSeekPlaceholder work not as expected in Grouped mode. When scroll fast on the top of the list appears sticky placeholder item.

**Reproduction**
```
function App() {
    const groupCounts = useMemo(() => {
        return Array(1000).fill(10);
    }, []);

    return (
        <GroupedVirtuoso
            components={{
                ScrollSeekPlaceholder: () => (
                    <div
                        style={{ width: "100%", height: "50px", backgroundColor: "yellow", border: "3px solid red" }}
                    />
                )
            }}
            style={{ height: 400 }}
            groupCounts={groupCounts}
            scrollSeekConfiguration={{
                enter: (velocity) => Math.abs(velocity) > 500,
                exit: (velocity) => Math.abs(velocity) < 200,
                change: (_, range) => console.log({ range })
            }}
            groupContent={(index) => {
                return (
                    <div style={{ backgroundColor: "var(--ifm-color-content-inverse)" }}>
                        Group {index * 10} - {index * 10 + 10}
                    </div>
                );
            }}
            itemContent={(index, groupIndex) => (
                <div>
                    {index} (group {groupIndex})
                </div>
            )}
        />
    );
}
```

**To Reproduce**
1. Put the code above instead to example code on this page [https://virtuoso.dev/grouped-numbers/](url)
2. Scroll very fast 
3. You will see like yellow items with red border scrolls but one of them sticks to the top. 

**Expected behavior**
To not show this sticky placeholder item on top

**Screenshots**
<img width="1277" alt="Monosnap 2024-07-26 23-21-52" src="https://github.com/user-attachments/assets/9ec68abd-76a8-4433-9b38-2d9b4cb98ac2">

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome

**Additional context**

**Comment by petyosi** [comment]
I do understand why you would want such behavior; However, the main idea of the scroll seek placeholders is to avoid the data rendering (and, maybe requesting it), including the sticky placeholder.

**Comment by AlexxGlobenko** [comment]
Hi @petyosi 
In this case sticky placeholder displays like list item. So in this case I think it should be displayed like header/group title item or not displayed at all.
