### ISSUE TITLE
[BUG] Excess re-render of TableVirtuoso items when props doesn't change

### ISSUE THREAD

**Issue by tsarapke** [petyosi/react-virtuoso#1115]
**Describe the bug**
In our project, we want to add some resize and dnd functionality using `react-draggble`.
So we have a component, where we have imported `TableVirtuoso` from `react-virtuoso` and `Draggable` from `react-draggble`.
They both rendered in the same `div`.

In the same scope, we have `useState` to remember "divider" position, which implemented with `Draggble`.
That divider does not affect parent size or anything related to `TableVirtuoso`. It's just some stuff which need to render over the table.

But when we update state after dragging, it cause re-rendering of all table rows. Even if `TableVirtuoso` props doesn't changed.

I can see `TableVirtuosoRoot`, `VirtuosoScroller` and `VirtuosoItems` are `memo` components. 
`TableVirtuosoRoot` and `VirtuosoScroller` are not called after state update. But `VirtuosoItems` by some reasons does.

**Reproduction**
https://codesandbox.io/p/sandbox/virtual-table-resize-nmqw55

**To Reproduce**
1. Open sandbox
3. After render it will produce `console.log` for each row, as it first render (so it fine at this point)
4. Clear console
5. Drag green line to new place
6. Callback that render items will produce new `console.log`

**Expected behavior**
`TableVirtuoso` rows should not re-render when not related state in outer scope update

**Desktop:**
 - MacOS 14.5, Windows 11
 - Chrome 127.0.6533.73, Firefox 128.0.3

**Comment by tsarapke** [comment]
After some some research, I found out it happens due to calling of `applyPropsToSystem` inside `useIsomorphicLayoutEffect`, which is a part of `Component` generated by `systemToComponent`.
![image](https://github.com/user-attachments/assets/dad232cc-763c-4136-be76-79d1313e4717)

So, `applyPropsToSystem` is called on each re-render of parent where `TableVirtuoso` is rendered, what leads to `Items` re-render due to `listState` update
![image](https://github.com/user-attachments/assets/e48a96e5-127b-46b0-9aa4-46748bb043bb)

In react life circle we can see that `nextSnapshot` and `prevSnapshot` are the same (shape and values). But it indicated `snapshotChanged: true`, as system created SAME data from scratch. So it can't be shallowly equal as links to created data are different.
![image](https://github.com/user-attachments/assets/e5704be6-dd5a-4a32-b21b-d0e01c99043b)

As workaround, for now we did like:

```ts
import { memo } from 'react';
import { TableVirtuoso } from 'react-virtuoso';

const MemoizedTableVirtuoso = memo(TableVirtuoso);

export default MemoizedTableVirtuoso;
```

But probably it should be done under the hood `react-virtuoso`? For me it looks like `useIsomorphicLayoutEffect` should be used with some kind of deps, like:
```ts
useIsomorphicLayoutEffect(() => {
      applyPropsToSystem(system, props)
}, [system, ...props])
```
I know spreading in deps is antipattern, but at the same time it should be invoked only in case if deps has been changed.

**Comment by petyosi** [comment]
Thanks for sharing your approach here. As far as my understanding of React goes, doing a re-render cycle when the parent re-renders is normal (as a reference, I put a non-memoized component [in your example](https://codesandbox.io/p/sandbox/virtual-table-resize-forked-frtk9j?file=%2Fsrc%2FApp.js%3A49%2C1)). 

If you're concerned about performance you can certainly memoize `TableVirtuoso` or `TableRowComponent`. This is what I [recommend in the documentation](https://virtuoso.dev/#performance).

Hope this helps.

**Comment by tsarapke** [comment]
@petyosi 

In documentation you mentioned memoizing only for `Item` (row in case if table). Meanwhile it's not obvious that you should wrap `TableVirtuoso` itself with `memo`, even if `Item` already wrapped with `memo`.

Why did you memoize `TableVirtuosoRoot`, `VirtuosoScroller` and `VirtuosoItems`, but not the most parent? 

Even if you will wrap `Item`s with memo, it would be not obvious how developers should figure out that they should wrap a `TableVirtuoso` itself with `memo` in case of performance issues.

Let's say I have a boolean flag at the same scope with `TableVirtuoso`, which I periodically update. And I created memoized `Item` component to render row content. But each memoize item continue update when I change flag.

The last thing I would think about is wrapping `TableVirtuoso` with `memo`, as I do expect from `TableVirtuoso` to handle it under the hood.

**Comment by petyosi** [comment]
I'm sorry that the component does not meet your expectations. I hope you find a solution that fits your needs.
