### ISSUE TITLE
[BUG] VirtuosoGrid items is flickering while scrolling when they don't have same height

### ISSUE THREAD

**Issue by doublelam** [petyosi/react-virtuoso#1118]
**Describe the bug**
VirtuosoGrid items is flickering while scrolling when they don't have same height
**Reproduction**
https://virtuoso.dev/grid-responsive-columns/
replace the live editor content with:
```js
// Ensure that this stays out of the component, 
// Otherwise the grid will remount with each render due to new component instances.
const gridComponents = {
  List: forwardRef(({ style, children, ...props }, ref) => (
    <div
      ref={ref}
      {...props}
      style={{
        display: "flex",
        flexWrap: "wrap",
        ...style,
      }}
    >
      {children}
    </div>
  )),
  Item: ({ children, ...props }) => (
    <div
      {...props}
      style={{
        padding: "0.5rem",
        width: "100%",
        display: "flex",
        flex: "none",
        alignContent: "stretch",
        boxSizing: "border-box",
      }}
    >
      {children}
    </div>
  )
}
const randomHeight = new Array(10).fill(0).map(v => Math.random() * 200 + 50)
const ItemWrapper = ({ children, ...props }) => (
  <div
    {...props}
    style={{
      display: "flex",
      flex: 1,
      textAlign: "center",
      height: randomHeight[props.index],
      padding: "1rem 1rem",
      border: "1px solid gray",
      whiteSpace: "nowrap",
    }}
  >
    {randomHeight[props.index]}
    {children}
  </div>
);

function App() {
  return (
    <>
      <VirtuosoGrid
        style={{ height: 500 }}
        totalCount={10}
        components={gridComponents}
        itemContent={(index) => <ItemWrapper index={index}>Item {index}</ItemWrapper>}
      />
      <style>{`html, body, #root { margin: 0; padding: 0 }`}</style>
    </>
  );
}

render(<App />)
```

and scroll the list on the right

**Expected behavior**
The list should scrolls steadily
**Screenshots**

https://github.com/user-attachments/assets/188e5378-5c4e-4845-99ad-175bf0fe0a94

**Comment by wilfredjonathanjames** [comment]
Encountered the same behaviour with wrapped text using `TableVirtuoso`. Can't tell if I'm missing some important setting or limitation. Ideally this would work.

Video [here](https://youtu.be/2RyPiCexLB4)

**Comment by dwbelliston** [comment]
Seeing the same. @petyosi would you share some tips on this? I see you marked it "not planned". 

Should we only have the same height messages? Thanks.

**Comment by fengliner** [comment]
Encountered  the same issue. Have some solutions to solve it?

**Comment by wilfredjonathanjames** [comment]
I wrote my own virtualiser. Seemed easier tbh.

**Comment by petyosi** [comment]
OP's topic (screenshot is from the README):

<img width="887" alt="Image" src="https://github.com/user-attachments/assets/09603f54-bcc4-4895-8e74-500b360498be" />

@wilfredjonathanjames problem is unrelated; I can't comment on it as no reproduction was provided. 

Locking to prevent further offtopic.
