### ISSUE TITLE
Unable to use VirtuosoMessageList without license in dev for trial purpose 

### ISSUE THREAD

**Issue by anikesh-butler** [petyosi/react-virtuoso#1123]
I'm trying to use VirtuosoMessageList for testing purposes before thinking about purchasing a license but i'm not able to try it without licenseKey. 

Please confirm if it's possible to test it without purchased license or not as documentation seems to be not fully helpful https://virtuoso.dev/virtuoso-message-list/licensing/#trial--evaluation.

**Comment by petyosi** [comment]
Hi @anikesh-butler; You can use an empty license key and the component will work in development mode. Development mode means that you're accessing your project at `localhost`, `127.0.0.1`, or `0.0.0.0`. 

Hope this helps,
