### ISSUE TITLE
[BUG] JSX transform incompatible with React 19

### ISSUE THREAD

**Issue by pzaczkiewicz-athenahealth** [petyosi/react-virtuoso#1127]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 

Noted. I cannot immediately promise funding or a contribution. For now, just trying to document the issue before it becomes bigger.

**Describe the bug**
According to React 19 documentation, React.createElement is no longer going to be supported. The react/jsx-runtime transform from 2020 is required: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#installing

To be fair, React 19 is not out of canary status, but as a component library, it helps to be ahead of the curve.

**Comment by petyosi** [comment]
Can you test v4.10.2?
