### ISSUE TITLE
[BUG]: Dynamic height after items are scrolled, scroll is jumping. NOTE: I don't use margins.

### ISSUE THREAD

**Issue by hristijantrpcevski** [petyosi/react-virtuoso#1129]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 
-- I already  send a email.

**Describe the bug**

All my items have a initial height of 250px and taking the full width of the screen but i have another content which is showing on click of the button and when that content is  displayed,  it takes 70% of the screen and the virtuoso items are taking 30% of the screen and in that case the height of the items is changed  to be 450px. But if i have scrolled a couple of items with height of 250px and then i click on the button the height changes to 450px and i try to scroll upwards to show inside the dom already scrolled items, the height is still cached as 250px and when is entering the dom  the height of the item goes to 450px and all items start jumping.

**Reproduction**
Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

**To Reproduce**
1. Go to 'https://codesandbox.io/p/sandbox/nrmcrh'
2. Click on 'Scroll couple of items and click show button to the top right corner'
3. Scroll up to 'Now scroll up to already cached items and the items will start jumping'

`Same thing is happening here https://virtuoso.dev/auto-resizing/,  resize the container, scroll 100 items, inspect the dom and monitor data-know-size,  return the resize container as it was and now scroll upwards and you will see when item is displayed inside the dom the data-know-size will change from 120px to 94px.`

**Expected behavior**

I expect to happen, already cached items to be calculated or data-know-size to be same as the ones are displayed inside the dom.
And the scroll to stay in the same position, not like when `key` props is used, scroll to top to be activated because the list is re-rendered.

**Screenshots**

**Desktop (please complete the following information):**
-
 - OS: [e.g. iOS] - Windows can behave unexpectedly.
 - Browser [e.g. chrome, safari]- All browsers

**Additional context**

**Comment by petyosi** [comment]
I replied to your email.

**Comment by gutsyphilip** [comment]
Hi @petyosi 
I'm facing a similar issue. Please is there anywhere public you can point me to for your thoughts/comments on this?
