### ISSUE TITLE
TableVirtuoso does not render topItemCount items

### ISSUE THREAD

**Issue by dev-bjoern** [petyosi/react-virtuoso#1130]
**Describe the bug**
When using the topItemCount prop for the TableVirtuoso, the items are not rendered. They appear to be an empty div on top of the other items.

**Reproduction**
https://codesandbox.io/p/sandbox/sandpack-project-forked-qflzwl

**Comment by petyosi** [comment]
Agreed, this feature is not functional, I have not implemented it at all, from what I see in the source. PR is welcome, you can check the way it works for the regular virtuoso component.
