### ISSUE TITLE
[BUG] Restoring scrolled down grid causes unequal hook amount error during render

### ISSUE THREAD

**Issue by schroda** [petyosi/react-virtuoso#1131]
**Describe the bug**

Starting with [v4.10.0](https://github.com/petyosi/react-virtuoso/compare/v4.9.0...v4.10.0), restoring a grid state, which was scrolled down, causes a "Rendered more hooks than during the previous render." error.
This only happens for scroll offsets greater than 0

**Reproduction**

https://codesandbox.io/p/sandbox/peaceful-aryabhata-forked-zfkzmn

**To Reproduce**

1. scroll down in the grid
2. click an item
3. click the back button

**Expected behavior**

The grid should be restored without causing an error

**Video**

https://github.com/user-attachments/assets/63a58a9e-dac3-4827-ac92-af23a76ca7de

**Desktop (please complete the following information):**

 - OS: iOS, Windows.
 - Browser: chrome (iOS), edge (windows)

**Comment by petyosi** [comment]
Got it, Pepe repro was essential :)
