### ISSUE TITLE
scrollingStateChange called erroneously when list is modified

### ISSUE THREAD

**Issue by jmeistrich** [petyosi/react-virtuoso#114]
I would expect that scrollingStateChange is only called when the list is scrolled by the user, but it seems to be called when Virtuoso re-renders for a totalCount change. In my own app, when I insert into the list I see it callback three times with false, true, false. 

I modified the prepending example to show a repro of this, and it gets many more scrollingStateChange callbacks than in my app, but I'm not sure why. https://stackblitz.com/edit/react-jjjnhr?file=example.js

**Comment by petyosi** [comment]
Looking at the code of the scrollingStateChange, this is entirely possible. Will dig into it.

**Comment by petyosi** [comment]
@jmeistrich - can you check v 0.16.7?

**Comment by jmeistrich** [comment]
@petyosi That fixed it. Thanks!

**Comment by Ponjimon** [comment]
I cannot confirm this being fixed, I'm still experiencing the same behavior as OP
