### ISSUE TITLE
Focus lost when typing in an input on table row when using Table Virtuoso

### ISSUE THREAD

**Issue by tranchem** [petyosi/react-virtuoso#1142]
**Describe the bug**

Maybe I am implementing wrong (or this is not supported) but seems focus is lost when typing in an input on a table.

**Reproduction**

https://codesandbox.io/p/sandbox/2hkpfq

**Expected behavior**

Input wasn't lost focus

**Screenshots**

https://github.com/user-attachments/assets/aa4c7be6-ced6-4e3a-8558-4cfd4c3a29d4

**Comment by petyosi** [comment]
The sandbox does not work.
