### ISSUE TITLE
Focus lost when typing in an input on table row when using Table Virtuoso

### ISSUE THREAD

**Issue by tranchem** [petyosi/react-virtuoso#1143]
**Describe the bug**

Maybe I am implementing wrong (or this is not supported) but seems focus is lost when typing in an input on a table.

**Reproduction**

https://codesandbox.io/p/sandbox/2hkpfq

**To Reproduce**

1. Click on Input
2. Typing

**Expected behavior**

Input wasn't lost focus

**Screenshots**

https://github.com/user-attachments/assets/ae19782c-438f-4e66-a3e9-ea8747b1eeaa

**Comment by petyosi** [comment]
https://github.com/petyosi/react-virtuoso/issues/715

**Comment by tranchem** [comment]
> #715
I read the context documentation, but i can't do it for my code. Sorry
Can you make sample in my codesanbox. Please! Thank you so much!
