### ISSUE TITLE
[BUG] GroupedVirtuoso computeItemKey index out of bound

### ISSUE THREAD

**Issue by schroda** [petyosi/react-virtuoso#1146]
**Describe the bug**

For GroupedVirtuoso the computeItemKey function gets called for a non existing index (e.g. 2 items, gets called for index 2)

**Reproduction**

https://codesandbox.io/p/sandbox/grouped-virtuoso-compute-item-key-index-out-of-bound-pghf43

**To Reproduce**

1. Scroll to the end of a grouped list to cause the last item to get rendered

**Expected behavior**

Only gets called with existing indexes

**Screenshots**

/

**Desktop (please complete the following information):**

/

**Additional context**

/

**Comment by petyosi** [comment]
The computeItemKey needs to return a key for the group item as well.

**Comment by schroda** [comment]
still seems broken even in case it should call the function for the group items as well
it always gets called for the amount of "normal" items plus 1, regardless of how many group items there are

e.g. 4 items, 3 groups => gets called for 0, 1, 2, 3, 4 (see updated codesandbox)

besides this, group items already have their own render function, which makes sense since you most likely don't have the group and normal items in one list, so wouldn't it be better to do the same for the key computation

**Comment by petyosi** [comment]
That's because the first exception cancels the rendering.

**Comment by schroda** [comment]
right...
![ShameTheofficeGIF](https://github.com/user-attachments/assets/86d5daa4-5f4d-44bc-bff6-18d9df9039a2)

so what is the simplest way to select the proper item (group or normal), there seems to be no indication which ends in having to convert the index to the specific list or create a list that has the group and normal items in the correct order, which both seems to be unecessary complicated compared to how the rendering works
