### ISSUE TITLE
[BUG] small scrolls resulting in jank/scroll position resets

### ISSUE THREAD

**Issue by herschelrs** [petyosi/react-virtuoso#1150]
Scrolling with up/down arrow results in small scroll position jumps after ~1/5 of key presses, or continuously but erratically if the key is held down. These also happen with very slow continuous mouse scrolling. These feel like they're happening towards the end of the scroll, but not quite at the end; there's a few frames of scrolling movement afterwards, usually. These seem to be more like errors in the scroll position, rather than skipped frames or lag otherwise, they don't seem to correspond to skipped or partial frames according to the browser's performance profiler, and they happen even with extremely lightweight components (see repro.) 

This seems to happen with or without `useWindowScroll`. Note that scrollToIndex with smooth scrolling, and pgdn/pgup work fine. (Or at least, if there are scroll position jumps, the scrolling is moving fast enough anyway that I can't see them.)

I'm unclear if this is about using dynamically sized elements, I think I wasn't getting it with uniformly sized elements.

Tested on Chromium 129.0.6668.100 and Firefox 131.0.3 on Arch Linux.

Reproduction: [https://codesandbox.io/p/sandbox/5ncc9x](https://codesandbox.io/p/sandbox/5ncc9x)

**Comment by petyosi** [comment]
Your example has margins in the content. Read the troubleshooting section of the docs.
