### ISSUE TITLE
[BUG] can't set initialTopMostItemIndex to undefined

### ISSUE THREAD

**Issue by tstehr** [petyosi/react-virtuoso#1155]
Hi 👋 ,

first of all thank you for the great work with Virtuoso! I've been using the library for a few years now. I found it really easy to adapt to deal with performance problems with long lists, and also love the way I can customize all of the behaviors to fit my requirements. 

**Describe the bug**

I'm trying to set `initialTopMostItemIndex` based on whether an external variable is set as follows, with `activeItemIndex` having a type of `number | undefined`.

```typescript
<Virtuoso
  initialTopMostItemIndex={
    activeItemIndex
      ? { index: activeItemIndex }
      : undefined
  }
/>
```

However, that leads to the following error:

![Screenshot 2024-11-06 at 13 10 49](https://github.com/user-attachments/assets/47f9daa1-f26e-4083-a222-501cbed2e7af)

**Reproduction**

https://codesandbox.io/p/sandbox/competent-glade-gv4pfj?file=%2Fsrc%2FApp.tsx

**To Reproduce**

1. Click the "Re-render and toggle initialTopMostItemIndex" button in the CodeSandbox preview
4. See the error appear in the browser console

**Expected behavior**

Setting `initialTopMostItemIndex={undefined}` should behave identical to the prop not being present at all. These are not strictly equivalent in JS terms, but given that the TypeScript typings for the component allow setting the prop to `undefined` it's quite unexpected for that to lead to an immediate crash.

**Desktop:**

 - OS: macOS
 - Browser: tested in Chrome, Safari amd Firefox

**Additional context**

For now I'm using the following workaround to ensure the prop is unset when the variable it depends on is set to `undefined`:

```typescript
<Virtuoso
  {...(activeItemIndex !== undefined
    ? {
      initialTopMostItemIndex: { index: activeItemIndex },
    }
    : {})}
/>
```

**Comment by petyosi** [comment]
Duplicate. I do understand the convenience of passing undefined, but internally this is quite the hassle to deal with. The approach you've outlined is correct. https://github.com/petyosi/react-virtuoso/issues/777

**Comment by tstehr** [comment]
Oh, I somehow failed to see the issue this duplicates. Thank you for the explanation!
