### ISSUE TITLE
[BUG] Out of range indexes when prepending items

### ISSUE THREAD

**Issue by myandrienko** [petyosi/react-virtuoso#1157]
**Describe the bug**

When prepending list items (e.g. for inverse infinite scrolling) by decreasing `firstItemIndex` and increasing `totalCount`, there is an intermediate state during which Virtuoso callbacks (e.g. `computeItemKey`) receive out-of-range indexes as an argument.

**Reproduction**

1. Go to [the sandbox](https://codesandbox.io/p/sandbox/g5jswl)
2. Click on the "Prepend 100 items" button
3. In the console, see the "Out of range" log

**Expected behavior**

Index provided as an argument to the callback functions is always in range given the current list length and first item index.

**Additional context**

As far as I can see, the current system allows for a temporary inconsistent state when updating multiple props at once. In this case, first an update to the `totalCount` prop is taken into account, the list is re-rendered with the new `totalCount` but stale `firstItemIndex` (causing out-of-range indexes), and only then an update to the `firstItemIndex` is taken into account.

**Comment by petyosi** [comment]
Agreed - the firstItemIndex prop approach is very ugly and can result in an inconsistent. You can try to push both into a single state structure, maybe that would work. 

If you're building a reverse infinite scroll, I highly recommend the message list component. It has [an imperative data API for that purpose](https://virtuoso.dev/virtuoso-message-list/working-with-data/#prepending-data).
