### ISSUE TITLE
[BUG] Virtuoso Grid has layout shift when using max-width on parent

### ISSUE THREAD

**Issue by cpaczek** [petyosi/react-virtuoso#1158]
**Describe the bug**

if you set a max width on the parent of a grid it causes layout shift as you scroll. 

(my guess as to why this happens is virtuoso uses width of each card and the overall width of the container to determin how many cards there are per row.

**Reproduction**
Here is a simple reproduction, as you scroll you can clearly see that the items are shifting around 
```
// Ensure that this stays out of the component, 
// Otherwise the grid will remount with each render due to new component instances.
const gridComponents = {
  List: forwardRef(({ style, children, ...props }, ref) => (
    <div
      ref={ref}
      {...props}
      style={{
        display: "flex",
        flexWrap: "wrap",
        maxWidth: "200px",
        margin: "auto",
        ...style,
      }}
    >
      {children}
    </div>
  )),
  Item: ({ children, ...props }) => (
    <div
      {...props}
      style={{
        padding: "0.5rem",
        width: "33%",
        display: "flex",
        flex: "none",
        alignContent: "stretch",
        boxSizing: "border-box",
      }}
    >
      {children}
    </div>
  )
}

const ItemWrapper = ({ children, ...props }) => (
  <div
    {...props}
    style={{
      display: "flex",
      flex: 1,
      textAlign: "center",
      padding: "1rem 1rem",
      border: "1px solid gray",
      whiteSpace: "nowrap",
    }}
  >
    {children}
  </div>
);

function App() {
  return (
    <>
      <VirtuosoGrid
        style={{ height: 500 }}
        totalCount={1000}
        components={gridComponents}
        itemContent={(index) => <ItemWrapper>Item {index}</ItemWrapper>}
      />
      <style>{`html, body, #root { margin: 0; padding: 0 }`}</style>
    </>
  );
}

render(<App />)
```
just paste it here: https://virtuoso.dev/grid-responsive-columns/
**Expected behavior**

https://github.com/user-attachments/assets/2de38e4e-db86-4e74-8127-a516c7952b98

It should remove 3 elements at a time.

The goal I am trying to achieve is to have a max width and only 3 cards per row so that people on ultrawide monitors don't have just a massive amount of data.

**Comment by petyosi** [comment]
You should move the max width setting to the VirtuosoGrid component instead.

**Comment by cpaczek** [comment]
> You should move the max width setting to the VirtuosoGrid component instead.

Ya that works however our issue is that it causes the scrollbar to be right next to the elements, it there a way to have gutters so the scrollbar is still to the right side of the page?

![image](https://github.com/user-attachments/assets/ec085012-9c3a-4939-a579-f441a201d4e7)
