### ISSUE TITLE
Not Fixed Header

### ISSUE THREAD

**Issue by marine1079** [petyosi/react-virtuoso#116]
Can I have not fixed header component scroll with virtuoso component?

```
<Parent component> --> It scrolls.
...
<Header component> --> Should move with Virtuoso (not fixed at the top)
<Virtuoso/> --> Should not scroll alone without Header, Parent component.
...
</Parent component>
```

How can I have the header component like this?
I tried ScrollContainer but I didn't find the solution.

**Comment by petyosi** [comment]
Check this Issue for a solution: https://github.com/petyosi/react-virtuoso/issues/71
