### ISSUE TITLE
[BUG] : On click of each item, Enitre Item content re-render.

### ISSUE THREAD

**Issue by Naps2024** [petyosi/react-virtuoso#1165]
**Describe the bug**

In the below example. I need to create a virtuoso Grid, on the click of each item it re render the entire component. 

**Reproduction**

(https://codesandbox.io/p/sandbox/6lv54c)

**To Reproduce**

1. Click on any item
2. See on Console, it will re -render all item's on each click

**Expected behavior**

It would not re-render entire content

**Screenshots**

![image](https://github.com/user-attachments/assets/3ed5443b-4245-47c6-9046-67d64f69ebb0)

**Desktop (please complete the following information):**

 - OS: Windows 11.
 - Browser: Chrome, Firefox

**Additional context**
I have seen the same issue on React-window. I need to handle 1 million image click at a time when click one by one. In grid if there are 100 items it re-render 100 items. It make dom busy and make latency on checkbox change event.

**Comment by petyosi** [comment]
This is not a bug in the component but a problem in your memoization logic.

**Comment by Naps2024** [comment]
Hi @petyosi Could you please help me with the memo logic where I am doing wrong because I am struggling this with from 15 days.
