### ISSUE TITLE
[BUG] Detached DOM 

### ISSUE THREAD

**Issue by rajasekarm** [petyosi/react-virtuoso#1168]
**Describe the bug**

There seems to be an issue with detached DOM elements in React-Virtuoso. When items are unmounted, removed from the list, or become hidden, the corresponding DOM nodes are not properly cleaned up. As a result, these elements are retained in memory, causing memory leaks. This behavior leads to increased memory usage, slower scrolling performance, and higher CPU utilization due to excessive garbage collection.

**To Reproduce**

1. Go to https://virtuoso.dev/scroll-handling/
2. Scroll to 4th or 5th page.
3. Go to memory tab and profile. 
4. Filter by detached DOM node. 

**Expected behavior**

Detached dom nodes should not be seen in the memory tab.

**Screenshots**

![Screenshot 2024-12-07 at 12 49 32 AM](https://github.com/user-attachments/assets/8c988401-ee59-4139-a645-fd351771f159)

**Desktop (please complete the following information):**

 - OS: MAC
 - Browser CHROME

**Additional context**

**Comment by rajasekarm** [comment]
https://vueuse.org/core/useVirtualList/#usevirtuallist

Detached DOM is not seen here.

**Comment by petyosi** [comment]
As far as I can tell, this is related to the React devtools extension - at least in my browser. Here's how to verify that: 

- I took the example you pointed to, put it in a standalone vite project with nothing else
- loaded the page in incognito mode, with extensions disabled
- scrolled through the list, took a heap snapshot

No elements were caught. 

If I do that with react devtools enabled, there's indeed quite a few of them. 
<img width="358" alt="image" src="https://github.com/user-attachments/assets/df46a6d1-9d61-4bd1-aaed-5c5bb4121433">


Probably related: https://github.com/facebook/react/issues/28323
