### ISSUE TITLE
Incorrect data-known-size on group headers that lie outside of overscan

### ISSUE THREAD

**Issue by DrFrankenstein** [petyosi/react-virtuoso#117]
If I:
1. take `playground/grouped-load-on-demand.tsx`,
2. change the height of items to 200px,
3. focus on the list and hold down the 'End' key (or ⌘+▼ on Macbooks),
4. click on "Press to load more" a few times,

then in some cases, the `data-known-size` and `style.marginTop` attributes of the current sticky header are wrong. As a result, it breaks scrolling somewhat (especially around section boundaries) and leaves extra blank space at the end of the list (likely due to the header's margin-top overflowing). It usually takes the size of the last item, or just 1px, instead of its own size.

In this screenshot, the value of `data-known-size` should be 19, not 201. There's also a lot of blank space after the button.
![image](https://user-images.githubusercontent.com/44741/82379085-4c561000-99f4-11ea-95e7-1b284916b7ff.png)

This causes an issue in our app, because we auto-scroll to the bottom of the list on load, and if the last item is large enough, we end up with broken scrolling and the aforementioned empty space.

I'm not sure what the root cause of the issue is, unfortunately, but I suspect the size calculation of headers outside of the overscan might be going wrong.

This is also reproducible in https://virtuoso.dev/grouped-with-load-on-demand/, albeit with less visual breakage because the items are smaller.

**Comment by petyosi** [comment]
Hey, 

thank you for reporting that. Can you please:

1. Fork the example you refer to in Stackblitz and do the adjustments and paste the link here;
2. record a video/gif of the issue. In this way, I will be sure that I am not missing something or going mad.

**Comment by DrFrankenstein** [comment]
Here's the Stackblitz project: https://stackblitz.com/edit/react-gtqak8

And the video:
[virtuoso-issue-117-recording.mov.zip](https://github.com/petyosi/react-virtuoso/files/4664148/virtuoso-issue-117-recording.mov.zip)

Note that the first and third time I click the button, I'm holding down the "End" key to make it scroll down as soon as the new items are added. This reproduces the auto-scroll issue we're having.

**Comment by petyosi** [comment]
Got it. I will look into that in the next couple of days.

**Comment by petyosi** [comment]
This should be fixed in v1 (in beta). Check #203 for installation instructions.
