### ISSUE TITLE
[BUG]When the scrollbar is at the top, scrolling up quickly and then scrolling down causes the scrolling to stop working

### ISSUE THREAD

**Issue by menglu628** [petyosi/react-virtuoso#1170]
**Describe the bug**

when the scrollbar is at the top, if the user continues to scroll rapidly upwards and then quickly scrolls down, there may be intermittent issues where scrolling down stops working.

**Reproduction**
Every example can be reproduced.such as:
https://virtuoso.dev/hello/

**Expected behavior**

When at the top of the list, if you continue scrolling up and then scroll down, the downward scrolling should remain smooth without any stutter.

**Screenshots**

https://github.com/user-attachments/assets/7103312d-b1c3-4367-b18c-19e2aaf1c5bc

Please see at the end, the mouse is still inside the virtual list, but when scrolling down, it’s the browser’s scrollbar that moves, which seems to indicate that the focus has been lost inside the virtual list.

**Comment by petyosi** [comment]
I believe that this is a system/browser behavior - scrolling upwards in an already scrolled to the top element 'transfers' the scroll to the window element. As far as I can tell (Chrome/Mac), same thing happens with a simple div: 

https://codesandbox.io/p/sandbox/2c9w5x?file=%2Fsrc%2FApp.tsx%3A11%2C51

**Comment by menglu628** [comment]
I am also using Mac Chrome, and every example can be reproduced. In the virtual list, if you continue to scroll quickly upwards at the top of the list and then scroll down, there are cases where scrolling is not possible. If there is no browser scrollbar, and only the virtual list has a scrollbar, the issue of being unable to scroll down seems more prominent.

**Comment by menglu628** [comment]
> I believe that this is a system/browser behavior - scrolling upwards in an already scrolled to the top element 'transfers' the scroll to the window element. As far as I can tell (Chrome/Mac), same thing happens with a simple div:
> 
> https://codesandbox.io/p/sandbox/2c9w5x?file=%2Fsrc%2FApp.tsx%3A11%2C51
I am also using Mac Chrome, and every example can be reproduced. In the virtual list, if you continue to scroll quickly upwards at the top of the list and then scroll down, there are cases where scrolling is not possible. If there is no browser scrollbar, and only the virtual list has a scrollbar, the issue of being unable to scroll down seems more prominent.

**Comment by menglu628** [comment]
Take a close look at the 7th second of the video. When the mouse scrolls down within the virtual list, it is the browser's scrollbar that is moving, not the scrollbar of the virtual list.
