### ISSUE TITLE
Demo flickers on page scroll

### ISSUE THREAD

**Issue by cjcheshire** [petyosi/react-virtuoso#12]
Hey, just stumbled on your library (via Sid mailing list). Looks slick 🙌 

I spotted on the demo site it seems to not like the browser page scrolling? It results in a nasty flicker and a times no longer paints the list.

https://vimeo.com/339051112

Device is an iPhone X, iOS 12.2. Suspect you could replicate on other iOS devices.

**Comment by petyosi** [comment]
Thanks! 👍 I believe I introduced this regression recently; Seems specific to iOS. It's in my TODO list.

**Comment by cjcheshire** [comment]
No worries, I hate to bring problems without solutions :)

**Comment by petyosi** [comment]
Fixed in `v0.7.0`. Had to rework the positioning mechanism for that.

**Comment by x4080** [comment]
Hi @petyosi , There's still a screen glitch in iOS, it happened when scroll back to top, when near the top it will glitch, I'm using material ui navigation drawer on the left (if there's conflict)

Thanks

**Comment by petyosi** [comment]
@x4080 can you reproduce that on the [examples](https://virtuoso.dev/)? If not, can you fork one of them to Stackblitz and showcase it? I will take a look.

**Comment by x4080** [comment]
@petyosi I'll try it and let you know

**Comment by x4080** [comment]
@petyosi I havent tried using the examples, but when I take a look at the flicker, that happened outside of the virtuoso, I'm using material ui appbar, and inside paper component I put virtuoso and the flicker is in app bar when reaching near top of list and bouncing effect from safari is started

**Comment by petyosi** [comment]
I have to see that in order to help you. Please try replicating it in a sample (stackblitz or code sandbox). Cheers!
