### ISSUE TITLE
Scrollbar disappears when using top items

### ISSUE THREAD

**Issue by toonvd** [petyosi/react-virtuoso#120]
It is reproducible in Chrome on Mac in the demo: https://virtuoso.dev/top-items/. When scrolling without top items, we have a scrollbar, when scrolling with them, we don't. Is this default browser behaviour when using position:sticky?

**Comment by petyosi** [comment]
Can you send me a screenshot of what you mean? I am on a mac and I see the scrollbar, played with the general preferences as well.

**Comment by petyosi** [comment]
@toonvd - ping here :)

**Comment by toonvd** [comment]
Hi @petyosi 

I apologize for the delay, didn't have access to the laptop.
[https://ibb.co/9wNXBMm](url)

This strangely only happens on my old Macbook, my new one doesn't have the problem. Chrome version is the latest:
Versie 83.0.4103.61 (Officiële build) (64-bits).

I thought it could be related to browser caching first but that was not the case either.

**Comment by petyosi** [comment]
Can this be caused by this setting somehow, not sure... 

![image](https://user-images.githubusercontent.com/13347/83553822-793a1500-a514-11ea-8f3e-fb0054b3279e.png)

**Comment by toonvd** [comment]
Gonna close this for now as it seems like an issue related to config on the laptop itself.
Will let you know when I find out something. I just noticed it while devving on the datatable lib.
