### ISSUE TITLE
ScrollToIndex with {behavior: 'smooth'} breaks rendering

### ISSUE THREAD

**Issue by siwalikm** [petyosi/react-virtuoso#122]
Firstly thanks for this lovely project @petyosi  🙏

So the other day I was trying to use the scrollToIndex API with smooth transition as suggested by you in #64 by passing the behavior parameter like this -

https://github.com/petyosi/react-virtuoso/blob/8605ccb6be82b868b78ba1c2b1f2919e1bcdabab/src/EngineCommons.ts#L6

The scrolling behavior works fine but the rendering gets broken after scrolling to index.
Here's a live example of the issue - https://stackblitz.com/edit/scroll-to-index-smooth-example?file=example.js

**Comment by petyosi** [comment]
Hey @siwalikm , 

I clicked around the example and I could not notice anything broken, can you please help me? A screenshot or a gif can help. 

Cheers!

**Comment by siwalikm** [comment]
The first and third buttons have behaviour **scroll** in the example while the middle one is **auto**.
Jumping from first button to third button(<->) illustrates the breakage.
![chrome-capture](https://user-images.githubusercontent.com/20061595/84174305-13153b00-aa9c-11ea-91b4-265317732c24.gif)

**Comment by petyosi** [comment]
I think I have received similar reports, but I can't reproduce the problem on my side. Check the behavior I have: 
![virtuoso-smooth-scroll](https://user-images.githubusercontent.com/13347/84240578-ec401e80-ab06-11ea-9382-41df4c479af9.gif)

I will mark the issue as open and PR welcome - someone who can reproduce it and is willing to debug the code can give it a try.

**Comment by BrentFarese** [comment]
I can confirm that I experience this issue when using `smooth` as well.  Will try and see if I can re-produce and post something here.

**Comment by KiyoshiMori** [comment]
I have this bug too and I found that when I'm using custom ScrollContainer then it works right.
You can check it here: https://stackblitz.com/edit/smooth-behavior-without-render-breaks?file=example.js. Maybe it could be helpful if someone wants to fix it.

**Comment by petyosi** [comment]
@siwalikm I reworked the smooth scrolling behavior in v1 (beta, see #203). Please test and let me know how it works.
