### ISSUE TITLE
Grid: Different row heights

### ISSUE THREAD

**Issue by exentrich** [petyosi/react-virtuoso#123]
Thanks for such great library! It's the only one capable of rendering truly auto-sizable list items without hassle! That's killer feature. Will be great to have it on Grid too, not only equally sized row heights.

I implemented this requirement using Virtuoso component instead of Virtuoso Grid, by rendering needed columns per row. This approach works okay, but I'm sure performance could be better if I replace it to Virtuoso Grid.

Do you have any plans to support different row heights in Virtuoso Grid?

**Comment by petyosi** [comment]
Hi @exentrich! One thing which basically blocked my thinking here was the following:
non-equally sized row heights suggest "jagged" varying size tiles which leads my imagination towards the Pinterest kind of interface (otherwise you will have gaps between the different sized items). Is this what you have in mind?

**Comment by petyosi** [comment]
@exentrich an original constraint for the grid was responsive behavior. In the example above, if I am about to resize the container, the dark blue element will go to the first row. How would that work? That's what blocked me in my further consideration and brought me to the Masonry (interesting term btw!) line of thought, which indeed is quite complicated.  Let me know what you think, this is an interesting topic to me.

**Comment by exentrich** [comment]
I expect usual flex-box behaviour. Please check this simple example: https://jsfiddle.net/exentrich/358uyebq/2/

As you can see I have images with different height in cells. That could be combination of image + text, or just text, no matter, the main thing is that content of cells could be variable size.

When you resize container, the tallest cell stretches other cells in a row

**Comment by petyosi** [comment]
I see what you mean. This is possible indeed. My first thought is that an additional binary tree data structure is necessary to track and re-calculate the total height. at any dimension change, the structure of the item heights should re-produce the structure of the row heights.

Realistically, I am not going to get to that any time soon, so I will mark that as a PR welcome. If you are interested in a contribution please reach out to me, I will do my best to help. By the way, the [code of the grid](https://github.com/petyosi/react-virtuoso/blob/master/src/VirtuosoGridEngine.ts) is super simple compared to the list :).

**Comment by acnebs** [comment]
Having this as a Masonry Grid would be great.

Will have a go at a PR if I get the time.

**Comment by khmelevskii** [comment]
@petyosi As I can see this issue was close without implementing this behavior? Currently is is not possible to virtualize list with different row height?

**Comment by petyosi** [comment]
This is an old issue, but if someone is looking for a virtualized masonry, I'm working on an early prototype here: https://codesandbox.io/p/sandbox/masonry-xhjl8g?file=%2Fsrc%2FApp.tsx%3A12%2C1-13%2C1.

**Comment by Wangtaofeng** [comment]
> This is an old issue, but if someone is looking for a virtualized masonry, I'm working on an early prototype here: https://codesandbox.io/p/sandbox/masonry-xhjl8g?file=%2Fsrc%2FApp.tsx%3A12%2C1-13%2C1.

I tried your example and it feels good, I need it so much
