### ISSUE TITLE
followOutput doesn't work with react concurrent mode

### ISSUE THREAD

**Issue by chrisdostert** [petyosi/react-virtuoso#125]
First off, thanks for the awesome library.

I was testing experimental react-relay hooks which requires react concurrent mode and followOutput does not seem to work with it.

If I switch to relay-hooks (a 3rd party library offering relay hooks without requiring concurrent mode), it works.

**Comment by petyosi** [comment]
Interesting, can I get a repro of that? I will look into it further

**Comment by petyosi** [comment]
Closing - feel free to comment with a reproduction.
