### ISSUE TITLE
followOutput stops following if container height decreased

### ISSUE THREAD

**Issue by chrisdostert** [petyosi/react-virtuoso#127]
Repro Steps:
1) go to https://codesandbox.io/s/modest-rubin-9s52w
2) notice list is scrolled to bottom
3) click expand

Expected:
bottom of list stays at last item but scroll area is squished

Actual:
bottom item get's pushed offscreen

**Comment by petyosi** [comment]
@chrisdostert Interesting idea; right now, the `followOutput` does not track container resize, it tracks the addition of new items only. I will give this some thought, as expanding in this direction might make the behavior too aggressive and prevent scrolling to top.

**Comment by chrisdostert** [comment]
FWIW my use case is with chat. I have a virtuoso container of messages, below which I have an add message box. The add message box can expands as the user types because it's of arbitrary length. I want the virtuoso container to continue followingOutput as the user types into the add message box. I haven't found any way to do this yet. Let me know if theres a way you could think of (even if it's a hack for the moment). Cheers/Thanks!

**Comment by petyosi** [comment]
The quickest hack I would do is to nudge the chat list up (translateY) rather than resizing it.

**Comment by petyosi** [comment]
Closed with #297
