### ISSUE TITLE
Question: How to load on scrollToIndex

### ISSUE THREAD

**Issue by chrisdostert** [petyosi/react-virtuoso#128]
If I have a huge list which I can't load all at once, but want to allow scrolling to a particular item of, how do I load the items necessary on scrollToIndex? The equivalent in react-virtualized would be the InfiniteLoader component.

**Comment by petyosi** [comment]
Rough direction: 

1 - set the totalCount to the total count of the items in the list (not just the loaded ones). 
2 - have a data pager component that tracks which items are loaded and which not.
3 - render placeholders for items that are not loaded.
4 - Load items [at the `rangeChanged` event](https://virtuoso.dev/range-change-callback/).
5 - When items are loaded, refresh the component by [passing a new value to data-key](https://github.com/petyosi/react-virtuoso/pull/95/files) (which I have not documented yet).

If you manage to do it, it would be great if you can contribute with an example :). I will add it to the documentation. Cheers!
