### ISSUE TITLE
initialTopMostItemIndex does not use overscan for previous item indices

### ISSUE THREAD

**Issue by utileetdulce** [petyosi/react-virtuoso#129]
As you can see in your example (https://virtuoso.dev/initial-index/)
when using `initialTopMostItemIndex` the previous items do not get rendered (e.g. index 798 in the example). This behavior is not so problematic when it comes to small/simple list items, but it is when using items of great height or complexity. Increasing `overscan` results in more items renderes **after** the top most item but not **before**.

**Comment by petyosi** [comment]
@utileetdulce in v1, the overscan property accepts `{ main: number, reverse: number}` value, which lets the developer hedge against scrolling in both directions.
