### ISSUE TITLE
Renders nothing when defaultItemHeight is less than height of rendered items while using initialTopMostItemIndex

### ISSUE THREAD

**Issue by jmeistrich** [petyosi/react-virtuoso#132]
Using initialTopMostItemIndex and a small defaultItemHeight with a list of tall items causes nothing to render at all, even after scrolling.

Repro here:
https://stackblitz.com/edit/react-jjjnhr-jh8ggw?file=example.js

You can see it renders nothing, but if you increase defaultItemHeight to 28 or remove initialTopMostItemIndex, then there is no problem.

**Comment by petyosi** [comment]
It renders something on my side, at least - Latest Chrome on mac.

![image](https://user-images.githubusercontent.com/13347/84404390-6c51ab80-ac0f-11ea-8054-7051cb52b562.png)

Should I change something or do something?

**Comment by jmeistrich** [comment]
@petyosi Sorry, I must have saved it wrong. Updated the stackblitz. It's the combination of defaultItemHeight={18} and initialTopMostItemIndex={1} that makes it not render.

**Comment by petyosi** [comment]
Fixed in `0.17.2`

**Comment by jmeistrich** [comment]
Tested and it works well now, thanks!
