### ISSUE TITLE
Scrolling up is janky when initialTopMostItemIndex puts a large item at the top of the list

### ISSUE THREAD

**Issue by jmeistrich** [petyosi/react-virtuoso#133]
If initialTopMostItemIndex puts an unusually large item at the top of the visible area of the list, scrolling up from there causes large jumps and looks janky. I had tried setting a small defaultItemHeight, but ran into https://github.com/petyosi/react-virtuoso/issues/132. 

I found that removing:
```
if (initialTopMostItemIndex) {
  initialOffsetList = initialOffsetList.setInitialIndex(initialTopMostItemIndex);
}
```
from the top of offsetListEngine appears to fix it, but you said in https://github.com/petyosi/react-virtuoso/issues/89 that's not a good idea.

Here's a repro. Scroll up to see the problem.
https://stackblitz.com/edit/react-jjjnhr-534nmm?file=example.js

**Comment by petyosi** [comment]
Thank you. The suggested change has an accidental effect on the behavior, I am afraid. This is another aspect of the bottom-up scrolling I have tagged in several open issues.

**Comment by jmeistrich** [comment]
Just an update, now that https://github.com/petyosi/react-virtuoso/issues/132 is fixed, setting a small defaultItemHeight is now solving this issue for me without having to do the change mentioned above.

**Comment by jmeistrich** [comment]
@petyosi Actually, I spoke too soon. After more extensive testing it turned out that a small defaultItemHeight did not fix it, and I am currently using the change removing setInitialIndex to solve it. So I think this is still an open problem.

**Comment by raae** [comment]
I am seeing this as well, could this be solved by using the suggested approach in #188 (1) where there are invisible rendered items on above the list?

**Comment by petyosi** [comment]
@jmeistrich @raae I published `v0.21.0-alpha.1` that's supposedly improving this behavior. Notice that there are several deprecations in there, but it work better than the current one. Please let me know how it works for you - and, if possible, post runnable examples. Cheers!

**Comment by raae** [comment]
Will test tomorrow!

**Comment by raae** [comment]
Couldn't wait, tested now and its works on my demo https://codesandbox.io/s/musing-engelbart-67uwr?file=/src/App.js, but not in my project where I use ListContainer for instance. Any place to get an overview of deprecations?

**Comment by petyosi** [comment]
@raae - good news. I am still working on the deprecations, a migration guide will be part of the official release. 

Here's how you [can use custom list container](https://codesandbox.io/s/virtuoso-experiement-forked-pz4ej?file=/src/App.js) with `v0.21.0-alpha`.

**Comment by raae** [comment]
Great work! Any estimate on time? I might just postpone fixing this in my app until its release. I have a workaround that can work for a while more. 

If you need any help with docs or other "boring" tasks to get the release out let me know.

**Comment by petyosi** [comment]
@raae The tech work is done. I am working through the backlog of open issues and manually testing and creating examples, in order to solicit feedback from reporters. If everything goes well, I aim at a release candidate (which I would recommend as an upgrade) in 2 weeks time. 

I will certainly reach out for more feedback - thank you very much for your responsiveness.

**Comment by petyosi** [comment]
@raae @jmeistrich - I decided to label the next version as v1 to avoid breaking v0 users. Please test this in your setups. #203 refers to installation instructions and breaking changes. Thank you very much!
