### ISSUE TITLE
data-known-size incorrect for first rendered items

### ISSUE THREAD

**Issue by exentrich** [petyosi/react-virtuoso#137]
As you can see in screenshot of [official example](https://virtuoso.dev/auto-resizing/) below `data-known-size` attribute is incorrect:
<img width="958" alt="Снимок экрана 2020-06-19 в 13 05 20" src="https://user-images.githubusercontent.com/1203812/85121585-b4835600-b22d-11ea-8f91-079553ab6b6a.png">

I rely on this attribute for react-beautiful-dnd integration. Also I'm curios maybe this attribute used in library itself somewhere and if it incorrect does it break something?

If I scroll up/down this attribute become valid. Does it possible to show correct value right away?

**Comment by petyosi** [comment]
Hey @exentrich, 

Your observation is correct. The data attribute is used to pass *the assumed size* of the item to the DOM. After the render is done, [this hook](https://github.com/petyosi/react-virtuoso/blob/master/src/VirtuosoView.tsx#L39-L65) sees if the assumed size is incorrect and if so, sends the new value to the store for re-calculation. 

An optimization I have introduced is that, if overall the list looks fine (not shorter than the viewport), the list does not get re-rendered - hence the stale `data-known-size` attribute value. Doing so spares many re-rendering cycles. 

Up to the problem you describe - can you access the `offsetHeight` of the node directly? This is the first thing that comes to mind.

**Comment by petyosi** [comment]
@exentrich - this has been changed in v1, the number is up-to-date. Can you please check? #203 includes installation instructions and breaking changes.

**Comment by exentrich** [comment]
@petyosi Thank you! Great to hear that! This attribute is very useful for integration with `react-beautiful-dnd`
