### ISSUE TITLE
`adjustForPrependedItems` is not always synchronized with the new inserted data.

### ISSUE THREAD

**Issue by mgs95** [petyosi/react-virtuoso#138]
When there is more overload in the component (items are complex or several data is prepended), data insertion occurs before `adjustForPrependedItems`, making an akward jump.

The issue can be reproduced in the example https://virtuoso.dev/prepend-items/ by clicking quikly several times on `Prepend 100 items`. In my case this happens on each prepend because my items are more complex.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/23691885/85304621-400a1a80-b4ac-11ea-8072-b1c6fa540fdb.gif)

**Comment by petyosi** [comment]
Agreed, this is a known (and quite a complex issue) to address. The rest of the items with this tag are due to the same.

**Comment by mgs95** [comment]
Maybe, to solve this, you can request a new property (something like `nTopItemsAffected`) and forget about the `adjustForPrependedItems` function. In each update, if data size has changed **and** `nTopItemsAffected` is not zero you can adjust the scroll in the same render. I named the property `nTopItemsAffected` and not `nPrependedItems` so it can handle both insertions and deletions. Of course, this forces the user to keep track of the top affected items and has to set this value to zero when there are no new/old items at the top.

Btw, nice job with the library, I have tried a lot of virtualization libraries and this one is the best one for my needs :D .

**Comment by petyosi** [comment]
Thanks, the problem comes not due to the count, but due to the variable height of the prepended items. I am currently researching on a possible data-aware implementation that can handle jumps and pretends better.

**Comment by petyosi** [comment]
@mgs95 - fixing this was the major focus of v1, currently in beta. Please check #203 for installation instructions and breaking changes.
