### ISSUE TITLE
How to scroll to index on a useEffect

### ISSUE THREAD

**Issue by b-zurg** [petyosi/react-virtuoso#139]
I have a use case where I would like to scroll to an index as an effect but it seems to be troublesome using the `scrollToIndex` method.

I have a ref and am using the following code

```ts
  useEffect(() => {
    if (selectedIdx) {
      ref?.current?.scrollToIndex({ index: selectedIdx, align: "center" });
    }
  }, [selectedIdx, ref]);
```

I'm having the following error: 
```
 Error: Searching for max value in an empty tree
    at AATree.findMaxValue (react-virtuoso.esm.js:927)
    at OffsetList.itemAt (react-virtuoso.esm.js:1483)
    at react-virtuoso.esm.js:2037
    at react-virtuoso.esm.js:288
    at acc (react-virtuoso.esm.js:155)
    at react-virtuoso.esm.js:378
    at acc (react-virtuoso.esm.js:155)
    at react-virtuoso.esm.js:158
    at react-virtuoso.esm.js:174
    at react-virtuoso.esm.js:226
```

However if I set a timeout for 100 milliseconds and then run the scroll to selected then it works fine.  Any ideas?  I can provide more information if needed.

**Comment by petyosi** [comment]
The method is exposed when the scroll should happen at a later stage - can you try [using the `initialTopMostItemIndex`](https://virtuoso.dev/initial-index/) property instead?

**Comment by b-zurg** [comment]
Yes! It's an excellent property, but for me It's a bit tricky.  Here's my use case in a nutshell.

I have a tabbed interface that displays a list of items, this varies per tab.  Switching a tab doesn't unmount the component, but changes the results that are displayed and the selected result is shown in greater detail.

What I would like to do is scroll to the selected result for each tab.

Because the component is not remounted on a tab switch then the `initialTopMostItemIndex` property will not work after the first time.

**Comment by petyosi** [comment]
It looks like you are calling the method at a specific time when the internal structures are empty for some reason. Can you replicate it in a sandbox? I will take a look.

**Comment by b-zurg** [comment]
It turned out to be difficult to, which means I don't really understand the root cause of the issue.  I have worked around the issue by actually not rendering when switching data sets, as the data is null (though handled and set to defaults) for a little bit as the results load.  Some thing I'm doing is definitely the cause of this, and it seems to be a pretty edge-case situation.  

This is working for now, though I'd like to spend some time seeing if I can reproduce this later as that would just make the library more resilient :)  As I can't do that right now I'll close the issue. 

Thanks for your attention!

**Comment by petyosi** [comment]
There are lots of heuristics and possible race conditions with `scrollToIndex`, including one dreadful `setTimeout`. I think that at some point I have to fix the entire logic, but I am yet to figure out how to do it reliably. 

If at any point you stumble at any further clues, please share them. Cheers!
