### ISSUE TITLE
cant find vrituoso in windows global while using umd release

### ISSUE THREAD

**Issue by stunaz** [petyosi/react-virtuoso#14]
Hi, I wanted to test that lib on an umd application.
After putting the https://unpkg.com/react-virtuoso@0.7.0/dist/react-virtuoso.umd.production.js in the the head of my html. i cant find the Virtuoso.

Tried
- window.ReactVirtuos0
- window.Virtuoso

**Comment by petyosi** [comment]
Hey, 

In the UMD bundle, you can access both `Virtuoso` and `GroupedVirtuoso` from the `window['react-virtuoso']` object.

Cheers,
