### ISSUE TITLE
Remove scarf-js

### ISSUE THREAD

**Issue by samsch** [petyosi/react-virtuoso#140]
This package is using scarf-js. The dependency should be removed, and all major versions using it should have patch bumps with the change.

final-form/react-final-form#822

**Comment by tannerlinsley** [comment]
Wow, you should take a quick moment and research what you keep posting on libraries that use scarf before you go any further. 

Let me set this straight, scarf is not malware.

It’s an analytics package that is gdrp compliant out of the box, collects install counts, version counts, and publicly linkable company information at dev-install time (and nothing else) and reports that information to a dashboard that only Maintainers have access to.

By definition, is not even close to malware, nor does it have any more malicious capability on your machine that any other npm library you install every day.

Now, that said, if you really wish that Maintainers personally don’t see your company’s name and website on internal lists of users, then just opt out.

If you choose not to opt out for whatever reason, and you just have some issue with my personal choice to include analytics in these libraries that Are distributed to you for free... then sure. Fork it, change it, get yourself stuck. It’s open source after all.

But for heavens sake, get your terms right. Usages analytics is nothing even close to your “malware” claims.

**Comment by samsch** [comment]
Updated, Scarf is being removed from other packages as well.

https://github.com/tannerlinsley/react-query/issues/676

@petyosi If you wouldn't mind, please consider this the issue also for any other packages where you use(d) Scarf.

**Comment by petyosi** [comment]
@samsch - thanks for raising the concern. I have followed your suggestion, although the package was providing valuable insight and information about the project adoption and activity - something which is important and motivational for me as the author. @tannerlinsley - are you aware of any reasonable replacement? The npmjs stats are far from accurate (I assume lots of automation pulls packages, etc).

**Comment by samsch** [comment]
At the moment there isn't a direct replacement that was mentioned in discussion.

@aviaviavi (author of Scarf-js) is working to figure out a solution which doesn't have the same concerns, while also being implementable for various OSS devs. There's continued discussion on Reactiflux (mostly been in #news-and-links, but probably should move from there for being off-topic lol), with one potential idea to use a docs site that's self-hosted so you could do an IP->public business lookup (without storing IPs) of incoming requests without tracking real users, using in-library tools for non-library features (pre/postinstall for non-installation functionality), or sending potentially sensitive information without standard masking options.

**Comment by arjundevarajan** [comment]
@samsch @petyosi quick update here (nearly three years later!) the [Scarf project](https://about.scarf.sh/scarf-gateway) does now actually address most of these concerns. It's GDPR-compliant, so it doesn't store IPs long-term and it doesn't require a post-install hook, but it **does** still gather basic analytics around what companies are installing OSS software and where they're located, etc. Just thought it was worth mentioning!
