### ISSUE TITLE
Empty component prop

### ISSUE THREAD

**Issue by WillSquire** [petyosi/react-virtuoso#142]
An `emptyComponent` option could be a nice addition to render a component when the list is empty (i.e. `totalCount` = 0). A bit like MUI's `noOptionsText` on `autocomplete`, which renders when the options count is 0.

Just started using this library by the way and it's been a complete pleasure so far on a bit of pain point (infinite scrollers). So kudos!

**Comment by petyosi** [comment]
Thanks @WillSquire - that's an easy intro and a sensible one. I will mark it as PR welcome if someone beats me to it.

**Comment by petyosi** [comment]
Available in `v0.20.0`. Cheers to @shoNagai
