### ISSUE TITLE
Dynamic container height error

### ISSUE THREAD

**Issue by boomfly** [petyosi/react-virtuoso#144]
I am writing messenger app and try to make messages list starting from bottom.

Here example of issue: https://stackblitz.com/edit/react-virtuoso-container-autoheight-issue?file=example.js

Type some message and press button.

When new message added to list, Virtuoso height and top values recalculated and throws this error:

`TypeError: Cannot read property '0' of undefined`

But if uncomment line 31-33 which add some messages and fill full height it works normal without exceptions.

Error occurs in https://github.com/petyosi/react-virtuoso/blob/0f29dce3818d25817ceef0dea8228e1e3811c349/src/GroupIndexTransposer.ts#L66

**Comment by petyosi** [comment]
@boomfly I think I found the issue (some 0 / 0 divisions). Can you test with `0.17.6-beta`? It [works in the example](https://stackblitz.com/edit/react-virtuoso-container-autoheight-issue-811loy?file=package.json) you gave.

**Comment by boomfly** [comment]
@petyosi Thanks! It work, but i can't find source of 0.17.6-beta. It's your local version?

**Comment by petyosi** [comment]
Yeah, I haven't pushed yet. I wanted to verify the fix with you before I publish the next release.

**Comment by petyosi** [comment]
@boomfly I published 0.17.6
