### ISSUE TITLE
Display: none issue

### ISSUE THREAD

**Issue by KiyoshiMori** [petyosi/react-virtuoso#145]
Hi.
I got some bug that troubling me to use this library.

You can check it here: https://codesandbox.io/s/cool-feather-45gui?file=/src/App.js
If you'll start to fast clicking from tab1 to tab2, you should notice some thrown error from the library. `"Requested offset outside of the known ones, index: 0"`

As far as I could understand, it's related to display: none and visibility-observer. Because when itemHeight is set you won't get this error. But it can't be a solution for me, because of my groupItemHeight and ItemHeight are different and I want autoheight anyway.

**Comment by petyosi** [comment]
This could be an easy fix. However, I had trouble reproducing it :(, perhaps I did not click too fast. Can you record a video? Also, please provide some info about browser / OS.

**Comment by petyosi** [comment]
oh, I think I figured it out. You need to scroll down the list first.

**Comment by KiyoshiMori** [comment]
For now (or sometimes) it's happening when I'm clicking not even fast. 
https://a.uguu.se/UVTl2wFD0pho_react-virtuoso

I'm using Linux & chrome. My colleague using Windows and he has it too.

**Comment by KiyoshiMori** [comment]
Also, if it could help, you can check this example to realize that it's happening precisely because of display: none/visibility-observer.
https://codesandbox.io/s/determined-ganguly-o8oem?file=/src/App.js

**Comment by petyosi** [comment]
@KiyoshiMori - the issue is addressed in v0.17.7
