### ISSUE TITLE
How can I hide the sticky group-title when using GroupedVirtuoso.

### ISSUE THREAD

**Issue by shawnwangzZ** [petyosi/react-virtuoso#146]
In my case, I don't want the title sticky on top. I've tried to set the GroupContainer, but initialTopMostItemIndex will have some problem.
Here is the case.
`import React from 'react'
import { GroupedVirtuoso } from 'react-virtuoso'

const groupRender = index => {
  return <div style={{height: 20}}>group-{index}</div>
}

const itemRender = index => {
  return <div style={{height: 80}}>item-{index}</div>
}

const groupContainer = ({ children, style, ...restProps }) => {
    let newStyle = { ...style };
    newStyle = { ...style, position: 'relative' };
    return (
      <div {...restProps} style={newStyle}>
        {children}
      </div>
    );
  };

export default () => {
  // set the initialTopMostItemIndex to 999 to have the list start at the bottom
  return (
    <div>
      <GroupedVirtuoso
        groupCounts={[10,20,30]}
        overscan={200}
        initialTopMostItemIndex={3}
        group={groupRender}
        item={itemRender}
        style={{ height: '400px', width: '350px' }}
        GroupContainer={groupContainer}
      />
    </div>
  )
}`
Is there a solution to this?
Thanks!

**Comment by petyosi** [comment]
@shawnwangzZ if you don't want the sticky headers, the best option would be to use the flat list and render headers at specific indexes. Hope this makes sense.

**Comment by shawnwangzZ** [comment]
Thanks! I solved this with your suggestion.

**Comment by lynhan318** [comment]
I resolve this by adding visibility:'hidden' to the sticky element.
