### ISSUE TITLE
Overscan property ignored in GroupedVirtuoso when scroll position is at the top of the list

### ISSUE THREAD

**Issue by tschortsch** [petyosi/react-virtuoso#148]
It seams that the `overscan` property of the `GroupedVirtuoso` component is ignored when the scroll position is at the top of the list. As soon as I start scrolling the `overscan` value seems to work and the list items get preloaded. When scrolled back to the top of the list the preloaded list items are removed again.

You can reproduce this issue with the StackBlitz example from this doc page: https://virtuoso.dev/grouped-numbers/

Demo video: https://vimeo.com/441256062

Versions:
* react-virtuoso 0.17.7

**Comment by petyosi** [comment]
True.

**Comment by alaboudi** [comment]
The overscan prop does not work for me when used in the `GroupedVirtuoso` component as well

**Comment by petyosi** [comment]
@tschortsch @alaboudi this is fixed in v1 (in beta). Please test and give feedback. #203 includes installation instructions - please check the breaking changes.
