### ISSUE TITLE
Alternate row color

### ISSUE THREAD

**Issue by x4080** [petyosi/react-virtuoso#15]
Hi, I tried your component and works fast ! I wondered if we can add alternate row color using
 ```&:nth-of-type(odd)```

Since the item that we supply is inside another div, so it always @ 0 numbered row

Thanks

**Comment by petyosi** [comment]
Using nth-of-type won't work I am afraid - the component moves elements around, so an even item can become odd when you scroll down. 

You can use the item index instead - something [like this](https://stackblitz.com/edit/react-1dnzbx?file=example.js).

**Comment by x4080** [comment]
Thanks I think that will fix it
