### ISSUE TITLE
Support for a "data" prop

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#151]
Coming from `react-window` I'm missing the `itemData` prop, which allows for passing some extra arbitrary data down to children, it's pretty handy and makes for much cleaner code that doesn't need to resort to wrapping components, using React's contexts, or using some other more convoluted way to pass state down the tree.

**Comment by petyosi** [comment]
Agreed. I understand the practical aspect of the data context and am currently looking into it.

**Comment by petyosi** [comment]
`data` is available in v1 - check #203.

**Comment by fabiospampinato** [comment]
This kinda got implemented in v1, but in a way that makes it useless for my use case at least, since my "data" property is an array of objects to pass to _all_ items, there's no 1-to-1 mapping between my data array and my items array. 

IMO this extra limitation isn't worth it the extra convenience, like supporting other use cases has been traded for some extremely minor potential convenience (sparing the user a property access: `data[index]`), not worth it.

**Comment by petyosi** [comment]
In its current state, data brings a valuable feature - you can refresh the component contents without the awkward `data-key` property. 

What you describe sounds more like a `context` prop to me. What do you think?

**Comment by fabiospampinato** [comment]
Yeah exactly, that's how it works in `react-window`, perhaps the name chosen there wasn't perfect.

I'd be cleaner to just have 1 prop though rather than two largely overlapping ones.

**Comment by petyosi** [comment]
More of a note to myself: from what I understood [in this react-window thread](https://github.com/bvaughn/react-window/issues/85), `itemData` feels like a pre-hooks design choice - to me at least. The thread also alludes to certain optimization aspects of it.

**Comment by fabiospampinato** [comment]
It's kind of documented here: https://react-window.now.sh/#/api/FixedSizeList

> Contextual data to be passed to the item renderer as a data prop. This is a light-weight alternative to React's built-in context API.
