### ISSUE TITLE
Support having no "item" component

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#152]
I have a use case where each item in my list is essentially an HTML string, which I set in the ItemContainer component directly as otherwise I would have to provide another wrapper for it in the Item component. 

I'm currently just using `() => null` as an Item component, which btw triggers a TypeScript type error for some reason, but I would like better if I could just not set an Item component, maybe not dealing with Item components at all would also speed things up slightly 🤔

**Comment by petyosi** [comment]
@fabiospampinato - this is working in v1. You don't have to provide `item` (renamed to `itemContent`). #203 has installation instructions and breaking changes.
