### ISSUE TITLE
Improved support for scrolling to the very end

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#154]
Scrolling to the very end of a virtualized list where the height of items is not known causes a scenario where the end is first reached, then items get actually loaded and now the list is not scrolled till the end anymore and requires another potentially short scroll to reach it.

Maybe this fairly common use case could be improved on at the library-level.

**Comment by petyosi** [comment]
Hey, 

If I understand correctly your explanation, [the `followOutput` property](https://virtuoso.dev/stick-to-bottom) is supposed to address exactly that. Let me know if this is so.

**Comment by fabiospampinato** [comment]
@petyosi It sounds like something like that could help, in my use case "totalCount" is not increased though, simply once the last list items are loaded they end up taking more space than anticipated so the whole list stops being fully scrolled to the bottom 🤔

**Comment by petyosi** [comment]
I see. That's not something taken into account indeed. Does it work if you call the `scrollToIndex` method after the update?

**Comment by fabiospampinato** [comment]
@petyosi I haven't played with that but I guess when used properly it would work, I think this is something that should be taken care of at the library level though. 

In order to implement this properly one would need to detect when the end is scrolled too, when all visible items are loaded, maybe also how much time it passed since the end was first reached, if the user performed a scroll since the end was first reached and many other things too. These kinds of details seem more relevant to Virtuoso, probably it should take care of this rather than each app using it.

**Comment by fabiospampinato** [comment]
By the way this is a problem when scrolling to the very top too.

**Comment by jan-wilhelm** [comment]
@fabiospampinato have you found any workaround? I am running into the same problem myself

**Comment by choksheak** [comment]
I can confirm this is still happening. Virtuoso v1.9.3. Tried with 1000 rows, did scrollToIndex(999), and it can never get to the bottom. Virtuoso is a fantastic tool and having this blocking bug is very unfortunate indeed!!

**Comment by petyosi** [comment]
Closing this. see my comment - call `scrollToIndex` when the content get loaded. Detecting content load is outside of the scope of the library.
