### ISSUE TITLE
webpack: Failed to compile

### ISSUE THREAD

**Issue by AyumiKai** [petyosi/react-virtuoso#16]
ERROR in ./node_modules/react-virtuoso/dist/react-virtuoso.es.production.js
Module parse failed: /Users/xx/Desktop/xx/react-virtuoso/dist/react-virtuoso.es.production.js Unexpected token (1:12692)
You may need an appropriate loader to handle this file type.
--------------------------------------------------------------------------------------------
hi @petyosi , my packages version:
      "webpack": "^3.7.1",
     "@babel/core": "^7.1.2",
    "@babel/plugin-syntax-class-properties": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/polyfill": "^7.0.0-rc.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",

**Comment by petyosi** [comment]
This does not ring a bell. I am using [tsdx](https://github.com/palmerhq/tsdx) for the entire build/package setup, and the build artifacts work as expected in a CRA scaffold, Stackblitz, and CodeSandbox. What's the setup of your project? Perhaps you can compare it to the CRA scaffold and figure out what's the difference that causes this problem.

**Comment by AyumiKai** [comment]
> This does not ring a bell. I am using [tsdx](https://github.com/palmerhq/tsdx) for the entire build/package setup, and the build artifacts work as expected in a CRA scaffold, Stackblitz, and CodeSandbox. What's the setup of your project? Perhaps you can compare it to the CRA scaffold and figure out what's the difference that causes this problem.

yeah,It is my babel configuration  problem
