### ISSUE TITLE
Use default browser scrollbar

### ISSUE THREAD

**Issue by AkalUstat** [petyosi/react-virtuoso#161]
is there a way to avoid two scrollbars when using the virtualized list (and use the browsers default scrollbar)?

**Comment by petyosi** [comment]
By the default scrollbar I assume you mean the one attached to the window. This is not supported currently. Can you describe what you are trying to achieve? A screenshot or an example can help me understand better. 

Cheers,

**Comment by AkalUstat** [comment]
![Screen Shot 2020-08-11 at 5 34 02 PM](https://user-images.githubusercontent.com/43657841/89962197-e6df7d00-dbf8-11ea-89a8-27546598924a.png)
sure! as you can see here, the list has its own scrollbar and the whole webpage has its own individual scrollbar. Asking because according to [this thread]https://stackoverflow.com/questions/39180500/avoiding-double-scrollbars-with-grid-component-and-a-website-header() react virtualized can support just the one

**Comment by Alino** [comment]
my workaround here was to hide the main scrollbar with overflow-y: hidden

**Comment by petyosi** [comment]
Merging with #40
