### ISSUE TITLE
Error when using scrollToIndex inside an effect

### ISSUE THREAD

**Issue by BrentFarese** [petyosi/react-virtuoso#163]
An error seems to arise when using [scrollToIndex](https://virtuoso.dev/scroll-to-index/) inside an effect in React (e.g., `useEffect`).  The error:

`Error: Searching for max value in an empty tree`

The only related thing I found is [this thread](https://gitmemory.com/issue/petyosi/react-virtuoso/139/650760907).

Is this a known bug?  My way around it right now is to wrap the call to `scrollToIndex` inside a standard try/catch and that seems to work for right now (as it catches the error and seems to scroll to the right index after that).  But, is there a fix for this?  Happy to look at some source if someone points me to the `scrollToIndex` logic.

Great project!  Thank you.

**Comment by petyosi** [comment]
@BrentFarese Can you reproduce that in a codesandbox or stackblitz? I will take a look (and most likely fix it) as soon as I get a reliable repro.

**Comment by BrentFarese** [comment]
Yes, I was just able to reproduce the error in this [Codesandbox](https://codesandbox.io/s/react-virtuoso-bug-4o9vn?file=/src/Drawer.tsx).  Just click the "Open Drawer" button and you will see the error arise.

The example is slightly different from my setup where the error occurred, in that in the Codesandbox I use a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) whereas in my production code I just use [useRef](https://reactjs.org/docs/hooks-reference.html#useref) per react-virtuoso's documentation.

But, it seems the same error I get in my prod code arises in the Codesandbox when using a callback ref.  Doesn't seem to happen when just using `useRef`, but I am not sure why.

Hopefully this reproduction helps.  Thank you for looking at it!
