### ISSUE TITLE
GroupedVirtuoso does not work with React Testing Library

### ISSUE THREAD

**Issue by alaboudi** [petyosi/react-virtuoso#173]
Firstly, thanks for your work on the library.

I seem to be having issues with the GroupedVirtuoso component when testing it with React Testing Library. When I render the list, it comes out empty. I went through some of the issues previously raised issues and noticed a fix for the Virtuoso component (https://github.com/petyosi/react-virtuoso/issues/26). In that thread, the `initialItemCount` prop was suggested. Unfortunately that prop is not available on the GroupedVirtuoso component.

 Is there a similar fix for the GroupedVirtuoso component to enable SSR rendering?

**Comment by petyosi** [comment]
Hey, 

`initialItemCount` is an SSR oriented feature, and making it work for grouped virtuoso is not trivial. I am not familiar with React Testing Library, but the built-in [testing tools from React](https://reactjs.org/docs/testing-recipes.html) execute the `useEffect` hooks, meaning that grouped virtuoso should work in there (I haven't checked). 

Is there any way to make react testing library execute the hooks? Or are you specifically interested in testing the SSR?

**Comment by petyosi** [comment]
@alaboudi - in v1 (see #203), I added testing for SSR and grouped virtuoso. Here's how [the tests](https://github.com/petyosi/react-virtuoso/blob/next/test/ssr.test.tsx) look. Can you take a look? Please comment here with your findings, I will re-open the issue if necessary. 

Regards,

**Comment by ritu-coder** [comment]
@petyosi I am stuck with the same issue as OP.
@alaboudi did you figure out anything?

**Comment by GrrrLaChubby** [comment]
@petyosi , Hello i have the same issue with grouped virtuoso and your test link doesn't work. Do you have another link with test example ?

**Comment by istee** [comment]
Had the same issue, tried setting `initialItemCount`, but that didn't help:
```<GroupedVirtuoso
  style={style}
  groupCounts={groupCounts}
  groupContent={(index) => <GroupContent index={index} />}
  itemContent={(index) => <ItemContent index={index} />}
  initialItemCount={groupCounts.reduce((partialSum, a) => partialSum + a, 0)} // still no items are rendered in test environment
/>```

I ended up setting to `overscan` to a high number, so that every item is rendered, and virtualisation is basically disabled, as a workaround:
```<GroupedVirtuoso
  style={style}
  groupCounts={groupCounts}
  groupContent={(index) => <GroupContent index={index} />}
  itemContent={(index) => <ItemContent index={index} />}
  {...(process.env.NODE_ENV === 'test' ? { overscan: Number.POSITIVE_INFINITY } : {})} // workaround: setting overscan to a high value, so that every item is rendered
/>```
