### ISSUE TITLE
Retrieve visible rows?

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#174]
Hi, I'd need a way to retrieve the visible rows rather than the rendered ones (so, I'd need to exclude the overscan).

I can't seem to find any API to do that, may you help me please?

**Comment by petyosi** [comment]
Hey,

Check https://github.com/petyosi/react-virtuoso/issues/118 for details and potential workaround.

**Comment by FezVrasta** [comment]
Great thanks!
