### ISSUE TITLE
Is chat like endless bottom top scrolling with threshold possible?

### ISSUE THREAD

**Issue by JakeSchroeder** [petyosi/react-virtuoso#175]
Hey @petyosi thanks for this lib and all the work youve done on it.

I am building a chat-app and require the functionality of starting at the bottom, scrolling up and endlessely appending items with prefetching so it loads before the user scrolls to the top. Essentially like all the standard chat/convo apps.

Is this actually possible in the libs current state? Ive spent the better part of 3 days trying to get a demo working but the overscan, scrollbar, startReached and scrollseek seem to be broken/janky and not working as expected and it seems the issues are not being resolved.

I saw issue  https://github.com/petyosi/react-virtuoso/issues/44#issuecomment-580755793 where a possible work around was in place but this inverts the scrollbar... is there anyway to get that working properly or any other workarounds you know of? Thanks again.

**Comment by osadchiynikita** [comment]
+1 Also wondering @JakeSchroeder were you able to implement such behavior?

**Comment by felippepuhle** [comment]
There are some demos handling chat scenarios, the only one I wasn't able to do is: if fewer messages, messages should be bottom aligned.

**Comment by petyosi** [comment]
@felippepuhle there's a property for that, alignToBottom.

**Comment by felippepuhle** [comment]
@petyosi omg I'm so sorry, I didn't see it... nice work, we'll definitely use this package on our app!
