### ISSUE TITLE
[Bug] initialTopMostItemIndex render no list item when total items height is less than the container height

### ISSUE THREAD

**Issue by harish-aka-shivi** [petyosi/react-virtuoso#176]
Hi @petyosi, Thanks for the amazing library.

I am facing a bug related to `initialTopMostItemIndex`. 

When the sum of total items height is less than Container/Virtuoso height, and there is no scroll bar visible, then if I add a positive value to the `initialTopMostItemIndex` prop, the list renders as an empty list.

Here is the reproducible URL:
https://stackblitz.com/edit/react-l1eibb-gjtdpd?file=example.js

It is rendering as an empty list even though there are items present. if you increase the total count, it will render correctly

**Comment by chrisdostert** [comment]
> Hi @petyosi, Thanks for the amazing library.

+1 thank you!

Are there any known workarounds for this or is a fix in sight? This is a pretty major bug for chat applications at least.

**Comment by harish-aka-shivi** [comment]
The way I worked around this is by not using this method and instead using `scrollToIndex`

**Comment by megos** [comment]
I'm using `followOutput` instead of `initialTopMostItemIndex`.
If don't want to use this, `followOutput` uses when first render only. The sample code is below.

```jsx
const [followOutput, setFollowOutput] = useState(true)

<Virtuoso
  followOutput={followOutput}
  endReached={() => setFollowOutput(false)}
  ...
/>
```

**Comment by petyosi** [comment]
@harish-aka-shivi @chrisdostert @megos - I am working on the next release, `v0.21.0-alpha.2` [is addressing that bug](https://stackblitz.com/edit/react-l1eibb-3pbgdm?file=package.json). If possible, please test this release as there are many changes in it that I would like to verify before promoting to the official.

**Comment by petyosi** [comment]
To avoid breaking changes for v0 users, I am going to launch the next version as v1.0 (in beta). Check #203 for installation instructions and breaking changes.

**Comment by chrisdostert** [comment]
I tried the latest beta and I am still seeing this bug or one similar to it. If Initially I have one chat message and then add another chat message, the list goes blank. I'll try to find carve out some time to create a repro

**Comment by petyosi** [comment]
@chrisdostert - sounds like an evolution of some sort :). Please open a new issue once you get that repro. Thank you!
