### ISSUE TITLE
Strange bug with react dev tools 

### ISSUE THREAD

**Issue by ivandotv** [petyosi/react-virtuoso#177]
A strange thing is happening with react virtuoso in combination with react developer tools. As you can see from the video, when `highlight component updates` is switched on, and slow scrolling, the list keeps resetting to the top. 
Maybe it's some strange combination of my setup, or perhaps it's the library, I just wanted to let you know.
I've spent four hours debugging this, so I thought I should make a not of it here in case someone else experiences this.

**OS**: Linux (Wayland) 
**browser**: Chrome: Version 86.0.4240.75 (Official Build) (64-bit)
**react extension**:  DevTools version 4.8.2-fed4ae024

![Peek 2020-10-09 22-26](https://user-images.githubusercontent.com/390700/95628553-92347300-0a7e-11eb-87d4-d58da403fd4d.gif)

**Comment by petyosi** [comment]
Thanks for reporting that, likely the outline triggers a resize of some sort. I will take a look.

**Comment by petyosi** [comment]
Seems to be working fine with the current state.
