### ISSUE TITLE
Support CSS grid layout?

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#178]
Hi, I was trying to update my react-table + react-virtuoso table to use the new CSS grid layout provided by react-table but I realized Virtuoso needs one DOM element for each row to work.

Do you think it could be possible to use CSS grid with Virtuoso?

Example of react-table rendered with CSS grid:
![image](https://user-images.githubusercontent.com/5382443/96009101-8a8b1a80-0e40-11eb-8b5f-375f18912e77.png)

**Comment by petyosi** [comment]
Hey,

No, this is not supported by design and needs a ground-up reimplementation. Tables are a very different beast.
