### ISSUE TITLE
Detect isAtTop

### ISSUE THREAD

**Issue by WillSquire** [petyosi/react-virtuoso#179]
For hiding/showing scroll to top buttons - it might be nice to have a isAtTop property for 'batteries included' programming or being able to pass the `onScroll` prop to Virtuoso directly to get the scroll position (rather than through `ScrollContainer` prop).

**Comment by petyosi** [comment]
Hey @WillSquire ,

there is no special event for reaching top, but you can hook up to `rangeChanged` and use the top index for that purpose. It is not super accurate, but, unless your items are very tall, it should work reasonably well.

**Comment by WillSquire** [comment]
Thanks @petyosi ,

Great :) that works, but it does seem to only be triggered after the 3rd item (scrolling two pages down). Can this be made more accurate?

**Comment by petyosi** [comment]
Not sure what you mean - the event is triggered correctly: https://virtuoso.dev/range-change-callback/

**Comment by WillSquire** [comment]
Wow, that was fast. Thanks for the lightning response time. 

I think it's because I've got the `overscan` property set, however it tends to stutter on each page load without it (it's an infinite loader). This can be a closed issue as it does work, but I'd be curious on how to trigger it more frequently with `overscan` set?

Thanks

**Comment by petyosi** [comment]
Yep - indeed the overscan will cause the range changed to "lag". I am looking at ways to address that, will keep it open for now.

**Comment by petyosi** [comment]
This is easily doable these days using `onScroll` prop. All DOM attributes are assigned to the scroller element.
