### ISSUE TITLE
"SCRIPT1028: Expected identifier, string or number" error in MS Edge apparently due to a transpile issue

### ISSUE THREAD

**Issue by stoich** [petyosi/react-virtuoso#18]
Adding the virtuoso-package to our app causes it to crash with following error message ins MS Edge: "SCRIPT1028: Expected identifier, string or number". As far as I can tell MS Edge still doesn't support the es6 spread operator so seems this relates to how react-virtuoso is transpiled to es5

**Comment by petyosi** [comment]
Thank you for the report. Root cause was palmerhq/tsdx#101. Upgrading to the latest version solved the problem. Also, https://virtuoso.dev/ works in edge now.
