### ISSUE TITLE
Pass more props to item

### ISSUE THREAD

**Issue by WillSquire** [petyosi/react-virtuoso#180]
At the moment I get props by passing a closure to `item` that has things like `items` inside of it to access the payload, but it would be nice if I could pass additional props to it via a `itemProps` property (bit like what Mui do with `TextField`, etc). Other than keeping the item renderer out of the component, it would help to avoid using `useCallback` to prevent re-renders. It gets a bit bloated and complicated on detailed items.

**Comment by petyosi** [comment]
@WillSquire in V1, I introduced a `data` prop (`any[]`) the items from which is then supplied in the `itemCallback`, previously known as `item`. Hope this makes sense.
