### ISSUE TITLE
Transition causes scroll to jump

### ISSUE THREAD

**Issue by WillSquire** [petyosi/react-virtuoso#181]
If a transition animation is triggered whilst scrolling, scrolling will 'jump' to a previous scroll position. Unsure if this is library specific or if it's an underlying dom api triggering this, but whilst using [Mui Zoom](https://material-ui.com/api/zoom/) to show a scroll to top button once the user has scrolled down a bit (mentioned [here](https://github.com/petyosi/react-virtuoso/issues/179)) it causes the scroll position to 'jump' back up a few hundred pixels. Tried with other animations and it still happens (all using [react-transition-group](https://reactcommunity.org/react-transition-group/transition#Transition-props) under the hood). 

As soon as I removed the animation and just had it mount/unmount in and out it was ok and didn't jump (although there might have been a frame missing, but I couldn't really notice). Checked all the props going to `virtuoso` for equality (incase it was triggering a re-render of the component), but it didn't look like it.

Hopefully this helps someone else as it blew a day away for me!

**Comment by petyosi** [comment]
Hey, 

do you have a repro for that? I would like to take a look. Thanks!

**Comment by petyosi** [comment]
@WillSquire - I have released v1 beta, can you try it in your case? Not sure if it will help (#203 includes installation instructions). Comment here, I will re-open the issue if necessary.
