### ISSUE TITLE
Re-rendered because of hook changes

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#183]
Hi, I'm trying to improve the performance of my app and I noticed a lot of these messages:

![image](https://user-images.githubusercontent.com/5382443/96882097-3b1b9e80-147f-11eb-88bf-ace9c6dd3592.png)

They seem to be related to the VirtuosoStore.tsx file, do you think there could be a way to memoize the value to avoid unnecessary rerenders?

**Comment by petyosi** [comment]
@FezVrasta I haven't seen that - can you send a repro?

**Comment by FezVrasta** [comment]
Oh the message comes from [why-did-you-render](https://github.com/welldone-software/why-did-you-render), once enabled it logs this useful info.

The problem seems to be that the `render` function in `VirtuosoStore.tsx:177` is inline so it changes identity on each render.

**Comment by petyosi** [comment]
@FezVrasta thanks - I think I found what's going on, but I need to test the fix better. As far as I can see, it does cause a re-render initially, but not as you scroll. Let me know if I am on the right track.

**Comment by FezVrasta** [comment]
I get quite a lot of re-renders during the initial rendering phase (but that probably happens because I'm loading data asynchronously), but I also see it during scroll.

**Comment by petyosi** [comment]
Thanks. FWIW, I will try to get rid of the warning in the examples from the site.

**Comment by petyosi** [comment]
@FezVrasta @fabiospampinato - tried to play with why-did-you-render in [this example](https://stackblitz.com/edit/react-jn4qnf?file=example.js), but it does not seem to report any errors. Can you help? Thanks!

**Comment by FezVrasta** [comment]
wdyr only recently added support for the new React version, I think you need to update it and follow the instructions to enable it.

**Comment by fabiospampinato** [comment]
@FezVrasta just to check: are you seeing double renders with the production version of React? Because the development version double-renders on purpose.

**Comment by FezVrasta** [comment]
Yes it was the development version, isn't there any way to disable this behavior? I have other performance issues on that page and I can't figure out what's the problem with this double render.

**Comment by fabiospampinato** [comment]
@FezVrasta not that I'm aware of.

**Comment by Amethystafyy282** [comment]
Does anyone have any update on this? I've been testing recently and initial list got re-rendered a lot when using with `recoil` hooks (https://github.com/facebookexperimental/Recoil), other hooks like `useEffect` and `useState` are fine.

I've tried to use hooks in parent components but it didn't work out.
