### ISSUE TITLE
atBottomStateChange always return false when browser zoom is set to 90%

### ISSUE THREAD

**Issue by ZNackasha** [petyosi/react-virtuoso#184]
the following is a screen shot of dev tools showing the issue. we simply placed a breakpoint in the scrolledToBottomEngine function to see the values. please look at the watch list for clarification. looking at the scrollTop variable a decimal value simply does not make any sense to me.

![image](https://user-images.githubusercontent.com/11307112/97338960-607e2300-1858-11eb-8c98-fb518473cf39.png)

**Comment by petyosi** [comment]
Thanks, I will look into that.

**Comment by petyosi** [comment]
Fixed with #189.
