### ISSUE TITLE
List not updating with new items

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#187]
I have this bug where adding new items to a list doesn't make the list render the new items like it should.

I don't have a minimal repo that reproduces the issue, but I have recorded a video showing the issue in action: https://i.imgur.com/9OV4ERl.mp4, paragraphs of text on the left are rendered as items in a Virtuoso list on the right.

Basically new items are just not rendered, unless I scroll back far enough and then come back to the same position, perhaps resetting whatever internal bit of state is tripping Virtuoso, or after I add enough items Virtuoso finally decides to render them for some reason.

Any idea on what's causing the issue? Any workaround that I could try?

This is pretty much a deal breaker for my use case.

**Comment by petyosi** [comment]
Hello @fabiospampinato,

I have an idea what may cause that. Hopefully, the new `data` property I am working on will address the problem reliably. In the mean time, you can refresh the `dataKey` prop to manually tell the list to redraw. Here's [an example of it](https://stackblitz.com/edit/react-xlsdee?file=example.js). Please let me know if this works for you.

Regards,

**Comment by fabiospampinato** [comment]
From what I'm seeing setting a new `dataKey` causes the rendered items to be re-rendered, but since the new items were not rendered to begin with they are still not displayed 🤔 

Anything else I could try?

**Comment by petyosi** [comment]
@fabiospampinato this was a shot in the dark. I need to see a repro or at least a guidance on how you refresh the list to help further.

**Comment by fabiospampinato** [comment]
@petyosi Extracting a repro would be difficult as this component I'm using Virtuoso in is very much intertwined with the rest of the app, but essentially this is it:

```tsx
const Segments = ({ id, droppable, segments, className }: { id: string, droppable?: DroppableOptions, segments: MarkdownSegment[], className?: string }): JSXE => {

  const cache = useCache<CacheKey, CacheValue> ( id );

  const ScrollContainerWrapped = useCallback ( vprops => <ScrollContainer id={id} className={className} droppable={droppable} vprops={vprops} />, [id, droppable, className] ),
        ListContainerWrapped = useCallback ( vprops => <ListContainer vprops={vprops} />, [] ),
        ItemContainerWrapped = useCallback ( vprops => <ItemContainer segments={segments} vprops={vprops} />, [segments] ),
        ItemWrapped = useCallback ( index => <Item cache={cache} segment={segments[index]} />, [cache, segments] );

  return <Virtuoso style={{ height: 'auto', width: '100%' }} ScrollContainer={ScrollContainerWrapped} ListContainer={ListContainerWrapped} ItemContainer={ItemContainerWrapped} item={ItemWrapped} totalCount={segments.length} overscan={750} />;

};
```

Essentially a new `segments` value comes in, it will have one more segment in it, which would cause Virtuoso's `totalCount` prop to be updated, which should cause Virtuoso to render the new item since the list is scrolled to the very end, but that's not happening.

Also this issue doesn't happen for all values of `segments`, it seems that if the area where the new item would be rendered is already visible, i.e. there's no scrollbar because the current items don't fill all the available space, then the new item is rendered properly.

**Comment by petyosi** [comment]
I am 99% sure that this won't help - but, in order for the newly introduced item to become visible in this particular case, you should use the `followOutput` prop - [see demo](https://virtuoso.dev/stick-to-bottom). Otherwise, the newly introduced item won't be scrolled into view. However, this is not the problem in the video you sent - something does not get refreshed there. 

[Here's a working example](https://stackblitz.com/edit/react-jobtvx?file=example.js) that you can use as a starting point - if you can replicate what's going on, I will be able to help further.

**Comment by fabiospampinato** [comment]
> in order for the newly introduced item to become visible in this particular case, you should use the followOutput prop - see demo. Otherwise, the newly introduced item won't be scrolled into view. 

But I don't want them to be scrolled into view, I want them to be scrollable into view.

I've just tried `followOutput` and I can't notice any difference for my use case.

**Comment by petyosi** [comment]
@fabiospampinato - did this get sorted out with v1?

**Comment by fabiospampinato** [comment]
@petyosi I haven't looked into the issue more closely yet and I haven't upgraded to v1, I'll update you once I do that 👍

**Comment by fabiospampinato** [comment]
Upgrading to v1 seems to have fixed this problem! 🎉  Thanks for all the work you put on it!

Overall v1 feels snappier to me, which is super nice.

The upgrade experience overall wasn't too bad, but I had a couple of hiccups here and there, mainly regarding the changed behavior with `height: undefined` (it would be better to just throw an error here IMHO, or at least mentioning this in the migration guide), the requirement of `forwardRef` (and my ignorance with it) and the issue about assigning two refs to the same element. Nothing that can't be smoothed out though.
