### ISSUE TITLE
Empty list on display changes

### ISSUE THREAD

**Issue by GuillaumeAmat** [petyosi/react-virtuoso#19]
When the parent element of Virtuoso changes its display mode from visible to hidden, the list is eventually empty.

I use `@reach/tabs` and all the `TabPanel` elements contain a Virtuoso list. If I repeatedly click on the tabs to hide and display my lists, one of them end to be empty.

I also tested by manually set/unset `display: none` on the parent and the result is the same.

Any idea?

Thanks for the great work by the way 👍

**Comment by petyosi** [comment]
This seems plausible given the resize observable logic. I tried to reproduce it in [this example](https://stackblitz.com/edit/react-cv7uve?file=example.js), but it seems to work fine, so perhaps I am missing something.

 Can you fork the above so that I can reproduce it? Will take a look. 

Cheers!

**Comment by GuillaumeAmat** [comment]
I can't reproduce the behavior on your sandbox, this is really weird... Though, when I scroll a list, Firefox complains (warning in the console) about a positionning effect related to the scroll state.

The french warning message is:

> Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés.

I don't if it is related but it could be.

**Comment by petyosi** [comment]
Thank you. Went through the article, the warning is more generic, and not related. 

If you can deploy (or have deployed) your current setup somewhere, I can look at it. Perhaps there are other factors at play.

**Comment by petyosi** [comment]
@GuillaumeAmat - please ping me if you figure out something - I will re-open the issue. Thanks!

**Comment by GuillaumeAmat** [comment]
Sure, thank you for your time!

**Comment by GuillaumeAmat** [comment]
@petyosi I think I have a lead on that issue :)

I had a bit of time to test things here and there tonight and I figured this:

If I replace the

**Comment by GuillaumeAmat** [comment]
Picture this: I have three tabs (@reach/tabs), each containing a VIrtuoso list.

In the first I have 59 items and it never fails...
In the second I have 6 items, which are all displayed without scrolling (the last one is cut though).
And in the third one, I have 9 items.

All the items have the same height. SO when I switch over the 2 last tabs, after 2 times, the second list is empty and the last one only contains its last three items, as if the first 6 items were removed.

Another trip around finish to empty the third tab/list.

So, weird. ^^

**Comment by GuillaumeAmat** [comment]
Hey @petyosi, did you see my weird test? Could you consider reopening the issue?

**Comment by petyosi** [comment]
Hey @GuillaumeAmat  - where is the test you refer to? Is there anything I can run on my side? 

Apart from that, the change you refer to is not a feasible one, I am afraid.

**Comment by GuillaumeAmat** [comment]
> Hey @GuillaumeAmat - where is the test you refer to? Is there anything I can run on my side?

No online test, it is just the result of a "quick, naive and dirty" search. I was just hopping to ring a bell on a possible cause of that issue.

> Apart from that, the change you refer to is not a feasible one, I am afraid.

Yes of course, I wasn't asking that.
