### ISSUE TITLE
followOutput support for GroupedVirtuoso

### ISSUE THREAD

**Issue by osadchiynikita** [petyosi/react-virtuoso#191]
Hello @petyosi, first of all, thanks a lot for such helpful library, I was able to build solution I need with grouping and backwards  scrolling direction.

followOutput works great for `Virtuoso` plain list component, but it's not supported for `GroupedVirtuoso`

How complex is to add support for grouped and is it in near future plans? I

Thanks!

**Comment by petyosi** [comment]
Hey, 

That should be a trivial fix I think. I am working on a new release which improves the compatibility of the grouped and the regular component, so I will check how it works there.

**Comment by osadchiynikita** [comment]
@petyosi thank you! Feel free to ping me if testing or any else from my side needed

**Comment by petyosi** [comment]
@osadchiynikita I published an alpha version - v0.21.0-alpha.1. This is a [test case I did](https://stackblitz.com/edit/react-feqrnp?file=example.js). Notice that in addition to `true`, the `followOutput` now accepts `"smooth"` for a better UX. Interested in your feedback on that.

**Comment by osadchiynikita** [comment]
@petyosi Thank you for the very fast solution! On example I see it works exactly as expected. But in my app code I'm getting different TS compile errors. One is strange - `Uncaught TypeError: subscription is not a function`

Currently trying to debug and adapt my set up. Will provide more info once investigate

Here is the example of what props I'm using:

`
    <ListComponent
      ref={listRef}
      className={className}
      followOutput={'smooth'}
      item={(index: number) => renderItem(items[index], index)}
      startReached={isBackwards ? loadMore : undefined}
      endReached={isBackwards ? undefined : loadMore}
      computeItemKey={computeItemKey}
      initialTopMostItemIndex={getTopMostItemIndex()}
      rangeChanged={rangeChanged}
      groupCounts={groupCounts}
      group={group}
    />
`

**Comment by petyosi** [comment]
@osadchiynikita - Thank you very much; please reproduce that, I will take a look!

**Comment by petyosi** [comment]
nevermind, I got it. Undefined is not accepted as `endReached`. Will fix that, in the meantime you can work around it.

**Comment by petyosi** [comment]
Fixed in v1 beta.3 (along with `endReached` accepting undefined), check #203 for instructions.
