### ISSUE TITLE
Expose an event for scrolling to get access to scrollTop

### ISSUE THREAD

**Issue by wilderedin5** [petyosi/react-virtuoso#193]
Hi, I have several scrolls. I want to link them together. But to implement this, I need a scroll position.

Now I get the scroll position like this:
- Placed virtuoso in a div container on which to hang ref.
- Through ref, using the firstChild property, I made my way to the virtuoso container and got the scrollTop.

It will be cool if a callback appears that will return scrollTop from VirtuosoStore :)

**Comment by petyosi** [comment]
Agreed, many people have requested this.

**Comment by petyosi** [comment]
@wilderedin5 v1 (in beta) allows you to attach `onScroll` to the component (and any other HTML attributes or event handlers, for that matter). See #203 . 

Cheers,
