### ISSUE TITLE
VirtuosoGrid with groups?

### ISSUE THREAD

**Issue by caseyjhol** [petyosi/react-virtuoso#194]
Is there any way to combine VirtuosoGrid and GroupedVirtuoso? I've got a responsive grid of cards divided into groups. On wider screens there can be up to 3 cards in a row, and on small screens it's 1 card per row. The header row is full width regardless. All of the cards are the same height. Any ideas?

I'm trying with GroupedVirtuoso right now, and it's not working because there are multiple cards in a row (throwing off the container height).

**Comment by petyosi** [comment]
@caseyjhol - no, not supported at the moment. While possible, this is quite a complex feature to support. Closing, since I am not going to get to it in the foreseeable future.

**Comment by michaeltintiuc** [comment]
@paulm17 could you by any chance share your setup?

**Comment by paulm17** [comment]
> @paulm17 could you by any chance share your setup?

You need to go into a bit more detail.

**Comment by michaeltintiuc** [comment]
@paulm17 Which components did you use to achieve grouped grid as shown in the above loom video? I don't need the exact code, just the general concept, thanks for your quick reply btw!

**Comment by michaeltintiuc** [comment]
Ok, basically the idea is to make the grid a list? That's what I had in mind, but was wondering if there was something else. Thanks!

**Comment by rqbazan** [comment]
Hi guys @paulm17 @michaeltintiuc 

I sill don't get it, someone could share more information about the workaround for GroupedVirtuoso with grid elements? 🙏

**Comment by paulm17** [comment]
@rqbazan Loop through the array of items.  Making however many columns you want to show.  Then you group those into a row.  So a flat array turns into [[], [], [], [], []] and that's given to virtuoso.  Basically, virtuoso is taking a list array, but instead of 1 item being shown in the row.  The row then unpacks the array of items.  Is that clear?

**Comment by rqbazan** [comment]
Hey @paulm17, yes, thanks for the clarifications 🙏
