### ISSUE TITLE
followOutput breaks when item height changes

### ISSUE THREAD

**Issue by ath92** [petyosi/react-virtuoso#195]
Using latest version (0.20.1), `followOutput` breaks when an item changes height. I built a small example that should demonstrate this:

```javascript
export default function App() {
  const [total, setTotal] = useState(100)
  const [appending, setAppending] = useState(true)

  useEffect(() => {
    if (!appending) return () => {};
    function append() {
      setTotal(old => old + 1)
    }
    const interval = setInterval(append, 500)
    return () => clearInterval(interval)
  }, [appending])

  const [clickedIndex, setClickedIndex] = useState(null)
  const handleClick = useCallback(e => {
    setClickedIndex(parseInt(e.target.getAttribute('data-index')))
  }, [])

  return (
    <div className="App">
      <div>
        <Virtuoso
          totalCount={total}
          item={index => (
            <div
              onClick={handleClick}
              data-index={index}
              style={{
                height: index === clickedIndex ? '100px' : 'auto',
              }}
            >
              Item {index}
            </div>
          )}
          style={{ height: '100vh', width: '350px' }}
          followOutput
        />
      </div>
      <button onClick={() => setAppending(!appending)}>feed {appending ? 'on' : 'off'}</button>
    </div>
  )
}
```

As soon as you click an item and it resizes, the scroll position is no longer updated to follow the newly added items.

**Comment by petyosi** [comment]
@ath92 followOutput does not automatically monitor the resize of existing items - that would be very restrictive and can cause unwanted behavior. You can re-scroll the list to the bottom when expanding using the `scrollToIndex` method.

**Comment by ath92** [comment]
@petyosi That makes sense. The only caveat is that I'd need to know whether the list is already scrolled to the bottom, because if it isn't, I don't want to change the scroll position. Is there any way to find out if that's the case? At least the `ref` exposed by `Virtuoso` doesn't seem to provide that information.

**Comment by petyosi** [comment]
Correct, atBottomStateChange is the way to go.
