### ISSUE TITLE
List renders only single item when rendered in an iframe

### ISSUE THREAD

**Issue by Alino** [petyosi/react-virtuoso#196]
Hi, I have a component where I render this
```javascript
render() {
    return <Virtuoso
    totalCount={99}
    item={index => <div>Item {index}</div>}
    style={{ height: '400px', width: '100px' }}
  />
}
```

but only single one item is rendered 

![image](https://user-images.githubusercontent.com/763194/98810552-b689c380-241f-11eb-921c-e0fe2028b312.png)
![image](https://user-images.githubusercontent.com/763194/98810678-d9b47300-241f-11eb-9e5c-a2834b52896b.png)

anyone knows what could cause this?

**Comment by petyosi** [comment]
@Alino try reproducing the problem in a sandbox somewhere. My wild guess is that you are rendering the component hidden.

**Comment by Alino** [comment]
so I was playing around with this and found out that this happens when the component is rendered inside an iframe like this:

```javascript
import * as React from "react";
import * as ReactDOM from "react-dom";
import Example from "./example";

let iframeWrapper;
let iframe;
const defaultIframeWidth = 254;
const defaultIframeHeight = 477;
let iframeWidth = defaultIframeWidth;
let iframeHeight = defaultIframeHeight;
iframeWrapper = document.createElement("div");
iframeWrapper.id = "GCEP_globalPanelIframeWrapper";
iframeWrapper.className = "ui-widget-content";

iframeWrapper.style.position = "fixed";
iframeWrapper.style.top = "10px";
iframeWrapper.style.right = "15px";
iframeWrapper.style.zIndex = "2147483645";
iframeWrapper.style.borderRadius = "4px";
iframeWrapper.style.border = "solid 1px #ced1da";
iframeWrapper.style.overflow = "hidden";
iframeWrapper.style.backgroundColor = "rgb(239, 243, 246)";

iframeWrapper.style.height = iframeHeight + "px";

// overlay for draggable
const headerOverlay = document.createElement("div");
headerOverlay.id = "GCEP_globalPanelIframeOverlay";
headerOverlay.style.position = "absolute";
headerOverlay.style.top = "0";
headerOverlay.style.left = "0";
headerOverlay.style.width = "215px";
headerOverlay.style.height = "30px";
headerOverlay.style.zIndex = "2147483647";
headerOverlay.style.backgroundColor = "white";
headerOverlay.style.opacity = "0.001";
// reset css props
headerOverlay.style.padding = "0";
headerOverlay.style.margin = "auto";

iframe = document.createElement("iframe");
iframe.id = "GCEP_globalPanelIframe";
iframe.name = "GCEP_globalPanelIframe";
iframe.style.background = "#eff3f6";
iframe.style.border = "none";
iframe.frameBorder = "none";
// iframe.style.overflow = 'hidden';
iframe.style.zIndex = "100";
// iframe.scrolling = "no";

iframe.style.height = iframeHeight + "px";
iframe.style.width = iframeWidth + "px";

iframeWrapper.appendChild(headerOverlay);
iframeWrapper.appendChild(iframe);

document.body.appendChild(iframeWrapper);

iframe.contentDocument.write(`
        <html>
        <head>
            <meta charset="UTF-8">
        </head>

        <body style="background-color: #eff3f6; font-family: 'Source Sans Pro', sans-serif;">
            <div id="content">
                <!--<h1>Please wait...</h1>-->
            </div>
        </body>
        </html>
        `);

ReactDOM.render(
  <Example />,
  document
    .getElementById("GCEP_globalPanelIframe")
    .contentDocument.getElementById("content")
);
```

Here is a sandbox:
https://stackblitz.com/edit/lh3p1k--run?file=index.js
https://lh3p1k--run.stackblitz.io

**Comment by Alino** [comment]
is there a potential quick fix, or could you recommend to me any other alternative library please?
I tried react-window and react-virtualised already first but these had other issues with dynamic row sizes...

**Comment by petyosi** [comment]
I think this might be related to resizeObserver and its attachment to the original window. If you have the time, you can troubleshoot that.

**Comment by Alino** [comment]
I have cloned this repo to create unit test for this and fix it. After I looked at file ```Virutoso.test.tsx``` and I started doing this

```javascript
test('render more than one item inside an iframe', () => {
  const render = renderer.create(
    <div>
      <Virtuoso totalCount={100} initialItemCount={20} item={() => <div />} />
    </div>
  )
  const items = (render.toJSON() as any).children[0].children[0].children[0].children
  expect(items).toHaveLength(20)
})
```
I found out that the items.length is 1 unless you add an _initialItemCount_
And it also fixes my iframe issue.

**Comment by KeitelDOG** [comment]
I really like the Virtuoso package, and I use it after trying react-window and plugins, I prefer it.

I know the pattern is to only render the portion of items that has their parts in the Window range. But I was wondering, to improve scroll smoothing, if we could instead provide explicitly the Number of Items to be rendered. Like a `minRenderedCount={20}`.

My Items are complex enough, and are displayed like 3, 4 or 5 in a screen, maybe setting it to render 20 would be smoother when scrolling, to avoid waiting for client to render each time.

The virtualization solve the problem of RAM in a single tab, when you have large list, that could be 100 - 1,000 - 10,000 or more depending on data size. But there could be a compromise that consider the Screen as a 2x or 3x time screen height, and load 2x or 3x items instead.

I'm aware of Overscan for pre-calculation, React.memo, etc. But it's for rendering, like a pre-rendering too.

Maybe I'm wrong, but I think it would definitely be a smoother experience when the Item is complex with Images, long main Text and multiple other parts, like a Post. Because rendering them on the go can be a bit slow on items off screen.

**Comment by petyosi** [comment]
@KeitelDOG - not sure how your comment is related to the initial problem in this issue - can you clarify? Apart from that, I am personally not a fan of the overscan property, especially when combined with complex items which include images. However, you can give your idea a go - if it works better for certain cases, I would love to accept a PR.

**Comment by Alino** [comment]
I am closing this, as I think this is not relevant anymore since the big refactor.
