### ISSUE TITLE
Footer with VirtuosoGrid?

### ISSUE THREAD

**Issue by NTag** [petyosi/react-virtuoso#197]
Is it possible to have a footer with `VirtuosoGrid`? Which wouldn't be part of the grid but below it. If I try to add a `footer` prop to `VirtuosoGrid` I have a typing error.

**Comment by petyosi** [comment]
Not supported currently, but easy to add. If you decide to contribute, I may suggest you wait for a week or so, since I am in the middle of a large refactor.

**Comment by itayganor** [comment]
Is there a change for this being resolved? I'm looking for a header/footer solution to add top and bottom paddings to the scroller, just like we do in the regular List component.

I tried to contribute but the learning curve of the implementation makes this difficult since it's a new behavior for grid.

Thank you!

**Comment by harrisonlo** [comment]
@petyosi I think it's quite common to have top and bottom paddings in layouts, and most of us are "hacking" that with the `Header` and `Footer` components. What do you think about just adding a simple prop for the vertical paddings? (I'm willing to do a PR, I'd appreciate if you could point me to the relevant files tho!)

**Comment by petyosi** [comment]
@harrisonlo I am hesitant of adding styling props, to be honest - all in all, they won't be easier to implement than Header/Footer.

If you want to introduce header and footer, here's the rough checklist:

- Add the items [to the interface](https://github.com/petyosi/react-virtuoso/blob/master/src/interfaces.ts#L182).
- Include them in [the component system](https://github.com/petyosi/react-virtuoso/blob/master/src/Grid.tsx#L38).
- Render them [like the list does (look for Header/Footer)](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx).
- Track their size to the below observables:
- Add `headerHeight / footerHeight` measure observables, and include them in the totalHeight calculation ([roughly here](https://github.com/petyosi/react-virtuoso/blob/master/src/gridSystem.ts#L98)).
- Test how the whole thing works by duplicating one of the test cases in `e2e`.

**Comment by harrisonlo** [comment]
@petyosi Thanks for the reply. I saw that the `paddingTop` and `paddingBottom` values are updated inline as you scroll, so I thought when it reaches top or bottom (for which there seem to be logics already in place, with `atTopStateChange` etc.) we can simply set the value to something other than 0. Tho I haven't looked too much into the code to know if it'll break something.

**Comment by hungnguyentiki** [comment]
Hello, how about this issue? Do you have any plan to support it?

**Comment by joachimklug** [comment]
How is this feature supposed to work? Should the header / footer item be the first / last item of the grid or should it be separate and always represented in a new line? Here an example for the footer:

Option 1: The Footer Item is the last item of the grid.
<img width="407" alt="Screenshot 2022-01-23 at 00 15 16" src="https://user-images.githubusercontent.com/36903205/150658534-01213cd1-a3d1-4d4b-8dc6-f6399af21c15.png">

Option 2: The Footer Item is always in a new row under the last grid row.
<img width="411" alt="Screenshot 2022-01-23 at 00 16 39" src="https://user-images.githubusercontent.com/36903205/150658537-a5901c8c-e7c2-4306-bf6f-e14935e511e9.png">

**Comment by itayganor** [comment]
> Should the header / footer item be the first / last item of the grid or should it be separate and always represented in a new line?

The first option would be called `lastItem` rather than `footer`. 

Although one might see the footer (and header) as a "full-width item", they are actually content padders.

**Comment by cnt-null** [comment]
@petyosi The docs show an example of endless scrolling with `Virtuoso` + `endReached` + `Footer`.
`VirtuosoGrid` has `endReached` but  no `Footer`. Is there another way to show "Loading..." message for endless scrolling in this case?

**Comment by ErfanAsadi** [comment]
Hi @petyosi,
thanks for your wonderful library, 
is there any updates on this or lets start working on it?
