### ISSUE TITLE
translate(x, y, z) instead of margin-top

### ISSUE THREAD

**Issue by rafde** [petyosi/react-virtuoso#200]
I wonder if using `transform: translate(x, y, z)` was considered since it gains gpu acceleration where margin-top does not.
Using margin-top also does not provide smooth scrolling like `transform: translate(x, y, z)` does.

**Comment by petyosi** [comment]
Earlier versions were using translate, but as far as I remember, margin fixed glitches in safari, without any performance degradation. I have tried transitioning as well, it feels very unnatural.
