### ISSUE TITLE
Is it possible to use react-virtuoso with tree components?

### ISSUE THREAD

**Issue by dbrrt** [petyosi/react-virtuoso#202]
In the documentation, it says that you can use `react-virtuoso` with material-ui with a list, and I was wondering if the same library could be applied to other components from Material UI (e.g.: Tree View : https://material-ui.com/components/tree-view).

**Comment by petyosi** [comment]
That could easily be achieved if the treeview has a "flat" rendering rather than a nested one. I don't know if such mode is possible, though.

**Comment by dbrrt** [comment]
I was considering rendering the first layer "flat" with all lower level nodes and each node could be expanded independently from the view. Will give it a try.

**Comment by petyosi** [comment]
@dbrrt - please re-open if you manage to implement that - I would love to add such an example. Cheers!

**Comment by adsee42** [comment]
@dbrrt 
Hi, I'm planning to do exactly the same as you described.
Is there any code you could share?

**Comment by dbrrt** [comment]
I found another project implementing something similar with react-window, but if I manage to find time, I could implement an example with react-virtuoso, so will create a PR if relevant.

**Comment by adsee42** [comment]
@dbrrt 
I also tried `react-window` and `react-vtree`, but found their api too complicated...

**Comment by dbrrt** [comment]
@adsee42  Same, that's why I've had to look for some inspiration to implement that with `react-window`.  Here was my starting point https://github.com/victor-magarlamov/react-virtualized-tree.
`react-vtree` didn't work for me, as the examples from their storybook were raising typing issues and the API was quite complicated for me.
