### ISSUE TITLE
useScrollTop is very slow

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#204]
Hi, I'm testing @next and I noticed most of the time on scroll is spent on the `useScrollTop` hook, it leads to very long frames.

![image](https://user-images.githubusercontent.com/5382443/100238968-1ceb0780-2f31-11eb-8d03-5c466792dec5.png)

![image](https://user-images.githubusercontent.com/5382443/100238980-22485200-2f31-11eb-81e3-b5a1a29d26bb.png)

**Comment by petyosi** [comment]
Can you publish the test case somewhere?

**Comment by FezVrasta** [comment]
Unfortunately it's not an open source app so I can't 🙁

**Comment by FezVrasta** [comment]
I wonder if you could use `IntersectionObserver` as a more performance effective replacement to scrollTop? From what I see you are using the hook to accomplish a similar result?

**Comment by petyosi** [comment]
@FezVrasta I am not sure that I will be able to get away with intersection observer - nor if the slowdown you observe is not due to the underlying callbacks and updates. I will investigate - thank you very much for the suggestion and testing.

**Comment by FezVrasta** [comment]
I'm quite convinced the issue resides in Virtuoso, I recently tried to swap it with react-window and the performances were way better, but of course I lost all the nice features that Virtuoso provides out of the box.

**Comment by FezVrasta** [comment]
Something interesting to observe is that there are 3 calls to `scrollTop` on the same action:

![image](https://user-images.githubusercontent.com/5382443/100242045-a5b77280-2f34-11eb-99c9-4166c8b1fc1b.png)

In the screenshot above, the 3 long tasks are all scroll events. I would expect a single scroll event per call?

**Comment by petyosi** [comment]
That actually gives me a clue. Without any code reveal, can you post what props do you pass to the component?

**Comment by FezVrasta** [comment]
This is the relevant code:

```js
const footer = useCallback(() => {
  if (firstRow == null) {
    return null;
  }
  prepareRow(firstRow);

  return Array.from({
    length: Math.min(10, totalCount - rows.length),
  }).map((_, i) => <PlaceholderRow row={firstRow} key={i} />);
}, [prepareRow, rows.length, firstRow, totalCount]);

const components = useMemo(
  () => ({
    EmptyPlaceholder: loading ? null : EmptyComponent,
  }),
  [loading]
);

const itemContent = useCallback(
  (index) => {
    const row = rows[index];
    prepareRow(row);
    return (
      <Row
        row={row}
        onRowClick={onRowClick}
        onAddToQueue={onAddToQueue}
        onStartRead={onStartRead}
        onView={onView}
        onRemove={onRemove}
        onCompare={onCompare}
        tab={tab}
        isScrolling={isScrolling}
      />
    );
  },
  [
    isScrolling,
    onAddToQueue,
    onCompare,
    onRemove,
    onRowClick,
    onStartRead,
    onView,
    prepareRow,
    rows,
    tab,
  ]
);

<Virtuoso
  css={`
    flex: 1;
    overflow-x: hidden;
    ${style};
  `}
  totalCount={rows.length}
  endReached={onFetchMore}
  isScrolling={setIsScrolling}
  overscan={1000}
  footer={footer}
  components={components}
  defaultItemHeight={51}
  itemContent={itemContent}
/>
```

**Comment by petyosi** [comment]
@FezVrasta thanks to your report, I found some unnecessary re-renders and scrollTop calls. Just published beta.3 - please let me know if you see improvements in your case.

**Comment by FezVrasta** [comment]
beta.3 seems to be better, but I still see one extra call (beta.2 had 3, so you are going the right way!)

![image](https://user-images.githubusercontent.com/5382443/100352906-f63ed680-2fed-11eb-90ed-514ef4939735.png)

I also see this other long frame here:
![image](https://user-images.githubusercontent.com/5382443/100352968-1373a500-2fee-11eb-8ecf-4b0c556c9f1e.png)

**Comment by petyosi** [comment]
@FezVrasta can you try removing the `overscan` setting? This is how the timeline looks on my side without it:
![image](https://user-images.githubusercontent.com/13347/100364343-ab7d8880-3006-11eb-9dc1-9330b0935272.png)
and with `2000` set.
![image](https://user-images.githubusercontent.com/13347/100364401-c05a1c00-3006-11eb-9a43-a1f48b6404bc.png)

**Comment by FezVrasta** [comment]
I see less long frames but the rows render very slowly (this also happens with overscan but not that much).

![Kapture 2020-11-26 at 17 33 37](https://user-images.githubusercontent.com/5382443/100375129-9b1cdc00-300d-11eb-9010-fafff8404838.gif)

**Comment by FezVrasta** [comment]
Is there any progress on this? I can reproduce the issue on 1.5.13

![image](https://user-images.githubusercontent.com/5382443/113304379-41e9ef80-9302-11eb-98b6-6e496b0881e0.png)
the above is with no overscan set

**Comment by petyosi** [comment]
I haven't discovered any additional general performance improvements. Again, the best way to help me here is with a way for me to reproduce the slowness you observe on my side.
