### ISSUE TITLE
Empty list when topItems is equal to totalCount

### ISSUE THREAD

**Issue by antoniozzo** [petyosi/react-virtuoso#205]
When topItems is equal to totalCount the sticky items disappears above the list.
Easy to reproduce by editing the stackblitz code from https://virtuoso.dev/top-items/ and setting the totalCount to 2.

I'm creating a search list with a sticky input and sometimes the list of search results will be empty, resulting in this issue.

**Comment by petyosi** [comment]
@antoniozzo - [works with v1](https://stackblitz.com/edit/react-z4skoa?file=package.json) beta 3. if you are starting right now, please go ahead with it, I am about to make it the @latest version quite soon.

**Comment by antoniozzo** [comment]
Great, Thanks a lot!
