### ISSUE TITLE
Error: Zero-sized element, this should not happen

### ISSUE THREAD

**Issue by antoniozzo** [petyosi/react-virtuoso#206]
Got this error as soon as i switched to the new beta.

<img width="1028" alt="Skärmavbild 2020-11-26 kl  16 31 38" src="https://user-images.githubusercontent.com/4252730/100369308-08783f00-3005-11eb-824c-58e7d674c380.png">

**Comment by petyosi** [comment]
Can you post a repro in stackblitz? I have seen this happening with hot reloading, but it might be something else.

**Comment by Anuj-Shrestha** [comment]
Height of the divs (in your item or group) might have been zero (possibly due to lack of content).

**Comment by dmitrizzle** [comment]
Seeing this with Cypress tests

**Comment by petyosi** [comment]
@dmitrizzle - can you post a repro?

**Comment by dmitrizzle** [comment]
@petyosi unfortunately, I can not, it's a private one. I can only say that this isn't happening during normal workflow in either prod or dev mode (latest Chrome on macOS 10.14.6). I run a Next.js and am implementing Virtuoso like this:

```javascript
 <Virtuoso
      initialItemCount={rows.length}
      itemContent={index => rows[index]}
      onScroll={onScroll}
      overscan={1000}
      ref={listRef}
      totalCount={rows.length}
    />
```

My implementation makes use of "search" (really a browser-based filter on a list of items) and thus changes `rows` content rather often. It also mounts/dismounts `<Virtuoso />` in between changes to `rows`.

**Comment by GuillaumeAmat** [comment]
Hi @petyosi, here is a reproduction when using `@reach/tabs`: https://codesandbox.io/s/react-virtuosoissues206-r6l5j

As you can see, all the items can only have a proper render output, but the error pops at every tab switching.

**Comment by tutts** [comment]
II have the same issue and my scenario is similar to @dmitrizzle as its a live dashboard.

I'm unfamiliar with the codebase right now, but in the process of debugging the issue, but my problem stems from the fact I pass the index to the row, which I use to connect to redux to pull more row information, if this information is removed from the store, then I render a null row instead.

example: 

```javascript
const MissionRows = () => {
  const { width, height } = useWindowSize()
  const missionIds = useSelector(getFilteredMissionIds)

  if (!Array.isArray(missionIds) || !missionIds.length) return null

  return (
    <Virtuoso
      style={{ height, width }}
      totalCount={missionIds.length}
      overscan={{ main: 2, reverse: 2 }}
      itemContent={index => <MissionRow missionId={missionIds[index]} />}
    />
  )
}
```

```javascript
export const MissionRow = ({ missionId }) => {
  const mission = useSelector(state => getMissionById(state, missionId), shallowEqual)

  if (!mission) return null

  return (
    <MissionRowUI key={missionId} missionId={missionId} marked_for_action={mission.marked_for_action}>
      <Columns missionId={missionId} />
    </MissionRowUI>
  )
}
```

when that mission no longer exists in store redux will remove it from that row as you can see in the DOM here:

![image](https://user-images.githubusercontent.com/7454558/102464790-b72c0000-4044-11eb-8d82-baa39166fe78.png)

so a quick workaround for the time being is return a div with content to pass this check, it will then be removed upstream when the ids change upstream and cause a re-render

```javascript
export const MissionRow = ({ missionId }) => {
  const mission = useSelector(state => getMissionById(state, missionId), shallowEqual)

  if (!mission) return <div>this actually won't be seen</div>

  return (
    <MissionRowUI key={missionId} missionId={missionId} marked_for_action={mission.marked_for_action}>
      <Columns missionId={missionId} />
    </MissionRowUI>
  )
}
```

**Comment by tutts** [comment]
whoops! 🤦🏼‍♂️ yep nailed it -> "could be due to some exotic integration scenario" 😆 

thanks for the heads up @petyosi, best of luck with the patch!

**Comment by GuillaumeAmat** [comment]
It's working great here, thanks for the quick fix @petyosi 👌

**Comment by dmitrizzle** [comment]
Still happens within Cypress tests with 1.1.0

**Comment by fayez-nazzal** [comment]
Still happens in version 2.6.0, applying the following example with react-beautiful-dnd:
[https://virtuoso.dev/react-beautiful-dnd/](https://virtuoso.dev/react-beautiful-dnd/)

There is a comment 'check style.css for the height-preserving-container rule' though the rule does not exist in styles.css when opening the following sandbox:
[https://codesandbox.io/s/lsxev?file=/styles.css](https://codesandbox.io/s/lsxev?file=/styles.css)

**Comment by fayez-nazzal** [comment]
My bad!, Fixed it just by adding a height to 'HeightPreservingItem'.

**Comment by Aravindh-SNR** [comment]
@petyosi Is there a way to disable the error log for zero-sized elements? I need such elements for my use case and things are working as intended, but the console is filled with these logs and it would be great without them.

By the way, the library is awesome. Thanks a ton for the great work!

**Comment by petyosi** [comment]
@Aravindh-SNR  - no, it does not work. Several things are subtly broken, and you should not work around that. Filter your data to exclude the items you don't want to render.

**Comment by Aravindh-SNR** [comment]
@petyosi I see, thanks for the reply.

I have rows that can be expanded to show nested rows. I render the cell in nested rows conditionally, i.e. when the parent row is expanded, the cell is rendered. When it is collapsed, the nested row is empty.

Like you said, I could filter to exclude/include the nested row itself but then I'd be changing the entire state (data) causing everything to re-render, which I'm trying to avoid.

Sorry to circle back but do you have any thoughts on this scenario? The approach I've taken seems to work as expected but if there are things broken, I won't work around that.

**Comment by OneTuskedMario** [comment]
@Aravindh-SNR did you ever find a solution to this?

**Comment by Aravindh-SNR** [comment]
@OneTuskedMario Sorry I couldn't respond earlier. My problem was not with zero-sized elements as such but only with the console errors for these elements. I do understand @petyosi's point about things being subtly broken but I couldn't find a better alternative and things are working as expected for me.

As for the console errors, I managed to get rid of them by passing logLevel as undefined (or a number > 3 should work too since 0-3 are the defined values). Again, I know this is kind of a hack but had to be done in my case.
