### ISSUE TITLE
How to create a full page/full screen flexbox product list endless scroll?

### ISSUE THREAD

**Issue by 7sxzx** [petyosi/react-virtuoso#210]
Can someone please help me in creating a endless scroll product list full page/full screen?

Currently, i'm unable to find such examples in docs.

Thanks in advance.

**Comment by DoneDeal0** [comment]
Just add endReached to trigger a fetch function when the user reaches the bottom, and maybe add a footer to handle the loader ui. 

```
                endReached={() => canLoadMore && loadMore()}
                footer={() =>
                  isFetching && (
                    <Suspense fallback={null}>
                        <Loader />
                    </Suspense>
                  )
                }
```
