### ISSUE TITLE
v1: what type should be used for grid ref?

### ISSUE THREAD

**Issue by NTag** [petyosi/react-virtuoso#211]
I have the following code, with the v1 beta-5:

```js
import React, { useRef } from 'react';
import { VirtuosoGrid } from "react-virtuoso";

const App = () => {
  const gridRef = useRef<any>(null); // ← what type should I use, instead of 'any'?

  return (
    <div>
      <button onClick={() => gridRef.current.scrollToIndex(2000)}>Go to index 2000</button>
      <VirtuosoGrid ref={gridRef} … />
    </div>
  );
};
```

I can't figure out what type I should use in `useRef` (in v0 I used `useRef<VirtuosoGrid>` but that doesn't work anymore with the v1.

**Comment by petyosi** [comment]
Good question, I will put a note to document that.  The package exports `VirtuosoHandle`, `GroupedVirtuosoHandle` and `VirtuosoGridHandle` typescript types. 

Please let me know if you stumble upon any regressions with the Grid. 

Cheers,

**Comment by petyosi** [comment]
Documented here - https://virtuoso.dev/virtuoso-grid-api-reference/

**Comment by NTag** [comment]
Awesome, thanks!
