### ISSUE TITLE
Possible Bug: The "Virtuoso" for the list layout ignore the last 3~4 items

### ISSUE THREAD

**Issue by FOfficial** [petyosi/react-virtuoso#213]
Basically I've a list of less than 60 items and everything seems to works quite well except the fact it seems to be ignoring the last few items in the list when I reach to bottom of the list!

I'm not doing anything crazy other than what's specified in the API docs and it seems completely random. When I scroll the list for the first time it renders fine, but scrolling up and then down again seems to be ignoring the last few records and I didn't realise this until very recently that I was looking up some of the items on the list that was initially there but not anymore.

I would appreciate any help from the anyone that may have encountered similar issue and possible fix for it.

Regards

**Comment by petyosi** [comment]
This typically happens because you have elements with `margin` in the list items.
