### ISSUE TITLE
How to customize the props of component.Item

### ISSUE THREAD

**Issue by ChiaJune** [petyosi/react-virtuoso#214]
I want to use react-virtuoso in @material-ui/Autocomplete

**Comment by petyosi** [comment]
If I understand you correctly, In v1, you can pass an array to `data` property - the items will be passed to the `itemContent` callback - [check this example](https://github.com/petyosi/react-virtuoso/blob/next/site/docs/hello.md#list-with-data). 

Let me know if this makes sense.

**Comment by mbrevda** [comment]
Any demo of this working? Here is a codesandbox _mostly_ working, but there are still some quirks. For example, the list wont open (I have it hardcoded to be open). Also, the list won't scroll when using up/down arrow keys to move through the list. Would be great to get this fully working!

https://codesandbox.io/s/material-demo-forked-r6i2y?file=/demo.tsx

**Comment by Mario-Eis** [comment]
Is there any resolution yet? Passing props to the items content is not enough. props must be passed to the items root directly

**Comment by petyosi** [comment]
This is now addressed with the context prop.

**Comment by Mario-Eis** [comment]
Is this documented? Passing anything to the context prop does not change the context parameter in the Components interface. 

```
  <Virtuoso
            style={{height: "400px"}}
            data={itemData}
            context={itemData.map(data => data.props)}
            components={MUIComponents}
            itemContent={(index, {props, option}) => option.text}
        />
```

```
const MUIComponents: Components<any> = {
    List: List,
    Item: (props, context) => {
        console.log(context)
    }
}
```

**Comment by mbrevda** [comment]
> This is now addressed with the context prop.

There seems to be some confusion around this. Is there an example or docs of how to use context?

**Comment by petyosi** [comment]
Several of the examples in the docs are using it. What's the confusion?
