### ISSUE TITLE
v1 beta customize Scroller only render the first screen data

### ISSUE THREAD

**Issue by ChiaJune** [petyosi/react-virtuoso#215]
reproduce demo:
[customize-scroller-bug](https://codesandbox.io/s/customize-scroller-bug-b8b48?file=/src/App.js)

**Comment by petyosi** [comment]
Thanks, I fixed it, will work in the next beta. Unlike the previous version, I think there won't be much need to customize the scroller component - all HTML props are passed through the virtuoso component to the element. I am keeping it for compatibility though.

**Comment by Amareis** [comment]
>there won't be much need to customize the scroller component
I don't think so, because for some real custom scrollbars it's really needed, and HTML props is not enough.

BTW, when it will be released?

**Comment by petyosi** [comment]
@Amareis I will deploy the new web site and promote next to master over this weekend. There are no outstanding issues I am aware of ATM.
