### ISSUE TITLE
Question: How to sync scroll with the whole page?

### ISSUE THREAD

**Issue by xxczaki** [petyosi/react-virtuoso#216]
On my page, I have 2 panes, one of which includes expressions and the other one - results. When the user types on the expressions pane, the results are automatically updated. Full page scroll works on both of the containers.

I would like to scroll the whole page, that is both the expressions pane and virtuoso-wrapped results pane. I can't achieve that, because the Virtuoso component requires a fixed height.

Is there any way to do that?

**Comment by petyosi** [comment]
If I understand you correctly, what you are looking for is not supported. The component does not require a fixed height, but it does need its own scrollable container - you can't (yet) attach it to the window scroller. 

If the above is not what you had in mind, perhaps a code sandbox example could help me. Cheers,

**Comment by petyosi** [comment]
@xxczaki this is supported in v1.3.0 - check the demo https://virtuoso.dev/window-scrolling/
