### ISSUE TITLE
Consider removing default height value of "100%"

### ISSUE THREAD

**Issue by tvquizphd** [petyosi/react-virtuoso#220]
Scroll to the Example below to see the screenshot of the [live codepen demo](https://codepen.io/tvquizphd/pen/dyppGwm) in Safari.

### Background:

I'm addressing an issue in Safari when the parent `div` of Virtuoso has the style `display: flex`. Default flex display relies on the children having their `height` style remain unset. This allows the computed `height` to expand to fill all the allocated space in the flex container.

### Issue:

I currently need to manually pass `height: undefined` when setting the style property of Virtuoso to overwrite the default `height` value of `"100%"`. This works just fine to allow the computed `height` to expand to fill the allocated space in the flex container, but it seem like a bit of a hack. In order for Virtuoso to officially support the benefits of a `style` with no `height` attribute, the cleanest solution would be to leave `height` unset by default.

### Proposal:

I propose the default behavior of Virtuoso should be to leave the `height` of the top-level div unset if no `height` is passed in the style property of Virtuoso. Projects that rely on the current default behavior of `height` will need to update their codebases to pass `height: "100%"` in the style property when rendering Virtuoso. Since the [docs](https://virtuoso.dev/virtuoso-api-reference/) do mention that the `style` property is optional, this will technically be a breaking change.

On a cursory look at the code, it's possible this could be achieved by removing the default height of `VirtuosoScroller` on [line 5 of VirtuosoScroller.tsx](https://github.com/petyosi/react-virtuoso/blob/fd46af5c6580210f62f2c45e7040d589f13e5f80/src/VirtuosoScroller.tsx#L5). I have not tested this.

### Bonus of consistency:

I'll mention that `width` currently has no default value. If no `width` is passed to Virtuoso, there will be no width set in the style of the top-level Virtuosos `div`.  So, the proposed changes will make the default behavior of `height` consistent with the default behavior of `width`.

# Example

- The left part of the screenshot shows the results in Safari where `style={width:'100%'}`. The default `height` of `'100%'` results in a computed `height` of `0px`, and the list is invisible.
- The right part of the screenshot shows the results in Safari `style={height: undefined, width:'100%'}`. With no `height` set, the computed `height` fills the containing `flex` element, and the list is visible. This, after the proposed change, would be the behavior without needing to set `height: undefined`.

![comparison](https://user-images.githubusercontent.com/75504552/101707474-46d81a00-3a59-11eb-9841-f3324a9de9c0.png)

**Comment by tvquizphd** [comment]
I realize, that, perhaps, there are more people currently relying on the default `"100%"` height than would benefit from the proposed default of leaving the `height` attribute unset. However, there are likely others like me who didn't know what to do at first to override the default height of `"100%"`. The solution of passing `{height: undefined}` is somewhat counterintuitive.

If you decide not to change the default `height` behavior, it would be worth it to explicitly add a section to the **Gotchas** of [virtuoso.dev](virtuoso.dev) to suggest `{height: undefined}` when using css that relies on Virtuoso having the `height` property unset.

Either way you want to go on this, I'd be happy to either test out the proposal or write a bit for the Readme.

**Comment by petyosi** [comment]
Thank you for your time! Removing the default height would result in rendering nothing by default, which will leave a lot of people scratching their heads on what's to be done. 

As I am reworking the website, I will include a "troubleshooting" section in there and get back to you for a contribution on the specific Safari issue you refer to.

**Comment by tvquizphd** [comment]
Thanks! I'm just glad to have this specific issue documented for now, and I'll be happy to contribute the `{height: undefined}` solution to a troubleshooting section when the new website is mature enough. 

I recognize that my particular case of setting up Virtuoso as a `flex item` is not particularly common, and, as far as I know, people will only notice it's an issue when testing in Safari.

Thanks for you time as well, and thanks for making a great library!

**Comment by petyosi** [comment]
@tvquizphd I just created a troubleshooting page for the new website - Check [this commit](https://github.com/petyosi/react-virtuoso/commit/960549548d15f9e479e40aebaf885581d5814e94). Would be great if you submit a PR following the problem/fix format. 

Thank you once again,
