### ISSUE TITLE
scrollToIndex with custom ScrollContainer

### ISSUE THREAD

**Issue by MaxBrokhman** [petyosi/react-virtuoso#222]
Is there a way to use scrollToIndex with custom ScrollContainer or this is not possible currently?

**Comment by petyosi** [comment]
@MaxBrokhman I am not sure that I understand the question - the custom ScrollContainer can not break `scrollToIndex` (unless it breaks the entire component). The DOM element ref is used for both scroll position tracking and for scroll setting.  

By the way - are you using v1 beta or v0.20?

**Comment by MaxBrokhman** [comment]
@petyosi I am using v0.20. I tried to reproduce it in a simple example, but everything is working fine, the problem is somewhere in my code, sorry for this issue
