### ISSUE TITLE
V1) initialTopMostItemIndex change from 0 to 1 makes list go empty

### ISSUE THREAD

**Issue by chrisdostert** [petyosi/react-virtuoso#223]
Repro steps: 
1. open https://stackblitz.com/edit/react-l1eibb-ghmdzz?file=ExampleComponents.js
2. click add item
3. click add item

Expected
Second iteme added to both non-virtualized and virtualized list

Actual
virtualized list goes blank

Note: if you remove initialTopMostItemIndex entirely it works.

**Comment by chrisdostert** [comment]
possibly related to https://github.com/petyosi/react-virtuoso/issues/176

**Comment by petyosi** [comment]
@chrisdostert thank you for the test case, resolved. I am about to release v1 over the weekend, so I will not publish a new beta for that.
