### ISSUE TITLE
Scrolling sticky item over static one

### ISSUE THREAD

**Issue by voliva** [petyosi/react-virtuoso#224]
I've noticed that the sticky items currently scroll behind the active one before going active:
![group_under (2)](https://user-images.githubusercontent.com/5365487/101921348-3183fc80-3bcd-11eb-9ca7-1564dc47b25e.gif)

It feels a bit weird to me - For me it's more natural to have the sticky item getting on top of the previous one, and staying there. It's also the default behaviour of using a non-virtualized scroll with some position: sticky items.

I could hack around and managed to achieve this by adding some sticky styles also to the group header:
![group_over](https://user-images.githubusercontent.com/5365487/101921157-f5e93280-3bcc-11eb-85a1-94a25bf48d20.gif)

Would you consider adding this in?

**Comment by petyosi** [comment]
@voliva That's amazing! I always hated that visual detail but never had the willpower to tackle it. I will try to incorporate it as a built-in mode.

**Comment by petyosi** [comment]
@voliva added the proposed change in the upcoming v1 release, which I plan on publishing this weekend.
