### ISSUE TITLE
@material-ui/useAutoComplete + react-virtuoso optionItem's focus exception

### ISSUE THREAD

**Issue by ChiaJune** [petyosi/react-virtuoso#230]
When I use react-virtuoso and @material-ui/useAutoComplete together, the keyboard focus of optionItem is abnormal. Please help me to find out what is wrong, Thanks!

[demo](https://codesandbox.io/s/tender-resonance-kur6v?file=/src/DemoHooks.tsx)

**Comment by petyosi** [comment]
Can you explain what's the expected behavior and what's broken? I am not familiar with useAutoComplete.

**Comment by ChiaJune** [comment]
Very sorry for my bad english. Using the keyboard to operate the focus, when the focus reaches the last option, it will return to the top and start again
![Kapture](https://user-images.githubusercontent.com/12479827/101986746-d2a4ad00-3cca-11eb-8702-4b034b31d002.gif)

**Comment by petyosi** [comment]
Got it. The easiest way to handle keyboard navigation is through the `scrollIntoView` call. Check [this sandbox](https://codesandbox.io/s/frosty-archimedes-urzyq?file=/src/index.js:737-738) - essentially the scrollIntoView call will always keep the current item centered and scroll through the list.

**Comment by ChiaJune** [comment]
Thank you very much for your help, but onFocus will not trigger on ListItem. I think this is not a react-virtuoso's issue, so I closed it
