### ISSUE TITLE
Overscan is not working

### ISSUE THREAD

**Issue by Amareis** [petyosi/react-virtuoso#231]
I'm using 1.0.0 and pass `overscan` prop (I tried both form), but it still renders only visible items.
Passing props:
![image](https://user-images.githubusercontent.com/4806617/102009297-5789d800-3d58-11eb-8f09-ab0c44cf97d3.png)
Rendered content (in elements): 
![image](https://user-images.githubusercontent.com/4806617/102009312-6f615c00-3d58-11eb-81ec-5a393316349d.png)

**Comment by petyosi** [comment]
From what I see, it actually works. You have a height of 500px, but the items cover 588px, which roughly matches `main: 30, reverse: 10 }.

**Comment by Amareis** [comment]
Uh-oh, I'm really stupid - I think that it's about items count, not a pixels >< Thank you for good library!

BTW, will you return example with react-custom-srollbars to docs?

**Comment by petyosi** [comment]
@Amareis - I totally forgot about that one. Care to submit a PR? The site is now easily accessible and runnable from the repository. Thanks!

**Comment by Amareis** [comment]
> @Amareis - I totally forgot about that one. Care to submit a PR? The site is now easily accessible and runnable from the repository. Thanks!

I want it because I need it in our project :) But when I do it, maybe I'll make PR, yep.

**Comment by bernhardc** [comment]
I just wanted to add that I also thought that `overscan: number` referred to the number of list items, not pixels.
Maybe it would be beneficial to clarify that in the docs.

Awesome library by the way!
