### ISSUE TITLE
Prepending Items reverse endless scrolling scenario with GroupedVirtuoso

### ISSUE THREAD

**Issue by osadchiynikita** [petyosi/react-virtuoso#232]
@petyosi Hello, many thanks and congratulations with v1 release! Reverse endless scrolling works as expected with plain Virtuoso list, and I'm trying to achieve the same behavior with GroupedVirtuoso, but have some issues.

1. `startReached` is not triggering callback for some reason. `endReached` works well though
2. When setting `data` prop list rendering not properly, seems like ignoring groups and groupCounts

https://stackblitz.com/edit/react-kjchm8-mxn3ry?file=example.js

Thank you and let me know if any other info needed!

**Comment by petyosi** [comment]
Thanks for the bug report. I am not sure how to deal with data and grouping, to be honest. What would be your intuitive API? Do you want to pass array of arrays? Do you expect to have data items for the groups?

**Comment by osadchiynikita** [comment]
@petyosi thanks for the fast feedback. Not sure I understand the issue properly, but maybe allow to pass `totalCount` prop for `GroupedVirtuoso` same as for `Virtuoso`. And in my case I'll pass `totalCount={items.length + groups.length}`

P.S. Just a minor note, probably related to the same root - `firstItemIndex` is not working properly without `data`
