### ISSUE TITLE
Infer type of 2nd positional parameter in itemContent callback

### ISSUE THREAD

**Issue by bb** [petyosi/react-virtuoso#233]
Hi Petyo,

thanks for creating react-virtuoso. It works really great for me.

I just upgraded to 1.0 and wanted to try the new `data` parameter in `itemContent` and noticed it was typed `any` instead of the inferable type from `<Virtuoso data={...} ...` prop.

I think it can be added like this:

```ts
export interface VirtuosoProps<ItemType extends any> extends Omit<ListProps, 'groupCounts' | 'groupContent'> {
...
  data?: ItemType[]
...
  itemContent?: (index: number, data?: ItemType) => ReactNode
...

export interface GroupedVirtuosoProps<ItemType extends any>
  extends Omit<VirtuosoProps<ItemType>, 'totalCount' | 'itemContent'>,
...
```

However, I don't know to parameterize the `export const` lines at the very end of components.tsx, yet. Maybe you do? If you have a pointer how to fix that, I might be able to provide a PR.

**Comment by petyosi** [comment]
@bb - Me neither, TBH. I googled several "generic React components" phrases, but nothing seems to make sense.

**Comment by bb** [comment]
Thanks for the quick reply! I don't have the time to investigate deeper right now, but I'll give it another try later. Or maybe somebody else chimes in. 😉

**Comment by bb** [comment]
For Future-Me or whoever implements that: I just noticed that this would ideally also apply to `data` property of `Item` and `RecordItem` as well as `ItemContent` and `GroupItemContent` (defined in interfaces.ts). This would help e.g. in `itemsRendered`.

**Comment by petyosi** [comment]
I don't think (but I might be wrong) that you have to interfere with interfaces.ts. The "official" typings of the component are re-declared in `components.ts` for documentation purposes. While they do extend some interfaces from interfaces.ts, this is mostly to avoid duplication.

**Comment by seahorsepip** [comment]
I had a try at adding generic typing to the `Virtuoso` and `GroupedVirtuoso` components.
