### ISSUE TITLE
GroupedVirtuoso.  Issue with rangeChanged and initialTopMostItemIndex

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#234]
Hi @petyosi 

We are currently in the process of upgrading to virtuoso 1.0 (thanks for the great effort by the way).   I noticed an issue that might have already existed in 0.x

We are using rangeChanged to take note of the top most index, then when the user navigate back and forth from the list, we re-position him where he left.

The issue that I noticed is with the grouped version. 

rangeChanged seems to give indexes that include the groups (eg. first item after first group is 1 instead of 0)
initialTopMostItemIndex seems to want the index of items only (without including the groups).

That result in an off-sync, where the user will be pushed down X items from where he was, corresponding to the amount of groups there were before that index.

Let me know if you want a sandbox example,  but I guess this is easily reproduceable.     It would be nice if rangeChanged would give out indexes without taking groups into account.

Thx

**Comment by petyosi** [comment]
Thanks, this is absolutely a mistake on my side. I will update the `rangeChanged` parameters in grouped mode to match the behavior of `scrollToIndex`

**Comment by petyosi** [comment]
@Ethorsen thanks for the context. I figured out how to fix `rangeChaged` but looking through what you describe as a use case, it won't work reliably because of list rendering specifics. Instead, I will implement a way to restore the scroll position using a property like `initialScrollTop` (with certain caveats).

**Comment by Ethorsen** [comment]
Sure I will adapt the code as needed.  

Right now, for plain Virtuoso lists, combination of rangedChanged and  initialTopMostItemIndex  is close enough for our needs tho. But yeah its no pixel perfect.
