### ISSUE TITLE
Question: What would be the simpliest/cleanest way to add extra padding to first and last items

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#238]
Might be a dumb question.  We usually have some padding on each list item, spacing them evenly one from another.  

eg. padding: 8px 0;

Only the first/last items in the list seem too close to borders and we add an extra padding only for those items.  

eg. first item would become: 16px 0 8px 0;  and last would be 8px 0 16px 0;

I usually do this by adding extra padding to the list container itself or by using the css :first-child :last-child modifiers.  But for obvious reasons this wont work here.  

My current solution is to determine in itemContent if its first/last item using its index, and add proper classes to these 2 items.   But this is repetitive in our use cases so I'm just wondering if there would be a easier/cleaner/more obvious way I might have missed.

Thx

**Comment by petyosi** [comment]
You may try adding an "empty", padding-only header/footer for that.
