### ISSUE TITLE
Scroll bottom escape during resize of the new row height

### ISSUE THREAD

**Issue by hubertsuprunowicz** [petyosi/react-virtuoso#241]
I have implemented infinite loader with some default height of the loading row and I wanted to use it with `stick to bottom`  property, but after main data was loaded (bigger than placeholder) the scroll was jumped to the difference of `loading row` and `loaded row` regardless `stick to bottom` property.

Row implementation example:
```
if(!data) return <Loading/>
return <Row>...</Row>
```

Infinite loader: http://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader

**Comment by petyosi** [comment]
Can you post a repro?

**Comment by hubertsuprunowicz** [comment]
> Can you post a repro?
Unfortunately not, but I can reconstruct it if you need

**Comment by petyosi** [comment]
That's necessary, yes. Also - check if the emptyplaceholder prop or the footer component props won't work for you.

**Comment by hubertsuprunowicz** [comment]
`emptyplaceholder` is not gonna help because it is only relevant to the length of 0 if I understand it correctly, however, I could have items right before and they are from i.e. first pagination (0-20).

Hope this gonna help: https://codesandbox.io/s/lucid-sanne-yyq2u?file=/src/App.js

Moreover, my total amount of items is predefined constant.

**Comment by petyosi** [comment]
Thanks, I think I understand your implementation now. `followOutput` reacts to the initial row size - it does not track subsequent row resizing, as this can cause plenty of unexpected behavior and permanent "stickiness". 

In your case, you may use the `scrollToIndex` method when the data is loaded.
