### ISSUE TITLE
VirtuosoGrid: Excessive re-rendering and cpu usage

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#243]
Hi @petyosi,

Thx again for v. 1.1.0  Works like a charm.

I was hoping we also could get rid of our old virtualized grid and move to VirtuosoGrid.  Its our first usage of the component.

Everything was fine, but I noticed my CPU was spiking when visualizing the grid, without even touching anything.  The example on virtuoso website is also somewhat using the CPU quite a bit. 

https://virtuoso.dev/grid-responsive-columns/

I activated whyDidYouRender on all pure components, and I can see a constant re-rendering even if nothing changed. 
![image](https://user-images.githubusercontent.com/1493968/102826044-ed9fad00-43ad-11eb-8512-3d5f4100157d.png)

As soon as I switch back to list mode, it goes away.

Let me know if you want a codesandbox.

Thx
Eric

**Comment by petyosi** [comment]
Thank you! I have never managed to setup wdyr properly with virtuoso - can you help me with a sandbox?

**Comment by Ethorsen** [comment]
Hey.

Here's 2 sandboxes.  What I noticed is that the problem wasnt there in v1.0.0

Codesandbox with v1.1.0 https://5si10.csb.app

Codesandbox with v1.0.0 https://9so7o.csb.app


To edit  https://codesandbox.io/s/5si10?file=/src/App.js
