### ISSUE TITLE
VirtuosoGrid: Items are re-mounted on every list rendering instead of updating

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#244]
Hi,

I was trying to trigger a CSS animation on elements inside an item.   These animations are being triggered on a click of a button inside the item, effectively changing the item data.  

The animation was not happening, although I could see the new css classes being applied.  Looking into it for a bit, I noticed that all the grid items were being re-mounted on each change of the data, instead of being simply updated.  

Setting the computeItemKey does not solve it.     

Quick sandbox demonstrating the issue.   
https://codesandbox.io/s/crazy-snowflake-cyzsl?file=/src/App.js

You get a console.log on item mount.  Scrolling around will correctly mount only new items.   But if you click on any item, you'll notice that all rendered items are being re-mounted.  I tried to wrap ItemWrapper and Item with React.memo with no luck.

Thx

**Comment by petyosi** [comment]
Here's a [demo that seems to be working](https://codesandbox.io/s/laughing-agnesi-kuuqg?file=/src/App.js:1513-1529) with 1.1.2.
