### ISSUE TITLE
Prepending items stops work correctly for negative firstItemIndex values

### ISSUE THREAD

**Issue by mastergenius** [petyosi/react-virtuoso#245]
In [Prepending Items](https://virtuoso.dev/prepend-items/) scenario when firstItemIndex became negative (when we add more than START_INDEX users) scroll preserving stops working if items with negative indexes rendered in a viewport.

For easy reproduction you can set START_INDEX to 1000, usersToPrepend to 1000 and add Header with Add button (to overcome problem with startReached triggered only once from issue #242) `components={{Header: () => (<button onClick={prependItems}>Add more</button>)}}`.

To work around this problem currently, we can use big enough value as the initial firstItemIndex.

**Comment by petyosi** [comment]
Acknowledging that, I should document this.

**Comment by seahorsepip** [comment]
In the demo, negative values seem to work fine on my end: https://virtuoso.dev/prepend-items/

![image](https://user-images.githubusercontent.com/16677786/103019036-6afe2580-4546-11eb-9f81-35ae3052f32c.png)

**Comment by petyosi** [comment]
@seahorsepip scroll preserving means that when you insert 100 items at the top, the list compensates that and re-scrolls to the previously visible range. 

I assume that you have a different concern regarding resizing though :). If you want to, you can open a new discussion - I have enabled discussions for the repo to see how it goes.

**Comment by JakeSchroeder** [comment]
Any fix for this or workaround? 
I don't see how it's possible to implement a proper infinite scrolled chat app with this issue.
