### ISSUE TITLE
Rendering white background on scroll chrome only

### ISSUE THREAD

**Issue by JakeSchroeder** [petyosi/react-virtuoso#249]
Here is an example:

https://drive.google.com/file/d/16l2XfoiodlixqsCfqnFTrapW7b1JOdJB/view?usp=sharing

When scrolling the background is white and it glitches.

Works as expected on firefox,edge,safari

**Comment by petyosi** [comment]
Observing the list DOM tree in the inspector slows down the rendering a lot. Do you reproduce the same behavior in the [demos](https://virtuoso.dev/)?

**Comment by JakeSchroeder** [comment]
Closing the inspector corrects the rendering.

Thanks!
