### ISSUE TITLE
Expose callback prop for `itemsRendered`

### ISSUE THREAD

**Issue by petyosi** [petyosi/react-virtuoso#25]

**Comment by joshacheson** [comment]
@petyosi are you open to having someone else implement this? I could be up for giving it a shot late this week or next week.

**Comment by petyosi** [comment]
@joshacheson That would be awesome! Give it a shot.

**Comment by joshacheson** [comment]
Heya! I'm working on this today (And on other days if necessary :)). I'm curious how you make use of `playground/` for testing? I'm not sure what browser environment allows you to directly import / use `.tsx`.

**Comment by petyosi** [comment]
Hey @joshacheson , 

you just run `parcel playground/index.html` and you are good to go.
