### ISSUE TITLE
GroupedVirtuoso totalListHeight is not calculated correctly when groups are updated.

### ISSUE THREAD

**Issue by krmzbbr** [petyosi/react-virtuoso#250]
Hoping you can shed some light on this.

I am using GroupedVirtuoso in a scenario where groups and items are updated frequently. Group height are always the same, but item heights can be different for each item. It looks like list height is not being calculated correctly after new groups are rendered which causes the scrollbar to display incorrectly.

I created a demo here [https://codesandbox.io/s/virtuoso-uh8xs?file=/src/index.tsx](https://codesandbox.io/s/virtuoso-uh8xs?file=/src/index.tsx)

If you create new groups and scroll all the way down, you will see a lot of empty space at the end of the list when a new group is generated - it might take a couple of tries. totalListHeightChanged also starts reporting negative numbers.

Currently, my workaround is to change the key of the GroupedVirtuoso to force it remount, which fixes the scrollbar but hoping the find a solution.

![image](https://user-images.githubusercontent.com/7927474/103312573-1db90280-49e3-11eb-8709-c2be05ef22c4.png)

**Comment by petyosi** [comment]
Thanks for the repro @krmzbbr, 

Grouping mode internal structures are complicated and costly to recreate. My initial implementation discarded all known heights when group counts were changed. That mode would correctly support your scenario but does not work well for infinite scrolling, where new groups are appended to existing ones. What the code does currently is to "retrofit" newly passed group counts over existing ones - and this does not work well in cases like this demo.

If what you are doing in real mode is similar to the example above, passing a new key for a remount is the way to go. The previously built internal component state is irrelevant (and costly to readjust to new content) anyway. 

Hope this makes sense,

**Comment by krmzbbr** [comment]
Thank you for confirming this. You are correct that new groups and items are completely different than the original ones so I think trying to do the calculations from scratch would not be any different than remounting the component.

It works really well as it is so I will leave it like that. Thank you for sharing your work.

**Comment by petyosi** [comment]
Doing the calculations from scratch is most likely going to be faster, to be honest. Closing this one, feel free to comment if you need any help.

**Comment by krmzbbr** [comment]
OK, if it is going to be faster, may I suggest an API method that would flush cache and recalculate. Not sure if a lot of people will need it but it does makes sense in this situation.
