### ISSUE TITLE
startReached event is continuously being fired

### ISSUE THREAD

**Issue by Eliyar** [petyosi/react-virtuoso#251]
Hi, while trying to implement the prepending items scenario, I've noticed that the `startReached` event will continuously fire on the latest version (v1.2.2 at this time). 

I've tried downgrading the version and on v1.1.3 it is working as expected, where the scroll position is fixed on the `startReached` event and items prepended.

Here is the sandbox link for v1.2.2, demonstrating the issue:
https://stackblitz.com/edit/react-swssri?devtoolsheight=33&file=src/List.js

Here is the sandbox link for v1.1.3, working as expected:
https://stackblitz.com/edit/react-7zmrtx?devtoolsheight=33&file=src/List.js

Both examples use the same Prepending Items scenario from the documentation.

Please let me know if the links are not working.

**Comment by petyosi** [comment]
Thanks, [here's a fixed stackblitz with 1.2.3](https://stackblitz.com/edit/react-2muuo1?devtoolsheight=33&file=src/List.js).
