### ISSUE TITLE
Group headers are offset by the Header components height using GroupedVirtuoso

### ISSUE THREAD

**Issue by mellson** [petyosi/react-virtuoso#252]
Happy new year 🎊 and thanks for creating this wonderful library!

I'm just starting to play around with it now and loving it so far.
Using GroupedVirtuoso and a Header in the components prob, I run into an offset problem.

The height of the header component seems to interfere with how the group headers are exchanged.

I've created a simple example at CodeSandbox based on the [grouped numbers example](https://virtuoso.dev/grouped-numbers/) - the [sandbox is here](https://codesandbox.io/s/lucid-cohen-q44wp?file=/src/App.js).

**Comment by petyosi** [comment]
Nice catch, I will look into it.

**Comment by mellson** [comment]
Awesome, thanks @petyosi the new version does indeed fix this problem
