### ISSUE TITLE
react-virtuoso is not working with simplebar-react

### ISSUE THREAD

**Issue by tiagoevanp** [petyosi/react-virtuoso#253]
simplebar-react npm page:https://www.npmjs.com/package/simplebar-react

Isn't possible to rewrite the viewport element in react-virtuoso: https://github.com/petyosi/react-virtuoso/blob/2c117ac5e4ade1c385b50451c5d2bf1d8edf1551/src/List.tsx#L309

I want to use the simplebar as a custom List stylized component, but unfortunately wasn’t possible.

**Comment by petyosi** [comment]
If I understand the simplebar logic, you don't have to override the viewport - instead, you should override the root element.

**Comment by petyosi** [comment]
[This is the example](https://virtuoso.dev/custom-scroll-container/) you should be looking at.

**Comment by petyosi** [comment]
For what is worth, I tried to integrate it the way it's supposed to work, but the markup looks strangely modified - parts of the virtuoso DOM have classes assigned and the scrolling does not work. 

At this point, this looks more like an issue that could be addressed on the Simplebar side. Maybe there are other custom scrollbar solutions that could work for you. 

As a reference, [here's an implementation using react custom scrollbars](https://codesandbox.io/s/intelligent-snyder-ox4iz?file=/src/index.js).

**Comment by tiagoevanp** [comment]
Thanks, I will do more tests...

**Comment by ozsirma** [comment]
> Thanks, I will do more tests...

@tiagoevanp  you can use overlayscrollbars as an alternative to simplebar.
https://github.com/KingSora/OverlayScrollbars

As a reference, [virtuoso + overlayscrollbars ](https://codesandbox.io/s/react-virtuoso-custom-scrollbar-mz4lg?file=/src/CustomScrollbar.js)

**Comment by tiagoevanp** [comment]
Rocket.Chat is using the [rc-scrollbars](https://github.com/sakhnyuk/rc-scrollbars) for now. Thanks for your reply!

**Comment by NathanDeveloping** [comment]
> > Thanks, I will do more tests...
> 
> @tiagoevanp you can use overlayscrollbars as an alternative to simplebar.
> https://github.com/KingSora/OverlayScrollbars
> 
> As a reference, [virtuoso + overlayscrollbars ](https://codesandbox.io/s/react-virtuoso-custom-scrollbar-mz4lg?file=/src/CustomScrollbar.js)

Thank you for this! But it's not working with GroupedVirtuoso. After a bit of scrolling we lose the sticky group headers...

Any idea how to fix it ?
