### ISSUE TITLE
"ResizeObserver loop limit exceeded" error with images

### ISSUE THREAD

**Issue by petyosi** [petyosi/react-virtuoso#254]
Discussion [in this fork](https://github.com/edunad/react-virtuoso/commit/581d4558f2994adea375291b76fe59605556c08f).

[Repro here](https://codepen.io/failcake/pen/WNGKoYL).

A possible fix is to wrap the callback call in RAF. Should test that, as it might cause render delays.

**Comment by petyosi** [comment]
@edunad - please give this a try.

**Comment by edunad** [comment]
Seems to be fixed, thanks!

**Comment by petyosi** [comment]
@edunad I had to revert that change - unfortunately, it introduced an issue with reverse scrolling (#269). Can you try the workaround from this discussion - https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956

**Comment by hilts-vaughan** [comment]
FYI This happens for legitimate reasons in that you are modifying the same thing you observe -- I think this is a legitimate use case and opened https://github.com/w3c/csswg-drafts/issues/6173 to discuss it.

You can see the above for more info as well; please chime in if this is something that has caused you pain in the past.

**Comment by gabrielmicko** [comment]
I still have this issue in the newest version 2.2.1

**Comment by ychcg** [comment]
> I still have this issue in the newest version 2.2.1

I also have this issue after update version 2.2.1.
I don't know it can help but I use scrollIntoView as new feature.

**Comment by seschwartz8** [comment]
I'm getting this error on 2.2.2

**Comment by petyosi** [comment]
See my previous comment for a possible workaround

**Comment by andrisole92** [comment]
+1
