### ISSUE TITLE
EmptyPlaceholder not working

### ISSUE THREAD

**Issue by nullset** [petyosi/react-virtuoso#256]
Since upgrading to v. 1.2.4 from the earlier 0.x release, the empty placeholder option no longer seems to work.

```
<Virtuoso
          ref={listRef}

          defaultItemHeight={30}
          className={className}
          totalCount={state.list.length}
          totalListHeightChanged={handleListHeightChange}
          itemContent={renderItem}
          endReached={handleEndReached}
          components={{
            EmptyPlaceholder: () => <div>I am empty</div>,  // Does not work
            Header: () => <div>I am the header</div>,  // Works as expected
          }}
        />
```

Am I using this option correctly? Thanks!!

**Comment by petyosi** [comment]
This seems right, and it [works well in this example](https://codesandbox.io/s/frosty-joliot-psp9v?file=/src/App.tsx). Maybe one of the other props interferes with it - can you fork the codesandbox?

**Comment by nullset** [comment]
Must have been my build process ... it appears to be working for me now. Sorry for the noise!
