### ISSUE TITLE
When totalCount reduces abruptly and we scroll to last item using scrollToIndex , virtuoso adds padding bottom and there are no items in most of the visible screen

### ISSUE THREAD

**Issue by ProtoGanesh** [petyosi/react-virtuoso#259]
When total size of items reduces abruptly and we scroll to last message using scrollToIndex , virtuoso adds padding bottom and there are no items in most of the visible screen. Items are pushed out of view and scroll is at the bottom

**Comment by ProtoGanesh** [comment]
![VirtuosoIssue](https://user-images.githubusercontent.com/28604594/104442105-9bbc0280-55ba-11eb-9738-8f5bca54a300.PNG)

**Comment by ProtoGanesh** [comment]
it happened when we dynamic height items.

**Comment by petyosi** [comment]
Can you post a repro? 

In general, I recommend remounting the component if you change its data. Check [this thread](https://github.com/petyosi/react-virtuoso/issues/250).

**Comment by ProtoGanesh** [comment]
cant' post a repro but that thread worked and remounting works. thank you very much for the idea. one problem we have when items are removed the container size is not adjusted that needs a look into maybe in future releases (in case i am in same channel of chat application and i delete message).

**Comment by petyosi** [comment]
@ProtoGanesh The fix which I just published is likely resolving both your initial issues and 

> one problem we have when items are removed the container size is not adjusted

Given that I understand it correctly. Check the example I used to test in the commit above. 

Still, I do recommend remounting the component when switching chats. For maximum performance, you can also keep separate instances per conversation.

Please confirm that the fix I published works for you - if not, please provide a reproduction for me to help you further. 

Cheers,

**Comment by ProtoGanesh** [comment]
yes it does work. sorry for late response but my server was down yesterday and so couldn't test. but thank you very much for responding so quickly and resolving the issue.
