### ISSUE TITLE
Custom fully managed scroll bar

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#265]
I think it would be a good idea to eventually make Virtuoso work with a custom scroll bar component that it manages fully, like VS Code does basically.

Without this I don't think it's possible to provide a **perfect** user experience.

Right now when scrolling pretty quickly or if the computer is particularly busy it can happen that the user will see some visual glitches, all glitches should be removed eventually, and without a custom fully managed scroll bar I think that's impossible.

# Example use case

How it works now:

- The user clicks somewhere in the scroll bar.
- The scroll position jumps immediately.
- If the content to paint for the new position isn't ready yet the user will stare at a blank list for a bit, even if it's just a couple of frames the user experience will suffer from this.

How it could work with a custom fully managed scroll bar:

- The user clicks somewhere in the custom scroll bar.
- The scroll bar updates immediately, giving an instant feedback to the user for a good user experience.
- If the content to paint for the new position isn't ready yet then nothing happens in the list for a bit, as soon as the new content is ready the list can be repainted with the new content, with no visual glitches (assuming the content doesn't take too long to get ready, if it takes too long for that then that problem is probably outside of Virtuoso's area of competence anyway).

This is just an example, taking control of the scroll bar can similarly help improve the user experience while scrolling too.

**Comment by petyosi** [comment]
I understand the underlying motivation, but I don't believe that custom scrolling implementation will address that. Most likely, be an uncanny valley experience. Mobile devices, laptop trackpads, etc provide a variety of different scrolling methods with their own kinetics. An emulation will feel different.

Instead, I would rather improve the performance of the component to its fullest - both in terms of code and best practice recommendations. Any help (repros, test cases, PRs, etc) in that direction is greatly appreciated.

**Comment by fabiospampinato** [comment]
> I understand the underlying motivation, but I don't believe that custom scrolling implementation will address that.

Isn't that the only thing that could address that? How else could you possibly address that if you don't control scrolling?

Even if Virtuoso had no overhead at all you'd still get that problem.

> Mobile devices, laptop trackpads, etc provide a variety of different scrolling methods with their own kinetics. An emulation will feel different.

It would be difficult to emulate the native behavior, but VS Code does it perfectly on desktop, I know less about mobile but there are efforts like Flutter that basically paints everything itself on a canvas, scrolling there seems to work well too from what I've seen.

I'm suggesting something that wouldn't make sense to implement for a long time, but that I see as a necessary step toward perfection, and basically I want to strive for perfection, which means either Virtuoso becomes perfect or it will have to be replaced by something else eventually, perfection can't be improved upon.
