### ISSUE TITLE
Scroll to item while in group mode

### ISSUE THREAD

**Issue by martiancoding** [petyosi/react-virtuoso#267]
Hello everyone! Amazing library, love it! A project I'm currently working upon demands scrolling to an item and also show group headers to the user. So far, I have [managed to group](https://virtuoso.dev/scroll-to-group/) a flat list of cards and am stuck at scrolling to a particular card on click from an external button. The example I followed from the documentation by using the "**virtuoso.current.scrollToIndex()**" method is scrolling to the group header. Any pointers towards an example showing scroll to an item while in grouped mode will be helpful. Thank You.

**Comment by petyosi** [comment]
The group headers are sticky - they will stay at the top of the list. If you pass the correct card index, it should scroll to the point where this card is the first item visible below the header. 

Hope this makes sense. Post a reproduction if you are facing problems with the above.
