### ISSUE TITLE
Unable to scroll to bottom in reverse mode with a Footer

### ISSUE THREAD

**Issue by dannycarrera** [petyosi/react-virtuoso#270]
When using virtuoso in reverse mode with a Footer; there seems to be no way to scroll to the bottom. For example, a typical chat app will have messages in reverse and an input box beneath the messages. I'm using a footer to add some space between the messages and the input box. After appending a new message, I'm unable to get the scroller back to the bottom.

`scrollToIndex` will only scroll to the last item
`scrollTo` requires virtuoso's scrollHeight (#262 could solve this)

**Comment by petyosi** [comment]
Agreed, #262 can help. However, using `align: 'top'` [seems to work as well](https://codesandbox.io/s/young-darkness-xrskn?file=/src/App.tsx:772-789). Modify the example unless I am missing something.

**Comment by dannycarrera** [comment]
Thanks @petyosi . `align: 'start'` works well. My mistake was that I was using `align: 'end'`

**Comment by natew** [comment]
As of the current version it seems to actually add space below the bottom to force the footer to actually go to the top of the frame, unless I'm missing something:

![Image](https://github.com/user-attachments/assets/ad46784d-c6e2-4d76-8b5d-19aa38ef224a)

You can see padding-bottom is set to 1024px which pushes the footer to the start of the frame. Smart if you want that functionality, but breaks if you want the footer to act as a hidden spacer for a floating input!

**Comment by natew** [comment]
aha - `start-no-overflow`

**Comment by natew** [comment]
Hm, but this then breaks with `.append` after that, it no longer scrolls to the very bottom. And if you follow immediately with `methods.scrollToItem` its glitchy as it tries to move scroll twice.
