### ISSUE TITLE
Inconsistent scrollToIndex after adding new item

### ISSUE THREAD

**Issue by dannycarrera** [petyosi/react-virtuoso#271]
`scrollToIndex` does not consistently scroll to last item after adding a new item. Calling it in `useEffect` or `totalListHeightChanged` both result unexpected scroll locations. [Example](https://codesandbox.io/s/dazzling-chebyshev-f7kze?file=/src/App.tsxl)

**Comment by petyosi** [comment]
Check the configuration in [this example](https://virtuoso.dev/stick-to-bottom/). It won't work with a custom footer, though - it would be easier for you to figure out an alternative way to add the padding to the bottom.

**Comment by dannycarrera** [comment]
@petyosi Thanks for the quick reply. I checked out the 'Stick to Bottom' example. This works well when adding a new item when already at the bottom of the list. `followOutput` does not work when scrolled partially up the list. 

I updated the [example](https://codesandbox.io/s/dazzling-chebyshev-f7kze?file=/src/App.tsx) to show you. When at the bottom already, `followOutput` works. When partially scrolled up, it does not.

I'm not too concerned with the footer. I will find an alternative to adding padding to the bottom.

Is there no callback once the final item is rendered? That seems like the right time to call `scrollToIndex`

**Comment by petyosi** [comment]
The behavior of `followOutput` is intentional. If the user has scrolled to the top, forcing them to the bottom of the list is not a good UX. The chat UIs I have examined usually display an indicator that fresh content is available down the bottom, with a button scroll down. 

Calling scrollToIndex after totalCount changes is not trivial due to items' measurements. That's why I implemented the properties I refer to in the example above. Your best bet would be to wrap the call in a `setTimeout`.

**Comment by dannycarrera** [comment]
I 100% agree with you @petyosi that it's bad UX to force a user to scroll down when new _incoming_ messages are appended. I was working on the case when a user is scrolled up and sends an _outgoing_ message. For this case it's better UX to scroll to the bottom when the user submits a new message.

Instead of using `setTimeout` I ended up calling `scrollToIndex` before submitting a new message and letting `followOutput={'smooth'}` handle scrolling the last part. This provided the best visual effect. These are still 2 separate scroll events though. 1 scroll event after submission would be optimal.

I believe this issue should be reopened as `scrollToIndex` is, in fact, inconsistent after adding a new item. Is it possible to have a callback similar to `totalListHeightChanged`, but it gets called_after_ `itemContents` are rendered? It could be called `totalCountChangedAndRendered`. This would be a great time to call `scrollToIndex`. But I think that would be a new issue?

**Comment by petyosi** [comment]
Ah, this absolutely makes sense. Thank you very much for providing the background! I am opening #272 to track that. Feel free to comment with additional information. 

Will give this some further thought before deciding on the API.
