### ISSUE TITLE
Weird scrolling behavior when list have really tall items

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#273]
Hi @petyosi,

I was struggling to get a simple thing to work consistently and reliably on our SMS conversation lists.   

That is the **initialTopMostItemIndex** or the **initialScrollTop** options.    

I want the list to be at the bottom on load, so I set it either with
` initialTopMostItemIndex={messages.length - 1} `
or I tried 
`initialScrollTop={Number.MAX_SAFE_INTEGER}`

For most of our lists, it is positioning well.  But for some, you can see the scroll bar at the end for a second and then position itself at X amounts of pixels from the bottom.    I've been looking for quite a bit and the only thing I could notice on those lists was the presence of some real long messages that result in items being >3000px in height.   I also notice that when scrolling up through those long messages for the first time,  the scrollbar is acting weird (sometimes going really fast) and the message is jumping around up and down.

I also notice the `data-known-size` attribute does match the items height perfectly.

I've tried to reproduce the behavior with this sandbox.

https://codesandbox.io/s/funny-grass-nu70k

Let me know if there is something I can do to help figure this out.

Thx

**Comment by petyosi** [comment]
Thank you for the repro @Ethorsen - that's very helpful. 

The first behavior (alignment of the item specified in initialTopMostItemIndex) is by default - as the name implies, it aligns the specified item to the top of the list. I do understand that you are looking for alignment to the bottom. Will give this some thought and maybe alter the prop to accept an alignment option. 

The second problem I see in the sandbox seems like a bug that I will have to look into. Keeping this issue open for updates.

**Comment by Ethorsen** [comment]
Thx @petyosi 

For the alignment problem, I haven't been able to reproduce in the sandbox.  I only get it on some of our conversations list.     It is not aligning on the beginning of the last message, but randomly X pixels above the bottom.  (i've seen anywhere from 1px to 400-500px).  
Like I said, you can initially see the scroll bar being at the end and then jump up a bit. Like if some messages would grow after initial rendering.

Only after I noticed the issue with the tall messages (they are not toward the ends), and I though it might be related.  But obviously it might not.

**Comment by petyosi** [comment]
@Ethorsen check if your project is up-to-date - I recently identified and fixed a bug where `followOutput` interfered with the `initialTopMostItem` prop.

**Comment by Ethorsen** [comment]
I am under 1.4.0

**Comment by ACT1GMR** [comment]
@Ethorsen hi thanks for producing our concern as well, we have exactly same issue here (a chat platform with very variable message boxes height and with a lot of content). I updated your sandbox to latest virtuoso (1.5.1) and still jumpy flashy behavior happened there. @petyosi first thanks for your great repo that heal a lot of pains here and around react world but please check this sandbox with latest virtuoso version you will see problem still exits. a more weird things that after first shown of the evil box if you go back and repeat the scenario it will not happen. seems initial height calculation or something not resolve in first actions ( don't know just guess )
here the latest virtuoso with exact same sandbox that @Ethorsen generated.

https://codesandbox.io/s/keen-wood-9dimc

**Comment by petyosi** [comment]
@ACT1GMR so far, the sandbox of @Ethorsen revealed 3 problems:

1. A tall item at the bottom followed by a short one causes an initial jump. Extracted to #276 and solved in v1.5.1
2. Reverse scroll compensation was not functioning as expected in Windows. Extracted to #278 and solved in v1.5.1 (I hope). 
3. **An item taller than the viewport** causes a jump in reverse scrolling mode. This is not solved - hence this issue is still open. 

Hope this makes sense. My understanding is that you are observing the third problem. Let me know if this is so.

**Comment by ACT1GMR** [comment]
@petyosi 
1- fixed here also
2- don't know
3- **exact and single point of failure for dynamic height list item cases here** 
OK I will follow up. thanks again

**Comment by ACT1GMR** [comment]
one workaround existed right now that cause as less issue as possible @Ethorsen @petyosi :
instantly after list fetched and rendered you can goto last index manually:
`this.virtuoso.current.scrollToIndex({
        index: messages.length - 1
        });`
and scrolling looks normal.

**Comment by petyosi** [comment]
Here's an updated version of the [originally reported sandbox](https://codesandbox.io/s/suspicious-kalam-jxr7i?file=/src/index.js).

**Comment by ndave-ut** [comment]
> @ACT1GMR so far, the sandbox of @Ethorsen revealed 3 problems:
> 
> 1. A tall item at the bottom followed by a short one causes an initial jump. Extracted to [Initial scroll up is jumping around when initialTopMostIndex={lastIndex} is used #276](https://github.com/petyosi/react-virtuoso/issues/276) and solved in v1.5.1
> 2. Reverse scroll compensation was not functioning as expected in Windows. Extracted to [upwards scroll compensation mechanism is unreliable on Windows #278](https://github.com/petyosi/react-virtuoso/issues/278) and solved in v1.5.1 (I hope).
> 3. **An item taller than the viewport** causes a jump in reverse scrolling mode. This is not solved - hence this issue is still open.
> 
> Hope this makes sense. My understanding is that you are observing the third problem. Let me know if this is so.

Hi @petyosi 👋  Is the #3 fixed? because I'm still observing issue in reverse scrolling mode for items taller than viewport

**Comment by Axultan** [comment]
Hi @petyosi, 

We have the same problem as @ndave-ut
