### ISSUE TITLE
Providing a react Ref to scrollerRef is generating an error

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#274]
A react ref created with React.createRef/useRef will spit out an error if given directly to scrollerRef prop;

This will generate an error
```
const scrollerRef = useRef();
<Virtuoso
   scrollerRef={scrollerRef}
```

Work around for now, give a callback function
```
const scrollerRef = useRef();
<Virtuoso
   scrollerRef={(ref) => { scrollerRef.current = ref; }}
```

https://codesandbox.io/s/long-pine-e9g8g?file=/src/App.js

**Comment by petyosi** [comment]
Can confirm that - it does not accept a react ref. The TS signature and the docs describe that. The workaround is not that much of a problem, but I am open to PRs.

**Comment by gajus** [comment]
You should memoize that callback

```ts
const handleScrollerRef = useCallback((ref) => {
  scrollerRef.current = ref;
}, []);
```
