### ISSUE TITLE
How can I set classes in grid

### ISSUE THREAD

**Issue by Spaubleit** [petyosi/react-virtuoso#275]
Hello. Great library. Very powerful and easy to use. In docs I find info about list and item classes:

> he component provides no styling out of the box; the styling and the layout of the items can be specified by passing two properties - itemClassName and listClassName.

But when I try to pass them I get typescript error:
> property listClassName does not exist on type 'IntrinsicAttributes & VirtuosoGridProps'

I can't find more info in repository. Is it docs outdated? Thank you.

**Comment by petyosi** [comment]
@Spaubleit that's a bug on my side, thanks for reporting. I haven't exposed those classes during the migration to v1. Will publish a fix tomorrow.
