### ISSUE TITLE
Initial scroll up is jumping around when initialTopMostIndex={lastIndex} is used

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#276]
Hi @petyosi,

Sorry it might be a duplicate/same issue as #273. But I'm unsure so I post it here.   Feel free to close/merge if its the case.  

I've been spending some time trying to figure out this one.  But just can't fix.     I've also been able to reproduce in a sandbox.

https://codesandbox.io/s/throbbing-resonance-7eupw

- Scenario is still our SMS conversation list.   
- We scroll to the end on mount with initialTopMostIndex={lastIndex}
- When you initially scroll up (mouse wheel, keyboard arrows or even scrollbar arrows), the scrollbar and content is jumping around up and down.
- Its only doing this when items have not been rendered yet.   So lets say you scroll up 100 items. Now for those 100 items, the scrolling behavior will be smooth (up or down).

Thx again for this great library.

**Comment by petyosi** [comment]
I think I am fixing this exact problem right now. Will publish a fix tomorrow after some more tests.

**Comment by petyosi** [comment]
Check v1.5.0. I think the problem manifests itself only for a very tall bottom item with a short one on top of it.

**Comment by Ethorsen** [comment]
Problem seem to be persistent.

https://codesandbox.io/s/throbbing-resonance-7eupw

When scrolling up,  the items are still jumping around.

**Comment by petyosi** [comment]
Can you record a gif? We might be talking about different cases.

**Comment by petyosi** [comment]
FWIW, here's what I see - https://share.getcloudapp.com/2NuEKAgw

A thing (which is my fault to a certain extend) is that the examples use random sized items, which makes it hard to reproduce issues like this. If you reproduce it, notice if there was something specific about the problem - for example, a very tall item or a very short one. 

Also, the fix I introduced in 1.5.0 addresses an initial "jump". #273 is still open, as a very tall item will disrupt reverse scrolling.

**Comment by Ethorsen** [comment]
Here's what I'm seeing.

<a href="https://ibb.co/CK7bS1N"><img src="https://i.ibb.co/YBkcVRY/test.gif" alt="test" border="0"></a>

That said, I started to think it might be browser related.  I'm using Vivaldi which is normally acting like any other chromium based browser.  But there is some exceptions.

After doing tests with major desktop browsers (all latest, windows 10).
Chrome:  Ok
Firefox: Ok
Opera: Ok
EdgeChromium:  Has the problem
Vivaldi:  Has the problem
Brave: Untested

**Comment by petyosi** [comment]
Thank you @Ethorsen - this gives me the clue. I managed to reliably reproduce the problem in both Chrome and Edge in Windows. The problem seems to be related to the kinetics of the OS. 

[Tracking the issue here](https://github.com/petyosi/react-virtuoso/issues/278).

**Comment by Ethorsen** [comment]
Amazing work thanks a lot
