### ISSUE TITLE
Possible to have infinite number of reverse scrolled items?

### ISSUE THREAD

**Issue by tolfino** [petyosi/react-virtuoso#277]
The docs talk about using `firstItemIndex` to support this use case:

> Use when implementing inverse infinite scrolling - decrease the value this property in combination with data or totalCount to prepend items to the top of the list.
>
> Warning: the firstItemIndex should be a positive number, based on the total amount of items to be displayed.

Unless I'm greatly misunderstanding, it seems like `firstItemIndex` can only be used if I know what the `totalCount` is? Is it not possible to infinitely scroll in the reverse direction and is it bounded by how many indices are available between the current index and `firstItemIndex `?

Thank you!

**Comment by petyosi** [comment]
Your understanding is correct - the list won't support *infinite* amount of items. You should pick a sufficiently large number for that prop that's either your totalCount or guaranteed to be larger than it.
