### ISSUE TITLE
`scrollToIndex` not working with `useWindowScroll`

### ISSUE THREAD

**Issue by tadeolinco** [petyosi/react-virtuoso#284]
Just posting some feedback. Here's a producible sample https://stackblitz.com/edit/react-xbdrl5

Awesome work with the library!

**Comment by petyosi** [comment]
I need to investigate this further, but for now, adding this:
```
<style>
html {
  height: 100%;
}
</style>
```
makes [the example work](https://stackblitz.com/edit/react-htmmbk?file=src%2Fstyle.css).

**Comment by tadeolinco** [comment]
@petyosi thanks for quick fix! :100:
