### ISSUE TITLE
ScrollSeekPlaceholder not working well with logitech mx master

### ISSUE THREAD

**Issue by RanST-dev** [petyosi/react-virtuoso#288]
I have a Logitech MX Master mouse with a fast scroll option, as well as a Logitech MX Anywhere mouse with the same feature.

When I scroll really fast and stop suddenly, the list will be stuck with placeholders. If I scroll again slowly it will be updated and show the component defined in `itemContent` prop.
I guess it has something to do with debouncing of on scroll event, but I am not sure.

Is there any way to fix it?

It happens with the example: https://virtuoso.dev/scroll-seek-placeholders/

Screenshot:
![image](https://user-images.githubusercontent.com/62574602/106748379-d64f1300-662d-11eb-8159-68e0bdfb3c1d.png)

**Comment by petyosi** [comment]
I don't have access to such a device, so I am not sure what's going on. You can easily run the project locally and throw some [breakpoints in the code](https://github.com/petyosi/react-virtuoso/blob/master/src/scrollSeekSystem.ts) - this is the system in question. If you are interested in doing that and need some help, let me know - I will reopen the ticket.

**Comment by psirenny** [comment]
I don't think this is device specific. I encounter the same problem with an Apple mouse. For me, it seems I often have stray `enter` callbacks fire _after_ the exit callback. I've observed this in my project but haven't created a reproducable example.

**Comment by vnesterovspirent** [comment]
This behavior is reproduced with a usual mouse, are there any solutions to this problem?

**Comment by petyosi** [comment]
@vnesterovspirent are you willing to debug it and submit a PR? As guidance, this is the code that handles scroll seek logic:

https://github.com/petyosi/react-virtuoso/blob/master/src/scrollSeekSystem.ts

**Comment by vnesterovspirent** [comment]
Thanks for the hint, I will try to figure this out.
