### ISSUE TITLE
Potentially Dangerous bug with VirtuosoGrid

### ISSUE THREAD

**Issue by AlonBru** [petyosi/react-virtuoso#289]
when using VirtuosoGrid component, for some reason sometimes there is a bug causing the list's topand bottom padding to change rapidly causing flickering that I assume might be dangerous to an epileptic person.  
provided is an gif of the problem, only in reality the flickering is much faster, which could not be properly captured by the screen recorder.  
example:
<details>
  <summary>warning: flashing images, click to reveal</summary>
  
  ![virtubug](https://user-images.githubusercontent.com/66993391/107124998-b29aff80-68af-11eb-9715-b62113169446.gif)  
</details>
the virtuoso component:    
![image](https://user-images.githubusercontent.com/66993391/107125280-8f714f80-68b1-11eb-8a96-d53d940b6663.png)  
the issue does not seem to be affected by changing the overscan.
the data is coming from a react-query infinite query
I am using 
- package version: react-virtuoso version 1.24
- browser: Chrome 88.0.4324.104
- OS: windows 10 20H2

I would be glad answer any questions and test any fixes that you may have regarding what may be causing it

#### update
- the jittering seems to happen when scrolling to slightly above the seam between one query's data and the next.

**Comment by petyosi** [comment]
Please reproduce this in a code sandbox.

**Comment by AlonBru** [comment]
Can't seem to, I'm afraid. the problem does not appear on the demo...  
[demo](https://codesandbox.io/s/magical-cherry-55r8s?file=/src/App.js)  
the things that seem to be changing are the top and bottom padding of the list element, can you you tell me what has influence on their values?

**Comment by petyosi** [comment]
Padding is changed to cut off the list to its visible window. Check if you are not using margins in your items.

**Comment by AlonBru** [comment]
this is the ItemWrapper used in the "components" propety:  
![image](https://user-images.githubusercontent.com/66993391/107147490-17f5fb80-6957-11eb-8ebb-bf3750cba0f4.png)
and this is the content:  
![image](https://user-images.githubusercontent.com/66993391/107147344-33143b80-6956-11eb-9100-56801b904c16.png)  
they don't use margins, and I've tried disabling all css props one by one and together, to no avail.
the demo I made is quite barebones, and still does cause the jitter when it's in my project (though not in the sandbox..)  

I understand what the padding is used for, I asked what goes into calculating them, so I may see if it's doing something unexpected on my end.

thanks for your quick replies

**Comment by AlonBru** [comment]
![image](https://user-images.githubusercontent.com/66993391/107148169-82f50180-695a-11eb-8277-0785a48125c5.png)


changing the marked values (height, max-height, min height) seems to have solved the problem, at least for now, but I still don't really know what caused it.  
height:244px seems fine,   
height:243px causes problems.
I can't be sure it's safe.

**Comment by petyosi** [comment]
@AlonBru reopen this if you can reliably reproduce the problem in a sandbox. Thanks!
