### ISSUE TITLE
Create callback prop for getting total height

### ISSUE THREAD

**Issue by theonlylies** [petyosi/react-virtuoso#29]
I need get full height for implement my own scroll behavior around `scrollTop` for `VirtuosoScroller`.
I think that need/can to be implemented some callback prop for `Virtuoso`, that can be passed into `VirtuosoView` and call function with `fillerHeight` as param.
if you know some better solution. pls tell me 
if this idea not bad - i can try to create PR
sorry for my lang

**Comment by petyosi** [comment]
Hey, 

Thank you very much for your suggestion. You can expose the fillerHeight via callback prop easily. The `isScrolling` property is exposed in a similar manner. You don't need to change the VirtuosoView. Check https://github.com/petyosi/react-virtuoso/pull/28 request, which does something similar (exposing output stream as a prop).

Let me know if you need any help with the PR. 
Cheers,

**Comment by theonlylies** [comment]
@petyosi 
i add some dirty PR. I'l be glad if you help me with this #30
