### ISSUE TITLE
VirtuosoGrid, Firefox: Negative index is passed to itemContent in initial rendering

### ISSUE THREAD

**Issue by Spaubleit** [petyosi/react-virtuoso#290]
**Describe the bug**
I got -1 index in usual VirtuosoGrid usage. Also get warning: `Infinity` is an invalid value for the `paddingTop` css style property.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-index-error-r3hj9?file=/src/App.tsx

**To Reproduce**
Just open console

**Expected behavior**
I expect to never get a negative index :)

**Desktop**
 - OS: Fedora 33,  Gnome 3.3.3 Wayland
 - Browser: Chrome 88.0.4324.150, Firefox 85.0
 - react-virtuoso: 1.5.4

**Comment by petyosi** [comment]
What's the idea behind your setup? The grid element does not have a height.

**Comment by Spaubleit** [comment]
Thank you for fast response. I forget about the height of the grid, but the error does not depend on it. The grid is now rendered with the same issues.

**Comment by petyosi** [comment]
As far as I can see, the error is no longer reproducible in Chrome. Firefox reports the Infinity error and the -1 index. Let me know if this matches what you observe.

**Comment by Spaubleit** [comment]
You're right. I have the same behavior. Firefox is my main browser, apparently so I discovered this issue.
