### ISSUE TITLE
[BUG] Prepening items scenario implementation blinks.

### ISSUE THREAD

**Issue by dodosan-89** [petyosi/react-virtuoso#292]
**Describe the bug**
When using the Virtuoso component in a Prepending items list scenario the list of items blinks when new items are pre-pended at the top.

**Reproduction**
Can be observed on Prepending items example: https://virtuoso.dev/prepend-items/

**To Reproduce**
1. Scroll to the top-most item
2. Observe that the whole list of items blinks before new items are prepended.

**Expected behavior**
Should not blink.

**Additional context**
This behaviour is very garring in chat usage of this list since all message bubbles blink when new items are rendered.

**Comment by petyosi** [comment]
At the moment, I don't have any ideas on how to improve this behavior Prepending items is a multi-step operation - items are inserted at the top, and then the element scrollTop is re-calculated and restored at its previous point. This causes the blink you describe. 

If this is a critical problem for you, you can overlay a loading indicator on the UI.
