### ISSUE TITLE
Support useWindowScroll for VirtuosoGrid

### ISSUE THREAD

**Issue by aravind-tc** [petyosi/react-virtuoso#294]
useWindowScroll is not working with VirtuosoGrid. Do you have plans to support this?

Thanks
Aravind

**Comment by petyosi** [comment]
Yes, but I don't have an ETA on this.

**Comment by aravind-tc** [comment]
@petyosi Do you need my help? I am willing to port the changes useWindowScroll from virtuoso to virtuosoGrid.

Thanks
Aravind

**Comment by petyosi** [comment]
Absolutely - a PR is more than welcome. [This is the commit](https://github.com/petyosi/react-virtuoso/commit/1ee6bff) for the list. The `WindowViewportInfo` should be extended with `width` so that it can be reused in the Grid.

**Comment by petyosi** [comment]
@aravind-tc `useWindowScroll` is available in the 1.7.0 release. Check [this codesandbox](https://codesandbox.io/s/bitter-sunset-9vwmq?file=/src/App.tsx) for a working example.
