### ISSUE TITLE
[BUG] followOutput stops following if viewport is resized. 

### ISSUE THREAD

**Issue by petyosi** [petyosi/react-virtuoso#297]
The implementation does not track the viewport changes - only the addition of new items. Should look into both increase and decrease. 

Necessary to check - if the viewport is resized, the list items may be resized as well. The repositioning should be applied after that.

**Comment by chrisdostert** [comment]
would be awesome if the solution to this could also solve https://github.com/petyosi/react-virtuoso/issues/127

**Comment by chrisdostert** [comment]
just tested and #127 works flawlessly now, amazing work!
