### ISSUE TITLE
Page down / spacebar buttons don't work in large lists

### ISSUE THREAD

**Issue by xrd** [petyosi/react-virtuoso#3]
Steps to reproduce:

1. Go to: https://virtuoso.dev/?path=/story/introduction--100-000-items
1. Click into the list.
1. Use page down or spacebar. 
1. Notice the list scrolls down one page.
1. Hit the spacebar/page down button again. Notice it no longer works.

Tested on Chrome Version 72.0.3626.109 (Official Build) (64-bit), Linux.

**Comment by petyosi** [comment]
Hey @xrd , 

thank you very much for spotting that. I fixed that in https://github.com/petyosi/react-virtuoso/commit/af28a5cc79d16d3c774ae912763980d0a5431b7a, published `0.2.0` and updated the examples. Works fine on my side, tested in Chrome, Safari, and Firefox.
