### ISSUE TITLE
[BUG] initialItemCount does not pull record from `data`

### ISSUE THREAD

**Issue by dlee** [petyosi/react-virtuoso#301]
**Describe the bug**
Supplying an `initialItemCount` breaks virtuoso.

**Reproduction**
https://codesandbox.io/s/admiring-hill-uvvkq?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/admiring-hill-uvvkq?file=/src/App.js
2. Notice that `initialItemCount={50}` and Virtuoso is broken
3. Set `initialItemCount={0}`
4. Notice that Virtuoso works again

Alternative reproduction steps:
1. Go to https://virtuoso.dev/hello/
2. Add `initialItemCount={50}`
3. Notice that the example breaks

**Expected behavior**
Setting an `initialItemCount` should not break Virtuoso.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by petyosi** [comment]
Got it, it seems to be missing the record from the data prop. Will look into it.
