### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jonathaneckman** [petyosi/react-virtuoso#302]
**Describe the bug**
Scrolling quickly in a grouped list with endless scroll throws a RangeError.

**Reproduction**
It can be reproduced in the `grouped-endless-scrolling` e2e test. 

**To Reproduce**
1. Scroll down super fast.
2. See error in console. 
    
    ```
    streams.ts:65 Uncaught RangeError: Maximum call stack size exceeded
       at streams.ts:65
       at Array.forEach (<anonymous>)
       at streams.ts:64
       at publish (actions.ts:93)
       at transformers.ts:104
       at pipe.ts:135
       at streams.ts:65
       at Array.forEach (<anonymous>)
       at streams.ts:64
       at streams.ts:99
    ```

**Expected behavior**
No error.

**Screenshots**
![fast-scroll](https://user-images.githubusercontent.com/11893200/108630459-f1de5a00-7432-11eb-81f4-8938f22ae5d4.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium based Edge

**Comment by petyosi** [comment]
Taking a look. Thanks for becoming a sponsor!

**Comment by petyosi** [comment]
@jonathaneckman it looks like I managed to mess up the example itself at some point - thanks for spotting this. This is [the incorrect line](https://github.com/petyosi/react-virtuoso/blob/master/e2e/grouped-endless-scrolling.tsx#L100), by the way. loadMore effectively calls itself. 

Here's what [the fixed version looks like](https://codesandbox.io/s/modest-wu-fzwtn?file=/src/App.tsx) - I am doing my best with scrolling fast and the error is no longer there. Can you please confirm that it also works on your side? 

Cheers.

**Comment by jonathaneckman** [comment]
@petyosi the example looks good. I wasn't able to reproduce it.

**Comment by thecodrr** [comment]
@petyosi this bug is back in the latest version: 1.9.3

```jsx
             <Virtuoso
              data={items}
              computeItemKey={(index) => items[index].id || items[index].title}
              defaultItemHeight={estimatedItemHeight}
              overscan={20}
              totalCount={items.length}
              components={{
                Scroller: CustomScrollbarsVirtualList, // I am using react-scrollbars-custom
                Header: // Render a header
              }}
              itemContent={(index, item) => {
                    // render any kind of item here
                }
              }}
            />
```

Stacktrace:
```
Uncaught RangeError: Maximum call stack size exceeded
    at listStateSystem.ts:164
    at utils.ts:20
    at pipe.ts:158
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at publish (actions.ts:93)
    at transformers.ts:104
    at pipe.ts:135
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at streams.ts:99
    at utils.ts:34
    at pipe.ts:135
    at pipe.ts:158
    at utils.ts:20
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at publish (actions.ts:93)
    at transformers.ts:104
    at pipe.ts:135
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at utils.ts:34
    at utils.ts:20
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at streams.ts:99
    at utils.ts:34
    at pipe.ts:135
    at pipe.ts:158
    at utils.ts:20
    at pipe.ts:158
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at publish (actions.ts:93)
    at transformers.ts:104
    at pipe.ts:135
    at streams.ts:65
    at Array.forEach (<anonymous>)
    at streams.ts:64
    at streams.ts:99
    at utils.ts:34
    at pipe.ts:135
    at pipe.ts:158
```

**Comment by petyosi** [comment]
Can you create a code sandbox? Also, does it persist if you remove the custom scrollbar?

**Comment by thecodrr** [comment]
> Can you create a code sandbox? Also, does it persist if you remove the custom scrollbar?

It is unpredictable. I was having it for a bit consistently but now everything seems fine.
