### ISSUE TITLE
Memory Leak on large list of data

### ISSUE THREAD

**Issue by fakhrishahab** [petyosi/react-virtuoso#303]
I try to use react-virtuoso for rendering a large count of list data, but I found the memory usage is still increase since the items was destroyed from the DOM.
It's not returning back the allocation memory to the OS.

**Comment by petyosi** [comment]
Hey,

please provide more information on the subject, including a simple, runnable example that demonstrates the issue you are observing, instructions on how to reproduce it, along with relevant information - browser, OS, etc. I will re-open the issue once this information is available and I can look at it.
