### ISSUE TITLE
[BUG] Creating infinite data virtuosu with prepending items (chat)

### ISSUE THREAD

**Issue by DrLiamKless** [petyosi/react-virtuoso#304]
**Describe the bug**
My bug is that i have an infinite data (using useInfiniteQuery from react-query) and im using it tu create a virtuoso chat.
the virtuoso sometimes dosent detect the "startReached" event, and also the paddings are randomly becoming higher then needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/67854560/109045527-5d972000-76dc-11eb-9165-2780ce19c82f.png)
![image](https://user-images.githubusercontent.com/67854560/109045596-76073a80-76dc-11eb-853f-b13c00c55282.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by petyosi** [comment]
Hey,

Debugging code in jpegs is not something I can do, yet. Please provide a simple, runnable example with minimum external dependencies (I am not familiar with react query) that demonstrates the issue you are observing, instructions on how to reproduce it. I will re-open the issue once this information is available and I can look at it.

**Comment by mchitson** [comment]
Hello i am experiencing the same issue, can we reopen this?

**Comment by mchitson** [comment]
so basically same use case am using it for a chat, and whenever i append a chat message that i type under the chat list, the endless scrolling just completely stops

displayMessages = (messages) => {
    return (
        // <div className='messages-infinite-scroll'>
          <Virtuoso className='messages-infinite-scroll'
            components={{
              Header: () => <div style={{ textAlign: 'center', padding: '1rem' }}>Loading...</div>,
            }}
            firstItemIndex={this.state.firstItemIndex}
            initialTopMostItemIndex={MESSAGE_LIMIT - 1}
            data={messages}
            startReached={this.handleInfiniteOnLoad}
            itemContent={(index, message) => {
              return (
                <Comment 
                  key = {message.timestamp}
                  content={message.content} 
                  author={message.user ? message.user.name : null}
                  avatar={<Avatar style={{ backgroundColor: '#2F4CF5' }}>{message.user ? message.user.avatar : null}</Avatar>}
                  datetime={this.getTimeElapsed(message)}
                />         
              )}}
            />
        // </div>
   );

**Comment by Bessonov** [comment]
@mchitson you should create a reproducible example.
