### ISSUE TITLE
[BUG] New item causes page to jump when not scrolled to the bottom of the window

### ISSUE THREAD

**Issue by mattmuirhead** [petyosi/react-virtuoso#305]
**Describe the bug**
When a new item is added to the data, and the user is not scrolled to the bottom of the window it causes the page to jump and the user to lose their scroll position.

**Reproduction**

https://user-images.githubusercontent.com/7092741/109278809-deefcf00-7810-11eb-924c-0a276a1c4a5b.mov

In the above demo, user a (left side of screen) sends a message to user b (right of screen). User b is half way down the scroll list, however when a message is added the window shifts and user b is no longer in the same position they were.

**To Reproduce**
Implementation:

```
<Virtuoso
    ref={ref}
    firstItemIndex={firstItemIndex}
    initialTopMostItemIndex={initialTopMostItemIndex} //set to last message index
    data={data}
    followOutput={isAtBottom => isAtBottom}
    alignToBottom
 />
```

**Expected behavior**
When a new item is added, the scroll location should stay the same

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by petyosi** [comment]
I think this is related to a recent change I introduced in 1.5.9 - can you please reproduce this in a codesandbox? I will take a look.

**Comment by mattmuirhead** [comment]
Sorry this is due to a user error. I was incrementing the `firstItemIndex` when an item is appended. Will close the ticket.
