### ISSUE TITLE
No data in VirtuosoGrid

### ISSUE THREAD

**Issue by evskorobogatij** [petyosi/react-virtuoso#307]
Hello

I try too use virtuoso library. It's very nice for list.

But in my projects I mast use grid. 
I try write small sample for testings, based on  https://virtuoso.dev/grid-responsive-columns/
but not data rendered in my project:
https://codesandbox.io/s/test-ucokn?file=/src/App.js

How to fix this?

**Comment by petyosi** [comment]
You need to specify a height for your grid component - either with style or by using flexbox. Please refer to the working examples in the docs.

**Comment by evskorobogatij** [comment]
> 
> 
> You need to specify a height for your grid component - either with style or by using flexbox. Please refer to the working examples in the docs.

Where is working example?
This example https://virtuoso.dev/grid-responsive-columns/ is now fork

I rewrite container component. But nothing happens:
`
  const ListContainer = styled.div`
    display: flex;
    flex-wrap: wrap;
    height: 200px;
  `;
`

**Comment by DSK9012** [comment]
@petyosi 
I'm using v2.19.1. Seems data prop is not allowed in there. or Am I missing something? How we can pass our data to Grid?
