### ISSUE TITLE
Website examples using `data` prop do not work in MacOS Safari 

### ISSUE THREAD

**Issue by bhavesh-desai-scratch** [petyosi/react-virtuoso#309]
**Describe the bug**
React-virtuso does not seem to work in Safari for lists with a data source. None of the items are rendered to the screen.

**Reproduction**

If you open the demo page in Safari you can see the "List with data" example is blank.

https://virtuoso.dev/hello/

**To Reproduce**
Steps to reproduce the behaviour:
1. https://virtuoso.dev/hello/
2. Look at the "List with data" example.
3. Notice it is blank

**Expected behavior**
Would be great if the library worked in Safari

**Screenshots**
<img width="982" alt="Screenshot 2021-03-05 at 11 25 07" src="https://user-images.githubusercontent.com/15194540/110109494-7327dc00-7da5-11eb-8b5d-1350f772c20c.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Safari Desktop 14.0.3 

**Additional context**

**Comment by petyosi** [comment]
Now that's truly an amazing feat on my side. Looking into it.

**Comment by petyosi** [comment]
@bhavesh-desai-scratch - this seems to be an issue with docusaurus (the backend of the docs) itself. The list works fine in a code sandbox - [see here](https://codesandbox.io/s/dry-forest-hxr9u?file=/src/App.tsx).

**Comment by petyosi** [comment]
Works in current Safari, closing.

**Comment by piotr-cz** [comment]
Update: [v2.0.0 release notes](https://github.com/petyosi/react-virtuoso/releases/tag/v2.0.0) say to add ResizeObserver polyfill for older browsers, this fixed the issue for me
