### ISSUE TITLE
[BUG] followOutput is flaky on Big Sur Safari

### ISSUE THREAD

**Issue by jan-wilhelm** [petyosi/react-virtuoso#310]
**Describe the bug**
The ["Stick to Bottom" example](https://virtuoso.dev/stick-to-bottom/) stops sticking to the bottom every now and then on Safari, as shown in my screen recording.

**To Reproduce**
1. Go to https://virtuoso.dev/stick-to-bottom/ in Safari
2. Watch the example for a few seconds
3. Notice how after a while, it stops sticking to the bottom and shows the "Bottom" button instead, even though you did not scroll at all

**Expected behavior**
The `followOutput` prop should work consistently in Safari

**Screenshots**
Video of the recording:
https://user-images.githubusercontent.com/16737505/110155768-64154e00-7de6-11eb-94e4-c0154f992374.mov

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Safari

**Additional context**

**Comment by petyosi** [comment]
Thanks, I will take a look.
