### ISSUE TITLE
Scroll to index example not working with smooth scrolling on Chrome

### ISSUE THREAD

**Issue by johsunds** [petyosi/react-virtuoso#313]
First off, thanks for your work on this library!

I noticed while testing the scrolling example at https://virtuoso.dev/scroll-to-index/ that scrolling with `behavior: 'smooth'` doesn't have any effect on latest chrome. Seems to work fine on firefox.

**Comment by petyosi** [comment]
Thanks for the report, I will look into that over the weekend.
