### ISSUE TITLE
[BUG] scrollToIndex, smooth behavour doesn't seem to work

### ISSUE THREAD

**Issue by henrykuzmick** [petyosi/react-virtuoso#315]
**Describe the bug**
When setting `behavior` to `smooth` it still scrolls instantly

**Reproduction**
You can see it on the documentation website example https://virtuoso.dev/scroll-to-index/

**Comment by petyosi** [comment]
Yes, I broke this fairly recently while fixing a bug in Safari. Duplicate of #313, will fix this ASAP.
