### ISSUE TITLE
[Feature Request] Offset for scrollToIndex

### ISSUE THREAD

**Issue by henrykuzmick** [petyosi/react-virtuoso#316]
Hey 👋  first of all - thanks for the incredible lib!

An additional option of `offset` would be super helpful in `scrollToIndex`. 
In many cases having some margins would help with the look of things, for example, one may want to scroll to the top of some index, but also leave a 16px gap from the top.

Additionally, it would be cool to have some pixel value offset for `initialTopMostItemIndex`. Or a separate prop that would allow you to control the initial scroll offset in pixels

**Comment by petyosi** [comment]
Thanks, that's a good idea, and, in fact, fairly simple to implement. I will probably get to it at some point, but in the mean time, feel free to give it a try - [this is the place](https://github.com/petyosi/react-virtuoso/blob/master/src/scrollToIndexSystem.ts#L59) where the index argument type is transformed into a locaiton.

**Comment by itayganor** [comment]
This issue [should be closed](https://github.com/petyosi/react-virtuoso/commit/7ee4ced6c34f2612bd4cbe0c47b6193a526fc3a7), shouldn't it?

**Comment by isGabe** [comment]
I'm really glad this exists! Several times now I've been pleasantly surprised that an issue I had was already addressed by a feature that already existed. This should be added to the `scrollToIndex` docs, though, because I had no idea about it until I came a searched the repo 🙂
