### ISSUE TITLE
[BUG] Window Scrolling does not work in safari in ios 12 and below

### ISSUE THREAD

**Issue by sei666** [petyosi/react-virtuoso#324]
**Describe the bug**
Window Scrolling does not work in safari in ios 12 and below. Virtuoso shows several rendered blocks, but after scrolling, no new blocks are rendered. Problem tested in iphone 5s ios 12 and ipad 4 ios 10.

**To Reproduce**
1. Go to https://virtuoso.dev/window-scrolling/
2. Scroll down on ios 12 and below
3. No new blocks

**Expected behavior**
New blocks should appear.

**Screenshots**
![IMG_7738](https://user-images.githubusercontent.com/52584846/113009576-bf85f200-9180-11eb-983b-c2829f3dee79.png)
![IMG_7739](https://user-images.githubusercontent.com/52584846/113009600-c3b20f80-9180-11eb-9ada-4337e25b89fc.png)
![IMG_7740](https://user-images.githubusercontent.com/52584846/113009609-c57bd300-9180-11eb-9c0c-3df988d80fd5.png)

**Desktop (please complete the following information):**
 - Tested iphone 5s ios 12,  ipad 4 ios 10
 - Browser chrome, safari

**Comment by petyosi** [comment]
@sei666 are you willing to debug what's going on at that platform? [This is the hook](https://github.com/petyosi/react-virtuoso/blob/master/src/hooks/useScrollTop.ts) which deals with the scroll handling. My guess is that scrolling does not get reported at some reason.

**Comment by sei666** [comment]
@petyosi Unfortunately I have no experience with TypeScript. I don't know how to run this for testing.

**Comment by petyosi** [comment]
You can follow [the instructions from the contributing section](https://github.com/petyosi/react-virtuoso#fixes-and-new-features). There's a [window scroller test case](https://github.com/petyosi/react-virtuoso/blob/master/e2e/window-scroller.tsx). TypeScript should not be particular issue.

**Comment by sei666** [comment]
@petyosi Problem found. It really was hidden in useScrollTop.ts. You need to change one line in the handler UseCallback function. There was "const scrollTop = (el as any) === window || (el as any) === document? Document.documentElement.scrollTop: el.scrollTop", but there should be such "const scrollTop = (el as any ) === window || (el as any) === document? window.pageYOffset || document.documentElement.scrollTop: el.scrollTop ". Because in the first case on ios 12 and earlier, always document.documentElement.scrollTop gets zero.

**Comment by petyosi** [comment]
Thank you for looking into this. I will test this change later this week. If you want to, you can also submit a PR, but it is not necessary.

**Comment by sei666** [comment]
PR is created. Thank you so much for this great tool :) Virtuoso is the best!

**Comment by petyosi** [comment]
Merged and released; the change is available in 1.6.0.
