### ISSUE TITLE
[Question] Why does the outer list wrapper have a tabindex?

### ISSUE THREAD

**Issue by janKozie1** [petyosi/react-virtuoso#329]
First of all, thank you for the great library!

Keyboard navigation is an important part of an application for me and the tabindex being there breaks the flow of tabbing. Could it be removed?

<img width="352" alt="Screenshot 2021-04-01 at 18 07 29" src="https://user-images.githubusercontent.com/48291123/113322558-220ff700-9315-11eb-9cde-a2d3c0447317.png">

(screenshot taken from the first example on https://virtuoso.dev/)

**Comment by petyosi** [comment]
Yes, you can remove it by passing `tabindex={null}` (or, was it, `undefined`?) to the virtuoso component.  All HTML attributes set to the component are passed to the root DOM element.

The reason for this prop to be there by default is to enable scrolling with the keyboard. Once you click somewhere in the list, pressing up/down, etc. will scroll it.
