### ISSUE TITLE
List does not re-render properly when backing data is shuffled/filtered.

### ISSUE THREAD

**Issue by joshacheson** [petyosi/react-virtuoso#33]
I have created a codesandbox to illustrate the problem I'm having: https://codesandbox.io/s/wizardly-http-61djr. It's important to have the console open here to see the disparity between what "should" be rendered and what actually gets rendered.

In general, when a list is shuffled, `<Virtuoso/>` does not necessarily re-render in the correct order _or_ render all of the items that it should. Instead, virtuoso seems to hold on to old values, even when `computeItemKey` is used.

I came to find this issue when working on a list that was filtered by text. Changing the text filter would change where some items should appear in the list, or whether they should appear at all. I.e. while typing a filter, an item that was previously at index 5 might end up at index 2, and an item previously at item 4 should no longer appear at all. In that particular example, I ended up getting in to a situation where the `startIndex` for some range always exceeded `maxIndex` [here](https://github.com/petyosi/react-virtuoso/blob/master/src/OffsetList.ts#L224) and so some items would not render at all after filtering caused a reduction in the overall size of a list. It seemed to be that for some items/nodes, old indices were being held that were outside the bounds of a new, reduced size list.

I'm curious whether this can be considered a bug or whether virtuoso is not meant to support the use case of a filterable list, a list that shuffles, etc.

**Comment by joshacheson** [comment]
Sorry, I need to give a better example. I am closing this issue and will open a better one!

**Comment by petyosi** [comment]
I somehow missed this issue. To answer your question - yes, Virtuoso should work with filtering and shuffling of data. The problem with the example here is that there is an "empty" item (you can check #35 for more details). Setting the content of the `divItem` made the example work as expected ([updated version](https://codesandbox.io/s/dreamy-nightingale-h1n3h)).

**Comment by joshacheson** [comment]
@petyosi thanks for checking in. In the actually example in our own product, we had an element with no content _and_ that had a margin. I found the thing about margins in the gotchas, replaced it with a fixed element height, and everything worked great. It seems in this case that a fixed height worked just as well as adding content or what have you.

The only feedback I might offer is to make the gotchas more prevalent (like perhaps giving them a navigation item in the docs so people know they exist) or moving them more towards the top.

Cheers, and thanks for checking in on this!
