### ISSUE TITLE
[BUG] Safari and iOS Safari  issue with topItemCount and Material UI

### ISSUE THREAD

**Issue by cristianManrique** [petyosi/react-virtuoso#330]
**Describe the bug**
In this particular case, we add the Virtuoso list inside a Material-UI dialog to display a list with a sticky header item at the top of the list.

When we scroll down in Safari (either on Mac OS or iOS), the header keeps getting sticky for a little while and then it goes down as it is would be an item of the list.

**Reproduction**
https://codesandbox.io/s/youthful-lehmann-nclni?file=/src/App.js

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Safari on Mac or any iPhone
2. In the sandBox, click on 'OPEN DIALOG'
3. Scroll down the list
4. You can see the Header does not keep sticking at the top of the list

**Expected behavior**
On Android phone, iPhone, or any desktop browser, when we scroll, the header should be staying sticky to the top of the list.

**Screenshots**
Mac OS X Apple computer
On the left side : Firefox
On the right side : Safari

![2021-04-07 00 08 01](https://user-images.githubusercontent.com/16122298/113875707-0b3e2a00-9785-11eb-9697-f4159dd91d4c.gif)

<img width="1023" alt="Screen Shot 2021-04-07 at 12 09 18 AM" src="https://user-images.githubusercontent.com/16122298/113875728-109b7480-9785-11eb-9c5b-41b6692653da.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac and iPhone
 - Browser Safari on OSX and iOS

**Comment by petyosi** [comment]
@cristianManrique - material ui has a lot of transitions and animations by default which disrupt the measurement of elements. Can you provide a reproduction of the problem with Mui removed?

**Comment by petyosi** [comment]
[This simple setup works](https://codesandbox.io/s/zen-ride-zv7ih?file=/src/App.tsx) when I test it. Let me know if I am missing something.

**Comment by cristianManrique** [comment]
@petyosi   - The simple setup works well without any div wrapper with css, 

Why Virtuoso does not work with Material UI in Safari and work in any browsers on MAC, on PC, Android or iPhone? 
When I check Virtuoso added CSS. The first object in the list it`s in position sticky, and others in position absolutes.
Maybe be something is wrong when we scroll and Virtuoso list in Safari. Let me know if I am missing something with Safari and Virtuoso with MUI.
