### ISSUE TITLE
[BUG]`TypeError: Cannot read property 'getBoundingClientRect' of null` on Next.js

### ISSUE THREAD

**Issue by OrcaXS** [petyosi/react-virtuoso#331]
**Describe the bug**
I'm using Virtuoso with `useWindowScroll` on Next.js. Each list item is a next/link `<Link>` navigating to an individual page.
Clicking an item after scrolling will sometimes cause `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`.

**Reproduction**
https://codesandbox.io/s/unruffled-solomon-8p800

**To Reproduce**
1. Go to `https://codesandbox.io/s/unruffled-solomon-8p800`
2. Scroll down to somewhere after initial position
3. Click an item

**Expected behavior**
No error thrown.

**Screenshots**

https://user-images.githubusercontent.com/1764123/113963436-2891f780-985c-11eb-9d19-6329f8f7c8d0.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chromium 89, happens on Safari 14.2 as well

**Comment by petyosi** [comment]
Thanks for reporting this, this seems like an easy fix. I will look into it.
