### ISSUE TITLE
TopItemListContainer must be part of the custom components

### ISSUE THREAD

**Issue by ezsper** [petyosi/react-virtuoso#332]
I'm facing a problem with [`TopItemListContainer`](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L259) that when using groups it doesn't allow us to set a proper `z-index`. A proper solution would be to make `TopItemListContainer` a customisable component as `Item` or `Group`. Currently I'm having to apply zIndex with this selector `'& div[style*="position: sticky"]': { zIndex: 999 }`

**Comment by petyosi** [comment]
Agreed, that's a nice idea. Why don't you open a PR? [That part of the code is fairly trivial](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L64).

**Comment by ezsper** [comment]
> Agreed, that's a nice idea. Why don't you open a PR? [That part of the code is fairly trivial](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L64).

https://github.com/petyosi/react-virtuoso/pull/335

**Comment by ezsper** [comment]
Merged.
