### ISSUE TITLE
[BUG] crash noticed with the Virtuoso

### ISSUE THREAD

**Issue by aravind-tc** [petyosi/react-virtuoso#337]
**Describe the bug**<img width="1038" alt="Screen Shot 2021-04-13 at 11 37 02 PM" src="https://user-images.githubusercontent.com/37326359/114665534-03651500-9cb2-11eb-98df-ccf5ae82dbd6.png">We are using virtuoso for infiniate pagination scroll. While scrolling the elements, there is a crash noticed. 

**Reproduction**
Just list items using virtuoso and implement infinite pagination. Scroll up and down the list. You will notice a [crash.](url)

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1038" alt="Screen Shot 2021-04-13 at 11 37 02 PM" src="https://user-images.githubusercontent.com/37326359/114665534-03651500-9cb2-11eb-98df-ccf5ae82dbd6.png">**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows can behave unexpectedly.

**Additional context**

**Comment by petyosi** [comment]
@aravind-tc I will need some additional details to help you with this - the link you gave does not lead to reproduction. Can you reproduce the problem you describe on [the infinite scrolling example on the site?](https://virtuoso.dev/endless-scrolling/)?

**Comment by mgallo** [comment]
@petyosi I encountered the same bug trying to render a component that changes size after mount. I made an example to reproduce it on codesandbox: https://codesandbox.io/s/suspicious-sid-gniph?file=/src/App.js.  The issue happens when scrolling quickly up and down for few times.
There's any tip to make virtuoso work with this behaviour? thanks

**Comment by petyosi** [comment]
@mgallo I can't reproduce the stack trace in your example. It seems horribly broken for the same reason as #322, which  I do want to fix (but the fix I know breaks another scenario). Can you please record me a video or a gif?

**Comment by mgallo** [comment]
@petyosi thanks for the reply. Here's a video showing the issue https://user-images.githubusercontent.com/1528511/115354901-6d9e1e00-a1ba-11eb-92e7-0bbdf62e238f.mov, it doesn't always happen, in this case I scrolled down the list, waited for the render and then scrolled up quickly. Hope it helps to figure out the issue. Thanks
