### ISSUE TITLE
Feature request: support "if-needed" scroll behaviour

### ISSUE THREAD

**Issue by skrivanos** [petyosi/react-virtuoso#338]
It would be great if virtuoso supported the following type of  scroll behaviour natively:

https://user-images.githubusercontent.com/87463/114753540-db2ff180-9d57-11eb-93d3-c1e1a7be8d9f.mov

I managed to get it working with the following snippet, but it feels like a hack:

```ts
        let shouldScroll = true;

        // listRef.current is a wrapper around the Virtuoso scroller.
        if (listRef.current) {
          const itemEl = listRef.current.querySelector<HTMLDivElement>(
            `[data-item-index='${scrollIndex}']`,
          );

          if (itemEl) {
            const scroller = listRef.current
              .firstElementChild as HTMLDivElement;
            const scrollTop = scroller.scrollTop || 0;
            const scrollBottom = scrollTop + scroller.offsetHeight;
            const itemTop = itemEl.offsetTop;
            const itemBottom = itemTop + itemEl.offsetHeight;
            shouldScroll = itemBottom >= scrollBottom || itemTop <= scrollTop;
          }
        }

        if (shouldScroll) {
          virtuoso.current.scrollToIndex(scrollIndex);
        }
```

**Comment by petyosi** [comment]
A fairly easy way to achieve something similar (while not absolutely the same, as the container is re-scrolled continuously) is  `scrollIntoView`. [Check this comment](https://github.com/petyosi/react-virtuoso/issues/53#issuecomment-550183754).

**Comment by maccman** [comment]
+1 on having this added to the API

**Comment by petyosi** [comment]
@maccman @skrivanos I am thinking to implement this as a method: 
```ts
scrollIntoView(index: number, behavior: 'smooth' | 'auto')
```

The integrator will call it when the keyboard has navigated, (keyboard nav this is outside of the scope of the component). If the element is visible, nothing will happen. If partially visible or outside of the view, the component will figure out the direction and scroll it into view. What do you think?
