### ISSUE TITLE
[BUG] useWindowScroll will overlap footer

### ISSUE THREAD

**Issue by kelokchan** [petyosi/react-virtuoso#339]
**Describe the bug**
I have a `VirtuosoGrid` that is responsive to the screen. And I am using useWindowScroll since I do not want do have 2 scrollers in the screen. However, when I scroll to the end of the grid, the items overlap the page footer. The overlap will get even worse if I use a higher `overscan` prop value. The same issue won't happen if I use `Virtuoso` instead of `VirtuosoGrid` though. But I will need `overscan` to prevent too much re-render issue since on the actual site.

**Reproduction**
https://codesandbox.io/s/material-ui-react-virtuoso-forked-boyfs?file=/src/index.tsx

**To Reproduce**
1. Scroll to the end of the grid
2. The last row of the grid will overlap the footer

**Expected behavior**
The last grid item to be above the footer

**Screenshots**
<img src="https://user-images.githubusercontent.com/5347725/114973438-109d2200-9eb3-11eb-9697-bfe5486976ea.png" width="1000" />

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**

**Comment by petyosi** [comment]
@kelokchan I am afraid that the grid item measurement logic cannot detect the spacing from `gridGap`. Removing that fixes the issue. Use `padding` instead.
