### ISSUE TITLE
[BUG] useWindowScroll mode does not work with body { margin: 0 }

### ISSUE THREAD

**Issue by horprogs** [petyosi/react-virtuoso#340]
**Describe the bug**
The problem appears if I use normalize.css in the project, more specifically style
`body: { margin: 0 }`

**Reproduction**
https://codesandbox.io/s/bitter-sun-1lxze

If you removed `import "./style.css";` (or remove `body: { margin: 0 }` style) it would work properly. 

**To Reproduce**
1. add normalize.css to the project

**Additional context**
I'm not sure bug this or not, but it looks dangerous, how make it works? I guess I need to add some more wrappers and some styles. Thanks!

**Comment by petyosi** [comment]
Seems related to `body { margin: 0 }`. Not sure what the problem is, likely [a math here](https://github.com/petyosi/react-virtuoso/blob/master/src/hooks/useWindowViewportRect.ts) [or here](https://github.com/petyosi/react-virtuoso/blob/master/src/hooks/useScrollTop.ts#L20).
