### ISSUE TITLE
[BUG] Virtualized list doesn't scroll on iOS Safari when inside of a Modal

### ISSUE THREAD

**Issue by mclngl** [petyosi/react-virtuoso#342]
**Describe the bug**
List doesn't scroll on iOS Safari when inside of a modal component. Works fine on desktop and Android.

**Reproduction**
[https://codesandbox.io/s/amazing-shamir-212dx?file=/src/App.js](https://codesandbox.io/s/amazing-shamir-212dx?file=/src/App.js)

**Expected behavior**
List should be scrolling on iOS Safari as well.

**Additional context**
If I remove the Modal component it also works on iOS.

**Comment by petyosi** [comment]
@mclngl - I would suggest you file that to the other libraries you have in this example. Feel free to reference that issue.

**Comment by mclngl** [comment]
Thank you and sorry for the annoyance. 
In fact this is related to the way reakit handles body lock scroll
