### ISSUE TITLE
Omit resize observer polyfill from bundle

### ISSUE THREAD

**Issue by anilanar** [petyosi/react-virtuoso#343]
Use case:

We target modern browsers only so we don't need the polyfill.

**Comment by petyosi** [comment]
Can you submit a PR for that? I doubt that the rest of the code will work on any of those browsers, to be honest.  

https://caniuse.com/resizeobserver

**Comment by anilanar** [comment]
@petyosi This could be a breaking change tho. Perhaps the rest of the code works for those browsers after babelifycation? Or are you already aware of other DOM/ES apis that the codebase relies on that wouldn't work for, let's say, Safari 12.1 or Safari 13.0 which are quite "modern" actually.

**Comment by petyosi** [comment]
@anilanar isn't this a general problem with those polyfills? I am not following the development of those closely, but I was hoping that a browserlist configuration could make a polyfill "tree-shake" unnecessary code.

**Comment by anilanar** [comment]
The ecmascript version target: the consensus is to always  transpile library code to ES5.

For Ecmascript polyfills: The general consensus is to not babelify node_modules, so no, nothing would be polyfilled for libraries. In those cases, library authors are either choose not to use those APIs or they polyfill the API for small stuff. If there's something big (let's say, async iterators), they drop a note in README.

For DOM polyfills (resize/mutation observers, web components etc), the consensus is to always specify them in README as dependencies, except for small things like requestAnimationFrame which is small enough to polyfill.

I think for babeling, asking users to force include virtuoso in their babel process is viable.

Yeah, it's a lot, and considering that nobody complained about this before, you must have done some things right already. I'll check how virtuoso is built for release and comment further.

**Comment by anilanar** [comment]
> I was hoping that a browserlist configuration could make a polyfill "tree-shake" unnecessary code.

No. Instead, babel preset env (and/or auto-polyfill babel plugins) read the browserslist and choose whether to include a polyfill or not, but that doesn't apply to DOM polyfills. It's only for Ecmascript polyfills.

So as a library author, the ideal solution is to not include any Ecmascript polyfills but let users babelify library code. But as you can see in the above comment, the consensus is currently different due to too many different opinions from community leaders/library authors.

**Comment by petyosi** [comment]
@anilanar Thanks, I guess I hoped for too much. Up to your case, I assume you can use something like this: https://webpack.js.org/configuration/resolve/ to cut off the dependency?

**Comment by petyosi** [comment]
Resolved in v2.0.0
