### ISSUE TITLE
_this.props.group is not a function when using GroupedVirtuoso [BUG]

### ISSUE THREAD

**Issue by fonty422** [petyosi/react-virtuoso#349]
Trying to use the GroupedVirtuoso and Virtuoso components.
When a particular check box is selected, it needs to group the items and render the GroupedVirtuoso, otherwise use the Virtuoso.

``` javascript
let groups =["A", "B"]
let groupCounts = ["5", "5"]

return (
  <GroupedVirtuoso
    groupCounts={groupCounts}
    
    groupContent={index => {
      return <div>{groups[index]}</div>
    }}

    itemContent={index => {
      return <div >{this.props.data[index].value}</div>
    }}
  />
)
```

Running this results in a Type Error as in the title.

I also tried a direct copy and paste from https://virtuoso.dev/grouped-numbers/ which failed in the same way.
```javascript
  const groupCounts = []
  for (let index = 0; index < 1000; index++) {
    groupCounts.push(10)
  }

  return (
    <GroupedVirtuoso
      groupCounts={groupCounts}
      groupContent={index => {
        return (
          <div style={{ backgroundColor: 'white' }}>
            Group {index * 10} &ndash; {index * 10 + 10}
          </div>
        )
      }}
      itemContent={(index, groupIndex) => {
        return (
              <div>Item {groupIndex}.{index}</div>
        )
      }}
    />
  )
```

**Comment by petyosi** [comment]
Not sure that I understand your code. Virtuoso is a functional component, there's no `this` in the source. The example you have linked also works fine for me. Please use a codesandbox to re-create the problem.

**Comment by fonty422** [comment]
What a stupid mistake! Code sandbox showed that i was clearly using an outdated version. I had not long run yarn upgrade, but it did not upgrade to the latest and was stuck in v 0.12.something. The upgrade fixed it immediately. Sorry to have bothered you for something to trivial.
