### ISSUE TITLE
[Question] How do i pass additional props to components?

### ISSUE THREAD

**Issue by janKozie1** [petyosi/react-virtuoso#351]
There have been instances where I wanted to pass additional props to the `Header` and `Items`. 

I could do this
```js
const components = {
   Header: (virtuosoProps) => <MyComponent {...virtuosoProps} additionalProp={...} />
}
```
But that would create a new component on each render.
I could also pass it through context but that feels very unnecessary

**Comment by petyosi** [comment]
What's wrong with using contexts for that? That's exactly their purpose.

**Comment by janKozie1** [comment]
I don't think the purpose of context is passing prop one level down. My item component is a simple styled component which needs one additional prop to change styles. Making a wrapper around it to be able to use context seems just unnecessary. Some of the components are used in other places, which would require me to make more one-time-use components which are there just to subscribe to context.

**Comment by andreicorpo** [comment]
I agree with this. There should be a way to send some common props to the components. For example, I would like to be able to pass the same function to all of my items in the list.

**Comment by petyosi** [comment]
v2.7.0 introduced the `context` property, which gets passed to the components and to the item content callbacks.
