### ISSUE TITLE
your code for endless scroll keeps giving this error.

### ISSUE THREAD

**Issue by sameem786-blip** [petyosi/react-virtuoso#352]
<img width="798" alt="Capture" src="https://user-images.githubusercontent.com/70144568/116952573-625fed80-aca4-11eb-8b90-7e3c9c003acc.PNG">
<img width="720" alt="err" src="https://user-images.githubusercontent.com/70144568/116952576-64c24780-aca4-11eb-8de9-4e558a387f6d.PNG">

**Comment by petyosi** [comment]
That's an example function to generate random data.
