### ISSUE TITLE
How to configure overscan to render before the end is reached?

### ISSUE THREAD

**Issue by gajus** [petyosi/react-virtuoso#353]
```js
<Virtuoso
  css={css`
    width: 100%;
    height: 100%;
  `}
  data={filteredMessages}
  followOutput
  itemContent={(index, message) => {
    return <LogRow
      message={message}
      onUpdateFilter={onUpdateFilter}
    />;
  }}
  overscan={{
    main: 2_400,
    reverse: 2_400,
  }}
/>

```

I am trying to get rid of the flickering when scrolling by using `overscan`.

![2021-05-05 22-23-14 2021-05-05 22_23_46](https://user-images.githubusercontent.com/973543/117237451-a102be80-adf0-11eb-8c3a-1c2d0478be32.gif)

However, it looks like the way `overscan` works is that it does not start rendering new rows before the very end of current scroll is reached. I would think that flickering could be prevented if we were able to configure that `overscan` should always try to keep the amount of rows in`{ main: 2_400, reverse: 2_400, }` range visible, rather than waiting until user scrolls to the end.

I cannot tell if I missed something pretty obvious in documentation or I am thinking wrong about this problem.

**Comment by petyosi** [comment]
1. your understanding of how overscan works right now is correct. Its purpose is to reduce render cycles. I personally don't recommend it and I regret introducing it, as people usually assume it will be the magic dust that fixes their performance troubles. 

2. The behavior you describe is effectively increasing the viewport height to ~5k px. I don't think that this will help you with the flickering, but you can try it easily by putting a 5k px tall component in a shorter browser viewport and see if it will make any difference. If it does, I am open to PRs in the matter, as long as the current overscan behavior is kept. [This is the code in question](https://github.com/petyosi/react-virtuoso/blob/master/src/sizeRangeSystem.ts#L25).

3. The underlying problem that causes flickering is heavy components inside the list item, and item resizing after being rendered. Sometimes both. Memoization, fixing image sizes, etc helps with that.
