### ISSUE TITLE
Support iscrolljs?

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [petyosi/react-virtuoso#36]
https://github.com/ustbhuangyi/better-scroll
or
Provide dynamic setting margin-top method

**Comment by petyosi** [comment]
I am not sure what the library you refer to does and how it would work with Vrituoso. Can you please elaborate?

**Comment by theonlylies** [comment]
> https://github.com/ustbhuangyi/better-scroll
> or
> Provide dynamic setting margin-top method

DId you trying that?
https://virtuoso.dev/custom-scroll-container/

**Comment by NrqhEIcsRi004** [comment]
https://github.com/ustbhuangyi/better-scroll is not using the native scroll, it is made by dragging the calculation and setting translateY, so it can't be with https://virtuoso.dev/custom-scroll-container/ Working very well together
