### ISSUE TITLE
[Feature Request] Offset support for ssr

### ISSUE THREAD

**Issue by TrueCarry** [petyosi/react-virtuoso#361]
Can you please add option to render `initialItemCount` not from the start of the list?

```
const items = Array.from({ length: adjustedCount }).map((_, index) => ({ index, size: 0, offset: 0, data: data[index] }))
```
I think if you use `data[initialTopMostItemIndex + index]` instead of `data[index]` it should work, but I'm not sure how to access initialTopMostItemIndex from initialItemCountSystem.

**Comment by TrueCarry** [comment]
https://github.com/TrueCarry/react-virtuoso/commit/b068fa8a96b6f0de5e95519ded7d0227d1614ac1 I've tried to make it, and in simple case it seems to work, but I'm not sure if it'll break something or even work in real world. Would be great if you give me some pointers.

**Comment by petyosi** [comment]
@TrueCarry feel free to revive that by submitting a PR.
