### ISSUE TITLE
[BUG] Item component can't accept children as array

### ISSUE THREAD

**Issue by newsiberian** [petyosi/react-virtuoso#365]
**Describe the bug**
I tried to build Material-UI list w/ secondary actions area (https://next.material-ui.com/components/lists/#list-controls) and have failed, since Item component can't accept children as array. It is incorent to pass children within Fragment to MUI ListItem. Them must be placed directly, that is why I need an array.

**Reproduction**
I modified your example w/ a few additional lines https://stackblitz.com/edit/github-hv734y-w8tpep
I added button prop to ListItem and added secondary action w/ IconButton.

**To Reproduce**
1. Go to the example
2. See that list renders only one item

**Expected behavior**
A list must be rendered

Any idea that to do w/ this?

I've tried to pass `{[1, 3, 2]}` to Item and it goes into endless rerender  loop

![Peek 2021-05-22 16-22](https://user-images.githubusercontent.com/11130487/119221520-06a5b900-bb1a-11eb-822b-e4ba97f7d4d3.gif)

**Comment by petyosi** [comment]
Try using the latest version. I checked this in the example, and it seems to be working:

```jsx
<Virtuoso
  style={{ height: "400px", }}
  totalCount={200}
  itemContent={(index) => [<div>Item {index}</div>, <span>Foo</span>]}
/>
```
