### ISSUE TITLE
[Question] Is possible to trigger range update ?

### ISSUE THREAD

**Issue by MartinNovak1991** [petyosi/react-virtuoso#367]
I have a issue ... List item is expandable, but range is not updated after item expanding. Visible items is less because of item height (expanded), but range trigger is not fired and range is still same.  I must scroll for range update. How can I trigger range update manually, on demand?

**Comment by petyosi** [comment]
I am not sure what you are doing and why it does not work. But a wild guess would be that this issue will help you:

https://github.com/petyosi/react-virtuoso/issues/322
