### ISSUE TITLE
[BUG] ResizeObserver loop limit exceeded error is reported

### ISSUE THREAD

**Issue by ytnytn1** [petyosi/react-virtuoso#369]
**Describe the bug**
ResizeObserver loop limit exceeded error message is reported

**Reproduction**
https://codesandbox.io/s/material-ui-react-virtuoso-forked-z2bf5?file=/src/Tabs.tsx 

**To Reproduce**
1. You will see an error in the console right after the list is rendered

**Expected behavior**
ResizeObserver loop limit exceeded is not reported

**Desktop**
 - OS: Windows 10,
 - Browser: Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Screenshot**

![image](https://user-images.githubusercontent.com/15182577/119639553-eb9cb700-be41-11eb-9cde-1fab09cd97a9.png)

**Comment by petyosi** [comment]
Duplicate https://github.com/petyosi/react-virtuoso/issues/254

**Comment by petyosi** [comment]
You can read the comments in #254 and the mentioned workaround there.

**Comment by ivandotv** [comment]
I'm having this issue with version `1.8.6`
Is there  something we should do in user land?

**Comment by gabrielmicko** [comment]
Same issue in 2.2.1.
