### ISSUE TITLE
Auto size container height

### ISSUE THREAD

**Issue by fonty422** [petyosi/react-virtuoso#37]
An enhancement request - any chance of having the same autosizing as the width part?
Perhaps this is already doable via standard CSS things (like flex), but I can't seem to get it to work.
It would be useful to hard code a height of the scroll container, but also have it flex to fit the white space.
If the window changes size, or another component above changes size and pushes/pulls on the scroll container, it could automatically resize to only fill the white space.

This would be particularly useful for instances where the list takes up the whole width of the window, and it's annoying to have the window scroll and the list scroll right next to each other.

**Comment by fonty422** [comment]
Never mind. It can be resolved with pure CSS using flex.

**Comment by jaskinn** [comment]
@fonty422 - I'm struggling with the same thing. Did you apply flex settings (I'm guessing flex-grow) to the Virtuoso component or its parent?

**Comment by fonty422** [comment]
Yeah, I figured it out using plain old CSS.
I think the key is to ensure that _all_ parent components have a `height` assigned right back to `#root` and then use some flex settings.
I've knocked up a simple code sandbox for you to look at [here](https://codesandbox.io/s/cool-hill-69dz7?from-embed). The only thing I had to mess around with was the height of the `.box` bit, as a pure 100% would always leave a few straggling pixels off the bottom so I ended up with a double scroll bar from the window and the `Virtuoso` component. Fixed that with a 95% or similar on the box, then set the `Virtuoso` component style to 100% - always fits now, never goes off the bottom of the screen... unless I make the whole thing super small.

Keys are:
1. Make sure everything above has a height set
2. Make the grandparent(?) of the `Virtuoso` component has a flex type with column
3. Make sure to wrap the `Virtuoso` component in a `div` with a flex and height setting
4. Ensure the `Virtuoso` component has a style applied that sets the height to some %

**Comment by fonty422** [comment]
Except that today, for no known reason just yet, it stopped working in my code. I figured there was something I changed in the main code that messes something up, but no! Even the sandbox above no longer works... at least in Chrome. But Firefox works, so what;s going on there???

**Comment by fonty422** [comment]
Strangely, the .content style now needs a height in Chrome, which it didn't when I wrote that sandbox code. Very strange

**Comment by porkopek** [comment]
You can calculate dynamically the remaining height available for your Virtuoso table with JS. Something like

```JS

const [height, setHeight] = useState(0)
const ref = useRef(null);
useEffect(() => {
    const calculateHeight = () => {
      if (ref.current) {
        const virtuosoElement = ref.current;
        let topOffset = 0;
        let currentElement = virtuosoElement as any;

        // Calculate the total offset from the top of the document
        while (currentElement) {
          topOffset += currentElement.offsetTop || 0;
          currentElement = currentElement.offsetParent as HTMLElement;
        }

        const totalHeight = window.innerHeight;
        const calculatedHeight = totalHeight - topOffset;

        setHeight(calculatedHeight);
      }
    };
      window.addEventListener('resize', calculateHeight);
    calculateHeight(); // Initial calculation

    return () => window.removeEventListener('resize', calculateHeight);
  }, []);
  ```
    
  And then wrap your virtuoso component with a div like  
    
```JS
    <div  style={{height}} ref={ref}>
         <Virtuoso .../>
    </div>
```

This way, your virtuoso table will always fill the remaining available height in the screen as long as your screen is max height the window

**Comment by LiFaytheGoblin** [comment]
Thanks for the hints, I had the same issue and ended up calculating the remaining height dynamically with el.offsetHeight (the other element Virtuoso shared the space with) and container.offsetHeight (the container in which both elements are).

**Comment by Lyrics1** [comment]
const [height, setHeight] = useState(200); 设置一个最小高度
然后根据属性:  totalListHeightChanged={(h) => { setHeight(h) }}. 去动态更改高度，就可以实现自动容器的的需求了，如果容易有最大高度要求，设置一个maxHeight。就OK了

<Virtuoso
                        style={{
                          minHeight: 200,
                          height: height,
                          paddingRight: 3,
                          maxHeight: 600
                        }}
                        totalListHeightChanged={(h) => { setHeight(h) }}
...
/>
