### ISSUE TITLE
[BUG] unexpected issue while scrolling by adding custom scroll bar

### ISSUE THREAD

**Issue by sunil1167** [petyosi/react-virtuoso#373]
Not able to scroll to remaining items after adding custom scroll bar. please have a look.

https://codesandbox.io/s/stoic-hamilton-3w1z0?file=/src/App.js

--> please scroll to see issue

**Comment by petyosi** [comment]
Check this for more information and working examples. https://github.com/petyosi/react-virtuoso/issues/253
