### ISSUE TITLE
[Bug] Infinite loader, window scroll and dynamic item height

### ISSUE THREAD

**Issue by frikkf** [petyosi/react-virtuoso#379]
Hey!

I might have found a potential bug.

I am trying to use this wonderful library with dynamic item heights, window scrolling and infinite scrolling.

Should this be possible?

In my local project I cannot seem to trigger the **onEndReached** callback.

I will provide additional examples if it should work :) 

Thanks!

**Comment by petyosi** [comment]
Hey, 

Provide a minimal reproduction of the problem. I will take a look.

**Comment by frikkf** [comment]
Here is a minimal example: https://codesandbox.io/s/dry-thunder-yrc66?file=/src/App.js:620-668

Note: It seems like onFetchNext is triggered, but when scrolled to the bottom, I cannot find the first 100 items anymore.

After the first onEndReached I can find the 200th item, but then, it seems onEndReached is triggered, but new items are not rendered.

**Comment by petyosi** [comment]
Double-check what you are doing in `fetchNext`. You have a bug in how you construct new items.

**Comment by frikkf** [comment]
Updated the codesandbox and it works. 
Thanks for pointing out the small bug I had there.

Note to potential readers that might pop into this:
The sandbox example works with the window scroll and infinite loading of items.
Make sure you don't have a div with overflow-y: auto or scroll when you want to scroll using window :)
