### ISSUE TITLE
[BUG] endReached and Scroller cause scroll position reset

### ISSUE THREAD

**Issue by igorpost92** [petyosi/react-virtuoso#384]
**Describe the bug**
When using both endReached and Scroller component scroll position resets after endReached callback.

**Reproduction**
[https://codesandbox.io/s/beautiful-christian-yqgbr](https://codesandbox.io/s/beautiful-christian-yqgbr)

**To Reproduce**
1. Pass endReached prop
2. Pass components['Scroller'] prop
3. Scroll down to end
4. Scroll position resets

**Expected behavior**
Scroll continues from previous position

**Comment by petyosi** [comment]
That's because you are passing a new Scroller component with each rerender. Move the scroller outside of the component like this - https://codesandbox.io/s/bitter-bush-llgyq?file=/src/App.tsx:624-625.
