### ISSUE TITLE
[BUG] Lower rows are not visible when large amount of data

### ISSUE THREAD

**Issue by igorpost92** [petyosi/react-virtuoso#385]
**Reproduction**
[https://codesandbox.io/s/priceless-boyd-u2ik9](https://codesandbox.io/s/priceless-boyd-u2ik9)

**To Reproduce**
1. 1000000 items in data.
2. Scroll to row 932067.
3. No items are visible after that row.

**Expected behavior**
Items are visible

<img width="198" alt="Снимок экрана 2021-06-10 в 17 19 59" src="https://user-images.githubusercontent.com/18347537/121541703-34db3200-ca10-11eb-9354-eed590b6633d.png">

**Comment by petyosi** [comment]
That's a browser limit. Maximum height of an element is around 16M pixels. I have an open issue with a workaround in mind, but it is not great, so not sure if willing to offer it.
