### ISSUE TITLE
Usage of a useWindowScroll prop in integrating with react-beautiful-dnd

### ISSUE THREAD

**Issue by dmitryTurov** [petyosi/react-virtuoso#390]
**Describe the bug**
Errors while dragging an item:
Invariant failed: Cannot collect without a droppable ref
Invariant failed: Cannot stop drag when no active drag

**Reproduction**
https://codesandbox.io/s/usage-of-a-usewindowscroll-prop-in-integrating-with-react-beautiful-dnd-390-rm72r

**To Reproduce**
Drag an item

**Desktop:**
 - OS: ubuntu
 - Browser: chrome

**Comment by dmitryTurov** [comment]
Hello! Thanks for your work first of all @petyosi!
Obviously, I didn't get the main realization idea of wrapping the list into a document scroll container. If you have any suggestions on this case I would be extremely grateful

**Comment by petyosi** [comment]
What you have linked is just a blank sandbox. I assume you tried to combine the existing examples with `useWindowScroll`, but likely this needs more tweaks in the config of dnd.
Using window scrolling with beautiful dnd would be a useful example indeed, I would love to get a contribution on the matter.

**Comment by dmitryTurov** [comment]
Thanks for the reply!
Sorry, you are right I provided a broken link. Updated. In fact, you are right twice: it was just a copy of the example (https://virtuoso.dev/react-beautiful-dnd/) but with enabled useWindowScroll prop.
If I make it work with some workaround I'll ping you

**Comment by exneval** [comment]
I think I've found the workaround, kindly check this PR #397
