### ISSUE TITLE
[BUG] react-virtuoso bundle is large because of extraneous files

### ISSUE THREAD

**Issue by cameracker** [petyosi/react-virtuoso#392]
**Describe the bug**

Per NPM, the bundle size of react-virtuoso is 6MB. This is because of a large number of extraneous files contained in the bundle including:
* The end to end tests
* An example file thats 4MB in size

**Reproduction**
![image](https://user-images.githubusercontent.com/14242948/122329043-8f2f3380-cee5-11eb-87fb-f331805f8c5c.png)

**To Reproduce**

N/A

**Expected behavior**
The bundle should contain just the source for the library

**Screenshots**
![image](https://user-images.githubusercontent.com/14242948/122329923-17620880-cee7-11eb-8555-5c1e04eba0b8.png)

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by cameracker** [comment]
This is probably simple to fix but haven't used `microbundle` before

**Comment by cameracker** [comment]
Also something to note, the typedefs are weirdly large for some reason. This is less of an issue because it gets tossed in a production bundle. But maybe something to also watch

**Comment by petyosi** [comment]
Thanks, I will take a look at the typedefs. microbundle was the replacement I found for TSDX, which started great and then stalled. If you can recommend a similar (but alive) tool, I am all for it.

**Comment by ccoloma** [comment]
It seems this issue is half-solved. The PR works, but the npm registry continues with the problem.

![image](https://user-images.githubusercontent.com/717054/130210793-77efaf0a-6ebb-4142-859f-14b401b40ae7.png)

![image](https://user-images.githubusercontent.com/717054/130210874-08ec1b75-04a3-4f26-87dc-0f9f81a167a8.png)

**Comment by petyosi** [comment]
@ccoloma Thanks for spotting that. The original fix was right, but it did not take into account an e2e testing step in the automated release which polluted the `dist` directory. Just published a fix in 1.10.8:
https://cdn.jsdelivr.net/npm/react-virtuoso@1.10.8/dist/
