### ISSUE TITLE
react-virtualized WindowScroller alternative?

### ISSUE THREAD

**Issue by veyndan** [petyosi/react-virtuoso#40]
Is there anyway to achieve what [`WindowScroller`](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md) does in react-virtuoso? I'm looking to create a Twitter/Facebook style news feed where you use the native window scrollbars to scroll an infinite list (or in my case, grid). Thanks in advance.

**Comment by petyosi** [comment]
Hey, 

this is not supported currently, I am afraid. Technically, it should be fairly easy to build such variation of the component, reusing the same engine but rendering in a different manner. I can help with directions In case you are interested in contributing such implementation. 

Thanks!

**Comment by veyndan** [comment]
Thanks I may have a look at implementing it in the future.

**Comment by zsee** [comment]
Hi!
Good job on react-virtuoso! It seems like a nice library 👍 

I tried to achieve something similar to WindowScroller. It seems to be doable with these things / workarounds:
- Custom scroll container which reports and sets the window's scroll position +- `offsetTop` of the scroll container.
- Detection of position changes for the list. (eg. an element above disappears). Not sure how to this correctly, so -> polling `offsetTop`
- To limit the number of items rendered a `maxHeight: "100vh"` was added to the first div of the scroll container.
- Set a `minHeight` on Virtuoso so something is initially rendered. After that set the height to the total list height (using `totalListHeightChanged` for this).

https://stackblitz.com/edit/react-pgd1ms

Would it be possible to add something to the library to make this easier? I think adding the `maxHeight: "100vh"` shouldn't be an issue, and maybe also adding a prop that forces the initial rendering of some elements (so `minHeight` wouldn't be needed). 🤔

**Comment by NerdCowboy** [comment]
The workaround zsee posted seems to work if you have list that takes up the entire height of the viewport.

However, I don't believe it's possible to do with a GroupedVirtuoso if you have anything above the list as it calculates the top margin for the sticky group header by calculating the top offset, and it appears to only do that calculation when scrolling has stopped, so it will overshoot the top while scrolling and jump back down when done scrolling. In the below video I added `position: sticky` to Hello World.

![scroll-offset](https://user-images.githubusercontent.com/757960/82580942-b1b91680-9b44-11ea-8f73-7d44e148de8d.gif)

Anyone have any ideas on how to make this work?

**Comment by petyosi** [comment]
I took my time with this feature, but hopefully, this will help whoever finds this issue :). 

https://virtuoso.dev/window-scrolling/ - post some feedback here if you give it a try. Thanks!

**Comment by mciszczon** [comment]
@petyosi Does the window scrolling functionality only work with the list? Because I tried to use it with the grid component and I get this:

> Warning: React does not recognize the `useWindowScroll` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `usewindowscroll` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by VirtuosoScroller)
    in VirtuosoScroller (created by GridRoot)
    in GridRoot (created by ForwardRef)

**Comment by petyosi** [comment]
@mciszczon I have not ported it to the grid yet. Likely going to do that soon, but no concrete ETA.

**Comment by mciszczon** [comment]
> @mciszczon I have not ported it to the grid yet. Likely going to do that soon, but no concrete ETA.

Thanks @petyosi, I'm looking forward for it and will have your package on the radar. I'm afraid I'll not be able to help you with this too much, but what I can tell you is that it's really not that simple to make a virtualized grid in React. I've already used `react-list` and `react-virtualized` but both of these have some issues to them which are not trivial to fix.

Anyway, thanks for the reply and keep up the great work! 👍🏻

**Comment by petyosi** [comment]
@mciszczon the window scrolling implementation of the grid won't differ from the current one, except for the missing scroller. If you would like to share the challenges you are facing with grids react-list and react-virtualized ([maybe open a discussion](https://github.com/petyosi/react-virtuoso/discussions)?) I would be more than happy to review and comment. Thank you!

**Comment by omgoshjosh** [comment]
This library is great!

I am wondering if you had any thoughts on how I might get the scroll bar off the content?

Below is a screenshot of the corner where I have changed our margins to padding around the GroupedVirtuoso and the scrollbar is over the content.
![image](https://user-images.githubusercontent.com/1960929/114630323-32a66280-9c6f-11eb-9505-ef607fb5be9d.png)

i think we can live with this, but i figured i would touch base here to see if there's a way to get all the same great functionality but with a scroll bar that would respect the padding for the look i'm going for.

PS: I'm also looking for a way to put padding between groups, check this screenshot

![image](https://user-images.githubusercontent.com/1960929/114630501-97fa5380-9c6f-11eb-8043-b0b81ca32d18.png)

thanks
