### ISSUE TITLE
[BUG] initial rendering of grouped list with initialTopMostItemIndex flash renders the start of the list first

### ISSUE THREAD

**Issue by timrigginssf** [petyosi/react-virtuoso#400]
**Describe the bug**
I want the grouped list to initially render at a specific index so i set `initialTopMostItemIndex` to that index. 
It works but initially flashes the list with index of 0, then re-renders to the proper index. Does this happen to anyone else?
I would like to remove that initial render bc it looks sloppy.

**Code**
My code is pretty straight forward. GroupedVirtuoso exists in a functional component with all props passed in by parent. There is no component state.

`props.countToInitialSession`, which is passed to `initialTopMostItemIndex` prop, is never 0. So I am not sure why GroupedVirtuoso ever renders beginning of list

```
import { GroupedVirtuoso } from "react-virtuoso"
    <GroupedVirtuoso
        groupCounts={props.dayCounts}
        initialTopMostItemIndex={props.countToInitialSession}
        rangeChanged={props.scrollRangeChange}
        isScrolling={props.isScrolling}
        groupContent={(index: number) => {
          return (
            <li key={index}>whatever<li />
          )
        }}
        itemContent={(index: number) => {
          return (
            <li key={index}>whatever<li />
          )
        }}
      />
```

**Comment by petyosi** [comment]
Unless I am missing something, `initialTopMostItemIndex` should work in grouped mode. Here's [a basic test](https://codesandbox.io/s/jovial-rgb-b5zqj?file=/src/App.tsx) - notice the indices logged. Please modify the example to demonstrate the problem you are facing, I will reopen the issue.
