### ISSUE TITLE
[BUG] Unmounting list items when using components prop

### ISSUE THREAD

**Issue by dominikmlynarczyk** [petyosi/react-virtuoso#405]
Hey @petyosi 👋
**First of all I wanted to thank you very much for your work and contribution to react-virtuoso**. We are just implementing it in production in our application, where we previously tested other virtualization solutions, but the functionality of automatically measuring the height of a single list item totally convinced us to use your library. Great work!

However, we have a big obstacle that blocks us from releasing our app with virtualization, below I describe it:

**Describe the bug**
We use Virtuoso so that we pass from the parent component a prop `itemRenderer` that is used in a specific context in Virtuoso. Within Virtuoso, we use react-sortable-hoc library via `components` prop (as stated in the documentation [here](https://virtuoso.dev/react-sortable-hoc/)), because domain requires sorting ability. Also, within that component we add additional JSX responsible for rendering the SVG that enables sorting and in the specified container we only call the `itemRenderer` passing single item data to it.

A single list item is in two main states - read and edit.

In editable mode, we display input components and if we make them controllable, we hold state for the input value in local state. In the production version, we render very large lists of data, so if the user selects the first item in the list, goes into edit mode, enters data into the input component, then scrolls through the list and returns back to the input then they will lose their state. 

On the other hand, if we decide to store input value in the global state, when we go into edit mode and enter data within a single list element, we observe the unmounting of the component with each state change. For each state update for `onChange` event the component is unmounted which we can observe by losing focus on the `<input />` element.
**Importantly, by removing prop `components` from Virtuoso the unmounting problem goes away.**

**In the production version of our application, we want to keep the state of the input element locally, but in the same time dispatch an action that updates the entire list with other additional data. If we can't keep state for input value locally, due to problem with scrolling mentioned above, we can accept the workaround to extract local input value state to the global state.** 

**Reproduction** 
https://codesandbox.io/s/virtuoso-unmounting-rq4o9 

**To Reproduce**
1. Click the "Edit" button within the list item
2. Start editing text inside input element
3. Watch the component unmount by losing focus on the input element for each `onChange` event
4. Remove temporarly `components` prop from Virtuoso and observe that there is no unmounting problem

**Expected behavior**
Not unmounting list items when virtuoso is re-rendered, as it currently works when not using props `components`.

**Desktop:**
 - OS: Windows, macOS
 - Browsers: Chrome, Safari

**Comment by petyosi** [comment]
Anything you pass in the components should be cached, either hoisted to the top (best if doable) or with useCallback or useMemo hooks. Right now, on each render you pass a new instance of the component.

**Comment by dominikmlynarczyk** [comment]
Thank you for responding quickly. 🙏 
For the above codesandbox, could you show a working example with `useMemo` or `useCallback`? We probably can't use hoisting because the data to `components` that are passed in comes from props to the `VirtualSortableList` which is rendering Virtuoso.

**Comment by baryosef-loops** [comment]
Worth to mention anything about it in the documentation
