### ISSUE TITLE
[BUG] Overscan does not work in reverse as expected

### ISSUE THREAD

**Issue by cryptoethic** [petyosi/react-virtuoso#406]
Hey!

I'm using react-virtuoso and I have found a bug with overscan property.

When slowly scrolling up (in reverse order) items are not loaded in the background (wher it can't be seen according to overscan property). 
Some images for better understanding:

![not scrolling](https://user-images.githubusercontent.com/44468286/125933283-ff785e1e-e9c7-4b31-aaae-1c80f9d7d89c.png)
On this view I am not scrolling and would like to have some cards above rendered  (based on overscan property)

When I scroll a little bit up, some cards will render (depends on overscan property) - with 500 as overscan value about 4 cards are rendered and after scrolling 4 cards the same thing occurs again.
![image](https://user-images.githubusercontent.com/44468286/125933710-527b6f0f-62cd-4235-84e6-044b4d8061c9.png)

When scrolling downwards this problem does not occur - items are loaded before i can see them.

Any idea how to overcome this problem?

All best,
cryptoethic

**Comment by petyosi** [comment]
Can you create a simple repro? The idea of "reverse" is how much of overscan to apply in the direction reverse to the scrolling. So if you scroll up,`reverse` means how much pixels will be used for the bottom part of the list.

**Comment by cryptoethic** [comment]
![image](https://user-images.githubusercontent.com/44468286/125943901-a600edb6-a31f-47f7-98a9-3bdf19bb4d88.png)

The problem occurs when Header component is set.

https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-i4c92


Scroll down to have some rows not loaded above, then slowly scroll upwards

**Comment by cryptoethic** [comment]
@petyosi do you have any concept how to trace this problem. where to look for a solution? Maybe I could somehow help with resolving this issue ;)

**Comment by petyosi** [comment]
I am totally overwhelmed in my day job ATM. If you can debug that further, I would happily accept a PR. You can clone the repo, run `yarn browse-examples`, and tweak the `header-footer` example until you reproduce it. From there on, I am fairly certain that the logic the [size range system](https://github.com/petyosi/react-virtuoso/blob/master/src/sizeRangeSystem.ts) is missing an edge case.
