### ISSUE TITLE
[BUG] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cryptoethic** [petyosi/react-virtuoso#409]
Hello ;-)

I have found a bug in version 1.9.5 that didn't occur in version 1.9.1:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Array.slice (<anonymous>)
    at eval (urx.esm.js:305)
    at publish (urx.esm.js:183)
    at eval (urx.esm.js:862)
    at eval (urx.esm.js:566)
    at eval (urx.esm.js:306)
    at Array.forEach (<anonymous>)
    at eval (urx.esm.js:305)
    at eval (urx.esm.js:343)
    at eval (urx.esm.js:76)
 ```

Happens when changing height drastically of list item (expanding Card in my case)

**Comment by petyosi** [comment]
When opening an issue, please provide the respective means for reproduction. Otherwise it is not actionable on my side. Once I have such, I can take a look. Thank you.

**Comment by cryptoethic** [comment]
Wasn't able to produce such repo ;/

Looks like everything works fine 
https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-forked-ggrrg?file=/src/App.js

Can't stacktrace be helpfull? What is this urx library resposible for? Any Ideas how can I try to debug it?

**Comment by cryptoethic** [comment]
Can it somehow be connected with these changes?
![image](https://user-images.githubusercontent.com/44468286/126147859-fa5dad68-7ade-4fa3-a562-d76f7316070d.png)

**Comment by cryptoethic** [comment]
It looks like problem happens when scrolling to the top of the list

and starts occuring in this commit  https://github.com/petyosi/react-virtuoso/commit/acc1d7807cee3c780342d50c87f31ef9e2c3911f

**Comment by petyosi** [comment]
It could be, but I need to reproduce on my side in order to help.

**Comment by cryptoethic** [comment]
![image](https://user-images.githubusercontent.com/44468286/126152884-c0d7ad84-f3f0-4d72-9167-08fd261a7532.png)
https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-forked-6s3i9?file=/src/App.js

In this sandbox you can see that when scrolling with header visible there are tons of rerenders (console logs)
Still not able to reproduce  RangeError: Maximum call stack size exceeded

**Comment by cryptoethic** [comment]
![image](https://user-images.githubusercontent.com/44468286/126156244-c6bf3156-7096-44af-93fa-be1aa11a7e58.png)
 when slowly scrolling there is a gap where rerenders occures a lot an it is dependant on header height (bigger header, bigger gap)

**Comment by cryptoethic** [comment]
![image](https://user-images.githubusercontent.com/44468286/126160865-154b2d46-9d8e-477b-a426-b4fe51c1a11d.png)
got it in code sandbox @petyosi 

when  overscan is 0 then problem does not occur 

To reproduce: Open sandbox :
https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-forked-dr6bc?file=/src/App.js&resolutionWidth=320&resolutionHeight=675

Scroll little down and then slowly back to the top

**Comment by cryptoethic** [comment]
Thanks for your work on that issue.
Unfortunately release 1.9.6 reopens first issue #406:
![image](https://user-images.githubusercontent.com/44468286/126231124-26fceb35-1ace-45da-8c82-1b710f6d1df6.png)

**Comment by petyosi** [comment]
Interesting. I am using the fairly simple https://github.com/petyosi/react-virtuoso/blob/master/e2e/header-footer.tsx to test, and it works?

**Comment by cryptoethic** [comment]
Hmm. Your example works and i cannot reproduce error on that code.

Checkout this sandbox:
https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-forked-gnl1z?file=/src/App.js

There are two VIrtuoso where first doesn't have this error and second does. Only change is padding in itemContent.

And this sandbox is the same I used to show how to reproduce bug, but this time with react-vituoso 1.9.6
https://codesandbox.io/s/react-virtuoso-reverse-scrolling-header-issue-forked-tz43o?file=/src/App.js

Slowly scrolling to the top creates white gaps based on header height:
![image](https://user-images.githubusercontent.com/44468286/126290465-ab9e2904-59d4-498b-9e31-5adb4fe38254.png)
