### ISSUE TITLE
[Question] Active group content scrolling transition

### ISSUE THREAD

**Issue by andrewdieken** [petyosi/react-virtuoso#420]
The current active group content scrolling transition is for the next group content to scroll on top of the active group content replacing it and vice versa for the previous group content.

I'm wondering if it's possible for the next group content to push the active group content off the screen as opposed to the current behavior of having it scroll on top of it? If it's not possible, would it be possible to open a feature request to support this behavior?

<img width="402" alt="Screen Shot 2021-07-27 at 4 36 15 PM" src="https://user-images.githubusercontent.com/27448527/127236696-5901119e-6832-4d9c-aa1f-9556efee034f.png">

**Comment by petyosi** [comment]
Feel free to give this a try. I would welcome a PR.
