### ISSUE TITLE
QUESTION: It is possible to access data property through a ref

### ISSUE THREAD

**Issue by adamvietnam** [petyosi/react-virtuoso#421]
If a parent passes a reference down to a child component containing a list i.e.

```
   <Virtuoso data={listItems}
                  ref={someRef}
  .
  .
  .
  <Virtuoso/>
```

Can the parent then access the data property using the  ref in , for instance, an event handler i.e.

```
const parentOnClickHandler=(e) => {
    const itemsSelected=listRef.current.data.filter( (element,index) => {  
       return someRef.current.data[index].isSelected;
   });
}
```
At the moment, when I inspect the someRef.current I can see the API methods but not the API properties. 

I'm using version 1.10.2 of react-virtuoso and my code is in Javascript rather than Typescript so I can't import `<VirtuosoHandle>`

I'm also pretty new to ReactJS so apologies if this is dumb question.

**Comment by petyosi** [comment]
No, such API is not exposed. IMO, doing something like this violates the unidirectional data flow principles in React.

**Comment by adamvietnam** [comment]
I understand and suspected that was the case. 

I'll propagate upwards which I'm sure is the more sensible.

Thank you for your prompt response.
