### ISSUE TITLE
[BUG] List with expandable cards renders only a single item when using `totalCount` prop

### ISSUE THREAD

**Issue by tusharpahuja** [petyosi/react-virtuoso#425]
**Describe the bug**
List with expandable cards renders only a single item when using `totalCount` prop

**Reproduction**
Code sandbox link -> https://codesandbox.io/s/blazing-bush-3lkli?file=/src/index.js

**To Reproduce**
1. Go to the sandbox link and see that the list is rendering a single item.
2. On page reload, if you clearly observe, the items renders but disappear. 
3. Comment out the `totalCount` prop in the list and the items renders fine. 

**Expected behavior**
The items renders fine with `initialItemsCount` items rendering on first load and total of `totalCount` items rendering in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/18447348/128136108-e11a968a-4314-45f0-82c9-dc7ba8ffea13.png)

**Comment by petyosi** [comment]
@tusharpahuja your `ItemContainer` implementation is the culprit. You need to pass the received rest `props` to the root `div` element. You can search the issues and https://virtuoso.dev/ for working examples that you can use as a base. That one is pretty close to what you are doing: https://virtuoso.dev/material-ui-endless-scrolling/

**Comment by tusharpahuja** [comment]
Yup, it fixed the issue. Thanks @petyosi :).
Since it was working fine with `initialItemCount`, and stopped working after introducing `totalCount`, I thought some issue is there with the new prop. But I was incorrect.

Thanks for the quick response.

**Comment by tusharpahuja** [comment]
@petyosi can you help with some documentation on how the core logic for each list item height computation is handled for Virtuoso?

**Comment by petyosi** [comment]
Not sure I understand. The component doesn't compute item heights. It measures them. What's the problem you experience?

**Comment by roddc** [comment]
@petyosi Hi, I am facing the same issue with Antd Collapse, I have passed all props to the Item already, but still only first item got rendered. However, the whole list will be rendered if I use initialItemCount.
I am not sure if this is a compatibility issue.

```
import { Collapse } from 'antd';
const ItemWrapper = observer((props: any) => {
  return <Collapse.Panel {...props}></Collapse.Panel>;
});

 const Comps = useMemo(() => {
      const a = {
        List: forwardRef(({ style, children, ...rest }: any, ref: any) => {
          console.log('inner ', style, rest, children);
          return (
            <div ref={ref} style={{ ...style, height: '100%' }} {...rest}>
              <Collapse
                bordered={false}
                accordion
                expandIconPosition="end"
                // onChange={onCollapseChange}
              >
                {children}
              </Collapse>
            </div>
          );
        }),
        Item: ItemWrapper,
      };

      return a;
    }, []);

 <Virtuoso
        style={{ height: '100%' }}
        totalCount={items.length}
        logLevel={LogLevel.DEBUG}
        components={Comps}
        itemContent={(index, _, context) => {
          const item = items[index];
          return (
            <div>{items.id}</div>
          );
        }}
      />
```
