### ISSUE TITLE
[BUG] Weird scrolling behavior with react-beautiful-dnd

### ISSUE THREAD

**Issue by loun4** [petyosi/react-virtuoso#426]
**Describe the bug**
Dragging items to the bottom of the list causes strange scrolling behavior

**Reproduction**
https://codesandbox.io/s/react-virutoso-with-react-beautiful-dnd-forked-pslfr?file=/src/index.js

**Screenshots**

https://user-images.githubusercontent.com/1511512/128223648-dba6f815-cadc-44a1-9902-f64296693d67.mov

**Desktop (please complete the following information):**
 - OS: Mac OS 11.5.1.
 - Browser: Browser Chrome 92

**Comment by loun4** [comment]
Any suggestion or workaround to fix that ?

**Comment by loun4** [comment]
Another sample based on the official one (https://virtuoso.dev/react-beautiful-dnd/) :
https://codesandbox.io/s/react-virutoso-with-react-beautiful-dnd-bug-wgtmq?file=/src/index.js

We don't understand why this only happens when items are dragged to the bottom.


https://user-images.githubusercontent.com/1511512/129692686-ee29ed62-be69-48e5-b5e0-d85f5adae3a4.mov

**Comment by petyosi** [comment]
Feel free to examine the DOM structure and see what causes the flickering. I am unlikely to get to debugging that anytime soon.

**Comment by Guiw5** [comment]
have you tried adding an extra height to those container divs?

**Comment by Harshit369** [comment]
@loun4 were you able to control it somehow? it only happens when you drag something to the end of any other column. doesn't happen in the same one.

**Comment by OleksandrEmpeek** [comment]
I had this problem too, the solution for me was to add `{provided.placeholder}` to the end of the Droppable container
```JSX
<Droppable droppableId={`${status.Id}`}>
  {provided => {
    const columnFind = columns.find(column => column.statusId === status.Id);

    return (
      <div
        ref={provided.innerRef}
        className={classNames(styles.tasksList, {
          [styles.emptyColumn]: !columnFind?.tasks.length,
        })}
        {...provided.droppableProps}
      >
        {buildTasks(columnFind)}
        {provided.placeholder}
      </div>
    );
  }}
</Droppable>
```

**Comment by Aditi0505** [comment]
Hey, any solution to this? It is only happening for the bottom most element. My hunch is since the virtual list has it as the last element, it is unable to move upwards and css transition is not applied. Can someone please help? 

PS: I tired using `provided.placeholder` but apparently, virtual lists doesn't require one.

**Comment by zhangxuanou** [comment]
> 嘿嘿，这个问题有什么解决办法吗？它只发生在最底部的元素上。我的预感是，由于虚拟列表将其作为最后一个元素，因此无法删除顶部项目并相应地更改索引，并且不应用 css转换。有人可以帮忙吗？
> 
> PS：我厌倦了使用`provided.placeholder`，但显然，虚拟列表不需要它。

I want to ask if you have solved this problem?

**Comment by rishita2605** [comment]
For anyone who's looking for a fix of this issue, adding a min-height slightly more than the height of my list solved this issue for me 
https://github.com/atlassian/react-beautiful-dnd/issues/533
