### ISSUE TITLE
[BUG] Weird behavior when scrolling through already loaded elements, when their height is updated

### ISSUE THREAD

**Issue by andreivasilache** [petyosi/react-virtuoso#436]
**Describe the bug**
After some elements are loaded, and their height is updated, the scrollbar is jumping on scroll.

**Reproduction**
Please take a look over: https://codesandbox.io/s/relaxed-firefly-q8j33

**To Reproduce**
1. Go to https://codesandbox.io/s/relaxed-firefly-q8j33 ;
2. Scroll until the bottom of the page;
3. Double-click on the "Expand/Collapse All" button;
4. Scroll to the top. (Here the issue should reproduce, also the elements are not rendered as they should);
5. Click on "Expand/Collapse All;
6. Scroll to the bottom again. (The issue should reproduce)

Maybe the issue is related to the tables nested on three levels? 

**Expected behavior**
The scroll should be smooth, regardless of the height of the elements.

**Screenshots**
![weird jumping scroll](https://user-images.githubusercontent.com/33156276/130587379-e151545e-b344-4a45-b975-bb51d45feb17.gif)

- Browser: Chrome

**Comment by petyosi** [comment]
There's no solution for that ATM. The scroll size is calculated based on the previously known sizes. When you scroll up, the list encounters a bunch of short items where tall items were previously put and tries to compensate for them. The compensation works quite well for several odd-sized items, but there's just not an algorithm to handle that meaningfully with the test case you have provided. 

 The same goes for the opposite direction - encountering tall items where short items should be.
