### ISSUE TITLE
[BUG] List not rendering properly if initially rendered with CSS transform

### ISSUE THREAD

**Issue by ianplatt555** [petyosi/react-virtuoso#441]
**Describe the bug**
If I initially render a Virtuoso list inside of a container which has a CSS transform applied to it, for example `transform: scale(0);`, and then I change the transform eg. to `transform: scale(1)`, the list does not always render properly. 

**Reproduction**
Here's one simple example:
https://stackblitz.com/edit/react-qpcpm1?file=src/App.js

Here's another example where I set the Virtuoso height manually and add a CSS transition timer (click the button and then try to scroll):
https://stackblitz.com/edit/react-9xwzfz?file=src/App.js

Oddly, that last one works fine if you remove the transition timer and make it instantaneous. 

**To Reproduce**
It's pretty self-explanatory in the reproduction URL above. Just click the button and see how when they are scaled up, the list doesn't render properly at the larger size and bugs out (either rendering wrong or rendering no items at all)

**Expected behavior**
List rendering should not be affected by CSS transforms at all. It should be possible to scale up/down the list container using CSS transforms without any issues.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by petyosi** [comment]
Not possible I'm afraid. At scale(0) or any other hidden state, the items cannot be measured.

**Comment by ianplatt555** [comment]
But in this case, it's not just `scale(0)` or some hidden state. The issue is that when it's scaled small (eg. `scale(0.1)`) to start, and then scaled up (back to `scale(1)`), the list doesn't seem to resize properly. Take a look at the second example I linked. There's no scale(0) or hidden states involved. It just breaks when scaled up.

If this cannot be fixed, is there a workaround you would suggest? In my case the list is rendered as part of an animated container which scales into view.

**Comment by petyosi** [comment]
@ianplatt555 I see what you describe. It looks like the transition does not trigger a re-measurement (and that's a good thing, I guess, otherwise you will get constant re-renders while transitioning). feel free to debug the case further and submit a PR. You can check debugging instructions in [the contributing section](https://github.com/petyosi/react-virtuoso#contributing).
