### ISSUE TITLE
[BUG] atBottomStateChange not working correctly with Header

### ISSUE THREAD

**Issue by ianplatt555** [petyosi/react-virtuoso#445]
**Describe the bug**
When a fixed height header is added, atBottomStateChange does not seem to function properly, in particular, it seems offset by some amount from the bottom before it triggers. 

**Reproduction**
https://stackblitz.com/edit/react-askmht?file=src/App.js

**To Reproduce**
1. Go to the linked stackblitz
2. Scroll all the way to the bottom, note that it displays bottom: true
3. Scroll up just a tiny bit. Note that it still says Bottom: true (this is wrong)
4. Scroll up some more until it says Bottom: false

**Expected behavior**
atBottomStateChange should be triggered as soon as I scroll away from or to the exact bottom of the list, even when a header is present.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by ianplatt555** [comment]
Probably related issues that happen when that header is enabled:

1. followOutput seems to be quite buggy with the header on as well. Sometimes it works fine when appending an item, but other times it doesn't scroll down enough. Hard to reproduce consistently.

2. Resizing the list to be smaller also seems buggy with the header. It resizes fine but sometimes doesn't keep the scroll at the bottom even when followOutput=true. Here's a reproduction https://stackblitz.com/edit/react-xncddv?file=src/App.js. Scroll to the bottom and then click the change size button. Notice how the list is no longer at the bottom after the resize.

**Comment by petyosi** [comment]
@ianplatt555 that's a nice catch, thank you for the reproduction. `followOutput` is internally using the same state flag, so yes, most likely the fix I published (coming from the build as I reply) should address it. Let me know if this is not so.

**Comment by ianplatt555** [comment]
Thanks for the quick fix, looks like it's working!
