### ISSUE TITLE
[BUG] Jump on first render

### ISSUE THREAD

**Issue by maccman** [petyosi/react-virtuoso#446]
**Describe the bug**

We recently upgrade Virtuoso from 1.9.3 to 2.0.1. We have started to see some jumping behavior when the list is rendered.

I understand that Virtuoso is measuring items dynamically, but this never used to happen. See video for a demo.

https://user-images.githubusercontent.com/2142/132108435-3609c405-0557-4d83-b185-8d7186b2479d.mp4

Do you have any pointers for us to debug this?

***Implementation***

```jsx
        <div className="flex-1 flex-col overflow-hidden">
          <Virtuoso
            ref={virtuoso}
            width={'100%'}
            height={'100%'}
            data={notes}
            firstItemIndex={firstItemIndex}
            rangeChanged={onRangeChanged}
            initialTopMostItemIndex={noteIndex}
            endReached={onEndReached}
            startReached={onStartReached}
            itemContent={(_index, note) => (
              <DailyNoteEdit
                key={note.id}
                availableBacklinks={backlinks}
                notes={notes}
                note={note}
                fullScreen={fullScreen}
                semiScreen={semiScreen}
              />
            )}
          />
        </div>
```

p.s. THANK YOU so much for Virtuoso - it's epic.

**Comment by petyosi** [comment]
Thank you for the support @maccman, highly appreciated. I will examine the configuration, probably one recent bugfix I introduced causes the regression. Will let you know if I need further clues. To confirm, you're not scrolling to the last item of the list, correct?

**Comment by petyosi** [comment]
@maccman I could not clearly reproduce the jump on my side, but examining your configuration, I believe that the regression was introduced by the `setTimeout` addition in `1.10.6`. Can I ask for your help here? If my assumption is correct, if you install `1.10.5` the jump should not be there. Alternatively, but less likely, `v1.10.3` could be the culprit, in which case installing `1.10.2` would remove the jump. 

Both of those are fixable, of course. I assume you don't do anything additional on navigation or by manipulating the `ref`.

**Comment by maccman** [comment]
The jump was still there after installing 1.10.5. 

However, the jump goes away if I install 1.10.2.

**Comment by petyosi** [comment]
@maccman do you do something additional with the list `ref`?  If you want to set up a repro in your environment, I would love to observe that as well (you can reach out to my email in the GH profile).
