### ISSUE TITLE
[BUG] Scrollbar incorrectly positioned in Chrome during scrollbar-based scrolling

### ISSUE THREAD

**Issue by AaronPlave** [petyosi/react-virtuoso#449]
**Describe the bug**
The scrollbar does not correctly track with the user's cursor when dragging the scrollbar in Chrome. This oddly does not appear to be an in Firefox.

**Reproduction**
I'm able to reproduce this issue with the demo found at https://virtuoso.dev/hello/ using Chrome Version 93.0.4577.63 (Official Build) (x86_64) on Mac 10.15.7. Drag the scrollbar down at a medium or fast pace. The scrollbar will fall out of sync with the cursor. On Firefox 78.13.0esr the scrollbar seems to always stay in sync with the cursor.

Firefox scrolling:
![firefox_scrollbar](https://user-images.githubusercontent.com/4419607/132751474-a00ed539-441f-422f-a558-5dbcbd0da5c5.gif)

Chrome scrolling:
![chrome_scrollbar](https://user-images.githubusercontent.com/4419607/132751584-2f351225-9122-426f-8e2f-4067d977829b.gif)

**Additional context**
In my testing I did see that the issue may depend somewhat on the variability of item heights, or at least how much they differ from the first item or defaultItemHeight.

**Comment by petyosi** [comment]
I am not aware of any way to fix that, I'm afraid. as you scroll down, the size of the scrollable area changes. Apparently, Chrome does not sync the scroll thumb accordingly.
