### ISSUE TITLE
pin items broken, first item not sticky

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#45]
Hi, the first row of the list doesn't stick to the top.

You can reproduce it in the demo website example:
https://virtuoso.dev/top-items/

![image](https://user-images.githubusercontent.com/5382443/66069673-23aa0480-e550-11e9-9388-d0894c7c6d7f.png)

**Comment by petyosi** [comment]
@FezVrasta - this is related to the server-side rendering, at least on the site. Examining further.

**Comment by FezVrasta** [comment]
I get a very similar problem on codesandbox

**Comment by petyosi** [comment]
Can you post a link to the sandbox? Might be a different case then.

**Comment by FezVrasta** [comment]
https://codesandbox.io/s/crazy-buck-8js2n

here it is, if you set `topItems` to 1, it has no effect, you must set it to at least 2

**Comment by petyosi** [comment]
@FezVrasta I fixed the problem in the sandbox (never worked in the first place) in 0.12.2 - [updated sandbox](https://codesandbox.io/s/blazing-violet-48bwy). The problem on the demo site is a different story though, will keep the issue open.

**Comment by petyosi** [comment]
The above is resolved in 0.12.3.
