### ISSUE TITLE
[BUG] initialTopMostItemIndex is not working  if fixedItemHeight is set in safari

### ISSUE THREAD

**Issue by monzilnepali** [petyosi/react-virtuoso#451]
**Describe the bug**
initialTopMostItemIndex is not working if fixedItemHeight is set In safari.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-g5k9u

**Expected behavior**
initialTopMostItemIndex should work as expected in safari

**Screenshots**

https://user-images.githubusercontent.com/28225895/133617156-703f9d3c-7e79-4808-8409-5c462096bf0c.mov

**Desktop:**
 - macOS 11.5
 - safari

**Comment by petyosi** [comment]
Interesting. It also needs the "open" button logic you have in the sandbox, rendering it right away works fine as far as I can see. Right?

**Comment by monzilnepali** [comment]
@petyosi Yeah it seems to be working fine without "open" conditional logic.
