### ISSUE TITLE
doesn't work with iOS 10-11-12 [BUG]

### ISSUE THREAD

**Issue by meotimdihia** [petyosi/react-virtuoso#452]
**Describe the bug**
Doesn't work even with https://virtuoso.dev/endless-scrolling/ and my website.

**Reproduction**

Please try to register a free account on https://appetize.io/.

 "react-virtuoso": "^2.0.5",

**Desktop (please complete the following information):**
 - OS: 10-11-12
 - Browser Safari
  
May related to this bug: https://github.com/petyosi/react-virtuoso/issues/309. But it doesn't work on my website too.

**Comment by petyosi** [comment]
The virtuoso.dev example works as expected in iOS. Isolate the problem out of your website in a codesandbox.
