### ISSUE TITLE
[BUG] using `initialTopMostItemIndex` with `fixedItemHeight` does not skip rendering items at the start of the list 

### ISSUE THREAD

**Issue by botond-rostas** [petyosi/react-virtuoso#458]
**Describe the bug**
When `initialTopMostItemIndex` is provided with a positive number, the component still renders the first set of items (starting with index 0) after which it abruptly scrolls to the specified index rendering the next set of items (starting from the specified index).

**Reproduction**
https://codesandbox.io/s/react-virtuoso-forked-8us5k?file=/src/App.js

**To Reproduce**
1. on the above codesandbox open up the console
2. on render, even though the `initialTopMostItemIndex` is set to `62` the first 8 items are rendered initially after which the next set of items starting from 62 are rendered resulting in a quick scrolling effect

**Expected behavior**
Component should start rendering items from the index provided to `initialTopMostItemIndex` skipping the rendering of items before that index.

**Comment by petyosi** [comment]
@botond-rostas thanks for reporting that, I will take a look. Notice that the problem is reproducible only when the `fixed-item-height` prop is set.

**Comment by monzilnepali** [comment]
@petyosi Looks like this issue is related to [initialTopMostItemIndex is not working if fixedItemHeight is set in safari](https://github.com/petyosi/react-virtuoso/issues/451) right?

**Comment by petyosi** [comment]
I am not sure the two are related
