### ISSUE TITLE
[BUG] initialTopMostItemIndex={undefined} causes only first item is rendered

### ISSUE THREAD

**Issue by aq-saito** [petyosi/react-virtuoso#459]
**Describe the bug**
With react-virtuoso 2.2.1, setting `initialTopMostItemIndex={undefined}` to `<Virtuoso />` component causes that only the first item in the list is rendered at the first time. The rest of the list is not rendered.

This happens only when you specify `initialTopMostItemIndex` prop with an `undefined` value. Not happens without `initialTopMostItemIndex` prop.

This bug also shows the following waning on console:

```
Warning: Received NaN for the `data-item-index` attribute. If this is expected, cast the value to a string.
```

I think it is a major usage to set `initialTopMostItemIndex` to an undefined value by default, so that an actual index is set only when an "active item" exists.

**Reproduction**
https://codesandbox.io/s/frosty-silence-gxokf?file=/src/App.js

**To Reproduce**
1. Go to the sandbox: https://codesandbox.io/s/frosty-silence-gxokf?file=/src/App.js
2. See what is rendered in the `initialTopMostItemIndex = undefined` block.

**Expected behavior**
All of the items (`["foo", "bar", "baz"]`) is rendered at the first render without warnings.

**Screenshots**
<img width="762" alt="2021-09-27 10-27-04" src="https://user-images.githubusercontent.com/69131852/134832593-3efcaa99-e715-473e-a3b3-bbe91207777a.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser: Chrome 94.0.4606.61

**Additional context**
None.

**Comment by petyosi** [comment]
Like the docs say, the prop accepts numbers only. If you pass objects, strings, arrays null, undefined or whatever unexpected value, the component will not work. Being extra-defensive and adding prop types for runtime check is not worth the extra package size. 

As per your case, you should pass 0 instead.

**Comment by joshkel** [comment]
Could you please reopen this issue? It's extremely unusual, in both React and JavaScript, to treat an `undefined` property as different from not setting the value at all. For example, unless TypeScript's [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) option (which has been around for less than a year) is enabled, an optional property can be explicitly set to undefined without raising any issue:

```ts
/**
 * Set to a value between 0 and totalCount - 1 to make the list start scrolled to that item.
 * Pass in an object to achieve additional effects similar to `scrollToIndex`.
 */
initialTopMostItemIndex?: number | IndexLocationWithAlign
```

```tsx
{/* This is permitted because initialTopMostItemIndex is optional. */}
<Virtuoso initialTopMostItemIndex={undefined} />
```

My common approach for React component props that are only sometimes set is to do something similar to the following; this works with literally every other React component prop I've seen.

```tsx
const selected = shouldItBeDefined() ? value : undefined;
return <Virtuoso initialTopMostItemIndex={selected} />;
```

I totally understand not wanting to be extra-defensive and add additional runtime prop type checks; however, `undefined` in particular is common usage and is allowed by TypeScript, so it seems worth supporting.
