### ISSUE TITLE
[BUG] Library (version 2.2.1) not working on IOS less than 13.4 version.

### ISSUE THREAD

**Issue by Maxim725** [petyosi/react-virtuoso#461]
Hi!

Reproduction
This is an example that will help you figure out the problem.
https://codesandbox.io/s/priceless-easley-7std6?file=/src/MessagesList.js

To Reproduce
Steps:
1. Open site on IOS less than 13.4 version
2. See error

Screenshots
![image](https://user-images.githubusercontent.com/47459772/135421576-7fe5134d-5990-4308-8f7e-65fea595510c.png)

**Comment by petyosi** [comment]
@Maxim725 this is due to [resizeobserver](https://caniuse.com/resizeobserver) missing there. You should include the polyfill for older browsers.

**Comment by Maxim725** [comment]
Is this problem described on the library's website?

**Comment by petyosi** [comment]
It's not. I would happily accept a contribution on the matter - you can add it to this page for example: https://virtuoso.dev/troubleshooting

**Comment by Maxim725** [comment]
Okay
