### ISSUE TITLE
[BUG] Elastic behavior at the bottom causes flickering on IOS less than 14.4

### ISSUE THREAD

**Issue by Maxim725** [petyosi/react-virtuoso#462]
Hello! 
Bug with scrolling in IOS less than 14.4.

**Reproduction**
Links: 
https://7std6.csb.app/
https://codesandbox.io/s/priceless-easley-7std6?file=/src/App.js

I tested on a versions IOS
13.3
14.0
and
 14.4 and 15.0 there is no bug

**To Reproduce**
Steps to reproduce the bug:
1. Scroll to the bottom
2. Attempt scroll down 
4. See bug

**Comment by petyosi** [comment]
I don't have that exact version available, can you record a video?

**Comment by Maxim725** [comment]
Okay, I can

**Comment by Maxim725** [comment]
https://user-images.githubusercontent.com/47459772/135465744-3fba27ef-4620-46ee-836d-04579464298d.mp4

**Comment by Maxim725** [comment]
Yes

**Comment by ant-plotnikov** [comment]
@Maxim725 could it be an issue with margins? https://virtuoso.dev/troubleshooting/#list-does-not-scroll-to-the-bottom--items-jump-around
As I see in your sandbox https://codesandbox.io/s/priceless-easley-7std6?file=/src/App.js `p` elements have vertical ones

**Comment by Maxim725** [comment]
@ant-plotnikov Yes, I know about the problems with margin, but I forgot about p. I changed the tag and it didn't help.

**Comment by petyosi** [comment]
Closing - the version is more or less obsolete.
