### ISSUE TITLE
[BUG] startReached invoked continuously

### ISSUE THREAD

**Issue by maccman** [petyosi/react-virtuoso#475]
We are seeing issues where startReached seems to be getting invoked in a loop.

We have Virtuoso in a tab. It seems to happen when the element is display none (tab is hidden). If I, instead of hiding the tab with display none, put it position fixed way out of the viewport everything works correct.

LMK if you need more details to reproduce.

**Comment by maccman** [comment]
I have narrowed it down. If you call `scrollToIndex` when virtuoso is hidden then startReached is invoked continuously.

**Comment by petyosi** [comment]
Thanks, I haven't explored the behavior when hidden. In general, scroll to index can't work in that mode as the items can't be measured. Will noop work for your case?

**Comment by maccman** [comment]
Yeah I suspect that virtuoso just thinks you keep on scrolling up when it can't measure stuff properly. 

You might want to check if virutoso is hidden:

`  const isVirtuosoHidden = () => ref.current?.offsetHeight === 0`

I am working around this by keeping everything in the page. 

https://gist.github.com/maccman/51b4c8169093268f062238cee35743ed
