### ISSUE TITLE
[BUG] When a `VirtuosoGrid` layout is a CSS grid and its height becomes small, the scroll starts jumping/flickering upon reaching the bottom end

### ISSUE THREAD

**Issue by awgv** [petyosi/react-virtuoso#479]
**Describe the bug**
Looks like this:

https://user-images.githubusercontent.com/6409354/139575964-683ee24c-3328-4966-a0d2-5fce18e4d3d4.mp4

Flexbox is unaffected. “Small” is a variable number; in the CodeSandbox example that I attached below the flickering starts if the container’s height is `260px` or less, in a project of mine it’s a bit less than that—around `252px`. Also, the smaller a container’s height, the more intense is the flickering.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-css-grid-issue-3xw6t

**To Reproduce**
Scroll till you hit the bottom, then keep scrolling.

**Desktop:**
 - OS: Windows 11
 - Chrome v95.0.4638.69

Am I using `VirtuosoGrid` correctly? Thank you for your time.

**Comment by petyosi** [comment]
Grid gap is not supported. There's an issue that discusses this. PRs are welcome.

**Comment by awgv** [comment]
Thank you. If someone stumbles upon this thread, the issue’s tracked here: #363.
