### ISSUE TITLE
[BUG] List being re-render affected media item.

### ISSUE THREAD

**Issue by Amethystafyy282** [petyosi/react-virtuoso#482]
**Describe the bug**
I'd use Virtuoso for my chat app which is wonderful so far.

I have a List contained Video Components on each item, which is rendered base on item dynamic url.
But when List begin re-rendered, my component got re-rendered, too. That makes user loss their process to the video.

**To Reproduce**
1. Trigger List to re-render. Easiest practice is to lose focus and refocus on browser tab
2. `itemsRendered` got triggered a lot even though I dont have many item on the viewport, at least they are not exceed default width. Is that normal?

**Expected behavior**
Item component got re-render on scroll is understandable. But during on viewport, idk.

**Screenshots**
Component being re-rendered just like this.
![Screen Shot 2021-11-01 at 15 46 41](https://user-images.githubusercontent.com/63139844/139645886-6a369098-b0f0-492c-abc9-11f0dcec9219.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome

**Comment by petyosi** [comment]
Please reproduce the problem in a codesandbox. I will take a look.

**Comment by Amethystafyy282** [comment]
> Please reproduce the problem in a codesandbox. I will take a look.

I'm so ashamed of myself for not checking carefully before submitting this issue.
Apparently this is the one: https://github.com/petyosi/react-virtuoso/issues/183
Disabling the hook got everything work perfectly again.
Again, thank you for your time!
