### ISSUE TITLE
[BUG] ScrollSeekPlaceholderProps interface is incorrect

### ISSUE THREAD

**Issue by spiderhands** [petyosi/react-virtuoso#483]
**Describe the bug**
ScrollSeekPlaceholderProps interface has **index** field but should have **width** field.

[Here](https://github.com/petyosi/react-virtuoso/blob/16aca7514beefdc9a54e9f920337b46759acd45d/src/interfaces.ts#L53) is interface 

And [here](https://github.com/petyosi/react-virtuoso/blob/16aca7514beefdc9a54e9f920337b46759acd45d/src/Grid.tsx#L115) is implementation where width is provided

Custom item placeholder would be possible if **index** field is provided in the props as well.

I can open PR if you want

**Comment by petyosi** [comment]
Agreed, this needs a separate interface for the grid. PR is welcome.

**Comment by petyosi** [comment]
Fixed in c4c01210
