### ISSUE TITLE
[BUG] GroupedVirtuoso group content sticky missing z-index

### ISSUE THREAD

**Issue by Hideman85** [petyosi/react-virtuoso#486]
A simple issue of z-index of sticky element with the usage of group.
I do have a row with an item in absolute and having z-index since the sticky group title do not have z-index it shows the row element on top of it.

Result:
![image](https://user-images.githubusercontent.com/16165119/140298517-ff1848b7-e463-43a7-b6aa-20ae1b0561cb.png)

Expected:
![image](https://user-images.githubusercontent.com/16165119/140298660-f5897945-8e3f-4f4b-ad11-84dc6c35be79.png)

**Comment by petyosi** [comment]
I'm not sure I fully understand what you want, but you can control that using `components['Group']` - https://virtuoso.dev/api/interfaces/_interfaces_.components#group

**Comment by Hideman85** [comment]
I don't really want to customize the group component it is just that the default one miss a z-index property and the group is behind a row content actually.

Just have a look to the two screenshot and the div structure generated by virtuoso, the wrapper of group content is sticky but miss the z-index to be above the row content (in my sample the green bullet is a row content)

I don't really have the time to setup a sandbox and I manually fixed via css in my current app but it is a thing to fix in the lib for others :)

**Comment by asgerhallas** [comment]
@petyosi it seems to me that `components['Group']` targets the "wrong" element. How do you target the div highlighted in the "Result" image above? 

Group targets the grand child of that highlighted element, and here the z-index won't have the desired effect.

**Comment by ohmycode** [comment]
I'm facing the same problem using GroupedVirtuoso in combination with ionic list items (ionic framework). The virtuoso group header is wrapped in a sticky div, which is displayed behind the items, I can't find a clean solution to fix this behaviour. It would be great if the sticky wrapper had an z-index or a css class to attach it, which would fix the issue.
