### ISSUE TITLE
[BUG] Using custom component List cause the list re-render when data mutated

### ISSUE THREAD

**Issue by Amethystafyy282** [petyosi/react-virtuoso#487]
**Describe the bug**
Using custom component List cause the list re-render when data mutated

**Reproduction**
https://codesandbox.io/s/react-virtuoso-forked-fdhhb?file=/src/App.js

**To Reproduce**
1: Play Audio component
2: Click Add and see the List got re-render

**Expected behavior**
The List not being re-rendered

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by petyosi** [comment]
You need to memoize the custom component with hook or move it out of the 'App'.
