### ISSUE TITLE
[BUG] Grid screen shakes from rapid padding changes after scrolling

### ISSUE THREAD

**Issue by yinsang** [petyosi/react-virtuoso#495]
**Describe the bug**
Using virtuoso grid, set two item of a row, item height is prop up by item's name in flex, may one line , may two lines.

scroll fast will see screen shaking in mobile mode.
I guess that,  image rendering later make item height calculate to a wrong value of virtuoso-grid-list.

**Reproduction**
Use https://codesandbox.io/s/vibrant-bohr-ev4qg?file=/src/App.js  to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

**To Reproduce**
1. open [demo](https://ev4qg.csb.app/)
2. change Chrome devTools to mobile mode
3.  use mouse left button scroll the page about five times. 

**Expected behavior**
No shaking screen.

**Screenshots**
screenshots can't see the problem

**Desktop (please complete the following information):**
 - Chrome  Version 95.0.4638.69 (Official Build) (x86_64)

**Additional context**
if you give a minHeight to name ,error gone.
but prop up height is a necessary feature.
![image](https://user-images.githubusercontent.com/12373328/141072090-2ad031c6-c38f-4c03-afe3-a87ef071b22b.png)

https://user-images.githubusercontent.com/12373328/141072036-381a8067-78a9-4d31-9134-ef6643fc1d31.mov

.

**Comment by petyosi** [comment]
The Virtuoso Grid does not support items with variable height. See readme:
 
> The VirtuosoGrid component displays **same sized items** in multiple columns. The layout and item sizing is controlled through CSS class properties, which allows you to use media queries, min-width, percentage, etc.
