### ISSUE TITLE
[BUG] ScrollIntoViewLocation's "done" function doesn't wait until scrolling is finished

### ISSUE THREAD

**Issue by metapone** [petyosi/react-virtuoso#496]
**Describe the bug**
Inside ScrollIntoViewLocation's `done` function, if I query DOM to get the newly-scrolled-into-view element, the result will be null.

**Reproduction**
Use the code from https://virtuoso.dev/keyboard-navigation/ and add this part to the start of the `done` function:
```
const a = document.querySelector(`[data-index='${nextIndex}']`);
console.log(a);
```

The result should look like this:
````
      if (nextIndex !== null) {
        ref.current.scrollIntoView({
          index: nextIndex,
          behavior: 'auto',
          done: () => {
            const a = document.querySelector(`[data-index='${nextIndex}']`);
            console.log(a);
            setCurrentItemIndex(nextIndex)
          },
        })
        e.preventDefault()
      }
````

**To Reproduce**
Press up or down inside the list according to the example. The browser console will be logged `null` each time an arrow keyboard is pressed instead of the now visible element.

**Expected behavior**
DOM query should work for the new element.

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Chrome 95.0.4638.69 (64-bit)

**Comment by petyosi** [comment]
I'll take a look but I'm not sure that I can definitely fire the event when the DOM is in its final state - it's managed by React after all. Can you explain what's your intended implementation? Why do you need to access the DOM? Why don't you go through hooks?

**Comment by metapone** [comment]
Basically I have an excel-like form/list where each list item is actually a row of `input`s. I want the users to be able to input a lot of data in without having their hands leaving the keyboard to scroll down, so Down/Up arrow key would be used to jump to the next/prev item's 1st `input` by using HTMLElement.focus().

So when an user get to the last visible row and press Down, the current `input`'s `KeyDown` event handler would trigger `scrollIntoView` for the next row, and when done focus on the 1st `input` of that row. Currently `done` is triggered too soon sometimes and the cursor doesn't move; if I use `increaseViewportBy` to render the next item beforehand, then if the focus happens too soon the item will be dragged to the middle of the list's viewport instead of moving up just enough to stay at the bottom.

Attaching refs to all 1000 items would not be idea, and I don't know how to use hooks to solve this problem. Could you explain more about it?

**Comment by petyosi** [comment]
I see what you mean. This is an interesting case, which I think can be solved with hooks + a component in the item in a fairly elegant manner. Basically, you can call the DOM element focus in `useEffect` if the currently selected item is the one rendered.

**Comment by metapone** [comment]
I'm still not clear about this, is this what you meant?
- Create a state to store the item ID to be focused, and in `done` setState to the new item.
- Follow https://virtuoso.dev/range-change-callback/ to get the visible range.
- Use `useEffect` to monitor both the visible range and the item ID to be focused, and when they match call `focus()` and setState itemID to null

Will this be fast enough if the user hold down the Up/Down key to traverse multiple rows quickly? Last time I tested, probably because of the constant refocus and the amount of `input` in each row, the viewport freezed until the key was released, then it jumped to the correct final item.

**Comment by petyosi** [comment]
Not exactly. [Take a look at this](https://codesandbox.io/s/keen-gates-wxbpr?file=/src/App.tsx). I think it works as expected. 

If this helped you, please consider sponsoring the project. It will be highly appreciated and will help me with its ongoing development.
