### ISSUE TITLE
[BUG] atBottomStateChange fires multiple times on mount.

### ISSUE THREAD

**Issue by JavierM42** [petyosi/react-virtuoso#497]
**Describe the bug**
The atBottomStateChange callback fires at least twice when the Virtuoso component mounts.

**Reproduction**
https://stackblitz.com/edit/react-opcwka?file=src/App.js

**To Reproduce**
Check the console and see the three logs on every reload: `false`, then `true`, then `false` again.

If you set `initialTopMostItemIndex=999999`, `atBottomStateChange` will fire a fourth time with value `true`.

If there are not enough elements to introduce a scrollbar, it will fire only two times (first `false`, then `true`).

**Expected behavior**
`atBottomStateChange` only fires once on mount, with the correct value.

**Screenshots**
<img width="404" alt="Screen Shot 2021-11-12 at 11 32 36" src="https://user-images.githubusercontent.com/32175149/141484113-d74dfd33-9715-49b3-a9ba-571d582f93bd.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome

**Comment by petyosi** [comment]
That would be an improvement indeed, but I am not sure when I can get to it. In the mean time, debouncing it should work as a workaround.
