### ISSUE TITLE
Scroll at specific index

### ISSUE THREAD

**Issue by Maesimt** [petyosi/react-virtuoso#5]
Would like to see some features around scrolling to a specific index and an option to start at bottom.

**Comment by petyosi** [comment]
Feedback from twitter reg the same: https://twitter.com/zshrm/status/1129389811024973826

**Comment by petyosi** [comment]
@Maesimt , I just published v0.5.0, which has `scrollToIndex` - check the [example](https://virtuoso.dev/scroll-to-index). Let me know if this is what you had in mind.
