### ISSUE TITLE
Add Flow type annotations?

### ISSUE THREAD

**Issue by FezVrasta** [petyosi/react-virtuoso#50]
Hi, would you accept a PR to add Flow type annotations to the project?

**Comment by petyosi** [comment]
Is there anything that will generate them from the typescript ones? Otherwise, they would get out of sync eventually.

**Comment by FezVrasta** [comment]
There's [flowgen](https://github.com/joarwilk/flowgen), but AFAIK it only works for `.d.ts` files.

**Comment by petyosi** [comment]
It can be added as a build step after the d.ts files are generated by the `yarn build` I think.
