### ISSUE TITLE
[BUG] gropup content lose focus 

### ISSUE THREAD

**Issue by codingedgar** [petyosi/react-virtuoso#506]
**Describe the bug**
using `GroupedVirtuoso` and I have an input in the `groupContent` (an autocomplete to filter the elements of the group), when elements all filtered, leaving the list in a different state, therefore re-rendering the previous header, i lose focus of the input.

**To Reproduce**
1. Go to https://codesandbox.io/s/great-danny-4i571
2. Click on write in the inputs
3. Scroll down to
4. See how the inputs get cleared and lose focus

**Expected behavior**
Be able to avoid inputs losing focus, at least visible headers when scrolling up, that remain visible

**Screenshots**
![Nov-23-2021 13-05-52](https://user-images.githubusercontent.com/10213241/143060790-1c39f44e-9269-4c68-a156-58c311a59b6e.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Additional context**
I've tried memorized components and it is the same result, i guess because it is actually rendering a new component in other node of the DOM.

**Comment by petyosi** [comment]
Hey, 

I'm afraid that the re-render is unavoidable - the elements are re-parented. You will have to preserve the value/focus state in a state so that you can restore them at re-render.

**Comment by codingedgar** [comment]
> Hey,
> 
> I'm afraid that the re-render is unavoidable - the elements are re-parented. You will have to preserve the value/focus state in a state so that you can restore them at re-render.

thx, good hint 👍
