### ISSUE TITLE
[Feature request] offset for initialTopMostItemIndex

### ISSUE THREAD

**Issue by bartlomiejwendt** [petyosi/react-virtuoso#509]
Hi,
I have a case where I have a page with a virtualized list of elements that use useWindowScroll. You can click on that element and navigate to "detailed view" and after you're done you can get back to the list with your scroll position being in the same place. The problem is that I've also a sticky header and virtuoso can't handle that when setting initialTopMostItemIndex. The list element is being overflown by the height of the header (the actual scroll position is good and it is working perfectly fine) and I would like to add a negative offset for Y-axis (vertical) to prevent that.

Now we can use it in one of the methods (scrollToIndex) and it would be great to alsoo add such functionality to initialTopMostItemIndex.

So instead of using it this way:

`
<Virtuoso
  initialTopMostItemIndex={0}
/>
`

We could do something like:

`
<Virtuoso
  initialTopMostItemIndex={{
    index: 0,
    offset: -100
  }}
/>
`

Thank you guys!

**Comment by petyosi** [comment]
Thank you. Feel free to submit a PR that addresses that. I'll take a look.

**Comment by bartlomiejwendt** [comment]
I am going to do that when I will have some free time this week.

**Comment by petyosi** [comment]
This was merged at some point, we did not associate the issue with the PR.
