### ISSUE TITLE
Running playground

### ISSUE THREAD

**Issue by veyndan** [petyosi/react-virtuoso#51]
I'm attempting to work on a previous issue that I have created, and would like to use `playground` to aid me in debugging. However, I'm having a couple of issues getting it to work.

First up, neither of the following dependencies can be resolved.

https://github.com/petyosi/react-virtuoso/blob/fa21f922525d83fe67c0f05ae81ff0fb523a2558/playground/grid.tsx#L5-L6

Second up, and this one is more on my limited experience in React, is how would you go about running the playground? Intuitively, I would want to run `npm run playground` but no `playground` script exists.  Should I be running `create-react-app` in the `playground` directory? Something completely different?

**Comment by veyndan** [comment]
Thanks! Got it to work. I agree that running the `playground` could be a bit easier.

**Comment by petyosi** [comment]
A set of examples is present in the `e2e` directory. They are runnable through `npm run preview e2e/{example}.tsx`. [Documented in the contributing section](https://github.com/petyosi/react-virtuoso#contributing).
