### ISSUE TITLE
When scrolling up quickly, there will be a white background and no rendered items

### ISSUE THREAD

**Issue by BigTomM** [petyosi/react-virtuoso#510]
**Describe the bug**
When scrolling up quickly, there will first be a white background for a short while and then rendered items.
I’m working on a live chat app and encountered this problem when I upgraded from v0.20.0 to v2.2.8 recently.
When I implement the same function in v0.20.0, there is no such white background. This blank only appeared in v2.2.8.

**Reproduction**
https://codesandbox.io/s/react-virutoso-bug-510-0kk9i

**To Reproduce**
1. Use the mouse wheel
2. Scroll up 
3. Repeat

**Expected behavior**
Can see rendered items directly

**Screenshots**
Will stay white background for a short while before displaying items

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Edge 96.0.1054.34, chrome 96.0.4664.45

**Additional context**
the Screen recording:
https://user-images.githubusercontent.com/46660805/143559133-a5b7885b-c54a-416a-ae19-e2fd3172ba3b.mp4

**Comment by petyosi** [comment]
You have a `defaultItemHeight` set to a value which makes no sense given the example.

**Comment by BigTomM** [comment]
Thanks so much, solved it. I adjusted the defaultItemHeight to a reasonable value
