### ISSUE TITLE
Issue with items flickering, list not loading, and jumping

### ISSUE THREAD

**Issue by cang4** [petyosi/react-virtuoso#514]
I am trying to virtualize a list of images and display them as a grid but I am having issues with it. Currently I am trying to virtualize a list of images, but my code does not work with divs with a static height as items instead of imgs either. [Here](https://codesandbox.io/s/agitated-feather-t8su8?file=/src/ImageListComponent.js) is a reproduction of my code.

**Comment by petyosi** [comment]
You're most likely missing something in your setup. Check [this example](https://github.com/petyosi/react-virtuoso/blob/master/e2e/window-grid.tsx).
