### ISSUE TITLE
startReached not called when scrolling to the top

### ISSUE THREAD

**Issue by invincibleyolk** [petyosi/react-virtuoso#518]
version: 2.2.8

endReached is working, but startReached is not called. I used atTopStateChange to add the data, the data has added but the list still doesn't scroll up. I used the exact same codes in your example.

(I downgraded to 1.11 then it's working)
Any idea with the issue of the newest version? Cheers

**Comment by chaosuperDK** [comment]
Should be working at next release #517

**Comment by petyosi** [comment]
Sorry, I broke that by changing bundlers :(. Please upgrade to `v2.3.0`.

**Comment by invincibleyolk** [comment]
thanks!

**Comment by invincibleyolk** [comment]
![image](https://user-images.githubusercontent.com/37947268/145006115-b69a0796-7d86-4b39-9023-35cdb57dcfa2.png)

Hi @petyosi , I upgraded to v2.3.0 just now, and an error like this occured. I'm not sure if it's the problem of me using Vite.. but could you please have a look at it? Many thanks

**Comment by petyosi** [comment]
@invincibleyolk :( I should not have messed with those bundlers on the same day I got a booster shot. Please try `v2.3.1`.

**Comment by invincibleyolk** [comment]
> @invincibleyolk :( I should not have messed with those bundlers on the same day I got a booster shot. Please try `v2.3.1`.

It's working perfectly now! Thanks a lot! Take some rest then ;)
