### ISSUE TITLE
Item prop does accepts only ReactElement as a return type.

### ISSUE THREAD

**Issue by davide-igdb** [petyosi/react-virtuoso#52]
```typescript
type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```

All of the above types function correctly to render a React component. But item as a prop lacks the alternatives to `ReactElement` in it's return type.

I tried to return `null` from item and it works on the javascript side. But I have to cast `null as ReactElement` to make it work in ts.

Would you consider to type item as `(index: number) => ReactNode`? Or is there a reason why the return type is strict to be ReactElement only?

**Comment by petyosi** [comment]
I am 99% certain that returning `null / undefined` will confuse the measuring mechanism. Wh don't you filter the items from the data instead?

**Comment by davide-igdb** [comment]
As the index could be any number, I return null if said index is out of range. I covered it for testing purposes.

```typescript
  item={index => {
          const value = arrayOfValues[index];

          if (value === undefined) return null;

          // return the element instead
   }}
```

Just as a thought. In this scenario would you suggest to throw an error instead?

**Comment by petyosi** [comment]
Setting the totalCount to the correct number (say, 1000) means that you will get called with 0-999. The component takes care of rendering only the items in the specified range.

**Comment by davide-igdb** [comment]
Yes, I would have expected as much. I will proceed with a throw error as there is a chance that `value` is undefined. Not necessarily for totalCount being wrong, but items being undefined.

In anycase thanks. I appreciated the thread.
