### ISSUE TITLE
React Virtuoso Grid

### ISSUE THREAD

**Issue by kobe-14** [petyosi/react-virtuoso#523]
How do I get the iterator value,

`itemContent={(index, data) => {
       // here data is undefined
 }}`

**Comment by petyosi** [comment]
`data` is not supported for the grid component. Feel free to submit a PR or sponsor the development of this feature.

**Comment by IvanCoronado** [comment]
Simple workaround 

```
totalCount={data.length}
itemContent={(index) => <>{data[index]}</>}
```
