### ISSUE TITLE
List with window scroll does not calculate its height correctly, causing content below to jump when scrolling

### ISSUE THREAD

**Issue by sergsavoniuk** [petyosi/react-virtuoso#524]
**Describe the bug**
I'm using the Virtuoso component to create a virtualized list. On the page, I have a link that navigates users to a certain section of the page. When a user clicks on this link and then starts scrolling up -> the list starts jumping and scrolling behavior is not good.

**Reproduction**
[Sandbox](https://codesandbox.io/s/zen-wildflower-i2fce?file=/src/App.js)

**To Reproduce**
1. Go to [sandbox](https://codesandbox.io/s/zen-wildflower-i2fce?file=/src/App.js)
2. Click on the `Link1` -> the page should scroll to the paragraph with the id `1`
3. Start slowly scrolling up
4. The menu list starts jumping and text may appear behind a menu item card

**Screenshots**
video
https://user-images.githubusercontent.com/21188996/145822314-291b220a-21b1-4164-9676-48cfb75a428f.mp4

image
<img width="1789" alt="Screenshot 2021-12-13 at 08 34 43" src="https://user-images.githubusercontent.com/21188996/145822192-2aa92072-a3a2-4f12-907b-5558cf309ae2.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [chrome]

**Comment by petyosi** [comment]
Thanks for the report. I see why this happens and it's a legit bug, but it might be quite hard to address. As the user scrolls up, new items get loaded and the list height gets recalculated, displacing the wall of text below.

**Comment by TejaswiniKale20** [comment]
Thank in advance!

Even I am facing the same issue while scrolling the list.
At my end page flickers with forward scroll also.


Below is my code:
**Usage:** 

const onRangeChanged = (range: Object) => {
  rangeRef.current = range;
  if (process.env.NODE_ENV !== 'production') {
    console.log('DashboardVirtuoso onRangeChanged', range);
  }
};

const onItemSize = (
  el: HTMLElement,
  field: 'offsetHeight' | 'offsetWidth'
) => {
  const itemType = el.children[0]?.getAttribute('data-item-type');
  const itemHeight = el[field];
  const minHeight = getItemMinHeight(itemType);

  if (process.env.NODE_ENV !== 'production') {
    console.log(
      'DashboardVirtuoso onItemSize: ' +
        itemType +
        ' ' +
        field +
        '=' +
        itemHeight +
        ' minHeight=' +
        minHeight
    );
  }

  return itemHeight > minHeight ? itemHeight : minHeight;
};


<Virtuoso
  overscan={{ main: 500, reverse: 500 }}
  ref={virtuosoRef}
  useWindowScroll={true}
  components={{
    Header: () => {
      let vaCard = <></>;
      if (userData.va_user_id && userData.va_user_id > 0) {
        vaCard = (
          <Box mb={2}>
            <VirtualAssistantCard />
          </Box>
        );
      }
      return <>{vaCard}</>;
    },
    List: React.forwardRef(({ style, children }, listRef) => {
      return (
        <List
          id="dynamicList"
          component="div"
          ref={listRef}
          style={{ padding: 0, ...style, margin: 0, maxHeight: '100%' }}
          className={classes.listComponent}
        >
          {children}
        </List>
      );
    }),
    Item: ({ children, ...props }) => {
      return (
        <ListItem
          className={`listItem ${classes.dashboardCard}`}
          alignItems="flex-start"
          component="div"
          disableGutters={true}
          {...props}
        >
          {children}
        </ListItem>
      );
    },
    Footer: () => {
      return moreItemsAvailable.current ? (
        <VisibilitySensor
          onChange={handleFooterVisibilityChange}
          partialVisibility={true}
          offset={{
            bottom: -(document.documentElement.clientHeight * 2),
          }}
        >
          <Box py={8} px={20}>
            <LinearProgress color="secondary" />
          </Box>
        </VisibilitySensor>
      ) : (
        <></>
      );
    },
  }}
  data={items}
  itemContent={(index: number, item: any) => (
    /*Actual cards are added here*/
    <DashboardCard
      key={index}
      itemData={item}
      isMobile={isMobile}
      updateDashboardCard={updateItemsCardData}
    />
  )}
  style={{ height: '100%' }}
  rangeChanged={onRangeChanged}
  itemSize={onItemSize}
  increaseViewportBy={{bottom: 600, top: 800}}
/>


Please let me know if I am making any mistakes.

**Comment by TejaswiniKale20** [comment]
Also whenever flicker issue occurs, margin-top gets added automatically to list component, which results in blank patch at top.
