### ISSUE TITLE
[BUG] Not working with iOS versions below v13.4

### ISSUE THREAD

**Issue by arnaskro** [petyosi/react-virtuoso#526]
**Describe the bug**
React-virtuso does not seem to work in iOS versions >= 13.3. And there are no errors in console.
But it works with versions above v13.4.

**Reproduction**
https://1xdrf.csb.app/
https://codesandbox.io/s/agitated-williams-1xdrf?file=/src/App.js
https://virtuoso.dev/

**To Reproduce**
1. Get a device with iOS >= v13.3
2. Open the [sandbox link](https://1xdrf.csb.app/) or the [official website](https://virtuoso.dev/)
3. See that the list is not rendered and there are no errors.

**Expected behavior**
Would be nice if it works with v10 and above.

**Screenshots**

Device | iOS | Screenshot | Status
:--- | :--- | :--- | :---
iPhone 11 Pro Max | v13.3 | [Screenshot](https://user-images.githubusercontent.com/8274735/146019738-c19eb0f6-86e9-4339-86ec-4fd8cbcf019e.png) | ❌
iPhone 8 | v11.4 | [Screenshot](https://user-images.githubusercontent.com/8274735/146019744-03bada5a-5c25-49f5-af24-a6c688082866.png) | ❌
iPhone 11 Pro Max | v13.3 | [Screenshot](https://user-images.githubusercontent.com/8274735/146021111-c8031838-3f24-4d70-8d41-4c9c20c1e455.png) | ❌
iPhone 8 | v13.3 | [Screenshot](https://user-images.githubusercontent.com/8274735/146021121-40c0623f-2ac5-4e0d-a613-7f4db9723d19.png) | ❌
iPhone 13 Pro | v15 | [Screenshot](https://user-images.githubusercontent.com/8274735/146019731-9b2e1913-a85a-4586-bb07-e4fa4e8defb1.png) | ✅  just an example that it works with other versions

**Desktop (please complete the following information):**
 - iPhone 8/XS/11/11 Pro Max - iOS 13.3 - Safari/Chrome
 - iPhone 7 - iOS 10/12 - Safari/Chrome
 - iOS >= v13.3

**Comment by petyosi** [comment]
You need to polyfill the ResizeObserver: https://caniuse.com/resizeobserver.

**Comment by iplus26** [comment]
> You need to polyfill the ResizeObserver: https://caniuse.com/resizeobserver.

You should list this requirements in `Browser Support` section
