### ISSUE TITLE
[BUG] scrollIntoView with keyboard behaves erratically in grouped lists

### ISSUE THREAD

**Issue by mitchchn** [petyosi/react-virtuoso#528]
**Describe the bug**

Set up keyboard nav as described here: https://virtuoso.dev/keyboard-navigation/, but with a `GroupdVirtuoso`.

Arrow key navigation works until you hit the top or bottom of the visible list:

1. When reaching the bottom, the list sometimes skips a few places or scrolls without bring the item into view
2. When reaching the top, the list scrolls up a bit, but not enough to see the selected item.

**Comment by petyosi** [comment]
Can you create a sandbox to show that?
