### ISSUE TITLE
[BUG] Page becomes blank after upgrading to 2.3.3

### ISSUE THREAD

**Issue by yhuang1211** [petyosi/react-virtuoso#529]
Describe the bug

I have a reversed-scroll chat room implemented with react-virtuoso.  It was working well on v2.3.1.  However I updated to v2.3.3 today and it became a blank page.  It also kept calling startReached to load older messages until the oldest message was loaded.

**Comment by petyosi** [comment]
I need a reproduction for this to help. Please use a sandbox

**Comment by yhuang1211** [comment]
It seems if useWindowScroll is true the cells won't be rendered after the first page.  That's why we saw an empty page since we were using reverse-scroll.

https://codesandbox.io/s/crazy-breeze-j4ejg?file=/src/App.js

**Comment by Yuniac** [comment]
If anyone is facing this, the only solution I found was to not use `useWindowScroll`
