### ISSUE TITLE
[BUG] Passing undefined to the computeItemKey prop causes the component to crash.

### ISSUE THREAD

**Issue by cbadger85** [petyosi/react-virtuoso#532]
**Describe the bug**
When passing undefined to the `computeItemKey` prop, the component crashes with a `TypeError: x is not a function`.

**Reproduction**
https://codesandbox.io/s/new-wood-yp7yp?file=/src/App.js

**To Reproduce**
1. Pass undefined to the `computeItemKey` prop.

**Expected behavior**
When passing undefined to the `computeItemKey` prop, an `undefined` value should be ignored because `computeItemKey` is an optional prop.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome, Safari, Firefox

**Comment by petyosi** [comment]
Why do you pass `undefined`? if the item is undefined, just don't pass it. Going down that route, the component should start defending against values like [], empty functions etc.

**Comment by cbadger85** [comment]
For my use case, I'm creating a wrapper component and `computeItemKey` is a pass-through prop. Here's an example https://codesandbox.io/s/mystifying-snowflake-fd1rr?file=/src/App.js.

I understand that an object missing a key is not the same as an object with that key set to `undefined`. However, it's been common practice in most libraries I've worked with that they work the same. The typescript compiler didn't even support it until last year, and even then you have to turn the flag on. (https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#exact-optional-property-types).

**Comment by petyosi** [comment]
I understand the merits of such a design. However, it can certainly increase the complexity (and the size of the library) by trying to predict the intent of the user. Fixing that on a wrapper level is much better - and there are multiple ways to do so - [check this](https://codesandbox.io/s/nervous-frog-hw55x?file=/src/App.js).

**Comment by cbadger85** [comment]
Thanks, I found a similar workaround by doing:

```
const computeItemKeyProps = computeItemKey ? { computeItemKey } : { };

return <Virtuoso {...computeItemKeyProps} />
```
By doing it this way, I can ensure only the props I want are passed to the `Virtuoso` component. This can get cumbersome to do for every optional prop I want to pass down though.

I would argue that neither the complexity nor the size would be significantly impacted by the change. You could simply filter the props to remove any key with an undefined value. Something like this:

```
const filteredProps =Object.fromEntries(Object.entries(props).filter([key, value]) => value !== undefined));
```

I feel that treating missing props and undefined props as the same thing would be a small improvement to the already great developer experience of this library. I can make a PR for it if you like?

**Comment by petyosi** [comment]
You can give it a try. This is actually [happening here](https://github.com/virtuoso-dev/urx/blob/master/packages/react-urx/src/index.ts#L199-L219).
