### ISSUE TITLE
[BUG] When trying to render list with Material UI Table it only render half of the list after upgrading to v2.4.0 it worked fine with v2.3.1

### ISSUE THREAD

**Issue by calvin44** [petyosi/react-virtuoso#533]
**Describe the bug**
The list is rendered only half, the other half is empty 

**Reproduction**
https://codesandbox.io/s/react-virtuoso-test-huvxl?file=/src/App.js

**To Reproduce**
click add item button to add more items to the list
the full list is not rendered 

**Expected behavior**
It should be rendered normally till the end

**Screenshots**
![image](https://user-images.githubusercontent.com/39986974/148323852-35608029-a8d1-4538-bb6f-99a0bd7cb248.png)

**Additional context**
It worked fine in v2.3.1

**Comment by jhg023** [comment]
I'm experiencing this issue and was forced to downgrade to v2.3.1 as well.

**Comment by petyosi** [comment]
Hey, 

The setup has worked accidentally so far. It's not something that the library is designed to support at the moment. In fact, React itself gives you a very descriptive error about invalid markup. [Cleaning up the tables yields a working example](https://codesandbox.io/s/react-virtuoso-test-forked-k7cth?file=/src/App.js).

I'm going to close this issue. If you feel like supporting tables is something you want to contribute towards or sponsor, contact me.

**Comment by calvin44** [comment]
thank you for your answer, but can I know the reason why it worked fine in v2.3.1?

**Comment by petyosi** [comment]
It worked because of an insufficient `scrollTop` tracking logic that did not take into account list resizing.

**Comment by petyosi** [comment]
@calvin44 @jhg023 2.5.0 includes a proper table support - https://virtuoso.dev/hello-table/
