### ISSUE TITLE
[BUG] Regression - Reverse scrolling with initialTopMostItemIndex={itemsLength} is jumping around when using various height items 

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#538]
Hi petyosi,

**Describe the bug**
When initializing a list at the bottom, initial scroll up is jumping around as unknown items are being calculated.  This is affecting a chat box where I can't control the height of the items that will be rendered.

This bug (if its the same) has been fixed in the past. 
 See   https://github.com/petyosi/react-virtuoso/issues/276   and   https://github.com/petyosi/react-virtuoso/issues/278

**Reproduction**
https://codesandbox.io/s/virtuoso-reverse-scrolling-2-4-0-7eupw

**To Reproduce**
Scroll up to see the list jump around when processing larger items.

**Expected behavior**
Smooth scrolling.

**Desktop (please complete the following information):**
 - Windows 10 Edge/Vivaldi
 - Ubuntu 20.04 Firefox/Opera

**Additional context**
Running the same example in 1.11.1 seems much smoother (although not perfect as you sometimes feel a small jump).

https://codesandbox.io/s/virtuoso-reverse-scrolling-1-11-1-0oyw6

I'm not sure which version in between introduced the bug tho.

Thx

**Comment by petyosi** [comment]
Got it. It breaks for items taller than the viewport. Will invstigates.

**Comment by Ethorsen** [comment]
Amazing work like usual :)   Cheers
