### ISSUE TITLE
Cannot scroll very large lists all the way down when item styling affects height

### ISSUE THREAD

**Issue by mfarhadpur** [petyosi/react-virtuoso#54]
I was just playing with the Virtuoso component, and noticed for lists with very large number of items, you can't scroll all the way down if list items have styling that affects their height. You can verify this with a list of 1,000,000 items with some vertical padding or a larger font size set on the items. Not a deal breaker as it's unlikely this happens in practice, but was wondering what the underlying issue is.

**Comment by petyosi** [comment]
Can you reproduce that by forking one of the [site examples](https://virtuoso.dev/)? One thing which comes to mind is the maximum element height in the DOM (varies across browsers, but as far as I remember it was around 10M pixels in Chrome).

**Comment by mfarhadpur** [comment]
Sorry for not providing an example. [**Here**](https://stackblitz.com/edit/react-ajgjuz?file=example.js)'s a fork of the "100 000 Items" example, but with 500 000 items. I can only scroll down to item 453 431 on Chrome, 20 734 on Edge, and 9 on Firefox! So, it is probably the limitation you mentioned.

**Comment by petyosi** [comment]
I can confirm that the maximum element height is the limitation here - there are somewhat complex and unpleasant (from UX perspective) workarounds that can be applied - I will consider this further.

**Comment by petyosi** [comment]
This should work with v0.15.0
