### ISSUE TITLE
[BUG] Custom Scroller no longer works after upgrading to v2.3.2, main demo site example also appears broken

### ISSUE THREAD

**Issue by maxhelsel** [petyosi/react-virtuoso#541]
**Describe the bug**
List renders first page of items but fails to load more. See the example on virtuoso.dev site, [here](https://virtuoso.dev/custom-scroll-container/#list-with-custom-scroller)

**Desktop (please complete the following information):**
MacBook Pro (13-inch, M1, 2020)
MacOS Monterey 12.0.1
Chrome v97

Had to roll back my version to 2.3.1 to get it working again. Any idea what's going on?
Below is my implementation of custom scrollbars that work < v2.3.1.

```
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';

const CustomScrollbars = React.forwardRef(({ children, style, ...props }, ref) => {

  const refSetter = useCallback((scrollbarsRef) => {
    if (scrollbarsRef) {
      ref.current = scrollbarsRef.osInstance().getElements().viewport;
    }
  }, [ref]);
  
  return (
    <OverlayScrollbarsComponent
      ref={refSetter}
      options={{ overflowBehavior: { x: 'hidden' } }}
      style={style}
      {...props}
    >
      {children}
    </OverlayScrollbarsComponent>
  );
});
```

**Comment by petyosi** [comment]
Hm, this is indeed a regression for this scenario, but it's an easy update - the scroller needs to accept all props passed.

**Comment by maxhelsel** [comment]
Yes, before I opened this issue I did manage to get the example working by passing {...props} like you did - however, it seems to only be half a fix when using an outside component as the custom scroller, like OverlayScrollbars (which worked prior to 2.3.2).

It looks like it's not updating the padding inside the scroll container. I put together a quick sandbox to show further:

[https://codesandbox.io/s/virtuoso-custom-scroll-broken-2-3-2-zw1rw?file=/src/App.js](https://codesandbox.io/s/virtuoso-custom-scroll-broken-2-3-2-zw1rw?file=/src/App.js)

First button is OverlayScrollbars, second is the example from the site (which works and includes passing all props discussed above)

**Comment by petyosi** [comment]
Looking at the generated markup, the overlay scrollbars don't set the `data-virtuoso-scroller` attribute to the right element. 

To clarify the reason for the breaking change: it turned out that listening to `onScroll` does not track the resizing of the element causing changes to `scrollTop` - so 2.3.2 fixes that, using the data attribute in question.

**Comment by maxhelsel** [comment]
Yes, that's it. For anyone who stumbles upon this in the future, here's what I did to fix the OverlayScrollbars component to get it working > v2.3.2 again.

Here's the props that need to be injected post v2.3.2:

```
data-test-id="virtuoso-scroller"
data-virtuoso-scroller="true"
tabindex="0"
```

However, simply passing {...props} into the OverlayScrollbarsComponent does not work, as they end up injecting into the wrapper - not the internal scroll container itself. To fix, I looped the props passed from Virtuoso and injected them into the scroll element.

```
const CustomScrollbars = React.forwardRef(({ style, children, ...props }, ref) => {

  const refSetter = useCallback((scrollbarsRef) => {
    if (scrollbarsRef) {
      let customViewport = scrollbarsRef.osInstance().getElements().viewport;
      for (const key in props) {
        if (!props.hasOwnProperty(key)) {
          continue;
        }
        customViewport.setAttribute(key, props[key])
      }
      ref.current = customViewport;
    }
  }, [ref]);

  return (
    <OverlayScrollbarsComponent
      ref={refSetter}
      style={{ ...style }}
    >
      {children}
    </OverlayScrollbarsComponent>
  );
});
```
The above props get passed as attributes into the scroll container using the described method.

**Comment by paulm17** [comment]
@maxhelsel what version of OverlayScrollbars are you using?

I found a working sandbox running legacy versions: 

> https://codesandbox.io/s/react-virtuoso-custom-scrollbar-forked-k5omlm?file=/src/App.js:172-189

However, when I upgrade to the latest everything breaks.

If you are running the latest, mind sharing how you got this all to work?  Thanks

**Comment by maxhelsel** [comment]
@paulm17 I am currently in the process of refactoring my project to NextJs and **have not updated underlying dependencies in a while**; but I'll share the full code from the above example.

```
import React, { useRef, useCallback } from 'react';
import { Virtuoso } from 'react-virtuoso';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';
import NotificationItem from './NotificationItem.js';

const CustomScrollbars = React.forwardRef(({ style, children, ...props }, ref) => {
  const refSetter = useCallback((scrollbarsRef) => {
    if (scrollbarsRef) {
      let customViewport = scrollbarsRef.osInstance().getElements().viewport;
      for (const key in props) {
        if (!props.hasOwnProperty(key)) {
          continue;
        }
        customViewport.setAttribute(key, props[key])
      }
      ref.current = customViewport;
    }
    // eslint-disable-next-line
  }, [ref]);

  return (
    <OverlayScrollbarsComponent
      ref={refSetter}
      style={{ ...style }}
    >
      {children}
    </OverlayScrollbarsComponent>
  );
});

const ListNotifications = props => {

  const {
    items,
    handleMore
  } = props;

  const vRef = useRef(null);

  const row = useCallback((index, item) => {
    return (
      <NotificationItem
         key={index}
         notificationId={item}
      />
    )
    // eslint-disable-next-line
  }, [items]);

  return (
    <Virtuoso
      ref={vRef}
      data={items}
      endReached={handleMore}
      itemContent={row}
      components={{
        Scroller: CustomScrollbars
      }}
    />
  )
}

export default ListNotifications;

```
If that doesn't really help, try walking the example back using older versions and find the one that breaks. Then cross reference release notes to see where the issues might lie.

If you're having trouble with current packages, then I imagine I will too in the near future, so any solutions you figure out would be appreciated. Good luck

**Comment by paulm17** [comment]
@maxhelsel Thanks so much for following up.  Appreciate it.  I too am running nextjs and my code is similar to yours (exactly as the sandbox).

I have noticed that if I update either dependencies

> overlayscrollbars-react to 0.4.0 - it breaks
> overlayscrollbarsto 2.0.0-beta.0 - it breaks

For now I'm content with running an older version.  Once I finish the project I'm working on, then I'll circle back and try to work out why later versions break.

**Comment by maxhelsel** [comment]
@paulm17 Sure enough, once I got this and started updating and refactoring, I ran into trouble just like you. After spending a couple hours working through it, it seems Virtuoso is not to blame, but rather **OverlayScrollbars package > v2.0**.

That 2.0 update changed the rendering/lifecycle as well as the syntax. So **once you update to 2.0, the VIEWPORT element that we attach the ref to is unavailable in the callback** (see example above)

I started to get it working halfway, but there were too many issues so I reverted to the following versions:
```
package.json

"overlayscrollbars": "^1.13.3",
"overlayscrollbars-react": "^0.3.0",
"react-virtuoso": "^4.0.3"
```

At least this way, you can use Virtuoso@latest and just revert OverlayScrollbars to v1. Remember to revert both OverlayScrollbars packages to compatible versions since they're paired (above works).

**Comment by paulm17** [comment]
@maxhelsel many thanks for the follow up and explanation.  Also for the confirmation of versions.  I had settled on those packages (overlayscrollbars) as well so for you to confirm it helps.

**Comment by jkhaui** [comment]
It was painful, but I think I finally found a way to reliably wire up the latest versions of `react-virtuoso` and `overlayscrollbars-react`. Below is my custom Scroller component implementation:

```
const Scroller: Components['Scroller'] = React.forwardRef(({ style, children, ...rest }, ref) => {
    const [initialize, instance] = useOverlayScrollbars({
        // Just an example of providing custom options; they're not necessary to get
        // `overlayscrollbars-react` working with `react-virtuoso`
        options: {
            showNativeOverlaidScrollbars: false,
            overflow: {
                x: 'hidden'
            },
            scrollbars: {
                theme: 'os-theme-dark',
                clickScroll: true,
                visibility: 'visible'
            }
        }
    });

    React.useEffect(() => {
        initialize({
            target: ref.current,
            elements: {
                viewport:ref.current
            }
        }, {})
    }, [initialize]);

    const refSetter = React.useCallback(
        (node) => {
            if (node) {
                ref.current = node
            }
        },
        [ref]
    );

    return (
        <SomeThirdPartyWrapperComponent
            thirdPartyComponentProps={{
                abc: 123
            }}
        >
            <div
                ref={refSetter}
                style={style}
                {...rest}
            >
                {children}
            </div>
        </SomeThirdPartyWrapperComponent>
    )
})

```

My understanding is thar other approaches to integrating these two libraries together break because `overlayscrollbars-react` inserts some DOM resize observer html node as the 1st child of the virtuoso-scroller div element.

The only way to solve this is to completely change the way the markup is rendered, as suggested by the creator of the overlayscrollbars package here: https://github.com/KingSora/OverlayScrollbars/issues/521#issuecomment-1639059283

**Comment by resthedev** [comment]
> const Scroller: Components['Scroller'] = React.forwardRef(({ style, children, ...rest }, ref) => {
>     const [initialize, instance] = useOverlayScrollbars({
>         // Just an example of providing custom options; they're not necessary to get
>         // `overlayscrollbars-react` working with `react-virtuoso`
>         options: {
>             showNativeOverlaidScrollbars: false,
>             overflow: {
>                 x: 'hidden'
>             },
>             scrollbars: {
>                 theme: 'os-theme-dark',
>                 clickScroll: true,
>                 visibility: 'visible'
>             }
>         }
>     });
> 
>     React.useEffect(() => {
>         initialize({
>             target: ref.current,
>             elements: {
>                 viewport:ref.current
>             }
>         }, {})
>     }, [initialize]);
> 
>     const refSetter = React.useCallback(
>         (node) => {
>             if (node) {
>                 ref.current = node
>             }
>         },
>         [ref]
>     );
> 
>     return (
>         <SomeThirdPartyWrapperComponent
>             thirdPartyComponentProps={{
>                 abc: 123
>             }}
>         >
>             <div
>                 ref={refSetter}
>                 style={style}
>                 {...rest}
>             >
>                 {children}
>             </div>
>         </SomeThirdPartyWrapperComponent>
>     )
> })

Hey thanks for trying to work on this. Just me or the scrollbar stutters a lot while you are scrolling with this implementation?

**Comment by verbart** [comment]
> > const Scroller: Components['Scroller'] = React.forwardRef(({ style, children, ...rest }, ref) => {
> > const [initialize, instance] = useOverlayScrollbars({
> > // Just an example of providing custom options; they're not necessary to get
> > // `overlayscrollbars-react` working with `react-virtuoso`
> > options: {
> > showNativeOverlaidScrollbars: false,
> > overflow: {
> > x: 'hidden'
> > },
> > scrollbars: {
> > theme: 'os-theme-dark',
> > clickScroll: true,
> > visibility: 'visible'
> > }
> > }
> > });
> > ```
> > React.useEffect(() => {
> >     initialize({
> >         target: ref.current,
> >         elements: {
> >             viewport:ref.current
> >         }
> >     }, {})
> > }, [initialize]);
> > 
> > const refSetter = React.useCallback(
> >     (node) => {
> >         if (node) {
> >             ref.current = node
> >         }
> >     },
> >     [ref]
> > );
> > 
> > return (
> >     <SomeThirdPartyWrapperComponent
> >         thirdPartyComponentProps={{
> >             abc: 123
> >         }}
> >     >
> >         <div
> >             ref={refSetter}
> >             style={style}
> >             {...rest}
> >         >
> >             {children}
> >         </div>
> >     </SomeThirdPartyWrapperComponent>
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > })
> 
> Hey thanks for trying to work on this. Just me or the scrollbar stutters a lot while you are scrolling with this implementation?

Same for me: scrollbar stutters a lot while you are scrolling
