### ISSUE TITLE
[BUG] Console error when passing undefined initialItemCount prop

### ISSUE THREAD

**Issue by jCobbSK** [petyosi/react-virtuoso#547]
**Describe the bug**
When we pass the prop `initialItemCount={undefined}` into `<Virtuoso />` component. After initial render we get console error
```
Warning: `NaN` is an invalid value for the `paddingBottom` css style property
```
When we omit prop the error is not present.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-increasing-size-items-forked-3vhyx?file=/src/VirtualList.tsx

**To Reproduce**
Open the sandbox and look at the console logs.

**Expected behavior**
There shouldn't be difference between passing prop with `undefined` value and not passing the prop at all.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Additional context**
It seems this does not have any sideffects in behaviour, just polluting the logs.

**Comment by petyosi** [comment]
Why do you pass `undefined` and not `0` (or, omit the property)?
