### ISSUE TITLE
Is there a way to customize the rendering only of the current sticky group header element?

### ISSUE THREAD

**Issue by elena-gancheva** [petyosi/react-virtuoso#548]
Hi,

Is there a way to provide a custom rendering only for the "stuck" (`position: sticky`) group header element in GroupedVirtuoso?

**Comment by petyosi** [comment]
The short answer is no, you can't change the rendering of the *current* sticky header. All group headers have the same rendering, regardless of their position in the list. 

You can change the rendering of *every* group header with `Components.Group` - https://virtuoso.dev/customize-structure/. 

You can also alter the looks of the current sticky header with CSS, but I haven't tried that, and it might cause some unexpected behavior.
