### ISSUE TITLE
TScrollContainer type missing children props

### ISSUE THREAD

**Issue by iJimmyWei** [petyosi/react-virtuoso#55]
**VirtuosoScroller.tsx**
```
export declare type TScrollContainer = FC<{
    style: CSSProperties;
    className?: string;
    reportScrollTop: (scrollTop: number) => void;
    scrollTo: (callback: (scrollTop: number) => void) => void;
}>;
```
In VirtuosoScroller types is currently missing a `children` prop type, without this prop typescript will not allow you to pass in children to your custom scroll component.

An example of passing children down is shown here https://virtuoso.dev/custom-scroll-container/ but the given example uses merely javascript so typescript errors won't show here.

**Comment by petyosi** [comment]
I might be wrong here, but TScrollContainer takes children from the [FC interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L771).

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L515

**Comment by iJimmyWei** [comment]
Ah yea, I found the issue. So using the example given as is without declaring `children` as optional causes an error in typescript 

```
private MyScrollContainer = ({
        // className,
        // style,
        // reportScrollTop,
        // scrollTo,
        children,
 }: {
          children?: ReactNode,
      }) => {
        return (<div>{children}</div>)
      }     
```

However I would of expected `children` to be non optional, because of the way it's used and that `item` is non optional in this case, meaning that children would always be non optional too here.
