### ISSUE TITLE
[BUG] List items' height is calculated incorrectly on first load prior to the initial scrolling

### ISSUE THREAD

**Issue by FOfficial** [petyosi/react-virtuoso#550]
**Describe the bug**
I have used Virtuoso within my dropdown component and nothing has changed in my own code since the previous version of Virtuoso, however because of some API changes in the new Virtuoso I had to tweak a few minor things here and there that is fixed and works fine.

However the Virtuoso for some reason can't compute the correct menu items height on first-load, and it miscalculates my menu items as 20.25px as opposed to 36px, now once scrolling is initiated for the first time it recalculates them fine, however it leaves a massive padding in the bottom section of the menu items and it only renders up to index 17 whereas there is 25 of them, so somehow it skips the last 10 records and I believe that's got to do with the initial miscalculation of the first 10-11 items.

Now I was wondering if I'm missing something here or I'm doing something wrong that's causing this miscalculation for the first round!

Please see both screenshots linked below.

**Screenshots**

![on first load](https://raw.githubusercontent.com/FOfficial/public/dev/fhl/virtuoso-issue.png)

![on scroll](https://raw.githubusercontent.com/FOfficial/public/dev/fhl/virtuoso-issue-on-scroll.png)

Thanks

**Comment by petyosi** [comment]
Can't say for sure. Can you reproduce the problem in codesandbox? It would also help if you can compare with the version you upgraded from. 

I will re-open the issue once a reproduction is there.
