### ISSUE TITLE
[BUG] Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by omidtajik** [petyosi/react-virtuoso#553]
**Describe the bug**
When using TableVirtuoso component there is the unique key warning of react in console.

**Reproduction**
There is also in the sandbox demo of doc:
https://codesandbox.io/s/zv5ct

**Comment by petyosi** [comment]
Did you add keys to the cells?

**Comment by petyosi** [comment]
My mistake - this one is in the component code.
