### ISSUE TITLE
Scroll to bottom when data changes, but count happens to be the same

### ISSUE THREAD

**Issue by tsmarin** [petyosi/react-virtuoso#555]
Thanks for an awesome library! 

Running into an edge case when dealing with multiple lists, and trying to scroll to the bottom when switching to a different list.

**Describe the bug**
When the data changes, but the count of items is the same, there isn't a great way to scroll to the bottom of the new data. `followOutput` generally accomplishes this, but only gets called if the count changes. 

**Reproduction**
https://codesandbox.io/s/wonderful-darwin-nch9b

**Expected behavior**
Would love a reliable way to scroll to the bottom when the data changes - e.g. an 'onDataChanged' hook, as opposed to relying on the count changing. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by petyosi** [comment]
If you're replacing the data of the list, you can:

- Set initialTopmostItemIndex
- Set a distinct key property to cause a list reinit.

I've recommended that at other issues. If you're swapping data, there's no point in preserving the previous component.

**Comment by tsmarin** [comment]
Aha, makes sense! Thanks for such a quick response!
