### ISSUE TITLE
[BUG] VirtuosoGrid Flicker issue 

### ISSUE THREAD

**Issue by JudeTejada** [petyosi/react-virtuoso#560]
**Describe the bug**
I'm currently Using VirtuosoGrid on a project and I've been debugging for quite a while I notice on screen size such as desktop when I'm at the bottom of the list it and slowly starts to scroll up it  causes to flicker and items are being rearranged 

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-r9py9?file=/App.js

**To Reproduce**
Start  at a screen size of 1051px  on the code sandbox I had reproduced
scroll to the bottom and  slowly scroll up

**Expected behavior**
When slowly scrolling up  as an item being added to its original position it causes it to rearrange 

**Desktop (please complete the following information):**
 - OS: 
 - Chrome,firefox

**Comment by petyosi** [comment]
@JudeTejada please read the docs before opening the issue. Margins are not supported.
