### ISSUE TITLE
React-Virtuoso not working properly in Component with ShouldComponentUpdate implemented

### ISSUE THREAD

**Issue by ingenious-hans** [petyosi/react-virtuoso#563]
I am using Reac-Virtuoso. It was working nice and works nice only when React shouldComponentUpdate return true, otherwise it only render once then not render other items when scrolling

I am making this to prevent my app from unnecessary rendering, for example when some props don't change values

**Comment by petyosi** [comment]
Please follow the issue template I have created. I can't guess your setup.
