### ISSUE TITLE
Problem rendering list with useWindowScroll

### ISSUE THREAD

**Issue by PedroJBrito** [petyosi/react-virtuoso#565]
Hi,

I'm facing a problem when a display a virtuoso list using useWindowScroll, but whose scroll came from the nearest container and not from the top level container. 

I've reproduced a scenario similar to mine, basically we have a layout with some fixed components (Aside, top menu), and then we have the main container where pages are loaded. The page has some content before the virtuoso which makes it outside view initially. When we scroll down the list is only updated if we make some update on the page (I have introduced a button in this case to reproduce the update function). 

Link for codesandbox (https://codesandbox.io/s/green-currying-dun8t?file=/src/App.js)

Could you help me try to fixed this.
Thank you in advance for your answer.

**Comment by petyosi** [comment]
Hey, 

This seems like a case for `customScrollParent` - [check the update](https://codesandbox.io/s/new-leaf-cn0qh?file=/src/App.js).
