### ISSUE TITLE
[BUG] Components in view get unmounted & remounted, performance impact

### ISSUE THREAD

**Issue by russtuck91** [petyosi/react-virtuoso#566]
**Describe the bug**
There's an issue where the components in view are unmounted and remounted needlessly after any state update. The issue is only present when using custom components via the `components` prop.

This unmounting & remounting is not only bad for subcomponents that load asynchronous content like in my example below, but it's also bad for performance. The unmounting & remounting takes longer than updating a component which is already mounted.

**Reproduction**
In the following sandbox, I've created a table with expandable rows to show the issue:
https://codesandbox.io/s/virtuoso-mui-expandrows-remounting-8izsu?file=/App.js

- Each of the expandable rows is pretending to load some asynchronous content on mount, using a `setInterval()` call to act like asynchronous fetching. When the user clicks a button to expand a row, the pseudo-asynchronous content is loaded. 
- However, if you already have 1 row expanded and click to expand a 2nd row, you'll notice that **BOTH** expandable rows return to the "LOADING" state. This is because all the components in view are being unmounted and remounted brand new.
- Also, if you click the button at the top of the page, it will update a state variable that is not used by the TableVirtuoso at all. Yet, clicking the button causes all components in view to unmount & remount again.
- Finally, if you open the console, any time you click to expand a row or click the button at the top, you can see console log statements showing that all the components in view have been unmounted & remounted again.

The following sandbox demonstrates that the issue is not present if you do NOT customize components via the `components` prop:
https://codesandbox.io/s/virtuoso-basic-table-expandrows-staysmounted-q8d29?file=/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/virtuoso-mui-expandrows-remounting-8izsu?file=/App.js
2. Click the "EXPAND" button in the 1st visible row
3. Observe that it moves through the "LOADING" state before finishing loading and showing the content
4. Click the "EXPAND" button in the 2nd visible row
5. **See error:** Observe that BOTH expanded rows return to the "LOADING" state
6. Click the button at the top of the page
7. **See error:** Observe that any expanded rows return to the "LOADING" state
8. Open the console and clear all existing console logs
9. Click any "EXPAND" button in any row
10. **See error:** Observe the console log statements indicating that all the components in view have unmounted & remounted

**Expected behavior**
Already mounted components should be updated, instead of being unmounted & remounted.

**Additional context**
I have also tried to make use of the `computeItemKey` prop, but it has no effect on the unmounting & remounting.

Here is another sandbox with a slightly simpler example of components being unmounted & remounted:
https://codesandbox.io/s/virtuoso-mui-remounting-q10ui?file=/App.js
In this example, every row is treated as though it is asynchronously loading content. Clicking the button at the top updates a state variable that is not used by TableVirtuoso at all. Yet, clicking the button causes all components in view to unmount & remount again.

Here is the equivalent example WITHOUT the customized components via the `components` prop, and it works fine:
https://codesandbox.io/s/virtuoso-basic-table-staysmounted-492wp?file=/App.js

**Comment by petyosi** [comment]
That's due to the custom components being defined inline, which means that a new instance is passed with each re-render. [Move the definition out](https://codesandbox.io/s/virtuoso-mui-expandrows-remounting-forked-89dzq?file=/App.js:2274-2308) of the component rendering.

**Comment by russtuck91** [comment]
That did the trick! Thanks so much for your help. 

Also, a big thanks for making such a super useful library! Big kudos 👏
