### ISSUE TITLE
[BUG] Virtuoso doesn't work properly with custom scrollbar

### ISSUE THREAD

**Issue by Bomavi** [petyosi/react-virtuoso#567]
**Describe the bug**
I have tried to setup custom scrollbar from react-virtuoso docs. Custom scrollbar is - `overlayscrollbars-react`. The main problem, Virtuoso does render only first visible range of items and on scroll event it doesn't add any new items, looks like it doesn't listen to scroll event.

**Reproduction**
There is a good [solution](https://codesandbox.io/s/mz4lg?file=/src/CustomScrollbar.js), and it does work with Virtuoso v.2.3.1 and smaller, but with v.2.3.2+ it doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy example from the above
2. Use version of react-virtuoso v.2.3.2+
3. Try to scroll

**Expected behaviour**
Scroll should work as expected. New items should be added on scroll.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome

**Comment by petyosi** [comment]
Is this the same as https://github.com/petyosi/react-virtuoso/issues/564 and #541?
