### ISSUE TITLE
scrollTo not supported in Edge

### ISSUE THREAD

**Issue by NerdCowboy** [petyosi/react-virtuoso#57]
In Edge (pre-Chromium), scroll methods aren't supported that well. 

The example https://virtuoso.dev/scroll-to-index/ doesn't work at all in Edge.

To fix, will need to add a polyfill: 
https://github.com/iamdustan/smoothscroll

**Comment by NerdCowboy** [comment]
Closing. Realized I can implement the polyfill on my end.

Would recommend adding something to the docs though.

**Comment by petyosi** [comment]
@NerdCowboy Which polyfill did you end up using? A sample will help, I will add it to the docs. Thanks!

**Comment by NerdCowboy** [comment]
I used the polyfill in my first post https://github.com/iamdustan/smoothscroll

Here's the code to implement
```
import smoothscroll from 'smoothscroll-polyfill';

// Initialize polyfill
useEffect(() => smoothscroll.polyfill(), [])
```
