### ISSUE TITLE
[Feature Request] Footer for TableVirtuoso

### ISSUE THREAD

**Issue by russtuck91** [petyosi/react-virtuoso#570]
Could we get an option for defining a Footer component within the TableVirtuoso? 

Similar to the Footer that's available on the list, just the same thing for the table
https://virtuoso.dev/footer/

**Comment by petyosi** [comment]
Sure, feel free to submit a PR.

**Comment by jatravis** [comment]
Is anyone working on this? I'd like to work on it if it's available!

**Comment by petyosi** [comment]
Unlikely.

**Comment by russtuck91** [comment]
Go for it! It's been on my to-do list of "nice to have but I'll never get around to it"
