### ISSUE TITLE
Some unexpected behavior on virtualized table

### ISSUE THREAD

**Issue by SaitamaTyler** [petyosi/react-virtuoso#579]
Hi there,

I'm trying to make a virtualized table that has inline editors with TableVirtuoso and MUI table.

You can see actual code and behavior on CodeSandBox below.
One is without TableVirtuoso, and another one is with TableVirtuoso.

Without TableVirtuoso
https://codesandbox.io/s/suspicious-framework-r3qmb?file=/src/App.tsx

With TableVirtuoso
https://codesandbox.io/s/sharp-cache-lluh9?file=/src/App.tsx

I have questions about these.
On the example without TableVirtuoso, the table wouldn't scroll to the top even you click some row to select.
Also, it wouldn't leave focus even you type some text in the text field on the selected row.
But it would so on the example with TableVirtuoso.

Would you give me some advice?

I'm new to React, so feel free to point me out, if I do something wrong.
Thanks in advance.

**Comment by petyosi** [comment]
I think you suffer from component re-mounting. [Check the note here](https://virtuoso.dev/customize-structure/).

I recently updated all examples to use external components and context where necessary.
