### ISSUE TITLE
[BUG] TableVirtuoso component will randomly not render top items when using react-table

### ISSUE THREAD

**Issue by jatravis** [petyosi/react-virtuoso#591]
**Describe the bug**
When scrolling to the top of the table, the component will randomly not render the top items. It seems to only happen when scrolling with my mouse wheel, the actual scroll bar isn't causing an issue.

**Reproduction**
The bug can be reproduced in the code sandbox provided by the documentation
https://codesandbox.io/s/wuj7r

**To Reproduce**
1. Open the code sandbox
2. Scroll down until the top items are no longer being virtualized
3. Scroll back up to the top items
4. May need to repeat 2-3 times, the issue doesn't seem to be consistent

**Expected behavior**
All of the data items provided to the component are rendered.

**Screenshots**
The table component on initial load (data-item 0 is being being rendered):
![image](https://user-images.githubusercontent.com/18353104/155171008-dccdbea9-c2bd-4743-8281-4344ae6f47e3.png)

The table component experiencing the bug:
![image](https://user-images.githubusercontent.com/18353104/155171427-a5011462-fa94-4c4f-b9e2-e500c5df675e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
From what I can tell, this is only an issue with the TableVirtuoso component. I was using the original Virtuoso component for a few days, and never experienced the issue until switching over to TableVirtuoso

**Comment by jatravis** [comment]
@bjoe87 that's what I'm currently doing as well. You also need to increase the top of the view port by a number larger than the top most item in the table. I haven't had a chance to dig into it too much, but I think the issue revolves around how the `paddingTop` is being calculated in the Table component, because the `FillerRow` is still being rendered.

**Comment by maciejregula** [comment]
I can confirm that this also happens in the pure table with a fixed header, not only the react-table.

**Comment by benklenk** [comment]
I am still experiencing this bug on 2.16.5, but in a worse way: Whenever I set topItemsCount, the items "within" it are not rendered at all, leaving a white void with the height of the pinned items that in the DOM is simply a blank <tr/>

**Comment by petyosi** [comment]
@benklenk - you can open a new issue with repro. I will take a look
