### ISSUE TITLE
[BUG] undo prepend(shift from array) cause visible position change

### ISSUE THREAD

**Issue by rhinoc** [petyosi/react-virtuoso#596]
**Describe the bug**
prepending to items using `firstItemIndex` maintain the visible position, but undo prepending cause the visible position change. (items move up because of above items removed)

**Reproduction**
[![Edit sandpack-project (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sandpack-project-forked-n5jzd0?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**
1. go to the sandbox
2. click 'prepend': it's okay.
3. click 'unprepend': visible position change.

**Expected behavior**
click 'unprepend': visible position maintain.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by petyosi** [comment]
At first glance, this seems like a bug. I haven't explored contracting the message list in detail, as the common use case would be to expand it. 

What are you building so that you need to contract the list?

**Comment by rhinoc** [comment]
I need to display a group of items, and the first group is users' collection, below items can be collected or undo collected. so the first group's row count is resizable.

**Comment by danielsantiago** [comment]
I'm having the exact same issue. In my case I have need to add and remove items above the visible position area without any jump.

**Comment by danielsantiago** [comment]
For reference, my use case is that I'm receiving new items and deleted items in a web socket connection. I want to update the list in real time without changing the user scroll position.

**Comment by rhinoc** [comment]
> I'm having the exact same issue. In my case I have need to add and remove items above the visible position area without any jump.

This is a workaround, I use `scrollTo` to adjust scroll position after deleting items. it seems works but I suspect it may cause some flash effect (i.e. items moving up and down) when things got complicated. And it will also be painful if the row height is changeable.
https://codesandbox.io/s/sandpack-project-forked-ikdle3?file=/App.js

**Comment by petyosi** [comment]
Should be fixed in e861fe9acea5b2cbb425b35b2fac75aaff8c0c13

**Comment by alexgleason** [comment]
I'm having a similar problem except the list is not inverse scrolling (there's no `firstItemIndex`). Removing an item from above that's out-of-view causes the list to jump.
