### ISSUE TITLE
Breaks when items are removed (totalCount changed)

### ISSUE THREAD

**Issue by greyivy** [petyosi/react-virtuoso#6]
When totalCount is lowered (e.g. to 1), no items are rendered. Changing the totalCount appears to break the component in other circumstances too. For example, if totalCount is lowered to 0 and then increased again, only the last item is rendered.

**Comment by petyosi** [comment]
Thanks for reporting that. Which version are you using? I published 0.4.0 which addressed some race conditions. 

I did [the following reproduction](https://stackblitz.com/edit/react-f1eher?file=example.js) - The problem I see here is that pressing 0 / 1 does not clear the visible items. Will look into that.

**Comment by petyosi** [comment]
Updated the example above to `0.4.2`, seems to work fine: https://stackblitz.com/edit/react-f1eher-xjkzu1?file=example.js

Let me know if I am missing a case.

**Comment by greyivy** [comment]
Really appreciate you taking a look! Everything's working perfectly now.
