### ISSUE TITLE
rangeChanged - Error on startIndex

### ISSUE THREAD

**Issue by PedroJBrito** [petyosi/react-virtuoso#613]
Hi petyosi.

I'm evaluating the rangeChanged property and while checking your example "Range Change Callback" I saw the same problem I'm facing in my project and it's related with the startIndex. Your example starts with startIndex: 0 and endIndex: 3, however, if we scroll the list to the following position 
![image](https://user-images.githubusercontent.com/94718876/159288213-4005b215-19ae-4ee0-84bc-d097330d4207.png)
the information returned is startIndex: 0 and endIndex: 4. The endIndex is correct but the startIndex should be 1. It only changes to 1 when the element with index 1 is already leaving the viewport, and this is something that seems to occur with all items.

Is this the expected behavior when you implemented this? Is it a bug? Any workaround?

Thank you in advance for your help.

**Comment by petyosi** [comment]
This is the expected behavior - the range matches the elements in the viewport. Not sure why you consider this a bug?

**Comment by PedroJBrito** [comment]
The problem is that it doesn't match because as we can see in the picture we have {startIndex: 0, endIndex: 4} while it should be {startIndex: 1, endIndex: 4} as the startIndex: 0 is already out of the viewport

**Comment by petyosi** [comment]
Got it. Take a look [at this longer explanation](https://github.com/petyosi/react-virtuoso/issues/396#issuecomment-868940055) on why this is so.
