### ISSUE TITLE
[BUG] the code contrast in the documentation for dark mode is hard to read

### ISSUE THREAD

**Issue by codingedgar** [petyosi/react-virtuoso#614]
**Describe the bug**
The code and other items in the documentation are hard to read in dark mode.

**Reproduction**
**To Reproduce**
1. Go to https://virtuoso.dev/
2. Seek any code
3. See how it is hard to read

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10213241/159335051-06ffa50e-efca-41cd-b40a-a0661bc0ad79.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome Version 99.0.4844.74 (Official Build) (x86_64)

**Additional context**
Maybe is just on dark mode

**Comment by petyosi** [comment]
It looks fine on my side? 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/13347/169638658-4ffe3f69-c77c-4f33-a505-19cde3a441c0.png">
