### ISSUE TITLE
Feature request: horizontal list

### ISSUE THREAD

**Issue by NawarA** [petyosi/react-virtuoso#62]
I'm hacking at the library to get it to display a horizontal list. It seems built only for vertical lists. 

Is there any easy way to get it to display the virtualized list horizontally instead of vertically?

**Comment by petyosi** [comment]
Correct - I haven't implemented horizontal mode. I think that the code for the horizontal list will be exactly the same, but the component has to accept configuration to take scrollLeft / offsetWidth (vs scrollTop / offsetHeight) into account. 

All in all, this is a relatively low complexity capability, but it needs tests, docs, etc. If you are interested in contributing, please let me know.

**Comment by lumenlunae** [comment]
@shoNagai Hello! How do you feel about your feature commits so far? 

After trying and implementing react-window, react-virtualized, and react-virtuoso with beautiful-dnd, virtuoso was the one that caused me the least amount of problems but was missing horizontal. 🙏  How far did you get with it? I saw the branch had two commits in it. Thank you!

**Comment by theromis** [comment]
@shoNagai need horizontal scroll as well, have you had a chance to create a PR for your testing changes?

**Comment by seschwartz8** [comment]
Any progress on horizontal scrolling?

**Comment by chazzox** [comment]
any updates?

**Comment by seschwartz8** [comment]
> any updates?

I ended up using [react-window](https://github.com/bvaughn/react-window) instead

**Comment by NawarA** [comment]
This feature request is the main missing feature. 

More people can use the library if horizontal is supported

Please add.

**Comment by petyosi** [comment]
@NawarA - do you want to sponsor the development of the feature? If so, let me know.

**Comment by NawarA** [comment]
@petyosi What do you mean? Are you asking me to pay you to release the feature?

**Comment by wibed** [comment]
@petyosi could you open a gofundme or similar so we can chip in?

**Comment by petyosi** [comment]
@wibed with an attitude like the one in the comment above yours, I have little faith in the success of a such campaign.

**Comment by chazzox** [comment]
Petyosi afaik is not paid to maintain this package, making new features a long endevour. And since he his not making any money your essentially asking him to do work for free. As he has clearly stated, you can sponsor the repo, or make a pr (it is open source after all!). Otherwise the feature (afaik) has no plans of coming any time soon. no shade on the dev, what he's asking for is entirely fair lmao

**Comment by mihir-karbelkar-wiz** [comment]
@chazzox I understand that, however I was deciding between react window and this and found out that horizontal lists are not supported, hence wanted to know if there are plans for this, if not I'll pick up some other library. 


I am in no way forcing petyosi to build something, I just need information whether this is happening or not and on the basis of that I have to make a call for my project.

**Comment by wibed** [comment]
@mihir-karbelkar-wiz its not.

**Comment by mihir-karbelkar-wiz** [comment]
@wibed thanks. Maybe, I'll make try to make a pr for this.

Again, great work on the library @petyosi 🙌, found this to be one the best fit for the project, have looked at both react window and tanstack virtual.

Thanks, will try to help in this

**Comment by ItamarSmirra** [comment]
Just here to support the need of this feature. Only if possible of course.

Mui mention this package in their documentation so I am guessing the feature requests (or maybe feature demands is more accurate) got grown much more.

Thank you.

**Comment by petyosi** [comment]
@ItamarSmirra it's great that you are going to support this feature. Should I expect a sponsorship or PR from you? Let me know, thank you.

**Comment by hipstersmoothie** [comment]
@petyosi I'm interested in sponsoring this work. If I were to sponsor you say for 2-3 months could we get this feature?

**Comment by petyosi** [comment]
Thanks to @hipstersmoothie this feature is going to make it. Everyone, please check this implementation - looking for feedback. 
https://codesandbox.io/p/sandbox/horizontal-virtuoso-j2xn2q?file=%2Fsrc%2FApp.tsx%3A8%2C5. 

The horizontal positioning of the items is not "out of the box", so I chose to do so with `inline-block`.

**Comment by petyosi** [comment]
update: the sponsorship of this feature has been retracted. If someone is interested in having this published, contact me.

**Comment by IgnisDa** [comment]
Hello. Any updates on this?

**Comment by petyosi** [comment]
Horizontal mode is available in v4.8.0. https://virtuoso.dev/horizontal-mode/.

**Comment by mbret** [comment]
> Horizontal mode is available in v4.8.0. https://virtuoso.dev/horizontal-mode/.

Super sweet, any chance to have support for scrollLeft on the state as well ?
