### ISSUE TITLE
[BUG] Types regression in latest update (does not support style)

### ISSUE THREAD

**Issue by Xhale1** [petyosi/react-virtuoso#621]
**Describe the bug**
The latest update causes `style` to be removed as a supported prop on a Virtuoso component. `style` is still used in the docs so I assume it is still supported? Below is the error as reported by TypeScript in VSCode.

```
Type '{ style: { height: string; }; }' is not assignable to type 'IntrinsicAttributes & VirtuosoProps<any, any> & { ref?: Ref<VirtuosoHandle> | undefined; }'.
  Property 'style' does not exist on type 'IntrinsicAttributes & VirtuosoProps<any, any> & { ref?: Ref<VirtuosoHandle> | undefined; }'.
```

**Reproduction**
https://codesandbox.io/s/gifted-nobel-p9zrsg?file=/src/App.tsx

**To Reproduce**
1. Use virtuoso with TypeScript
2. Add a `style` prop

**Expected behavior**
`style` is supported

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS 12.3
 - Browser: Chrome 99

**Additional context**
n/a

**Comment by Edelf** [comment]
I'm facing the same error.

**Comment by petyosi** [comment]
Yep, it's a regression, I will fix as soon as possible.
