### ISSUE TITLE
[BUG] validateDOMNesting(...): <tr> cannot appear as a child of <div>.

### ISSUE THREAD

**Issue by Kestutis** [petyosi/react-virtuoso#625]
**Describe the bug**
I'm using react-virtuoso with react-table and flexLayout (instead of ordinary tableLayout) and you have div`s instead of thead/tbody/tr elements. It's required to support functionality as columns sizing, etc.

Getting error `validateDOMNesting(...): <tr> cannot appear as a child of <div>.` because there are couple of components that supports only table elements as parent nodes.

```typescript
// src/components/Table.tsx
const DefaultScrollSeekPlaceholder = ({ height }: { height: number }) => (
  <tr>
    <td style={{ height }}></td>
  </tr>
)

const FillerRow = ({ height }: { height: number }) => (
  <tr>
    <td style={{ height: height, padding: 0, border: 0 }}></td>
  </tr>
)
```

**Expected behavior**
It would be nice to have an option to overwrite these components

**Comment by petyosi** [comment]
@Kestutis do you want to open a PR? It should be fairly simple fix.

**Comment by Kestutis** [comment]
Create PR for a fix. Also included react-table flexLayout example. There are still single issue with TableHead typings, but it's not related with flex layout.
