### ISSUE TITLE
Content jumps when row gets unmounted

### ISSUE THREAD

**Issue by hauntedlollipop** [petyosi/react-virtuoso#627]
Hi, whenever the row above latest one visible gets unmounted, the scoller starts jumping.  I was wondering what might cause this?

https://user-images.githubusercontent.com/36665442/161822241-4414f085-c3ba-4b36-9e1c-57b70fb57161.mov

**Comment by petyosi** [comment]
No idea. Reproduce it in a sandbox with the bare minimum amount of code and post the url here, I might be able to help you.

**Comment by hauntedlollipop** [comment]
Okay, so here's the [sandbox](https://codesandbox.io/s/react-virtuoso-7xndzc?file=/src/App.js). With props `useWindowScroll`, and `initialTopMostItemIndex`, when trying to reverse scroll, Virtuoso gets all jumpy/flickery.
