### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by josephstgh** [petyosi/react-virtuoso#63]
Hi,

Is there a changelog for react-virtuoso?

Thanks

**Comment by petyosi** [comment]
Hey, 

I am documenting the major points for each release in the GH releases UI: https://github.com/petyosi/react-virtuoso/releases 

Let me know if you are looking for something in particular.

**Comment by josephstgh** [comment]
Would appreciate it to have changelog for every single release.

In the release page, only certain releases was updated with the changelog.

For example, `v0.12.1` to `v0.12.6` wasn't documented. Hence, I am not sure what changes there are, and if I can safety upgrade in my project.

**Comment by petyosi** [comment]
Thank you for the feedback - it is a valid one. Even though I am in a pre-release cycle, I am sticking to semantic versioning, so patch releases like v0.12.1 don't contain new features (let alone breaking changes) - it is just bug fixes or dependency bumps to fix security reports from Github. I do agree that people would benefit from knowing what those bug fixes are.

**Comment by josephstgh** [comment]
It would really help us (and others), knowing what exactly are the issue fixed. While using the library, we may come across certain issue/limitation/bug that could get fixed in any minor or patch release. Hence, with the changelog for every release (no matter the type), is important to us.

We are switching out from react-window, ag-grid to this, and so far, it seem really promising. Keep the good work up, and hope to see it grow.
