### ISSUE TITLE
[BUG] Virtuoso jumps and flickers around while reverse scrolling

### ISSUE THREAD

**Issue by hauntedlollipop** [petyosi/react-virtuoso#630]
Okay, so here's the [sandbox](https://codesandbox.io/s/react-virtuoso-7xndzc?file=/src/App.js). With props `useWindowScroll`, and `initialTopMostItemIndex`, when trying to reverse scroll, Virtuoso gets all jumpy/flickery.

**Comment by petyosi** [comment]
Sorry if this comes across as too direct, but I am not going to debug your application. Reduce the problem down to the essentials first. 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/13347/162170516-9a05b3b4-f5f1-4c65-8980-312531c1b5f5.png">

**Comment by hauntedlollipop** [comment]
Here's the simple version https://codesandbox.io/s/react-virtuoso-forked-wilv2t

**Comment by petyosi** [comment]
You have items with wildly varying sizes - 6000px and 700px. `defaultItemHeight` might help, but in general, this is a very extreme setup that will break the list logic of predicting the scroll size and item location. I would look into breaking your items apart into smaller chanks.

**Comment by hauntedlollipop** [comment]
> You have items with wildly varying sizes - 6000px and 700px. `defaultItemHeight` might help, but in general, this is a very extreme setup that will break the list logic of predicting the scroll size and item location. I would look into breaking your items apart into smaller chunks.

Thank you very much for your response
