### ISSUE TITLE
[BUG] TableVirtuoso with fixedHeaderContent bleeds outside of it's container

### ISSUE THREAD

**Issue by jtiala** [petyosi/react-virtuoso#631]
**Describe the bug**
A TableVirtuoso with `fixedHeaderContent` seems to occupy some space outside of the component at the bottom of the table. The amount seems to be related to the height of the header row, but not exactly the same. For 20px tall header the amount of overlap on the bottom seems to be about 12px.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-fixed-header-problem-7utl4w?file=/App.js
Also see comments on the code

**Expected behavior**
I would expect that a library component would not affect the app outside of its boundaries

**Screenshots**
<img width="820" alt="Screenshot 2022-04-11 at 16 25 39" src="https://user-images.githubusercontent.com/1576782/162749310-c34521cd-5db5-41fb-91fa-d5e043ecb580.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: latest Chrome

**Comment by petyosi** [comment]
Thanks for the repro. Certainly weird. The calculation seems to be off, I might be missing the fixed header in it.
