### ISSUE TITLE
[BUG] Avoid create new objects for style in List

### ISSUE THREAD

**Issue by henrinormak** [petyosi/react-virtuoso#635]
**Describe the bug**
[Code in List](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L267) is creating new objects on every render, which is breaking any sort of memoisation that might be happening with the Item component that is passed in.

Sort of related, but the style part is also not listed as being passed in to [Item here](https://github.com/petyosi/react-virtuoso/blob/master/src/interfaces.ts#L21-L26), would be nice to fix that as well.

I can provide a PR, let me know if that would be a good idea (maybe I'm missing something related to this).

**Comment by petyosi** [comment]
Good catch, yeah - PR would be great. You can pull that [style to a const like here](https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L169).
