### ISSUE TITLE
[BUG]Scrolling the page after AutoSize changes the width, the content positioning is not accurate

### ISSUE THREAD

**Issue by Veath** [petyosi/react-virtuoso#638]
**Describe the bug**
Scrolling the page after AutoSize changes the width, the content positioning is not accurate

**Reproduction**
[Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.](https://codesandbox.io/s/sandpack-project-forked-uibcjp?file=/data.js)

**To Reproduce**
1. Minimize the container and scroll the list to the bottom
2. change container width 
3. scroll up the page
4. see Row index 
```js
Row index 100 // this is incorrect item
Row index 98
Row index 99
Row index 100
```

**Expected behavior**
```js
Row index 97
Row index 98
Row index 99
Row index 100
```

**Screenshots**
 ![image](https://user-images.githubusercontent.com/15187953/163551906-a0daa719-2e90-4204-bfbf-95840fab40ce.png)
![image](https://user-images.githubusercontent.com/15187953/163552377-df47863e-ca99-4c44-887a-fafdc7dfca94.png)

**Comment by petyosi** [comment]
I'm not sure I'm following the description. You talk about Row 100, but the linked sandbox has only 30 rows. Your screenshots don't have the described inconsistency as well. Can you elaborate?

**Comment by Veath** [comment]
The description above is wrong, I uploaded a video，scroll up, row index 28 27 26... repeats

https://user-images.githubusercontent.com/15187953/163557245-343d412d-319c-45df-a416-8bbb412dd976.mov

**Comment by petyosi** [comment]
Can you record steps from the beginning? I do what you describe and it works for me.

**Comment by Veath** [comment]
> Can you record steps from the beginning? I do what you describe and it works for me.


https://user-images.githubusercontent.com/15187953/163562576-981df27a-0bbb-4961-b681-786aa6fdadd2.mp4

**Comment by petyosi** [comment]
The same steps work on my machine. Which browser/os do you use?

**Comment by Veath** [comment]
> The same steps work on my machine. Which browser/os do you use?

Desktop :
OS: macOS
Browser: Chrome  99.0.4844.51

**Comment by Veath** [comment]
I'm guessing it's because the item height is cached when scrolling down. Then when scrolling up, get the item height from the cache. Because the width of the container changes, the item height obtained from the cache is inaccurate and misplaced?

**Comment by Veath** [comment]
I found a very important premise, the more the container width changes, the more prone to this problem. For example, the container width is 100px when scrolling forward, then 1000px when scrolling backward.
