### ISSUE TITLE
[BUG] There is less hover area for ItemComponent directly under GroupComponent.

### ISSUE THREAD

**Issue by toshi1127** [petyosi/react-virtuoso#639]
**Describe the bug**

There is less hover area for `ItemComponent` directly under `GroupComponent`.
I think the reason is that `GroupComponent` has `z-index:1 style`, which causes hover events to take precedence.

**Reproduction**

As shown in the video below, the tooltip is closed because the GroupComponent's Hover takes precedence.

https://user-images.githubusercontent.com/32378535/163661449-658c5ef8-3985-4d13-b2a4-5f0d89ffa779.mov

**Expected behavior**

I want to be able to override `GROUP_STYLE` with Props. Can I submit a PR for this improvement?

**Screenshots**

**Desktop (please complete the following information):**
- OS: macOS
- Browser: latest Chrome

**Comment by petyosi** [comment]
If you want to, you can [filter out the passed style](https://codesandbox.io/s/sandpack-project-forked-yzxi5y?file=/App.js) through components.Group. However, this will cause the groups to slide under rather than over the sticky header.

**Comment by toshi1127** [comment]
Thank you, I think I can solve it.
