### ISSUE TITLE
Question: Is it possible to scrollToIndex with a transition?

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#64]
Something like domEl.scrollIntoView();

ex.
elmnt.scrollIntoView({block: 'start', behavior: 'smooth'}); 

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

Thx

**Comment by petyosi** [comment]
Yes, It is implemented but not released yet, I will publish a version in a week or two. There is a caveat though - if the item is far from its expected location, the list will “double jump”. I will update the issue once the release is out.

**Comment by petyosi** [comment]
Now that I gave the caveat above a thought, this could be avoidable.

**Comment by Ethorsen** [comment]
Very nice.  Let me know if you need any help with this matter, even if only for testing.

**Comment by uffou** [comment]
Is smooth scrolling possible now?

**Comment by savkelita** [comment]
> Is smooth scrolling possible now?

Yes it is! Sorry i’m on mobile device, but this may help as instant solution: https://github.com/petyosi/react-virtuoso/blob/8605ccb6be82b868b78ba1c2b1f2919e1bcdabab/src/EngineCommons.ts#L3 focus is on behavior.

**Comment by petyosi** [comment]
v1 beta improved the smooth scroll to index behavior - give it a try. Installation instructions are available in #203.
