### ISSUE TITLE
[enhancement] Add atStartThreshold

### ISSUE THREAD

**Issue by mikamations** [petyosi/react-virtuoso#641]
For prepended lists (reverse scroll) it would be great to have an atStartThreshold like atBottomThreshold so we can trigger new data API calls before hitting the top for a smoother endless scroll.

**Comment by petyosi** [comment]
This is nice to have indeed. Loading new data upwards is easier though, as the top is always `0`. You can hook up to the DOM `onScroll` event or the `rangeChanged` one. 

The `atBottomThreshold` prop value controls the `followOutput` behavior, where the logic is quite complex.
