### ISSUE TITLE
[BUG] VirtuosoGrid with MaterialUI Grid odd behavior

### ISSUE THREAD

**Issue by khuezy** [petyosi/react-virtuoso#646]
**Describe the bug**
Grid with MaterialUI Grid shakes on scroll and grid items are not rendered at bottom row

**Reproduction**
[codesanboxlink](https://codesandbox.io/s/sandpack-project-forked-v5vjvs?file=/App.js)

**To Reproduce**
1. Go to link above
2. Scroll down slowly and pause once you see the rapid flashing
3. See error
4. Note that the bottom rows are blank until you scroll further down

**Expected behavior**

**Screenshots**
![Screenshot 2022-04-25 201817](https://user-images.githubusercontent.com/811298/165213394-b401aa2d-7c4c-4962-a758-caddc4d0c615.jpg)

NOTE: the bottom row does not render the Grid item until you scroll further down.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Using emotion/styled works well (https://virtuoso.dev/grid-responsive-columns/)

**Comment by petyosi** [comment]
I don't provide customer support through GH issues. Feel free to debug the setup, and submit PR if the problem is in the library.

**Comment by khuezy** [comment]
Is it possible to debug in the Codesandbox? I've set the globalThis.VIRTUOSO_LOG_LEVEL to DEBUG but I'm not seeing any debug info.
