### ISSUE TITLE
Reverse scroll content jumps when row gets prepended at top

### ISSUE THREAD

**Issue by anandagarwal6040** [petyosi/react-virtuoso#648]
Hi, whenever new records get mounted at top on reverse scroll the scroller jumps. I was wondering what might cause this?
Here is my sandbox link: https://codesandbox.io/s/reverse-virtual-scroll-g8fqve

Any suggestions will be helpful, thanks in advance.

**Comment by petyosi** [comment]
Sorry, this is an open-source project - I can't debug your application. 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/13347/165455210-e601a935-dfda-4da2-a93a-72f7c9b620f8.png">
