### ISSUE TITLE
[BUG] - Adding a new element to the middle of the list (inserting it) causes re-rendering of all elements below newly inserted one

### ISSUE THREAD

**Issue by myrosyatsaplap** [petyosi/react-virtuoso#649]
**Describe the bug**
I have a dynamic list of items, which can be changed (items can be added at any index) by WebSocket at any time, and every time we get an updated data (e.g  a new item added to the list at a particular index), all items below the newly added one re-render even though nothing has been changed about them.

**Reproduction**
For illustration purposes, I've created a simple demo, which you can use to reproduce the bug and understand the issue better. Link for the Demo - https://codesandbox.io/s/virtuoso-rerender-bug-demo-8ddmii?file=/App.js

**To Reproduce**
1. Go to the Demo created following the link above
2. Click on **Update list** button on the top of the screen to simulate the fetch of updated data.
3. Watch the list being updated - all items below the newly added one re-render  (you can see the iFrame flashing)

**Expected behavior**
Insertion of a new element to the list does not cause the re-rendering of all items below it, only the newly added item renders.

**Screenshots**
- 

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome@latest

**Additional context**
I understand that as the library is using indexes as `data-keys`, this bug is caused by React natural behaviour of handling lists when their keys change.  But it would be great if the library could use the unique IDs as `data-keys`, so the fetch of new data would only cause the updated items being re-rendered.

**Comment by petyosi** [comment]
This should be fixable through the `computeItemKey` prop I believe. Read the docs for further details.
