### ISSUE TITLE
[BUG] scrollIntoView in GroupedList is broken

### ISSUE THREAD

**Issue by ryanmearns** [petyosi/react-virtuoso#654]
**Describe the bug**
On ArrowUp ScrollInToView with Grouped List leaves the item out of view.

**Reproduction**
I've used the keyboard navigation example with GroupedVirtuoso and generateGroupedUsers to reproduce the issue here: https://codesandbox.io/s/sandpack-project-forked-fjip1g?file=/App.js

**Expected behavior**
The top item should come into view.

**Desktop (please complete the following information):**
 - OS: iOS
 - Chrome

I'm happy to look into a fix if there are any ideas for how it could be fixed. To me it looks like the scroll event jumps to the top of the  div data-viewport-type="element" which is it out of sync with the position of the div data-test-id="virtuoso-scroller"

**Comment by petyosi** [comment]
So this seems interesting. The `scrollToIndex` implementation does take [into account the header height](https://github.com/petyosi/react-virtuoso/blob/2a1131ad84997ed94947324077c61316ac908c85/src/scrollToIndexSystem.ts#L76), so it *should* work. The `scrollIntoView` also [includes the headerHeight here](https://github.com/petyosi/react-virtuoso/blob/2a1131ad84997ed94947324077c61316ac908c85/src/scrollIntoViewSystem.ts#L24). Probably somewhere in those two files the logic is faulty.
