### ISSUE TITLE
Endless scroll with fetch API

### ISSUE THREAD

**Issue by Pavelhaj93** [petyosi/react-virtuoso#657]
Hello, 

I have a test interview for React Developer in React.js . I have a task to fetch API and use your Virtuoso to make a list with Endless Scroll and with each scroll to bottom fetch 10 more items. From your documentation I can see that it is pretty easy if you have the data already. I mean I could to endless scroll and I can fetch data but I dont know how to connect it together. I am wondering what is the generateUsers in your documentation because you import it there but dont show what it does. If you could help me I would really appreciate it. 

Thanks,

Pavel

**Comment by petyosi** [comment]
You can open any of the source code examples from the docs in codesandbox and examine the implementation there.

**Comment by Pavelhaj93** [comment]
Thank you I know but there is not a single example how to pass fetched data into itemContent, like how to map through an fetched data and show them in the Virtuoso list. Could you guide me to any documentation about it ? As I see all the data shown in examples are hardcoded.

Thanks a lot

**Comment by Pavelhaj93** [comment]
I figured it out, missed data={users} sry I am stupid.
