### ISSUE TITLE
[BUG] Negative index when scrolling beyond the top of `VirtuosoGrid`

### ISSUE THREAD

**Issue by rafaelalmeidatk** [petyosi/react-virtuoso#658]
**Describe the bug**

When the user scrolls fast enough beyond a `VirtuosoGrid` component that has the `useWindowScroll` prop it runs the `itemContent` function with a negative index
 
**Reproduction**
https://codesandbox.io/s/vigilant-violet-0nywe0?file=/src/App.js

**To Reproduce**
1. Go to the sandbox link
2. Scroll down the page (it doesn't need to be exactly at the bottom)
3. Press the Home button or use the scrollbar to quickly go to the top of the page, where the grid isn't visible anymore

**Expected behavior**
The `itemContent` function should not be called with negative indexes

**Screenshots**

<details><summary>Example</summary>
<p>
<img src="https://user-images.githubusercontent.com/11896398/167963419-187033da-23f1-4c72-b07c-1c7e48f13d4e.gif" />
</p>
</details>

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 100.0.4896.75

**Comment by petyosi** [comment]
Agreed, this should not be the case. I'll take a look

**Comment by rafaelalmeidatk** [comment]
@petyosi thank you for the quick fix! :heart:
