### ISSUE TITLE
[BUG] Error while using Virtuoso with OverlayScrollbars, introduced in 2.5.0

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#660]
Hi @petyosi 

**Describe the bug**
There is a crash when using Virtuoso with OverlayScrollbars as a custom scrollbar. 

```
TypeError
Cannot read properties of null (reading 'dataset')
eval
https://yos1zo.csb.app/node_modules/react-virtuoso/dist/index.m.js:968:55
ResizeObserver.eval
https://yos1zo.csb.app/node_modules/react-virtuoso/dist/index.m.js:912:34
```

The error was introduced in 2.5.0  with the changes in src/hooks/useChangedChildSizes.ts i'm guessing

**Reproduction**
https://codesandbox.io/s/react-virtuoso-custom-scrollbar-forked-yos1zo?file=/src/CustomScrollbar.js

**To Reproduce**
Switch to Virtuoso 2.4.1 makes the error go away.  

Switch to Virtuoso 2.5.0 creates the error.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1493968/168816224-c77c63df-0d09-4f00-a286-73b0ee8fea5d.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by petyosi** [comment]
Added details in #662
