### ISSUE TITLE
[BUG] - Error when toggling firstItemIndex

### ISSUE THREAD

**Issue by PedroJBrito** [petyosi/react-virtuoso#661]
**Describe the bug**
Hi,

I have a scenario with one list that should toggle between two data sets. One of the lists can start at a specific index, so the firstItemIndex may not be 0, and the other list always starts at 0. I'm trying to reuse the same virtuoso ref to display both data sets, but the problem is when I toggle to display the other data set, both the data and firstItemIndex are updated what produces a strange behavior. Any idea about how can I get over this problem?

What I want to avoid is a behavior similar to what we can see in the following repo. When I toggle between data sets I want to keep the list at the top
https://codesandbox.io/s/sandpack-project-forked-98kswr?file=/App.js:1644-1656

Thank you for your help.

**Comment by petyosi** [comment]
You should toggle the key prop as well.
