### ISSUE TITLE
[BUG] followOutput prop not working with margin top/bottom

### ISSUE THREAD

**Issue by pthanh1703** [petyosi/react-virtuoso#664]
**Describe the bug**
followOutput prop not working when the outer most cotainer of each itemContent have margin top/bottom or if inner child have margin top/bottom and that margin overflow the outer most container

**Reproduction**
itemContent have h4 tag margin overflow container: https://codesandbox.io/s/reproduce-margin-overflow-5ioucu?file=/App.js
outer most container have margin top: https://codesandbox.io/s/reproduce-container-margin-21epqx?file=/App.js

**Expected behavior**
The list scroll to the bottom

**Comment by petyosi** [comment]
Margins are not supported. Read the docs.
