### ISSUE TITLE
[BUG] Can't add props to table rows

### ISSUE THREAD

**Issue by hipstersmoothie** [petyosi/react-virtuoso#666]
**Describe the bug**

I would like to add props to table rows. Since this library doesn't give control of rendering the `tr` to me I cannot do this. I want to accomplish the following:

```tsx
<tr onClick={doSomethingUniqueForThisRow}>
  {/** Row contents */}
</tr>
```

As it stand today though I can't do this very easily. The table component has a `components` prop, but that mean I can't control the props for any of those components. Each one of my rows will have different props for each.

**Reproduction**

In the following code sandbox I showcase the exact behavior I want. 

https://codesandbox.io/s/sandpack-project-forked-lr5dkg?file=/App.js

**Expected behavior**

I should be able to control the rendering of the table row. 

The following code is how I would expect it to work. `itemContent` gets a new argument `props` which applies the `data-` attributes to make the virtualization work. With this method I can fully control all props applied to the row and add things like the `onClick`.

```tsx
export default function App() {
  return (
    <TableVirtuoso
      style={{ height: 400 }}
      data={generateUsers(100000)}
      itemContent={(index, user, _, props) => (
        // TableVirtuoso doesn't let me control the rendering of the tr
        // so the following code isn't valid and breaks the virtualization
        <tr {... props} onClick={() => console.log("Clicked ", user)}>
          <td style={{ width: 150 }}>{user.name}</td>
          <td>{user.description}</td>
        </tr>
      )}
    />
  );
}
```

**Additional Context**

I'm willing to contribute the change to make this happen. I currently have a patch applied the the package in my own code base that accomplished this. This change would be a breaking change.

**Comment by petyosi** [comment]
you can use the passed props to the TableRow for that - https://codesandbox.io/s/sandpack-project-forked-hes5d6?file=/App.js. It gives you access to a few things, which should be enough to get the necessary data.

**Comment by hipstersmoothie** [comment]
Unfortunately that's still not flexible enough for my use case. Say I have 4 different row types (file, folder, etc). How am I going to know what type of row is being rendered? If I can only define the row in one place (like in your example) it makes it really tough to make the rows do different things.

Here's a more concrete example that relates to the supplied code. What if there are multiple user types (user, admin, read-only)? When each row is clicked I want to route to a different part of my application and have different context menus? Since the TableRow is defined in another place I don't know what type the row is without adding a bunch of `data-` attributes and relying on DOM bubbling to communicate that.

Would you consider a PR for this? The change is relatively simple.

**Comment by hipstersmoothie** [comment]
For anyone encountering similar problems I used Radix's `Slot` component to get around this

https://www.radix-ui.com/docs/primitives/utilities/slot

```tsx
 const components = React.useMemo(
        () =>
            ({
                Table: RootImpl,
                TableBody: Table.Body,
                TableRow: Slot,
            } as Components),
        [],
    );
```

Now anytime it renders a row, the slot gets rendered, which spreads all props onto it's child, allowing you to render you `tr` with your `td`s.

**Comment by ruslaza** [comment]
hey, @hipstersmoothie 

thank you for your solution.

BTW, I have two `<TableRow>` on `itemContent` for Collapsible Table for Additional Information.

and based on `row` item, it should render 200 items though, but I got just only first one element if page renders.

Could you please why this happen?

This is [codesandbox](https://codesandbox.io/p/sandbox/virtuoso-rows-with-radix-slot-l3yzhh) link.

Thank you for your issue and solution again.
