### ISSUE TITLE
[BUG] React-virtuoso + Storybook

### ISSUE THREAD

**Issue by nosferatu500** [petyosi/react-virtuoso#668]
**Describe the bug**
ResizeObserver loop completed with undelivered notifications.

**Reproduction**
```
// index.js
import React from 'react'
import { storiesOf } from '@storybook/react'
import BarebonesExample from './barebones'

storiesOf('Basics', module)
  .add('Minimal implementation', () => <BarebonesExample />)
```

```
// barebones.js
import React from 'react'
import { Virtuoso } from 'react-virtuoso'

export default function App() {
  return <Virtuoso
    style={{ height: "400px", }}
    totalCount={200}
    itemContent={(index) => <div>Item {index}</div>}
  />
}
```

**Behavior**
It's actually works but I getting an error in the console 
`ResizeObserver loop completed with undelivered notifications.`

PS: Sorry, I don't know how to setup storybook on codesandbox.io (if it's even possible)

**Comment by petyosi** [comment]
Duplicate. Search in the issues before opening.
