### ISSUE TITLE
[BUG] children components of VirtuosoGrid get unmounted when navigate on Ionic5

### ISSUE THREAD

**Issue by 21hak** [petyosi/react-virtuoso#669]
**Describe the bug**
Children elements of `VirtuosoGrid` get unmounted when navigate to other page using Ionic router.  This only happens when custom scroll element is passed to `customScrollParent` props.  As children components are unmounted, scroll moves to top which causes problems.

**Reproduction**
https://codesandbox.io/s/pedantic-dirac-5lhh7k?file=/src/pages/ListPage/ListPage.tsx

**To Reproduce**
There are 4 cases. `Virtuoso` with/without custom scroll element and `VirtuosoGrid` with/without custom scroll element. 

1. Go to `ListPage.tsx`
2. Check each case. Each case is comment out.
3. Scroll down several times and route to DetailPage by clicking a link. Then, go back to ListPage by clicking header back button. 

**Expected behavior**
Items should not be unmounted after coming back to list page.  `Virtuoso` and `VirtuosoGrid` without custom scroll element works as expected. Only when custom scroll element is passed to `VirtuosoGrid` `customScrollParent` props, Items are unmounted and scroll position is set to top. 

**Desktop (please complete the following information):**
 - OS: macOs 12.3(m1)
 - Browser chrome 101.0.4951.64 (arm64), safari(15.4)

**Additional context**

**Comment by petyosi** [comment]
1. There's something wrong with the sandbox: 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/13347/170633485-67d79a7d-71f0-40d8-86e8-deacd162fc6f.png">
2. I have no experience with Ionic and his underlying navigation. Can you help me by reproducing the problem outside of it?

**Comment by 21hak** [comment]
Sry, I forgot to save😂 . Here's the link. https://codesandbox.io/s/compassionate-williamson-20b6gl?file=/src/pages/ListPage/ListPage.tsx
I'll reproduce without ionic. Thank you

**Comment by 21hak** [comment]
Hi! I made a quick reproduction. I think this happens when the `display` property of container element changed to `none`. 
https://codesandbox.io/s/small-cherry-zzobtx?file=/src/App.tsx

**Comment by petyosi** [comment]
Got it. There's a guard condition for that in the list but not in the grid, should be an easy fix.
