### ISSUE TITLE
Container height autosizing

### ISSUE THREAD

**Issue by toonvd** [petyosi/react-virtuoso#67]
Hi

In my example at https://codesandbox.io/s/muivirtuoso-w5lmq.
Autosizing is working correctly in Chrome and IE but not in firefox.

Using an auto resize lib fixes this issue, but having this dependency is not ideal.
Do you have any pointers by any chance?

**Comment by toonvd** [comment]
Hi @petyosi 

Managed to fix it by forcing the table itself as a flexbox with a flexDirection: 'column'.
If you want, I can clean this up and make a pullrequest for your demo.

**Comment by petyosi** [comment]
Reopening this to check it shortly, thanks @toonvd

**Comment by toonvd** [comment]
Hi

Great, FYI, this was not a problem with react-virtuoso but more of a styling issue on my side.
