### ISSUE TITLE
[BUG] TableVirtuoso multiple <td /> doesn't not calculate height properly

### ISSUE THREAD

**Issue by chrisd1999** [petyosi/react-virtuoso#672]
**Describe the bug**
TableVirtuoso table row with multiple `<td />` can't calculate the height on scroll, and produces unexpected gaps. This behaviour is worse while scrolling up other than down. This does not happen with for example, 4 `<td />`.

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-tmv7xf?file=/App.js

**To Reproduce**
1. Go to provided codesandbox.
2. Start scrolling Table with dozen `<td />` in the table row.
3. See the table has big white gaps while scrolling, takes time to recover.

**Expected behavior**
While scrolling with dozen of `<td />` it does not produce white gaps while scrolling.

**Screenshot**
![Screenshot 2022-05-31 at 14 24 44](https://user-images.githubusercontent.com/45801982/171163652-6e1f2375-675b-4846-9cba-5fed6be25c20.png)
![Screenshot 2022-05-31 at 14 36 02](https://user-images.githubusercontent.com/45801982/171164428-f9b3c99e-e643-4845-add0-54221fbf8e4a.png)

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser: Chrome

**Comment by petyosi** [comment]
I am not sure what you're trying to achieve, but the custom component setup you have totally butchers the intended markup of the component. Feel free to debug it further in a fork if you want to.

**Comment by chrisd1999** [comment]
@petyosi Hi, thanks for fast response. Using custom components sparingly, it does produce the same issue. The more `<td />` present in the table row, the more issues to calculate height properly. Could there be any other main causes, which hinder the performance? May you take look at the codesandbox?
Linked codesandbox: https://codesandbox.io/s/sandpack-project-forked-vy2fjs

**Comment by petyosi** [comment]
The problem you're facing is due to the table not having a fixed column size. This is absolutely necessary and mentioned on a few occasions in the docs and in the issues here. Check this fork for a very crude solution: https://codesandbox.io/s/sandpack-project-forked-wigzfz?file=/styles.css:330-351
