### ISSUE TITLE
[BUG] scrollerRef not called with useWindowScroll

### ISSUE THREAD

**Issue by alexgleason** [petyosi/react-virtuoso#674]
**Describe the bug**
When useWindowScroll is enabled, the scrollerRef callback is never called.

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-n73cye?file=/App.js

**To Reproduce**

1. Use `useWindowScroll`
2. Define a `scrollerRef`, and print something inside it
3. Mount the component. The callback is never called.

**Expected behavior**

`scrollerRef` gets called.

**Comment by petyosi** [comment]
What are you trying to achieve? With window scroll, the scrolling element is the window itself, which you can easily obtain.
