### ISSUE TITLE
[BUG] Prepending items causes a flicking in React 18

### ISSUE THREAD

**Issue by lightDer** [petyosi/react-virtuoso#681]
**Describe the bug**
ReactDOM.render is no longer supported in React 18. So I use [createRoot](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) instead. 
And I found that when scrolling to the top. After prepending items, the whole list is flicking. 
Does it seem like the position calculates again? 

**Reproduction**
Please see this [example (fork from doc. )](https://codesandbox.io/s/sandpack-project-forked-eiqhy5?file=/index.js)

**To Reproduce**
1.  Use `react-dom/client.createRoot.render` instead of `react/dom.render` in index.js
2. Scroll to top multiple times. 
4. Observe list carefully after prepending items. It has a flicking render. 

**Expected behavior**
After prepending items, the list viewport should stay in position which likes in the [doc. example](https://virtuoso.dev/prepend-items/).

**Screenshots**
https://user-images.githubusercontent.com/3839494/172744006-fc1bb2eb-f1cf-4e1d-99e9-80d0637a583f.mp4

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: Chrome 104.0.5098.0

**Comment by petyosi** [comment]
@lightDer It took me a few changes to get this working. Please let me know if you still experience the problem, as the fix involves `flushSync` - an API which is kinda not loved by React themselves.

**Comment by lightDer** [comment]
Hi @petyosi, thank you for your work! 🥳 The version 2.13.2 works on Chrome. But I found that it still has a flicking in Vivaldi (5.3.2679.55). It's odd because they both base on Chromium.

**Comment by petyosi** [comment]
Thanks for the confirmation. As far as I tested, it also flashes occasionally in Safari. Still, getting it working in chrome is an improvement.
