### ISSUE TITLE
[BUG] List stops scrolling and loses focus

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [petyosi/react-virtuoso#684]
**Describe the bug**
When you scroll the list using a touchpad, it scrolls only a few items and then it stops. You have to move the mouse to regain focus and be able to scroll again. Rinse and repeat.
Scrolling with keys works fine.

**Reproduction**
I thought this was some misconfiguration at my app, but the same thing can be seen at the examples at https://virtuoso.dev/.

**To Reproduce**
1. Go to https://virtuoso.dev/
2. Wait for one of the examples to load
3. Try scrolling with a touchpad or mouse
4. See that it stops scrolling and that you have to move the mouse to be able to scroll again.

**Expected behavior**
Normal scrolling.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 36 5.17.13-300.fc36.x86_64 
 - Browser: Brave [Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)]

**Comment by quangtd101246** [comment]
I have this bug too and demo on website virtuoso.dev have this bug too. Just have useWindowScroll props work ok
OS: Windows 10
Browser: Chrome (latest version)

**Comment by petyosi** [comment]
@Gabriel-Alves-Cunha I suspect that this is another variation of this problem: https://github.com/petyosi/react-virtuoso/issues/675. Can you test the workaround there and let me know if it affects your setup?

**Comment by Gabriel-Alves-Cunha** [comment]
> @Gabriel-Alves-Cunha I suspect that this is another variation of this problem: #675. Can you test the workaround there and let me know if it affects your setup?

This solution works: https://github.com/petyosi/react-virtuoso/issues/675#issuecomment-1148507209
:smile: thanks for the help!

**Comment by petyosi** [comment]
Thanks for getting back, I will make that a default one.
