### ISSUE TITLE
[BUG] TypeError A(react-virtuoso/dist/index.m) e.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by alexgleason** [petyosi/react-virtuoso#687]
**Describe the bug**
Hi there! I'm getting quite a lot of Sentry errors about this line here:

![Screenshot from 2022-06-20 11-38-49](https://user-images.githubusercontent.com/3639540/174646786-cd13fcd4-31bd-4d5e-a76b-12588455981d.png)

**Reproduction**

My first thought: it must be old browsers, but it's not. Here are some clients where this is failing:

![Screenshot from 2022-06-20 11-41-30](https://user-images.githubusercontent.com/3639540/174646919-adf33e77-2c56-4dfa-b941-adc6c9243d97.png)

![Screenshot from 2022-06-20 11-41-41](https://user-images.githubusercontent.com/3639540/174646929-8c6d0be8-1748-4f8b-a0c5-f1ac985b8af9.png)

Meanwhile, should be supported: https://caniuse.com/?search=getBoundingClientRect

**To Reproduce**

I can't reproduce it locally. Here are arguments from Sentry:

![Screenshot from 2022-06-20 11-44-07](https://user-images.githubusercontent.com/3639540/174647282-fbb421c3-8240-4ff1-8ea1-2e0b19768b35.png)

**Expected behavior**

No error is thrown.

**Comment by petyosi** [comment]
@alexgleason what you're seeing there is the default value of the `itemSize` property. My guess is that, somehow, this gets called on something that does not have the method - maybe `window`? 

Can you try something like this: 

```ts
export function customCorrectItemSize(el: HTMLElement, dimension: 'height' | 'width') {
  try {
    return Math.round(el.getBoundingClientRect()[dimension])
  } catch (e) {
   // you might want to throw a more meaningful error, like, getting the element id, or something.
    throw new Error(`${el} does not have getBoundingClientRect`)
  }
}
```

and then pass it:

```tsx
<Virtuoso itemSize={customCorrectItemSize} />
```

**Comment by petyosi** [comment]
@alexgleason did you find out something here? Curious to solve this.

**Comment by petyosi** [comment]
@alexgleason I think I found the problem (another report pinpointed it).

**Comment by alexgleason** [comment]
Thank you!
