### ISSUE TITLE
No scrolling in Firefox on a total count of 241834

### ISSUE THREAD

**Issue by toonvd** [petyosi/react-virtuoso#69]
Hi

I used the demo on https://virtuoso.dev/hello/ in Firefox.
When I changed the total count to 241834 (in the StackBlitz), the scrollbar went bigger and the max item I could reach was 11. This was the case for all counts higher than that number.

This is not the case in Chrome and other browsers (Safari, Edge). When I set the count to 241833 the problem is fixed. I tested this on my own environment with testdata too to rule out problems with your faker component. It showed the same behaviour. The index where it broke there was 313990, so the number of items is not the constant.

The test was made in the latest Firefox (73.0 (64-bits)) on Windows.

**Comment by petyosi** [comment]
@toonvd are you interested in a contribution? My guess is that the filler height hits some kind of a browser maximum. A workaround I have seen in the past is chunking such elements into multiple smaller ones (say - 10 divs with 1m px height rather than a single one). You can give this a try by [modifying the filler code](https://github.com/petyosi/react-virtuoso/blob/master/src/VirtuosoFiller.tsx).

Let me know how it goes. Thank you!

**Comment by toonvd** [comment]
Hi @petyosi 

Thank you for the pointer!
Will take a look at it tonight as I need it for a datatable with +- 2 million items.

**Comment by petyosi** [comment]
With those numbers, you might hit another limitation: the maximum scrollHeight of an element. 

Take a look [at this sandbox](https://codesandbox.io/s/snowy-rain-j37r0) for what I mean.

In Chrome, you get this:
![image](https://user-images.githubusercontent.com/13347/74418238-c05ea600-4e50-11ea-9292-0408f465569c.png)

In Firefox, you will get this:
![image](https://user-images.githubusercontent.com/13347/74418264-cb193b00-4e50-11ea-8d20-3aedcad71059.png)

In other projects, I have made workarounds for that, but they are not pretty and user-friendly, so I am hesitant on recommending them. I can give you suggestions on that as well if necessary.

**Comment by toonvd** [comment]
Hi

Sorry for the delay, I am working on it but have hit some issues as I am not that familiar with typescript. I was under the impression since the height prop had type: number I could do calculations on it but this is not the case. Better do some more reading on TS and FP :P

**Comment by toonvd** [comment]
Hi @petyosi chunking did not seem to have the desired effect (atleast not in the playground).

A simple change into:

```
import React, { FC } from 'react'

export const VirtuosoFiller: FC<{ height: number }> = ({ height }) => {
  if (height <= 1000000) {
    return <div style={{ height: `${height}px`, position: 'absolute', top: 0 }}>&nbsp;</div>
  } else {
    const numberOfChunks = Math.ceil(height / 1000000)
    let chunks = []
    for (let i = 1; i <= numberOfChunks; i++) {
      chunks.push(
        <div key={'chunk' + i} style={{ height: `${1000000}px` }}>
          &nbsp;
        </div>
      )
    }

    return (
      <div id="wrapper" style={{ position: 'absolute', top: 0 }}>
        {chunks}
      </div>
    )
  }
}
```

Still has a pretty low hard limit.

**Comment by petyosi** [comment]
Did you try to override it from the outside? If so, it won't work, because the filler is not overridable. Can you share what you did?

**Comment by toonvd** [comment]
Hi

I changed it in the file directly and tested it in the playground. I inspected the element and there were indeed multiple divs instead of 1.

**Comment by petyosi** [comment]
What was the limit you hit? Can it be related to the other problem (maximum scrollHeight) I referred to?

**Comment by toonvd** [comment]
Hi

It seems I have indeed hit that limit on the wrapper div.
I am trying to come up with a solution. I see that there are other libs that do not have said limitation, maybe I could take a look at their implementation for some ideas.
