### ISSUE TITLE
I have warning "ResizeObserver loop limit exceeded"

### ISSUE THREAD

**Issue by kambie10** [petyosi/react-virtuoso#699]
![Screen Shot 2022-06-29 at 21 25 27](https://user-images.githubusercontent.com/38092016/176460355-2d361920-09dc-4132-be2d-8e60c0b08781.png)
i have warning "service call failed, ResizeObserver loop limit exceeded"

flow code :

```
<VirtuosoGrid
   style={{ height: '100%' }}
   totalCount={total}
   overscan={20}
   components={{
      List: ListContainer,
    }}
    itemContent={renderBanner}
    scrollSeekConfiguration={{
     enter: (velocity) => Math.abs(velocity) > 200,
     exit: (velocity) => Math.abs(velocity) < 30,
     }}
  />
 ```

you have a solution, fix this warning ?

"react-virtuoso": "^2.16.0"
"react" : "17.0.2"

**Comment by petyosi** [comment]
https://github.com/petyosi/react-virtuoso/issues/254#issuecomment-766319461 see this.

**Comment by zlargon** [comment]
Does this warning cause any real issue? I'm just curious.

**Comment by LiomSV** [comment]
@petyosi Are there any plans to fix the issue? 

I saw a workaround [you've mentioned in another issue](https://github.com/petyosi/react-virtuoso/issues/254#issuecomment-766319461). 

But the workaround doesn't fit for Safari. The suggested approach mutes the errors and it relies on error's message, but Safari emits error with general message: "Script error." It seems that many other errors might be skipped muting such general error.

**Comment by petyosi** [comment]
@LiomSV I am not aware of a way to avoid that without damaging the performance of the component. feel free to explore what I did, reverted, and suggest a possible workaround.
