### ISSUE TITLE
Scrolling issue on iOS

### ISSUE THREAD

**Issue by tschortsch** [petyosi/react-virtuoso#70]
I have a list which fills the whole viewport of the browser. When I scroll down the list on an iOS device and then back up to the top of the list and keep on scrolling, the list content starts jumping / flickering. It seems to be an issue related to the rubber band effect on iOS devices. Here's a basic example of the described issue:
https://codesandbox.io/s/react-virtuoso-scrolling-issue-rzife (Use this view to try it on an iOS device: https://rzife.csb.app/).

Screen record of the issue: https://vimeo.com/391477355

**Comment by petyosi** [comment]
@tschortsch Fixed in v0.13.2 - give it a try.

**Comment by tschortsch** [comment]
Wow that was fast! I’ll try it out, thanks a lot.

**Comment by tschortsch** [comment]
Sorry to bother you again. But I just found out that the same issue appears when you reach the bottom of the list. See https://vimeo.com/392666471 or again this example https://codesandbox.io/s/react-virtuoso-scrolling-issue-rzife (with react-virtuoso 0.13.2).

**Comment by petyosi** [comment]
@tschortsch Agh, I need to boundary the scrollTop reporting properly :(. 

Will check both issues over the weekend. Thanks for your cooperation.

**Comment by petyosi** [comment]
Hey, check v0.13.3 - it fixed the problem in my tests.

**Comment by tschortsch** [comment]
You're awesome. Thanks a lot!

**Comment by JM-Master** [comment]
This problem still exists。When I reach the bottom of the list，keep on scrolling more then an item height ( because of  the rubber band effect ), the list content starts jumping / flickering . This triggered a re-render . Can we stop the calculation at bottom of the list ...

**Comment by petyosi** [comment]
@JM-Master please post a repro.

**Comment by JM-Master** [comment]
I  found out it appears when I add pictures . Use this view to try it on an iOS device: https://01nql.csb.app/

**Comment by mjlikre** [comment]
Hey community, i'm working with virtuoso and i'm seeing something similar when i attempt to open a modal
