### ISSUE TITLE
How to easly access to the data of a row ?

### ISSUE THREAD

**Issue by MGMehdi** [petyosi/react-virtuoso#700]
### Discussed in https://github.com/petyosi/react-virtuoso/discussions/683

<div type='discussions-op-text'>

<sup>Originally posted by **MGMehdi** June 14, 2022</sup>
Hello,

If I want to access to the data of a row I need to do this
```js
TableRow: React.forwardRef((props) => (
  <TableRow {...props} hover onClick={() => console.log(props.children.props.children[0].props.children)}/>
)),
```
Isn't there a better solution ?</div>

**Comment by MGMehdi** [comment]
Well, thanks I guess ?

**Comment by adirzoari** [comment]
@MGMehdi did you find a solution? I'm trying to make hover to row and call an action when hover

**Comment by AdamAtFoyer** [comment]
One way to retrieve the row's data is to use the "context", and get the index of the row using a data attribute:

```jsx
    TableRow: React.forwardRef((props, ref) => {
        const { context: { data, }, ...otherProps } = props;
        const index = props['data-index'];

        return (
            <TableRow {...otherProps} />
        );
    })
```

And in your virtuoso table:

```jsx
            <TableVirtuoso
                context={{ data, }}
                data={data} />
```
