### ISSUE TITLE
[BUG] VirtuosoGrid scrolls jump when its elements have different height

### ISSUE THREAD

**Issue by 21hak** [petyosi/react-virtuoso#703]
Describe the bug
There are two issues. Both seem to be related with VirtuosoGrid component with items that have different heights

1. Scroll keeps changing rapidly
While scrolling down the view, there are some points where scroll suddenly shakes really fast. 

2. Scroll sometimes jump
It's better to see the video below. 

https://user-images.githubusercontent.com/41908293/177904076-2819c496-76fa-4f32-b7d1-9541ae520d4a.mov

Reproduction
https://codesandbox.io/s/sharp-almeida-xofipy

To Reproduce
Scroll down slowly..

Desktop (please complete the following information):

OS: macOs 12.3(m1)
Browser chrome 101.0.4951.64 (arm64), safari(15.4)

**Comment by petyosi** [comment]
The Grid works for same sized elements.

**Comment by 21hak** [comment]
Hi! I got it that it's not a bug. Is there any way to show grid with different heights using react-virtuoso?
I'm developing a e-commerce service and trying to show product list in 2 column. However, the height of each product card can be different. (e.g. some products show review rating below a thumbnail). Should I use `Virtuoso` component rendering two element in one row? Any advice would be very helpful!
