### ISSUE TITLE
Difficulty scrolling to last element

### ISSUE THREAD

**Issue by lexahall** [petyosi/react-virtuoso#705]
**Description**
Scrolling to the last element (or close to last) in a list doesn't seem to work the same as scrolling the other elements. 

**Reproduction**
You can observe this behavior in the example on https://virtuoso.dev/scroll-to-index/

**To Reproduce**
1. Go to https://virtuoso.dev/scroll-to-index/
2. Set align to 'start'
3. Click "Scroll to 500" and notice that it scrolls with element 500 at the start of the scrollable area
4. Click "Scroll to 1000" and notice that it scrolls with element 999 at the end of the scrollable area, which still leaves an element out of scrollable view

**Expected behavior**
since there are not enough elements to scroll with element 1000 at the top of the scrollable area, I would expect to scrolll down as far as possible, rather than leaving an extra item out of view.

**Screenshots**
500: 
![image](https://user-images.githubusercontent.com/10774982/178076967-c40b1cec-ea4f-4eaa-973b-1a6dfb3af430.png)

1000:
![image](https://user-images.githubusercontent.com/10774982/178076981-0c544fcd-96b0-4530-a5c6-8be5e5488d97.png)

**Desktop (please complete the following information):**
 - OS: macOs - Monterey
 - Browser: chrome

**Additional context**
I've noticed a simliar issue happening in my own project, along with a few other strange scrolling behaviors.

**Comment by petyosi** [comment]
I tested the example and it works for me. To ensure I'm not missing something, I also forked it [into a sandbox](https://codesandbox.io/s/sandpack-project-forked-sh1bib). 

The example in question has two scrollable elements (my fault for not polishing it) - one for the sandbox iframe and one for the virtuoso element itself. Can this be the source of confusion?
