### ISSUE TITLE
Scroll position jumps after auto scrolling during drag and drop

### ISSUE THREAD

**Issue by shawnshuang** [petyosi/react-virtuoso#706]
**Description**

I’m running into an issue where the scroll position jumps after I auto scroll while dragging and dropping an element. I’m also not sure if this issue is coming from how I’m using `react-virtual` or `dnd-kit` (the drag and drop library that I’m using), so I’m creating GitHub issues in both repos.

The issue seems to occur sporadically. It occurs only if there’s auto scrolling during drag and drop. And it occurs only if the auto scrolling is done downwards.

Do you think this issue is coming from how I’m using `react-virtual`? If so, would you have any suggestions on how I can get rid of the scroll jump?

**CodeSandbox**

Here is a simplified [CodeSandbox](https://codesandbox.io/s/scroll-jump-issue-trmygd) that reproduces the issue. I left comments to explain code from `dnd-kit` in case you’re not familiar with the library.

**Video**

Below is a video that illustrates the issue. You can see that the elements are dropped in the correct order in the list, but the scroll position shifts when the element is dropped, which is disorientating.

https://user-images.githubusercontent.com/7409323/178077096-42a9444b-dd71-4e91-8b9f-bf0985c96d25.mov

**Environment**

I’m currently using a Mac and Chrome.

---

P.S. Thank you for the effort you put into `react-virtuoso`! I've also tried `react-window`, `react-virtualized`, and `react-virtual`, and I've found `react-virtuoso` to be the easiest to use.

**Comment by petyosi** [comment]
By `react-virtual` I assume you mean react-virtuoso. I have no experience with `dnd-kit`, so I can't comment nor help with the integration specifics. Here's an integration example that works with [React Beautiful DND](https://virtuoso.dev/react-beautiful-dnd/). If you manage to make your setup work, feel free to submit a PR with a similar example.

**Comment by Elringus** [comment]
In case someone stumble upon this looking for virtuoso+dnd-kit example, I've found this one to be working fine: https://codesandbox.io/s/confident-morning-tv8hg?file=/src/App.js
