### ISSUE TITLE
Is it possible to prepend custom elements to the list?

### ISSUE THREAD

**Issue by mdegrees** [petyosi/react-virtuoso#71]
It would be helpful to add a search bar for example, similarly to what twitter does for messages search:
<img width="379" alt="Screen Shot 2020-02-17 at 10 39 21" src="https://user-images.githubusercontent.com/3754709/74641631-eb5b3980-5171-11ea-9d8c-31dcc502b5f7.png">

In reactWindow I used to do it this way:

1) Add a paddingTop to the list
```javascript
    const Item = ({ index, style }) => {
      const item = items[index];

      return (
        <div
          style={{
            ...style,
            top: `${parseFloat(style.top) + topPadding}px`
          }}
        >
          <ItemRendrer item={item} />
        </div>
      );
    };
```

2) Then, using the list container renderer, I place the customElement at top of the list 

```Javascript
const innerElementType = React.forwardRef(({ style, ...rest }, ref) => (
      <div>
        {customElement}
        <div
          ref={ref}
          style={{
            ...style,
            height: `${parseFloat(style.height) + topPadding}px`
          }}
          {...rest}
        />
      </div>
    ));
```
My first reaction was trying to replicate the same workaround in Virtuoso but found that the style is not passed down as a prop in ItemRendrer. Maybe there is a better/cleaner way. 

Thank you by the way for the this awesome piece of software!

**Comment by petyosi** [comment]
I am considering an optional header component, in the same way as the footer. Meanwhile, you can easily do something like this (which is not very elegant, but works:): https://stackblitz.com/edit/react-y6fim2?file=example.js

Let me know what you think about it.

**Comment by mdegrees** [comment]
Thanks for the quick reply. It works but with some caveats: appending the element as a list item makes it subject to virtualization so you end losing its state and you can't have it behave as a sticky item.

**Comment by petyosi** [comment]
You can pin it with the `topItems` attribute: https://stackblitz.com/edit/react-y6fim2-54opt7?file=example.js

**Comment by mdegrees** [comment]
Awesome! I was not planning to have search as a sticky item (similarly to Twitter messages search) but I'll do it for now waiting for the custom header option. Thank you!

**Comment by andrewfluck** [comment]
I was thinking about doing this, but it doesnt seem like groups have support for it

I'm going for this kind of look. only the inbox toolbar should stick.
<img width="323" alt="Screen Shot 2020-03-14 at 5 58 32 PM" src="https://user-images.githubusercontent.com/8619094/76691097-71598b80-661d-11ea-88fe-904a0150f7cd.png">

**Comment by mdegrees** [comment]
@petyosi is it possible to achieve this by prepending the header element using the ListContainer? It works but wanted to make sure it's not anti-pattern

```javscript
const ListContainer = ({ listRef, children, className, style }) => (
  <div
    ref={listRef}
    className={className}
    style={{ ...style }}
  >
  <div>Custom header html </div>
    {children}
  </div>
)
```

**Comment by petyosi** [comment]
@mdegrees - no, not a good idea.

**Comment by petyosi** [comment]
v1 (available as beta) includes support for Header in the components prop. It works in both flat and grouped mode. Installation instructions (and breaking changes) are described in #203.
