### ISSUE TITLE
[BUG] Scrolling up causes a flicking in chrome and safari/iOS

### ISSUE THREAD

**Issue by kazukinagata** [petyosi/react-virtuoso#723]
**Describe the bug**

Scrolling up causes a flicking on safari and chrome/iOS. Flicking seems to be especially noticeable if the list includes images. I don't get this problem with android or chrome/Windows.

**Reproduction**

https://codesandbox.io/s/laughing-lederberg-uc31wy

**To Reproduce**
1. Open the page.
2. Scroll up.

**Expected behavior**

Scroll up smoothly.

**Screenshots**

https://user-images.githubusercontent.com/4246353/182093283-336ec4e3-cf6c-44f7-aa03-ee44cf56d27f.MP4

**Desktop (please complete the following information):**
 - OS: iOS15.6
 - Browser: chrome and safari

**Additional context**

versions:
- react@18.1.0
- react-virtuoso@2.16.6

**Comment by petyosi** [comment]
I am aware of the problem but not of any possible solution. Mobile safari ignores `scrollBy` calls while scrolling is in progress, which means that the dynamic height compensation does not work. There's a workaround for that, but it does not come without flickering.

**Comment by kazukinagata** [comment]
@petyosi Appreciate your reply! 

Yes, I saw https://github.com/petyosi/react-virtuoso/issues/598.  Is the workaround you mentioned disabling Kinect in safari? I'm facing the issue with chrome as well as safari.
