### ISSUE TITLE
Repeated rendering of the message list

### ISSUE THREAD

**Issue by minzhang2** [petyosi/react-virtuoso#725]
I am developing a message list, which contains pictures, videos, files, and languages. The pictures are downloaded when they are in the visible area. I found that the component has been loaded and unloaded many times, causing the download to be triggered many times, and it will flash. I hope to give some advice.

https://codesandbox.io/s/sandpack-project-forked-8lyucr?file=/App.js

<img width="567" alt="image" src="https://user-images.githubusercontent.com/15793061/183875262-abf89531-45c8-4e0b-a238-19f300d518e3.png">

**Comment by petyosi** [comment]
That's how virtualization works by design. Items outside of the viewport are unloaded.

**Comment by minzhang2** [comment]
I know the logic of virtual scrolling. The sub-components are rendered many times, which causes me to download the image multiple times. I originally wanted to remember a status sign that the image is downloaded. Due to multiple loading and unloading, the page will flash.
