### ISSUE TITLE
[BUG] Virtuoso doesn't render inside MUI Grid

### ISSUE THREAD

**Issue by CezCz** [petyosi/react-virtuoso#729]
**Describe the bug**
Virtuoso renders with 0px width when embedded in MUI Grid component.

**Reproduction**
https://codesandbox.io/s/flamboyant-golick-u4qcxo?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome, safari

**Additional context**
I tried to wrap Virtuoso in divs with `display:block`, but it didn't help the issue

**Comment by petyosi** [comment]
You should debug what's wrong with this horizontal sizing: 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/13347/184353310-bf852e46-dd8f-4b58-b5df-31cb335e9896.png">

You can also bring that to MUI, I would not call it a problem in react-virtuoso.

**Comment by CezCz** [comment]
Hey @petyosi thanks for replying. I believe however that it still comes from react-virtuoso. I have refined the example and replicated without MUI. Please see https://codesandbox.io/s/flamboyant-golick-u4qcxo?file=/src/App.js

**Comment by CezCz** [comment]
Would you have any workarounds suggestions? That would be great
