### ISSUE TITLE
Disable stickiness on the group elements

### ISSUE THREAD

**Issue by thecynicalpaul** [petyosi/react-virtuoso#73]
Not sure if this is the right place to ask, but is there an intuitive way to disable the sticky positioning of the groups? I've looked through code and wasn't able to find any leads unfortunately. My current hacky solution is to have a `useEffect` hook that waits for my custom group component to render, then immediately resets its parent's class name. It does have a bit of initial delay though, so it's not ideal. Otherwise I feel like this is something really nice to have. Really love this library by the way, and thanks for putting so much work into it!

**Comment by thecynicalpaul** [comment]
Ah, never mind - just realized that there is a `GroupContainer` prop; overriding that and setting a different classname does the trick. 

```tsx
const GroupContainer: TItemContainer = ({
  children,

  ...otherProps
}) => {
  const classes = useStyles();

  return (
    <div {...otherProps} className={classes.dateRangeVirtualContainer}>
      {children}
    </div>
  );
};
```

**Comment by geovannimp** [comment]
Just to help if someone else gets here in the future, I found a even easier solution:

```
components={{
  TopItemList: Fragment,
}}
```
