### ISSUE TITLE
[Docs] Replace react-beautiful-dnd with @hello-pangea/dnd

### ISSUE THREAD

**Issue by Xhale1** [petyosi/react-virtuoso#732]
[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) is no longer maintained and will not support React 18.

I'm maintaining a fork [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) which supports React 18 and React strict mode, amongst other improvements.

`@hello-pangea/dnd` is a drop in replacement for `react-beautiful-dnd`, basically requiring a find-and-replace for imports.

Would you be open to a PR which migrated `react-beautiful-dnd` to `@hello-pangea/dnd`?

Also: just wanted to say that I use this library every day and absolutely love it. Thank you so much for your work :)

**Comment by petyosi** [comment]
Hi @Xhale1 - massive respect for stepping up to fix react-beautiful-dnd. I am happy to accept the following:
- a new example with @hello-pangea/dnd
- add deprecation notice + link to the new one to the react-beautiful-dnd

This way, traffic to the previous example won't be lost, and people will have clear visibility of the recommendation. 

I am also happy to discuss virtualization integration in the library, as (just like in your case) both react-virtualized and react-window are no longer maintained. The integration could be much more streamlined.

**Comment by Xhale1** [comment]
Sounds like a plan.

I'll submit a PR here with those changes, and I'll make a PR over at @hello-pangea/dnd which does the same for react virtuoso:
- Add a new react-virtuoso example
- Add a deprecation notice to the react-window and react-virtualized

I'll ping you here when those are done.

**Comment by Xhale1** [comment]
@petyosi I added some react-virtuoso examples to Pangea dnd in this PR: https://github.com/hello-pangea/dnd/pull/415

Feel free to check it out to make sure we're utilizing your lib as effectively as possible. Working on a PR for this lib now

**Comment by petyosi** [comment]
Thanks, that works for me, left a couple of comments.

**Comment by petyosi** [comment]
@Xhale1 let me know once you get to that.

**Comment by nika-sukhorukova** [comment]
Is there any plans for fixing typo conflicts in this integrations?
There are some typo-erros in those examples. You've done great job. Everything works, but my linter is getting crazy)
For example scrollRef in Virtuoso component didn't accepting DroppableProvided innerRef

TS2322: Type (a?: HTMLElement | null | undefined) => void is not assignable to type (ref: HTMLElement | Window | null) => any

**Comment by simpleneeraj** [comment]
Hey Thank you Buddy, Just fixed the issue in my existing project
