### ISSUE TITLE
[BUG] Flicker on mount

### ISSUE THREAD

**Issue by ehlor** [petyosi/react-virtuoso#734]
**Describe the bug**
The list flickers after mounting. It seems that after mounting, 3 frames are being rendered with the first 2 having incomplete lists, causing the flicker effect.

**Reproduction**
https://codesandbox.io/s/agitated-chaplygin-773c28

**To Reproduce**
1. Go to codesandbox above.
2. Click on the button.
3. The list flickers.

**Expected behavior**
Was expecting no flicker, with the first frame being of a complete list (especially when using such a small item count).

**Screenshots**
![image](https://user-images.githubusercontent.com/38947148/185472312-a34184cd-ece7-498a-917e-22e74769cb3a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome (Version 104.0.5112.81)

**Comment by petyosi** [comment]
Confirming, that's how rendering works by default. I am not aware of a way to avoid that. You can set defaultItemHeight to something, this would avoid the initial probe item render. If the default height is not correct though, it can slow down scrolling a bit (depending on how incorrect it is).

**Comment by resthedev** [comment]
> Confirming, that's how rendering works by default. I am not aware of a way to avoid that. You can set defaultItemHeight to something, this would avoid the initial probe item render. If the default height is not correct though, it can slow down scrolling a bit (depending on how incorrect it is).

Do we have some way to detect when Virtuoso has finished its initial load? That way, we can smoothly show the list only once it has been fully initially loaded. Right now, I am facing the same issue as OP where it follows this sequence:
- Renders no items
- Renders one item (index 0)
- Renders first load of items

This leads to the flickering effect which isn't elegant and it's jarring.

**Comment by resthedev** [comment]
> > Confirming, that's how rendering works by default. I am not aware of a way to avoid that. You can set defaultItemHeight to something, this would avoid the initial probe item render. If the default height is not correct though, it can slow down scrolling a bit (depending on how incorrect it is).
> 
> Do we have some way to detect when Virtuoso has finished its initial load? That way, we can smoothly show the list only once it has been fully initially loaded. Right now, I am facing the same issue as OP where it follows this sequence:
> 
> * Renders no items
> * Renders one item (index 0)
> * Renders first load of items
> 
> This leads to the flickering effect as it moves through these stages which isn't elegant and it's jarring.
> 
> For now I am doing the following, and it works but maybe native support might be worth considering:
> 
> ```
> <Virtuoso
>       style={{ height: "100%", width: "100%" }}
>       data={items}
>       itemContent={itemContent}
>       useWindowScroll={useWindowScroll}
>       overscan={overscan}
>       itemsRendered={(renderedItems: ListItem<D>[]) => {
>         if (renderedItems.length > 1) {
>           if (onLoaded) {
>             onLoaded();
>           }
>         }
>       }}
>     />
> ```

Bump. Any updates on this? It's leading to some scroll jumping issues currently in my application because of rendering 0 items -> rendering 1 item -> rendering full list of items.

**Comment by RanGojo** [comment]
@petyosi Any idea how can I fix the initial load problem here?
I'm setting `defaultItemHeight={102}` to avoid first render with 1 item but I've faced with another problem.

![Recording 2024-02-04 at 20 15 46](https://github.com/petyosi/react-virtuoso/assets/99180934/ca4ebf81-f9b8-4b91-9f47-e962a3ab18e3)

**Comment by petyosi** [comment]
@RanGojo I don't think that your problem is related to the subject of this issue. If you need me to examine your project in details and advise you accordingly, [sponsor the project](https://github.com/sponsors/petyosi/sponsorships?sponsor=petyosi&tier_id=50934) and contact me over the email in my profile.
