### ISSUE TITLE
React v16.13.0: Warnings for some updates during render

### ISSUE THREAD

**Issue by alexdrimbe** [petyosi/react-virtuoso#74]
I use GroupedVirtuoso in React v16.13.0 and I get this warning:
Warning: Cannot update a component from inside the function body of a different component.

**Comment by petyosi** [comment]
As far as I can see, there is no such error in this example: https://virtuoso.dev/grouped-numbers/

Can you reproduce so I can take a look?

**Comment by alexdrimbe** [comment]
Take a look at this example: https://stackblitz.com/run?file=example.js

**Comment by petyosi** [comment]
The URL from above is not saved and takes me to Stackblitz homepage. You used the button from there, you need to fork it afterwards.

**Comment by alexdrimbe** [comment]
Take a look at this example: https://virtuoso.dev/grouped-with-load-on-demand/ in StackBlitz.

**Comment by nuintun** [comment]
Same

![企业微信截图_20200227162119](https://user-images.githubusercontent.com/1730277/75519404-17ae6a00-5a3e-11ea-8ce7-842b663ea662.png)

**Comment by petyosi** [comment]
Yes, confirming that. I will look into it as soon as possible.

**Comment by petyosi** [comment]
I found a workaround which I am not happy with. I will think a bit over other potential means to deal with the problem.
