### ISSUE TITLE
[BUG] Switching from GroupVirtuoso to Virtuoso for same list doesn't remove groupContent headers

### ISSUE THREAD

**Issue by rupert-ong** [petyosi/react-virtuoso#741]
**Describe the bug**
When switching from a `GroupedVirtuoso` to a `Virtuoso` instance for a list via a toggle, the headers created by the `groupContent` method remains in the `Virtuoso` list instance.

**Reproduction**
https://codesandbox.io/s/toggle-virtuoso-8mx4jn?file=/App.js

**To Reproduce**
1. Go to the [CodeSandbox](https://codesandbox.io/s/toggle-virtuoso-8mx4jn?file=/App.js)
2. Notice the list is ungrouped and `<Virtuoso />` is rendered
3. Click on the Toggle button at the top
4. Notice the list is ungrouped and `<GroupedVirtuoso />` is rendered. Data is different for illustration purposes
5. Click on the Toggle button at the top again
6. `<Virtuoso />` is rendered (notice the data is the same from step 1 and 2) but the sticky headers from the `groupContent` method remain

**Expected behavior**
The sticky headers created by `groupContent` will not persist in the `<Virtuoso />` list.

**Screenshots**
First load (Virtuoso list):
![image](https://user-images.githubusercontent.com/1529337/186693325-7b538245-5d97-468d-b439-69834ff9224e.png)

After toggle click (GroupedVirtuoso list):
![image](https://user-images.githubusercontent.com/1529337/186693520-e25b59b1-dca9-44dd-a8ce-e57d79902f76.png)

After toggle click (back to Virtuoso list) - Error occurs here - sticky headers remain:
![image](https://user-images.githubusercontent.com/1529337/186693742-476a2c45-abfb-4f35-91b9-7f21edef9869.png)

**Desktop (please complete the following information):**
 - OS: Currently on Windows, but issue is probably not OS related
 - Browser: Chrome

**Additional context**
Thank you so much for this amazing package. All the best.

**Comment by petyosi** [comment]
That's a funny one for sure, I am not sure why this happens. Under the hood, both components are one, so my guess is that that render persists the grouped state. There's an easy fix though - add a key prop: 
https://codesandbox.io/s/toggle-virtuoso-forked-ungyhh?file=/App.js:1701-1722

**Comment by losidk** [comment]
nice question and nice answer
