### ISSUE TITLE
 an item is considered "in view" if the top of the item is within view, not the whole item (or actually top AND bottom of the item). 

### ISSUE THREAD

**Issue by petyosi** [petyosi/react-virtuoso#748]
An item is considered "in view" if the top of the item is within view, not the whole item (or actually top AND bottom of the item). I'm attaching a screencast to show the issue. Notice that the bottom item is barely visible at the beginning, everything works fine as long as the top of the item you are scrolling is not visible :) (This is virtuoso 2.18.0)
[Screencast from 07. sep. 2022 kl. 09.16 +0200.webm](https://user-images.githubusercontent.com/59087796/188817372-1121cdb7-8a33-4df4-8106-0d60d58c3c42.webm)

_Originally posted by @mortmoe in https://github.com/petyosi/react-virtuoso/issues/745#issuecomment-1239015871_

**Comment by mortmoe** [comment]
Cool. Thanks for the great work and quick responses :) I'm in the process of refactoring several virtualized lists in my app to Virtuoso and really appreciate it. It simplifies the components a lot and just works better :D

**Comment by Nathan-Notifi** [comment]
Dealing with this too. I'd like to set it for prepending items where the bottom of the virtualized item is used

**Comment by maccman** [comment]
We are seeing this issue crop up in Reflect too.


https://user-images.githubusercontent.com/2142/193395399-178aeaae-73a9-48f9-bb1d-997fdd767a08.mp4

**Comment by petyosi** [comment]
@mortmoe @maccman I need your help to nail this down. I thought that I had the boundary logic messed up, but it turned out not to be the case - at least from what I see here: https://github.com/petyosi/react-virtuoso/blob/7f91b3201ec8371f25609bdfdaf3d5451e6f7871/src/scrollIntoViewSystem.ts#L23-L32

Also, I thought that the website example is overly simplistic by having the container being an exact multiplier of the item sizes. But forking it and modifying it seems to be working fine in [this sandbox](https://codesandbox.io/s/virtuoso-keyboard-nav-z7gtwh). 

What am I missing?

**Comment by petyosi** [comment]
@maccman @mortmoe , the problem was specific to the table, not considering the header/footer sizes.

**Comment by maccman** [comment]
@petyosi you are a hero!

**Comment by mortmoe** [comment]
@petyosi Thanks, works like a charm now :D
