### ISSUE TITLE
[BUG] zero sized element - not always a problem?

### ISSUE THREAD

**Issue by getnashty** [petyosi/react-virtuoso#749]
**Describe the bug**
In my use case, I occasionally hide a row... or a group of rows.. when they are meant to be "hidden" I just render an empty `<div />`, the javascript warning `Zero-sized element, this should not happen {child: div}` appears...

Now I understand why this happens.. but functionally, things work great... I can hide/show rows without issue...

I know if I want to get rid of the warning, I can set the height to be 1px... the issue is if I'm hiding a group of rows... those 1px's add up to be a big empty space..

My primary question here... is there any other way to just quiet this error? 

My second question, is there any case I'm not considering where this will become an issue? I've tested 100+ items, hiding 10+ rows in the middle and making them appear again with no issues at all (aside from this console warning).

Thanks!

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by petyosi** [comment]
You're welcome. I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
