### ISSUE TITLE
[BUG] VirtuosoGrid components props List type error?

### ISSUE THREAD

**Issue by tkmin** [petyosi/react-virtuoso#750]
I get type error at components={{ List: ListContainer }}

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-lhokkr?file=/App.tsx

**Expected behavior**
No type error?

**Screenshots**
![Screen Shot 2022-09-13 at 4 33 32 PM](https://user-images.githubusercontent.com/83566566/189839252-38271eab-94d0-42d5-a2af-90d328655305.png)

**Comment by petyosi** [comment]
This is some fun stuff from the [TS type system](https://medium.com/@thejameskyle/type-systems-covariance-contravariance-bivariance-and-invariance-explained-35f43d1110f8) and the ref prop.

You can work around it like this: 

```
const ListContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
` as GridComponents["List"]; // Import the GridComponents from 'react-virtuoso'
```

**Comment by tkmin** [comment]
> This is some fun stuff from the [TS type system](https://medium.com/@thejameskyle/type-systems-covariance-contravariance-bivariance-and-invariance-explained-35f43d1110f8) and the ref prop.
> 
> You can work around it like this:
> 
> ```
> const ListContainer = styled.div`
>   display: flex;
>   flex-wrap: wrap;
> ` as GridComponents["List"]; // Import the GridComponents from 'react-virtuoso'
> ```

Thank you!
