### ISSUE TITLE
[BUG] Virtuoso with custom scroll component jumps back to top of page

### ISSUE THREAD

**Issue by tomh05** [petyosi/react-virtuoso#756]
**Describe the bug**
When a custom scrolling component is used [as per the example in the docs](https://virtuoso.dev/custom-scroll-container/#list-with-custom-scroller), Virtuoso jumps back to the top whenever the component is re-rendered.

**Reproduction**

https://user-images.githubusercontent.com/1915147/193610752-a3ad421b-1f0b-491d-8bb5-782b5f8d47bd.mov

(Video has sound 🔈 ) 

Code repro here https://codesandbox.io/s/sandpack-project-forked-k37cbh?file=/App.js

**To Reproduce**
Follow steps in [codesandbox](https://codesandbox.io/s/sandpack-project-forked-k37cbh?file=/App.js), or 
1. Create an example based on the [Virtuoso Docs for a custom scroll component](https://virtuoso.dev/custom-scroll-container/#list-with-custom-scroller)
2. Add something that causes the component to re-render (e.g. a prop change)
3. Scroll down in the virtuoso view
4. Trigger the re-render.
5. Virtuoso will jump to the top.

**Expected behavior**
The virtuoso view should stay in the same position.

**Desktop**
Chrome on Mac OS

**Comment by tomh05** [comment]
Thank you! 🥳

**Comment by lexahall** [comment]
Thank you!
