### ISSUE TITLE
[BUG] scrollToIndex not working in useEffect on first render

### ISSUE THREAD

**Issue by addemod** [petyosi/react-virtuoso#757]
**Describe the bug**
When calling `scrollToIndex` inside useEffect, the view is not scrolled to the specified index on first render.

The view will scroll to the correct index on the next render, but never the **first**, so it feels like there's some problem with the useEffect calling the method before the component is ready.

This could probably be solved by some "onReady" callback on the component.

**Reproduction**
https://codesandbox.io/s/empty-frost-of7hl1

**To Reproduce**
1. Create a Virtuoso list or grid with a ref (doesn't matter if grid or list)
2. Call `scrollToIndex` inside the useEffect on the ref
3. The view is not scrolled to the specified index on first load
4. Click the button to force a re-render
5. The view is now scrolled to the correct index

**Expected behavior**
The view is supposed to be scrolled to the specified index when the component is ready, when using useEffect on the component ref.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (Version 106.0.5249.91)

**Additional context**
Can be solved by setting some timeout around the `scrollToIndex` call:
`setTimeout(() => ref.current.scrollToIndex(500), 50);`

**Comment by petyosi** [comment]
Don't do that. Use `initialTopMostItemIndex`.

**Comment by addemod** [comment]
`initialTopMostItemIndex` does not exist for grid unfortunately..
