### ISSUE TITLE
Pass rest props to ScrollContainer?

### ISSUE THREAD

**Issue by nuintun** [petyosi/react-virtuoso#76]
Now rest props will not be passed to the ScrollController, but sometimes we need to get rest props in the ScrollContainer!

**Comment by petyosi** [comment]
@nuintun If I understand you correctly, you can use custom scroll container for that purpose: 
https://virtuoso.dev/custom-scroll-container/

**Comment by nuintun** [comment]
@petyosi See:
```jsx
import React, { useRef } from 'react'
import { Virtuoso } from 'react-virtuoso'
import { getUser } from './FakeData'
import { UserItem } from './ExampleComponents'

const GenerateItem = index => {
  return <UserItem user={getUser(index)} index={index} />
}

// className is string | undefined, passed from
// the root component
//
// style is CSSProperties, setting the size and the
// overflow of the element. You may have to discard
// some of those if setting up a custom scroller.
//
// scrollTo is an event emitter, which executes
// the callback when the scrollToIndex method is called
//
// reportScrollTop should be wired up to the onScroll event,
// passing the current scrollTop position
const MyScrollContainer = ({
  className,
  style,
  reportScrollTop,
  scrollTo,
  children,
  onScroll
}) => {
  const elRef = useRef(null)

  scrollTo(scrollTop => {
    elRef.scrollTo({ top: scrollTop })
  })
  
  // Can't get onScroll prop here
  console.log(onScroll)

  return (
    <div
      ref={elRef}
      onScroll={e => reportScrollTop(e.target.scrollTop)}
      style={{
        ...style,
        border: '5px dashed gray',
        borderRadius: '4px',
      }}
      tabIndex={0}
      className={className}
    >
      {children}
    </div>
  )
}

export default () => (
  <Virtuoso
    ScrollContainer={MyScrollContainer}
    totalCount={1000}
    overscan={200}
    item={GenerateItem}
    onScroll={()=>true}
    style={{ height: '400px', width: '350px' }}
  />
)
```

**Comment by petyosi** [comment]
You don't have to pass `onScroll` through the Virtuoso component props; you can compose it [like this](https://stackblitz.com/edit/react-5vz9nl?file=example.js), for example.

**Comment by nuintun** [comment]
@petyosi  LGTM, 3Q~

**Comment by nuintun** [comment]
@petyosi 

I tried your idea, but there were some bugs: [Custom Scroll Container](https://stackblitz.com/edit/react-virtuoso?file=example.js), F12 and see console.

Scroll Container will be destroyed after update!

**Comment by petyosi** [comment]
You can use `useCallback` [like this](https://stackblitz.com/edit/react-virtuoso-i5qbqr?file=example.js). useMemo will probably work as well.

**Comment by nuintun** [comment]
@petyosi 

I've tried before, but if useMemo, `MyScrollContainer` will not be able to receive new props!

See: [Custom Scroll Container](https://stackblitz.com/edit/react-virtuoso?file=example.js).

**Comment by petyosi** [comment]
To be honest, I am getting lost in this example. If you feel like you can achieve your requirements by passing additional properties to the ScrollContainer, I suggest that you fork the project for now, implementation of that should be fairly easy.
