### ISSUE TITLE
Transpose items in the grid

### ISSUE THREAD

**Issue by hamza1311** [petyosi/react-virtuoso#761]
Currently, the grid displays items as:

| | |
|- | -|
| 1 | 2 |
| 3 | 4 |

I would like to display them as 

| | |
|- | -|
| 1 | 3 |
| 2 | 4 |

Is that possible? If not, I would like to see this feature implemented

**Comment by petyosi** [comment]
Everything the library [supports is documented](https://virtuoso.dev/) - you can also read the source code. If you're interested in sponsoring the development of a certain feature, contact me over email so we can discuss the scope. Alternatively, you can submit a PR.
