### ISSUE TITLE
When using virtuoso my menu gets covered/overlayed

### ISSUE THREAD

**Issue by michalzard** [petyosi/react-virtuoso#762]
![image](https://user-images.githubusercontent.com/58849789/194769041-0558a691-f158-4dee-a35d-4e04fe59dd03.png)

![image](https://user-images.githubusercontent.com/58849789/194769170-96a84b90-5e6f-4c8a-b28e-beb678ff830b.png)

When i click away before menu window closes the rest of items appear for a moment. 
Any ideas what could this cause? Perhaps do i have my Virtuoso setup incorrectly?

**Comment by michalzard** [comment]
It appears there's a bug where if im rendering virtuoso inside Mui Select element it covers the bottom part

**Comment by petyosi** [comment]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue.
