### ISSUE TITLE
[BUG] Rerender blink when using data (server side rendering)

### ISSUE THREAD

**Issue by blahbleepew** [petyosi/react-virtuoso#763]
**Describe the bug**
When you use initial items and data together it causes a re-render even though the data hasn't changed. This happens on vite-plugin-ssr, I could not reproduce with nextjs. It doesn't seem to happen when data isn't specified. specifying the height/width of the container or the items doesn't prevent it either.

**Reproduction**
https://codesandbox.io/s/charming-tu-jj09iu?file=/pages/index/index.page.jsx

**To Reproduce**
Click refresh

**Expected behavior**
It shouldn't rerender

**Screenshots**
![image](https://s7.gifyu.com/images/ezgif-3-800f2be10b.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave, Chromium

**Comment by petyosi** [comment]
Confirming that. It's weird that it does not happen in nextjs, though.

**Comment by blahbleepew** [comment]
@petyosi I could be wrong on that. I only briefly tested with nextjs, perhaps it wasn't being server-side rendered and I didn't realize it

**Comment by yokunjon** [comment]
I also experience this, using Remix, it does SSR, then on hydration rerender and flashing for a moment. I don't have a reproducable sandbox but I'll try providing one when I have the time.

**Comment by Katona** [comment]
I also experience it with NextJS, too.

**Comment by Melnychuk-27** [comment]
has anyone solved this problem?

**Comment by 12evgen** [comment]
I confirm that the error is still there. @petyosi Any ideas how to fix this?

**Comment by petyosi** [comment]
Everyone, please check how it works in v4.5.1. The behavior should be fixed. 

Cheers,
