### ISSUE TITLE
TableVirtuoso with react-table and useRowSelect remounting every table row[BUG]

### ISSUE THREAD

**Issue by csalem0105** [petyosi/react-virtuoso#764]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you choose to ignore the above, I am likely going to delete the issue. 

**Describe the bug**
When using TableVirtuoso with react-table and the useRowSelect hook every time you click a checkbox every row in the table is unmounted and remounted causing slowness issues.

**Reproduction**
[Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.]
https://codesandbox.io/s/sandpack-project-forked-xz8xrh?file=/App.js

**To Reproduce**
1. Go to 'the above codesandbox link
2. Click on 'Click any checkbox
3. Open console and see how every row is remounted

**Expected behavior**
Do not remount every row, instead rerender

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by petyosi** [comment]
https://virtuoso.dev/customize-structure/ - read the docs.
