### ISSUE TITLE
[BUG] initialTopMostItemIndex={undefined} causes runtime error

### ISSUE THREAD

**Issue by ondrejsevcik** [petyosi/react-virtuoso#777]
**Describe the bug**

According to the typescript typing, the property `initialTopMostItemIndex` is optional. But when `undefined` is passed into it, it causes runtime error.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4136929/196902203-3543782a-2112-40b6-9331-9670ef8f5db4.png">

**To Reproduce**
1. Go to https://codesandbox.io/s/boring-lamarr-eoks7x?file=/src/App.js
2. Change `initialTopMostItemIndex` from undefined to 0 and it will work.

**Expected behavior**

The TypeScript definiton should be updated or it should be possible to pass `undefined` into this property.

**Comment by petyosi** [comment]
This has been discussed on several occasions (here: https://github.com/petyosi/react-virtuoso/issues/532). I don't plan on supporting passing `undefined` to properties. The component has a complex internal state, so many of the properties actually work like calling a method - and undefined is ambiguous.

**Comment by petyosi** [comment]
I have not given this enough attention, but I am not sure if the typings themselves are to be changed or you need to do this on the project side: https://github.com/microsoft/TypeScript/issues/44421. Happy to accept a PR if you have the time to dive into the issue.

**Comment by ondrejsevcik** [comment]
The List component explicitly allows to pass `undefined` according to it's typings. I suppose this property is optional on purpose.

https://github.com/petyosi/react-virtuoso/blob/374f024f8c9bb4ed14505e4a57f75efa011e03c2/src/components.tsx#L80

I'm not sure why it works when you omit the property altogether, but when you pass undefined to it it breaks. Practically speaking, those two should be identical. 

```jsx
<Virtuoso data={data} />
// vs. 
<Virtuoso data={data} initialTopMostItemIndex={undefined} />
```

**Comment by petyosi** [comment]
Check the link I sent [and this one](https://github.com/microsoft/TypeScript/pull/43947). There is a difference between
```ts
property: number | undefined
```

and
 
```
property?: number
```

I believe that the typings are correct.

**Comment by ondrejsevcik** [comment]
@petyosi thank you for the link. I see now how these two are different.

Though, I think this will keep coming back to you - especially since this setting is not [enabled by default in TS](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes).

Anyway, I appreciate you looking into this. Thank you for your time 🙏🏽  I will close this issue now.
