### ISSUE TITLE
[BUG] scrollToIndex not working with useWindowScroll 

### ISSUE THREAD

**Issue by afonsopbarros** [petyosi/react-virtuoso#779]
I noticed this previous issues: https://github.com/petyosi/react-virtuoso/issues/284 says it's fixed in 1.5, I'm trying to achieve the same scenario, it works with useWindowScroll={false}, but not with true. Using 2.19 currently

Tested in https://github.com/petyosi/react-virtuoso/issues/284 sandbox link with 2.19.1 virtuoso, there was probably a regression, doesn't work there either.

**Comment by petyosi** [comment]
284 does not have a sandbox. Please create one and post it here, I will look into it and re-open the issue accordingly.

**Comment by afonsopbarros** [comment]
the sandbox was posted in the other issue: https://stackblitz.com/edit/react-xbdrl5 I just changed the version on package.json and it doesn't work.

**Comment by petyosi** [comment]
https://stackblitz.com/edit/react-xbdrl5?file=src%2FApp.js. This works for me.
