### ISSUE TITLE
rangeChanged not being called in GroupedVirtuoso.tsx

### ISSUE THREAD

**Issue by ysael** [petyosi/react-virtuoso#78]
Hi, 

it seems that the CB for the rangeChanged is not working the Grouped version. 

I also see that it seems to be missing here -> 
https://github.com/petyosi/react-virtuoso/blob/2c098fdeb8620d641103e7f315d292b65e75a859/src/GroupedVirtuoso.tsx#L31 

I could help with the pr :) 

thanks again for the great work!

**Comment by petyosi** [comment]
Thank you for your offer! PR is more than welcome.

**Comment by ysael** [comment]
PR on its way then :) quick question, how do we run the `Playground` ? 

thanks

**Comment by petyosi** [comment]
yeah, I need to put this in the README. 

`npx parcel playground/index.html` or whichever .html file you wish to test.

**Comment by ysael** [comment]
pr un-drafted and it seem to fix the issue :)

**Comment by petyosi** [comment]
Looks good to me, I will get to that later in the week and merge it with the other open one.

**Comment by ysael** [comment]
fixed thanks!!
