### ISSUE TITLE
[BUG] Endless Scrolling Table (MUI) - Snapping back to first item when more data loaded 

### ISSUE THREAD

**Issue by dylan1p** [petyosi/react-virtuoso#780]
**Describe the bug**
Using the TableVirtuoso component together with **MUI components** has a strange side effect once the data changes in length (more items loaded). In my case I'm fetching more data when the endReached callback is triggered. 
Once the data is loaded, this results in the scrollIndex returning to the first item. 

This only seems to happen when using the TableVirtuoso component together with MUI components as [here](https://codesandbox.io/s/sandpack-project-forked-lq3ifp) we can see everything working fine when the basic table example from the docs is extended to fetch data after scrolling to the end of the table.

Am I doing something wrong or is this a bug?

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-uwujdm

**To Reproduce**
1. Scroll to end of the table.
2. Wait for more items to be loaded.
3. See table snaps back to first item.

**Expected behavior**
Table maintains the same items in view as before new items are loaded.

**Screenshots**
https://user-images.githubusercontent.com/3330972/198025017-141b764c-7b67-437e-bf41-a526eebea4b1.mov

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Chrome

**Comment by petyosi** [comment]
From [the docs](https://virtuoso.dev/customize-structure/) and from a search in the GH issues:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/13347/198047594-95427637-58a0-402a-8ca0-43dcd9bb15d1.png">

https://github.com/petyosi/react-virtuoso/issues/756

**Comment by dylan1p** [comment]
Thank you! Would you like me to fix the MUI Table example, to avoid someone else running into this issue? -> https://codesandbox.io/s/7ybnok

**Comment by petyosi** [comment]
That would be great @dylan1p - I realized that the docs I have might have it somewhere for you to follow that pattern.

**Comment by adirzoari** [comment]
@dylan1p  @petyosi same issue, did u find a solution?

**Comment by adirzoari** [comment]
@petyosi @dylan1p I did this way:[https://codesandbox.io/s/sandpack-project-forked-3bbhpi?file=/App.js:1006-1015]( https://codesandbox.io/s/sandpack-project-forked-3bbhpi?file=/App.js:1006-1015)
but when I'm trying to add loading skeleton indication when load more data into the tableBody it cause re-render again.. what the best way to add loader in the bottom of the table to show load more data skeleton?
