### ISSUE TITLE
[BUG] list items not displayed if IOS v <=14.0 

### ISSUE THREAD

**Issue by AlexeiTolstonoh-ab-inbev** [petyosi/react-virtuoso#782]
Hello everyone, I have a bug on IOS v <=14.0
In my case, I'm trying to make infinite scroll without any tricks.
I also tried this for iOS versions:
13.3.1
13.3
13.2.3
12.5.5
12.4.1
12.3.1
But it doesn't work anywhere.

If the IOS version is higher or the Android platform, everything works great.
I use the official documentation to implement the functionality.
Perhaps you have an idea how this can be fixed and why this is happening?
Thanks

**Comment by petyosi** [comment]
you're probably missing the resizeobserver polyfill: https://github.com/petyosi/react-virtuoso/issues/782
