### ISSUE TITLE
[BUG] VirtuosoGrid showing 2 items when totalCount is 1

### ISSUE THREAD

**Issue by kelokchan** [petyosi/react-virtuoso#783]
**Describe the bug**
VirtusoGrid showing 2 items even though there's only 1 item 

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-n0sqog?file=/App.js

**To Reproduce**
1. Set `totalCount` to just `1`

**Expected behavior**
Should only show 1 item in the list 

**Screenshots**
![image](https://user-images.githubusercontent.com/5347725/199640635-cedcb4b6-7877-42f3-8ea5-cbb6735fa11f.png)

**Desktop (please complete the following information):**
- Mac OS
- Chrome

**Additional context**

**Comment by petyosi** [comment]
I think I broke that recently, will take a look.

**Comment by eikeon** [comment]
I believe this is the same issue I hit when upgrading from 3.1.1 to 3.1.2
