### ISSUE TITLE
[BUG] Elements flash into viewport when in a Tippy tooltip

### ISSUE THREAD

**Issue by itayganor** [petyosi/react-virtuoso#784]
**Describe the bug**
When there's a virtualized list inside a `<Tippy>` component, a flash is observed for elements entering the viewport.

**Reproduction**
Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

**To Reproduce**
1. Go to https://codesandbox.io/s/virtuoso-tippy-bug-0oxjls?file=/src/App.tsx
2. Scroll the list and see that everything works as expected.
3. Hover on "Hover me!"
4. Slowly scroll the virtualized list in the tooltip and see elements flash as they come in

**Expected behavior**
Just like in the regular list, elements should not flash.

**Screenshots**
![smoothbad (-3)](https://user-images.githubusercontent.com/6430313/200144438-d829a164-361c-4a23-975e-8c90fae24f51.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11, Latest
 - Browser: Chrome 107

**Additional context**
I guess this issue may be reproducible without using Tippy specifically.

**Comment by petyosi** [comment]
I believe that this is something related to the styling of Tippy that messes with the viewport sizing calculations. Hard to debug it. Can you reproduce outside of that lib? If so, let me know, I'll reopen and take a look.
