### ISSUE TITLE
[BUG] List struggles to "keep up" when scrolling fast when using React 18

### ISSUE THREAD

**Issue by glocore** [petyosi/react-virtuoso#785]
**Describe the bug**
When using React 18 with the new `createRoot().render()`, a brief blank area is seen when scrolling fast. This isn't observed when using React 17 or with React 18 in legacy mode.

**Reproduction**
With React 18 (forked from the sandpack in the getting started docs): https://codesandbox.io/s/sandpack-project-forked-mgmdo2
With React 17 (the original sandpack in the getting started docs): https://codesandbox.io/s/kh0fpq?file=/App.js

**Screenshots**
With React 18 (using `createRoot().render()`)

https://user-images.githubusercontent.com/24620401/200177660-694768d7-0871-432a-8b4f-f6cec214a0b7.mov  

With React 17

https://user-images.githubusercontent.com/24620401/200177679-ee1a0b45-79e5-4b5c-8255-73010f71aff0.mov  

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0
 - Browser: Google Chrome v107, Safari 16.1

**Comment by glocore** [comment]
I've also noticed the same issue in `react-window`.

**Comment by petyosi** [comment]
That's a valid report, I am aware of the issue. So far, I managed to find the necessary change, but it is not compatible with the traditional renderings. More details here: https://github.com/petyosi/react-virtuoso/issues/647.

**Comment by petyosi** [comment]
@glocore this is (I believe) improved in v4.0.0 (just published it).

**Comment by rzeinalli** [comment]
@petyosi Thanks for the such a great library. Really appreciated! 

I want to ask that, I'm on `react-virtuoso@4.1.0` with `react@18.2.0`, but still have blank even with 60-70 items in my list, but I'm using TableVirtuoso + Chakra-UI table components. Is it possible just rendering with library expensive and causes lag and blank page?

https://user-images.githubusercontent.com/111286191/225909793-8feb4f9c-e54a-4c9e-8dff-dbabb49267d5.mov

**Comment by rufatZZ** [comment]
@petyosi Thanks for the such a great library. Really appreciated! 

I want to ask that, I'm on `react-virtuoso@4.1.0` with `react@18.2.0`, but still have blank even with 60-70 items in my list, but I'm using TableVirtuoso + Chakra-UI table components. Is it possible just rendering with library expensive and causes lag and blank page?

https://user-images.githubusercontent.com/111286191/225909793-8feb4f9c-e54a-4c9e-8dff-dbabb49267d5.mov

**Comment by jamilalisgandarov** [comment]
@petyosi Hi there, I am still experiencing this issue on v4.6.2 (React 18).
