### ISSUE TITLE
[BUG] Multiple virtuoso in the same page will cause unexpected scroll behavior 

### ISSUE THREAD

**Issue by KKzLEO** [petyosi/react-virtuoso#786]
**Describe the bug**
https://codesandbox.io/s/sandpack-project-forked-jzsscm?file=/App.js

Hi, thanks for creating this awesome library, I encountered a weird behavior that If there are two grids in the same page and share the same scroller(window scroller), some weird scroll behavior would happen when we're scrolling, e.g. the screen starts pulsing when scrolling to some position or I can't scroll down to the end. Is it forbidden that using two virtuoso in the same page or did I do something wrong? thank you so much

https://user-images.githubusercontent.com/26006239/201289432-214c4dca-97c7-4f2d-b8ae-8d1ad7e53ae2.mp4

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-jzsscm?file=/App.js

**To Reproduce**
1. Scroll down slowly
2. See error

**Expected behavior**
1. Scolling smoothly

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome 107.0.5304.88
 - Virtuoso version: 3.1.3

**Comment by petyosi** [comment]
The sandbox you've linked does not match what I am seeing in the video. Keep in mind that the grid needs same sized items to work correctly.

**Comment by KKzLEO** [comment]
> The sandbox you've linked does not match what I am seeing in the video. Keep in mind that the grid needs same sized items to work correctly.

sorry, I've updated the link

**Comment by petyosi** [comment]
> The grid needs same-sized items to work correctly.
