### ISSUE TITLE
Feature request: Support different height of row and different number of item in row

### ISSUE THREAD

**Issue by khmelevskii** [petyosi/react-virtuoso#793]
I'm trying to virtualize grouped list which implemented as a flat list
This is a result
<img width="660" alt="image" src="https://user-images.githubusercontent.com/668591/202576567-307616f9-6999-4e5c-b97c-2d248bdba49e.png">

This is component
```
<Grid>
  <Header />
  <Block />
  <Block />
  <Block />
  <Block />
  <Header />
  <Row />
  <Row />
  <Row />
  <Row />
</Grid>
```
Any ideas how such layout can be virtualized?

**Comment by petyosi** [comment]
I don't provide free support through Github issues. If you want to ask for support or request features, consider [sponsoring the project](https://github.com/sponsors/petyosi).
