### ISSUE TITLE
[BUG] Items are not correctly removed from react-hook-forms field array

### ISSUE THREAD

**Issue by alexanderkogan** [petyosi/react-virtuoso#798]
**Describe the bug**
When using a field array from react-hook-forms with TableVirtuoso, items aren't correctly removed from the array.

**Reproduction**
I could reproduce the issue with this codesandbox: https://codesandbox.io/s/fieldarraytablevirtuoso-chl9cs
It is only visible in the console though, when you click the submit button.

**To Reproduce**
1. https://codesandbox.io/s/fieldarraytablevirtuoso-chl9cs
2. Open the Console
3. Click on 'Append'
4. Click on 'Send'
5. See an array of length 2 printed out.
6. Click on 'Delete'
7. Click on 'Send'
8. See an array of length 2 erroneously printed out.

**Expected behavior**
The onSubmit function should receive an array of length 1, the array seems to be stale though.
Without TableVirtuoso the array behaves as expected, see: https://codesandbox.io/s/fieldarraymap-8f3x6y

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome, Firefox

**Comment by petyosi** [comment]
I have no experience with react-hook-forms, and I have no idea how can the table implementation (or the virtualization, for that matter) can cause that problem. The code you've posted looks right to me, but I don't know the gotchas of that library. 

GIven that, I can't help you. Feel free to investigate and submit a PR if you find something.
