### ISSUE TITLE
[BUG] Flex-wrap list jumping / scrolling by itself

### ISSUE THREAD

**Issue by luizfm** [petyosi/react-virtuoso#799]
**Describe the bug**
When using display: flex + flex-wrap: wrap, the list keeps jumping and scrolling by itself. It's possible that’s because the flex-wrap: wrap and virtualized list are conflicting somehow.

**Reproduction**

https://user-images.githubusercontent.com/45155140/205326220-4c91942b-003c-4633-99aa-e62ae850147f.mov

**Expected behavior**
I not pretty sure if we have an offset to be set in this case, but I couldn't find an easy solution for this.

**Comment by petyosi** [comment]
That's not supported.

**Comment by nemonemi** [comment]
A bit more comprehensive and constructive answer would be appreciated.
Like, if one experiences this type of scrolling, which is surely not an expected, or desired behavior, how to go ahead about it? What best practices would you propose to avoid such a behavior, if there's no fix to follow this up?

**Comment by petyosi** [comment]
It's great that you have such expectations from the level of support in this project. In that case, look at the sponsors' option - this will allow me to devote more time to answering your questions.
