### ISSUE TITLE
Use with react-custom-scrollbars

### ISSUE THREAD

**Issue by mcastro84** [petyosi/react-virtuoso#8]
Could this library be used alongside react-custom-scrollbars? I was previously using react-window and this was supported by passing a ref of the rendered list to react-custom-scrollbars onScroll method but doing the same seems to not work with virtuoso as the ref is not a DOM element.

I've attached an example of what I'm trying to achieve.
Edit: here's the link - https://codesandbox.io/s/practical-bouman-z6wqd

**Comment by petyosi** [comment]
Thank you for the suggestion - this should be easy to do if the component exports render property that allows customization of the scrolling container. I will give this a shot.

**Comment by petyosi** [comment]
@mcastro84 I managed to do the idea described above, will include it in the next release. Quick question - what are you trying to achieve? If you are trying to scroll to a given index or location, I plan to do that as part of the core API of the component.

**Comment by mcastro84** [comment]
Thanks for the quick reply petyosi.
Scrolling to a specific index would be great also but at the moment I'm just trying to scroll the list using the custom scrollbars instead of using the native scrollbar.
My approach to this was to get the ref of the list container (in this case <Virtuoso>), get the scrollTop value every time the list is scrolled and then trigger the event scroll manually.

As an example, in the codesandbox code, I'm generating 100 items but when I scroll only 17 items show and that seems to be because Virtuoso isn't aware that the list is being scrolled.

Again, thanks for your help

**Comment by petyosi** [comment]
Hey, 

just published `v0.5.0` that provides access to the scroll container and allows you to swap it with a something like the custom scrollbars component. You can check the [example](https://virtuoso.dev/custom-scroll-container)  and use it as a starting point for your implementation. 

Let me know if the above works for you.

**Comment by mcastro84** [comment]
Thank you petyosi, that should do the trick. I'll give it a try and get back to you.
