### ISSUE TITLE
[BUG] Header not taken into account when initially scrolling to top

### ISSUE THREAD

**Issue by ramirez** [petyosi/react-virtuoso#805]
**Describe the bug**
I have a very simple virtuoso list and I'm using a header component that is a div with some text on it. When initially loading the page, my list always starts scrolled to the first element of the list, skipping below the header.

**To Reproduce**
Create a simple virtuoso list with a somehow large header component.

**Expected behavior**
I expect the list to start at the top of the list, including the header, unless instructed to scroll to a specific item, or allow to specify the header

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS.
 - Browser chrome, safari, firefox.

**Comment by petyosi** [comment]
Please provide a minimal reproduction in a sandbox. I will reopen the issue once that's here.
