### ISSUE TITLE
[BUG] - onScroll event is not firing when useWindowScroll={true}

### ISSUE THREAD

**Issue by andrisole92** [petyosi/react-virtuoso#812]
**Describe the bug**
I have a simple Virtuoso list. When enabling `useWindowScroll` the onScroll callback is not firing.

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-dst6gf?file=/App.js

**To Reproduce**
1. Go to Code Sandbox
2. Toggle useWindowScroll
3. Scroll with useWindowScroll enabled to see there is no console output
4. Scroll with useWindowScroll enabled to see there is console output

**Expected behavior**
onScroll should be triggered

You are welcome for this bug report!

**Comment by petyosi** [comment]
See #674.

**Comment by andrisole92** [comment]
I think you are closing issues too fast. My problem isn’t really solved and you are marking it as completed.

I think you need to update docs to reflect this at least.

I am looking for a way to block scrolling temporarily.
