### ISSUE TITLE
[BUG] Documentation site appears broken

### ISSUE THREAD

**Issue by six-transit** [petyosi/react-virtuoso#814]
**Describe the bug**

None of the codesandbox examples appear to be working at the moment:

![image](https://user-images.githubusercontent.com/96151753/210463211-031fe0df-ed2d-4276-b5d8-2e0e02426a09.png)

**To Reproduce**

1. Navigate to https://virtuoso.dev/
2. Scroll down a bit

**Expected behavior**

Examples on documentation site are functional

**Comment by petyosi** [comment]
Thanks for that! Apparently, codesandbox is picky about `* as React` imports and modules, might be an issue in other environments too.
