### ISSUE TITLE
[BUG] Scroll position is not maintained when changing previous overscan row heights

### ISSUE THREAD

**Issue by adamsas** [petyosi/react-virtuoso#822]
**Describe the bug**
There seems to be an issue where the scroll position "jumps" when rows in the reverse overscan are changing their heights.

**Reproduction**
Code sandbox: [https://codesandbox.io/s/sandpack-project-forked-y5loeq](https://codesandbox.io/s/sandpack-project-forked-y5loeq?file=/App.js)

In my example:
1. I generate a list of 100 empty rows that display loading indicators.
2. I preload the data at the end at index 99 and call scrollToIndex to scroll to it.
3. The rangeChanged property calls an async loader that loads the rows in the overscan index range between 96 and 99).
4. Note that the scroll position is still on row 99.
5. The "overscanned" rows at index 96, 97, and 98 get loaded, rendered, and measured.
6. The issue is that the scroll position was at row index 99, but it jumps up quite a bit to index 95 for some reason.

**To Reproduce**
1. Go to the sandbox URL
2. Wait 1 second to see the jump to row 99 (working correctly).
3. Wait 3 seconds for simulated load on overscan rows and note the scroll jump away from row 99 to row 95.
5. Refresh example output to reproduce issue again.

**Expected behavior**
I expect the scroll position to be maintain at the same row index even though overscan rows are being measured before.

The issue does not exist when rows are changing heights otherwise or when the overscan is happening for indexes below the current position.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1
 - Browser: Safari 16.2

**Comment by petyosi** [comment]
That's somewhat expected, and as far as I can tell, unsolvable in a reliable way. The list has no knowledge or understanding of the loading mechanism you have, nor can determine what "the correct" location would be.
