### ISSUE TITLE
Compatability with antd Select

### ISSUE THREAD

**Issue by Sajdini** [petyosi/react-virtuoso#825]
Hi,
I cannot combine it with antd Select component. When i put only Select.Option in itemContent, Select (in this case the parent element) recognizes virtuoso as a single Select.Option. If i put the whole Select component in itemContent, it renders multiple Selects, equal to the data length.

I’d really  appreciate if i get some instructions to work around this

**Comment by petyosi** [comment]
I don't provide free support through Github issues. If you need help, support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
