### ISSUE TITLE
Feature request: Slow down the speed of ScrollToIndex  

### ISSUE THREAD

**Issue by sthirunavukarasu** [petyosi/react-virtuoso#829]
I got a new requirement for my project with some time limit to reach out to the specific item of the list using ScrollToIndex property.

 Is there any way to slow down or increase the speed of the scroll index like the example link I have mentioned here
1. http://jsfiddle.net/forestrf/tPQSv/139/
2. https://codesandbox.io/s/react-window-animated-scroll-to-forked-pj0y3q?file=/src/index.js
3. https://stackoverflow.com/questions/64180685/how-to-slow-down-scroll-to-top-speed#:~:text=you%20may%20need%20to%20remove,time%20to%20scroll%20to%20top.

**Comment by petyosi** [comment]
I don't provide free support through Github issues. If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
