### ISSUE TITLE
logLevel prop doesn't exist

### ISSUE THREAD

**Issue by YassienW** [petyosi/react-virtuoso#842]
According to the documentation [here](https://virtuoso.dev/troubleshooting#list-is-jumping-around-or-misbehaving), i should be able to set a `logLevel` prop in order to debug the library. This prop does not exist according to typescript, and setting it doesn't log anything in console. Is the documentation incorrect or am i missing something?

**Comment by petyosi** [comment]
You're not missing anything, I forgot to include the prop in the interface.
