### ISSUE TITLE
Feature request/question?

### ISSUE THREAD

**Issue by mambans** [petyosi/react-virtuoso#845]
Hello, I'm curious if there are anyway of creating a footer for each group in Grouped mode.

If I just append a "footer item" to the list it well get overwritten when any new items are added above it in the list. So for example if I have an input at the bottom of each group and the groups count changes, the input will get over/rewritten and lose its text.

**Comment by petyosi** [comment]
No, this is not supported. If you need this feature, you can sponsor its development or submit a PR.

**Comment by mambans** [comment]
Oke, thanks.
