### ISSUE TITLE
Question: Is it possible to set a variable height?

### ISSUE THREAD

**Issue by haiquangtran** [petyosi/react-virtuoso#85]
Is there a way to set a variable height on the Virtuoso List? 

I have a screen with multiple cards. My use case is that some of my cards have Collapse components (in Material UI) to it which have a slightly larger height, while others do not have collapse components. When I let Virtuoso list set the height for me, it has some unwanted behavior when expanding my card where the child offsetHeight causes the view to scroll  to the bottom of the expanded card view (which is what I do not want). By setting a fixed height, I was able to make it the correct functionality I want, however, I need to cater for scenarios where some card heights are larger than others.

I was thinking something along the lines of this:
```typescript
 const getItemHeight = (index: number) => {
   // random condition
   return index % 2 === 0 ? 255 : 155;
  };
```
```typescript
 <Virtuoso
        style={{ width: '100%', height: '100vh' }}
        totalCount={100}
        // Generate variable heights
itemHeight={index => getItemHeight(index)}
        item={index => GenerateItem(index)}
      />
```

Is this possible?

**Comment by petyosi** [comment]
The whole point of the component is not to deal with height settings. Can you replicate the problem you describe? I would like to understand what's happening better. You can use the "edit in stackblitz" button from [the site](https://virtuoso.dev/hello/).

**Comment by haiquangtran** [comment]
Please see the following example: https://stackblitz.com/edit/react-rnfywu?file=example.js.

You can replicate my issue by scrolling down then all the way to the top, then pressing the "Test" button.

**Comment by petyosi** [comment]
@haiquangtran - thanks, this seems like a bug I have introduced recently to compensations for scrolling up. I need to investigate this further.
