### ISSUE TITLE
[BUG]TS2314: Generic type 'ItemProps' requires 1 type argument(s).

### ISSUE THREAD

**Issue by wibed** [petyosi/react-virtuoso#856]
i build for production on linux and receive:
`TS2314: Generic type 'ItemProps' requires 1 type argument(s).`

but when i add a type it tells me `ItemProps is not generic`

which puts me in a loop so to speak

**Comment by petyosi** [comment]
Follow the issue template. I can't help you like this.

**Comment by wibed** [comment]
@petyosi 

it seems the type has been updated to a generic type.
therefor the error.

**Comment by wibed** [comment]
i had locally running a later version of react-virtuoso then on my deployment.
thus the confusion.
