### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by grandleo** [petyosi/react-virtuoso#857]
Good afternoon. I have this problem, I use the same table on different pages with different content widths. I can’t set the column width because I don’t know what content will be initially.

Here is the table script - https://codesandbox.io/s/sandpack-project-forked-8pfnog?file=/data.js

That's what I'm talking about - https://skr.sh/vImJufSqT45

Can the library know the widest part of the column initially?

**Comment by petyosi** [comment]
No, no way to do that.
