### ISSUE TITLE
[BUG] Item doesn't re-render when using `Set` and value changes

### ISSUE THREAD

**Issue by scottwarren** [petyosi/react-virtuoso#860]
**Describe the bug**

If there are external values that use Sets (even if passed into the context, and used to generate an item's key) that should cause the item to re-render the item doesn't re-render, even if the item key includes them

**Reproduction**
Use https://codesandbox.io/ to illustrate the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

https://codesandbox.io/s/sandpack-project-forked-zty8fu?file=/App.js

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sandbox
2. Click on an item to select it

**Expected behaviour**

Item should become selected (blue border) but only happens when the next re-render of the item happens (e.g. scrolling)

**Screenshots**

![2023-03-13 16 30 18](https://user-images.githubusercontent.com/2718494/224731993-e77ee76e-5ad8-4d5c-97fa-d71919085792.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome

**Additional context**

**Comment by scottwarren** [comment]
Have changed to use an array instead of a set to represent the selectedItems in the Codesandbox and it appears to work as expected, so I assume it's around the set itself

**Comment by scottwarren** [comment]
Example using an array instead of a Set: https://codesandbox.io/s/sandpack-project-forked-ml0bd0?file=/App.js

**Comment by scottwarren** [comment]
Going to close because I think the solution is to not use Sets

**Comment by petyosi** [comment]
The array example creates a new array. The set one mutates the existing set object. This won't work in React in general.
