### ISSUE TITLE
Example in documentation for using MUI leads to losing scrollbar position

### ISSUE THREAD

**Issue by timrae** [petyosi/react-virtuoso#866]
**Describe the bug**
This is more of a shortcoming in the documentation than a bug per se

**Reproduction**
The example code on the [main documentation](https://virtuoso.dev/mui-table-virtual-scroll/) and also the example code on the [MUI website](https://github.com/mui/material-ui/blob/v5.11.14/docs/data/material/components/table/ReactVirtualizedTable.js) are using inline functions for the components.

However in [another part of the docs](https://virtuoso.dev/customize-structure/) (buried deep in the very last page) you say:

> If you pass the components inline and combine that with useState, each re-render will pass a fresh instance component, causing unnecessary unmounting and remounting. Don't do this...

Actually it's not just a performance problem... The sample code given in the MUI section leads to the scrollbar position getting lost when you call `setState()`, which is a rather annoying bug that took me a whole day of work to hunt down.

Here's a [sandbox showing the problem](https://codesandbox.io/s/sandpack-project-forked-exhl0i?file=/App.js) with minimal changes to the sample code from the docs. If you scroll down and double click on an item then the scroll position jumps up to the top unexpectedly.

Here's a [sandbox showing how to fix the problem](https://codesandbox.io/s/sandpack-project-forked-5b7zti?file=/App.js) which I'd propose you might like to use as a basis for some changes to the docs, to avoid unnecessary banging of user heads on walls.

**Expected behavior**
If using inline functions is not recommended (due to incompatibility with useState), then I'd expect all the example code to avoid doing so.

**Comment by petyosi** [comment]
@timrae thanks for the time - this is one step short of a PR I would gladly accept. I've been in the process of fixing the inline components in the docs to avoid the pitfall, but this is not done yet. I will take your code for a change. 

Question - you point out that the example on the MUI website has the same problem, but this is not the case, as far as I can see. The `VirtuosoTableComponents` are defined outside of the `ReactVirtualizedTable`. What am I missing?

**Comment by timrae** [comment]
Great thanks for that :)
You're right, the code on the MUI website doesn't have the problem, it was a long day ‼️
