### ISSUE TITLE
Render item out of sync when totalCount gets updated

### ISSUE THREAD

**Issue by iJimmyWei** [petyosi/react-virtuoso#87]
Hi,

**Problem**
When the `totalCount` prop gets changed, it seems like the item render is always one step behind before it catches up with the actual index count.

For instance, if I add an item onto my list of 5 items, `totalCount` gets immediately changed to 6, however the items that are rendered by Virtuoso still render up to the 5th item (i.e index of 4).

The next render afterwards will catch back up and render items up to the 6th item (i.e index of 5).

**Why is this important?**
This is an issue because if you're removing an item, or switching data sets without `Virtuoso` having done a full render, it'll attempt to access an index that doesn't exist on that array. Consequently, your app will crash from that.

**Steps to reproduce**
https://stackblitz.com/edit/react-vgunct-yqp9hg?file=example.js

1. Click on example above, then enable console viewing
2. Click on "add item"/"remove item"
3. `totalCount` gets incremented, but notice how the index is still behind
4. In the next render after, notice that the index has now catched up to the `totalCount`

![image](https://user-images.githubusercontent.com/46089773/77526314-4aebe980-6e82-11ea-9288-625189d977b6.png)

**Comment by toonvd** [comment]
Hi

This is still an issue when totalcount goes over 14:

https://stackblitz.com/edit/react-vgunct-yqp9hg
