### ISSUE TITLE
[BUG] fixedHeaderContent flickering in Safari desktop

### ISSUE THREAD

**Issue by DmitryBara** [petyosi/react-virtuoso#872]
Reproduce:
https://codesandbox.io/s/sandpack-project-forked-wtr54j?file=/App.js

Description:
`fixedHeaderContent` flickering in Safari desktop. Chrome working good.

My environment:
Mac OS Monterey 12.6.3
Safari Version 15.6.1 (17613.3.9.1.16)

Video describing the bug:
https://user-images.githubusercontent.com/64595561/229040087-c6a6f60a-6c11-4b66-818c-633a9704ab3b.mp4

**Comment by petyosi** [comment]
I remember a similar bug reported that got resolved by safari at some point. I am on Ventura, with Safari 16.4, and the sandbox seems stable. 

There should not be anything on the component side that can cause such flickering - the header does not get remounted, and there are no props being touched. As you can see, it works as expected in Chrome. 

Let me know if you discover something more.
