### ISSUE TITLE
[BUG]scroll make items rerender

### ISSUE THREAD

**Issue by liangxiwei** [petyosi/react-virtuoso#873]
**Describe the bug**
the List set outcontainer in customScrollParenthas, only 2 items, and it will rerender when scroll.

**Reproduction**
maybe no need

**debug info**
the liststate will create the new one when scroll.and the 
```const listState = useEmitterValue('listState'); will rerender because the listState is an object```

maybe use !deepEqual to insteadof equal symbol "!==" in useEmitterValue method

**Comment by petyosi** [comment]
I'm afraid that this report makes no sense to me. Follow the bug template to make it actionable. I will reopen this issue once there's something I can comprehend.

**Comment by aleclarson** [comment]
I'm looking at the same issue, but the `listState` appears to be stable, contrary to what @liangxiwei suggested.

- `react-virtuoso 4.12.3`
- `react 19.0.0` (with react-compiler)

```tsx
<Virtuoso
  className="flex-1"
  useWindowScroll
  data={items}
  endReached={fetchNextPage}
  computeItemKey={(_, item) => item.id}
  itemContent={(_, item) => (
    <Item item={item} />
  )}
  components={{
    EmptyPlaceholder,
    Footer,
    List,
  }}
/>
```

**Comment by petyosi** [comment]
That's expected. The Liststate is supposed to change when scrolling.

**Comment by aleclarson** [comment]
Well the strange thing is none of its data appeared to have changed, but a new `listState` object was created nonetheless.

**Comment by petyosi** [comment]
@aleclarson Not sure what you're seeing, here's how the `listState` changes in a hello world example:

<img width="441" alt="Image" src="https://github.com/user-attachments/assets/2efa5301-7894-4e9c-8bf1-3279b719b508" />

In general, it should refresh when new items appear or get removed. 

If you have a potential concern about performance, can you please make a sandbox repro? I will take a look.

**Comment by aleclarson** [comment]
Here's a reproduction:
https://stackblitz.com/edit/vitejs-vite-6xxbrxfd?file=src%2FApp.tsx,src%2Fmain.tsx&terminal=dev

**Comment by aleclarson** [comment]
The `List` component is being re-rendered many times while scrolling near the end of the content. Notably, no items are being added or removed as this happens, as the content isn't long enough to trigger such an event.

While it's proven difficult to reproduce in a minimal example, I can verify within my private app that the `listState` is being repeatedly recreated during the excessive rerendering period. I wonder if there shouldn't be a custom comparator used on this line:
https://github.com/petyosi/react-virtuoso/blob/7a80ea20b14fde47534a997558e80dceaaa0d30f/src/listStateSystem.ts#L327

**Comment by petyosi** [comment]
@aleclarson recalculating the state is an expensive operation. There are several check that *should allow recalculation* only when the current one does not satisfy the conditions (e.g. the rendered items no longer cover the visible area). If for some reason those checks  are not working (which I guess might happen in your project), then I do want to have a reproduction of some sort so that I can actually address the root problem rather than patching the symptom. 

If you're concerned about sharing code publicly, you can contact me with more details at petyo@virtuoso.dev.
