### ISSUE TITLE
[BUG] Text input in th, used as react-table filter, lose focust after change

### ISSUE THREAD

**Issue by aleks-devel** [petyosi/react-virtuoso#876]
**Describe the bug**
Text input in th, used as react-table filter

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-55gjp4

**To Reproduce**
1. Create a basic react-table
2. Enable useFilters plugin
3. Add text input field to th to filter content
4. Try to write something
5. The text field immediately loses focus when the first character is entered.
6. And, in fact, in my project, when you enter, the table is scrolled approximately to the middle. But I couldn't replicate this error in codesanbox

**Expected behavior**
You can write anything in the text field, without any problems, and the tables will have filtered rows

**Desktop (please complete the following information):**
 - OS: Fedora 37.
 - Browser - Chrome 111.0

**Comment by petyosi** [comment]
This is because of the inline components - [check this example](https://virtuoso.dev/mui-table-virtual-scroll/) for explanations and recommended way. I think that there are several similar closed issues, too.
