### ISSUE TITLE
Using fixedHeaderContent with rgba => background color (thead => tr => th

### ISSUE THREAD

**Issue by polyakh** [petyosi/react-virtuoso#879]
When we create a `fixedHeaderContent` component using an `rgba` bg-color for all of the table header elements, we may encounter a problem where the table body elements appear below the header when scroling.

I attempted to convert an `rgba` color to hexadecimal format, but I ended up with an incorrect [color.](url)
[Example:](https://codesandbox.io/s/sandpack-project-forked-cucn2t?file=/App.js:255-273)
Thank you so much.

@petyosi

**Comment by petyosi** [comment]
That's intentional across both the table and the lists - it allows things like fixed header "pills" to be done. 

I am monitoring the repository closely, so there's no need to tag me. If you are looking for further attention and support from me, you can sponsor the project.
