### ISSUE TITLE
Property `item` of Virtuoso doesn't get called

### ISSUE THREAD

**Issue by mrdivyansh** [petyosi/react-virtuoso#88]
Property `item` of Virtuoso doesn't get called further if the first iteration returns null/undefined/<div />.

I am not sure whether it's a feature or bug. However, it sounds like a bug to me.

[Demo](https://stackblitz.com/edit/react-kn82nn?file=example.js)

**Comment by petyosi** [comment]
@mrdivyansh This won't work for multiple reasons (see #35 ) - if you have empty items, you should filter them before passing to the component.
