### ISSUE TITLE
Previous page Displaying the List Lost Scroll Position[BUG]

### ISSUE THREAD

**Issue by davie1989** [petyosi/react-virtuoso#882]
**Describe the bug**
Hello, I like this library. However, there is one feature it is lacking and I think the developer doesn't seem to care about it despite it's importance. And that is the ability to maintain scroll position when you click on an item on a list that redirects you to another page.

**To Reproduce**
For example, I have page A displaying a large list  with `useWindowScroll={true}`. When I click on an item on the list to navigate to page B, upon coming back, page A losses it's previous scroll position.

If this feature can be added, it would make the props `useWindowScroll={true}` very useful and the go-to library for cases like this.

**Expected behavior**
Usually, the most usefulness of `useWindowScroll={true}`  is for things like news feed and the likes. Imagine being on Twitter and you scrolled to a certain tweet and then you clicked on any avatar to visit a user profile and then upon coming back, the tweet feed starts from the very beginning again.

**Comment by petyosi** [comment]
What you describe is doable with the current API. In fact, I have integrated that in several cases. The integration depends on the routing solution used in the app. Unless I am mistaken, there's no universal way for this feature to work on a component level. 

I would also like to point out that your tone feels very passive-aggressive. This is an open-source project. If something is missing from it, you can fork the project and do it yourself, or you can sponsor it, so that "the developer who does not seem to care" can spend some time on it.

**Comment by davie1989** [comment]
> What you describe is doable with the current API. In fact, I have integrated that in several cases. The integration depends on the routing solution used in the app. Unless I am mistaken, there's no universal way for this feature to work on a component level.
> 
> I would also like to point out that your tone feels very passive-aggressive. This is an open-source project. If something is missing from it, you can fork the project and do it yourself, or you can sponsor it, so that "the developer who does not seem to care" can spend some time on it.

I spoke that way because you know a lot of people are currently having such issue with the library. And most of them seem to use a hacky way to go around it which is not efficient. 

I would also like to ask why such feature should not work out of the box at component level. At least, that is how most virtualization library works. And you made mention that you have integrated this type of thing, well, it seems you alone knows how to do that with the library you created.

Also, concerning forking the library and adding the functionality, there will be no need as I started designing mine to cover this use case and more.
