### ISSUE TITLE
[BUG] In Some Browser Without JavaScript operator: Spread syntax (...) Cannot run!

### ISSUE THREAD

**Issue by hunter524** [petyosi/react-virtuoso#887]
In Some Browser Without JavaScript operator: Spread syntax (...), Cannot Run!
We should Recompile this project in node_modules again to transform this operator. Waste a lot time!

Such as chrome  (55.0.2883.91) in Android Device with OS Version Android 7.1.2!

vite.config.ts ,target: ['es2020', 'edge88', 'firefox78', 'chrome79', 'safari14'], can support more browser direct ?

**Comment by petyosi** [comment]
I have no resources to test and maintain browser compatibility with browsers from 2016. If you want to support them (and the library works there, which I don't know), your option is to transpile the library - this is, in fact, the right thing to do, as other people might not need that support so they can opt-out for the modern syntax, saving 1-2kb.

Alternatively, you may look into using version@3 which was transpiled using a different tool, it might work for you too.
