### ISSUE TITLE
[BUG] Scroll To Bottom Doesn't work for me, even on the demo documentation website

### ISSUE THREAD

**Issue by ljs19923** [petyosi/react-virtuoso#890]
https://virtuoso.dev/scroll-to-index/

I'm not able to see the last block "1000" when I scroll to 1000 with or without animation, to the end
So impossible to scroll to the bottom

<img width="475" alt="Screen Shot 2023-05-01 at 17 03 41" src="https://user-images.githubusercontent.com/5727223/235432557-0bd5291b-68e8-4e42-83df-c2dd1495f514.png">

Thanks a lot

**Comment by ljs19923** [comment]
My bad. This works

virtuoso.current.scrollToIndex({
        index: messages.length,
        align: "end",
        behavior: animated ? "smooth" : "auto",
      });

**Comment by ljs19923** [comment]
In fact, sometimes it doesnt work totally.. some pixels are missing to go to the bottom :/

**Comment by petyosi** [comment]
This example needs some sizing love, but the feature I believe works well. There's a double scroller - one for the iframe and another one for the virtuoso list itself. [Opening it in a sandbox](https://codesandbox.io/s/320guo) works, unless I am missing something.

**Comment by trey-wallis** [comment]
@petyosi I am getting the same behavior in my app. The last row is not put into view. I am using `v.4.3.8`. I tried the sandbox link that you posted above and that has the same behavior as well. I am using a Chromium-based browser.

**Comment by trey-wallis** [comment]
I also tried using a popup window. If I am scrolled to the very top, it does not scroll to the very bottom.

<img width="300" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/40307803/42d6791b-a3ef-4ec9-aa5c-b0cd0bb85291">

**Comment by petyosi** [comment]
Can you record a video? Ensure that the problem is not due to the double scroller being present.

**Comment by trey-wallis** [comment]
Yes, there is a double scroller. I didn't notice that. So the example should work then, assuming that the double scroller wasn't present?

In appears in my app, I am having the issue when is no double scroller. Here is a video.

The `New Row` button will add a new row. This is the hook I'm using. I have checked the table for `margin` values and I have none.

```javascript
	const tableRef = React.useRef<VirtuosoHandle>(null);

	const didRowsChange = useCompare(bodyRows.length);

	/**
	 * Scrolls to the bottom of the page when the "New Row" button is pressed
	 */
	React.useEffect(() => {
		if (didRowsChange) {
			tableRef.current?.scrollToIndex({
				index: bodyRows.length - 1,
				align: "end",
			});
		}
	}, [didRowsChange, bodyRows.length]);
```

My table has a fixed header, a fixed footer, and `border-collapse: separate`. I can create a sandbox if that would be helpful.


https://github.com/petyosi/react-virtuoso/assets/40307803/d9b25287-c062-40d3-aa5b-fc5a7e1935f6

**Comment by trey-wallis** [comment]
Okay. Here is a reproduction of the issue. https://codesandbox.io/s/scroll-to-bottom-bug-mk33xi?file=/src/App.tsx:3112-3184. 

It appears that the `padding: 0` on the body `td` is the issue. Once I remove that, it scrolls to the bottom.

**Comment by petyosi** [comment]
@trey-wallis the problem you experience is not related to the styling, but to the timing of the scroll to index call. It happens before the internal row count / size calculations and scrolls with one row less. 

The list and the table expose a property called `followOutput` that does what I believe you're trying to implement. See [this version of your sandbox](https://codesandbox.io/s/react-virtuoso-scroll-bug-forked-yl4zpk?file=/src/App.tsx:1214-1299).

If you experience further problems, I may suggest that you open a separate issue, following the template. Also, review the examples in the docs website, as some of the more complex scenarios need a specific approach to work as expected.
