### ISSUE TITLE
[BUG] `VirtuosoGrid`: `React does not recognize the 'logLevel' prop on a DOM element.`

### ISSUE THREAD

**Issue by psychedelicious** [petyosi/react-virtuoso#891]
**Describe the bug**
The `logLevel` prop does not work on `VirtuosoGrid` - there is a console error, and there are no additional messages in the console.

```
Warning: React does not recognize the `logLevel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `loglevel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at VirtuosoScroller (https://5slkdt.csb.app/node_modules/react-virtuoso/dist/index.mjs:2734:79)
    at GridRoot2 (https://5slkdt.csb.app/node_modules/react-virtuoso/dist/index.mjs:3285:65)
    at eval (https://5slkdt.csb.app/node_modules/react-virtuoso/dist/index.mjs:423:22)
    at App (https://5slkdt.csb.app/App.js:38:43)
```

**To Reproduce**
1. Go to https://codesandbox.io/s/sandpack-project-forked-4oyszv?file=/App.js
2. Look in the console

**Expected behavior**
`logLevel` works

**Screenshots**
![image](https://user-images.githubusercontent.com/4822129/235432224-91db8d54-4eea-4b82-a325-1cb4523504f7.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: FF, Chrome

**Additional context**
The `Virtuoso` works with `logLevel`. Happy to have a look at this.

**Comment by petyosi** [comment]
Yeah, that's easy to fix. I did not wire that property up correctly.
