### ISSUE TITLE
[BUG] only one item rendered, using components 

### ISSUE THREAD

**Issue by wibed** [petyosi/react-virtuoso#895]
https://codesandbox.io/s/sandpack-project-forked-ndgbbu?file=/App.js

only renders one item somehow.

i expected item to wrap around any eventual itemcontent.

**Comment by psychedelicious** [comment]
You need to add `{...props}` to the `Item` component for `react-virtuoso` to know what to do with it:
```typescript
const Item = ({ children, ...props }) => {
  return <div {...props}>{children}</div>;
};
```
