### ISSUE TITLE
[BUG] Removing a group from `alignToBottom` GroupedVirtuoso leaves an empty space

### ISSUE THREAD

**Issue by beermindnor** [petyosi/react-virtuoso#896]
**Describe the bug**
When item removed. It appeared blank height item, It should move to the bottom

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-6jyqe4?file=/App.js

**Expected behavior**
Items should stick to the bottom as `alignToBottom` describe

**Screenshots**

https://user-images.githubusercontent.com/19164145/236524270-21af052d-cbdd-47ac-a64e-22a505a745fa.mov

Any comments and suggestions will be appreciated.

**Comment by petyosi** [comment]
This is not a bug in Virtuoso; your example has faulty state management logic. Here's an [updated version of it](https://codesandbox.io/s/sandpack-project-forked-y1vr9c).

**Comment by beermindnor** [comment]
> This is not a bug in Virtuoso; your example has faulty state management logic. Here's an [updated version of it](https://codesandbox.io/s/sandpack-project-forked-y1vr9c).

Thanks, This is very useful

**Comment by petyosi** [comment]
No problem - if my comment helped you, consider [sponsoring the project](https://github.com/sponsors/petyosi) - there are one-time options too. Every bit helps with the maintenance and support.

**Comment by beermindnor** [comment]
@petyosi how to solve this example? https://codesandbox.io/s/sandpack-project-forked-pnx5yy Let me know if something went wrong with the groupCounts?

**Comment by beermindnor** [comment]
> @petyosi how to solve this example? https://codesandbox.io/s/sandpack-project-forked-pnx5yy Let me know if something went wrong with the groupCounts?

Can I re-open this?

**Comment by petyosi** [comment]
I don't understand what's the problem with the example above. Can you explain?

**Comment by beermindnor** [comment]
Sure, When item removed until 2 items remain. There is blank space under the last item.

**Comment by petyosi** [comment]
Reproduction steps:
- https://codesandbox.io/s/sandpack-project-forked-pnx5yy
- Add one item so that a second group appears
- Remove item (back to one group)

Unexpected whitespace appears below the list
