### ISSUE TITLE
RenderItem not triggering when totalCount is not changing but data is

### ISSUE THREAD

**Issue by toonvd** [petyosi/react-virtuoso#90]
Hi

When having new data but the same totalCount, item generation is not triggering.
Is there a way to force the trigger?

If you open up the console https://stackblitz.com/edit/react-vrcu3a?file=example.js you can see the problem.

**Comment by toonvd** [comment]
Hi

This can also be fixed by using computeItemKey, the problem is mainly the keys not changing.

**Comment by petyosi** [comment]
Another way to fix this (and an easy one) would be to introduce a new property called data-key - changing its value to something like `Symbol()` can be used to re-render the list.
