### ISSUE TITLE
[BUG] atBottomStateChange not triggering reliably in production, but does in development

### ISSUE THREAD

**Issue by paulo2703** [petyosi/react-virtuoso#902]
First of all again, thank you for the absolute amazing library and the bug-fixing on our previous issue, reinstating chat-states works now just perfectly!

**Describe the bug**
Please refer to the attached clips. By changing the chat in the first video (i.e., changing the virtuoso set of messages and virtusoso key property) and completely refreshing the list in the 2nd clip, the atBottomStateChange should turn to true, as the last message is presented. But in production and as shown in the clips the atBottomStateChange property isn't firing correctly in production, at least most of the time. Our guess is that it has something to do with the bundling of the library but we couldn't really narrow down the cause. We are using the latest version + NextJS 12/13. 

Please find the code [here](https://github.com/paulo2703/flowui/blob/main/src/features/chats/components/chat-view/layout/virtuoso-list.tsx) - The shown log comes directly from the atBottomStateChange property without any modification.

It works perfectly in Development mode, only building the project causes the issue.

**Expected behavior**
As happening in Development mode, the atBottomStateChange should always return true, as the list bottom is shown

**Desktop (please complete the following information):**
 - OS/Browser: Happens on iOS and Chrome, so it might be related to the build and not OS-related

**Issue**

https://github.com/petyosi/react-virtuoso/assets/70726673/475e6e60-02bb-43ca-a705-38b874ee55f7

https://github.com/petyosi/react-virtuoso/assets/70726673/b467806e-9292-4f23-93bb-e0414e47236d

**Comment by petyosi** [comment]
Acknowledging the problem. Reproduced it in a production build with nextjs one of the examples. I will look into it shortly.

**Comment by kotvasili** [comment]
same happens with startReached for prepending items. Works perfectly in dev but doesn't fire in release build

**Comment by petyosi** [comment]
@kotvasili i will need a reproduction for that. The problem here is related to event firing on mount.

**Comment by petyosi** [comment]
Follow up - this seems to be specific to next.js production builds. Both CRA and Vite work reliably in production... 

I will try to reach to the next team.

**Comment by petyosi** [comment]
https://github.com/vercel/next.js/issues/49949

**Comment by kotvasili** [comment]
@petyosi from what I see repro is simple:
pick example like this - https://codesandbox.io/s/gv2fdy?file=/App.js&utm_medium=sandpack
add code to an empty next project
check dev build works as expected
build app and run prod version
startReached doesnt fire initially when top reached.

Based on your comment above it might be related to next as well

**Comment by petyosi** [comment]
Yes, it's related to next. Seems like a class of problems related to next in production.

**Comment by petyosi** [comment]
I am fairly certain that this is a bug in the SWC compiler. [Here's a playground](https://play.swc.rs/?version=1.3.58&code=H4sIAAAAAAAAA1WPwQqDMAyG7z7Ff0xhh93FPYXsLhpZoWtHlpbB6LtrtQ53KcnP1y8Jf15BFHP0o9rgoQ8Jqo57%2B2SyXlnS4Ay%2BDeBYMUYR9nofXOS2ZrqiIWpphTWKB03Bs0F3A6VCbmVR4E%2BADukQAXYGVZWp8CHcgby9FVn%2Fvln7vSE6TTgjKdgJ17bmZSs6L2Cq%2BILfpSXJbZObBWSr33cZAQAA&config=H4sIAAAAAAAAA32US5LjIAyG932KlNe9nVnMAXo3Z6AICIc0Ri4k0nF15e4jY%2BcxHTk7W59%2BCSSh77fdrjuS6%2F7svuVTfkZbCMrtXyw0ZbZnsXTgBkuuxJG79ys90oyCTQTNdFlIx7b0wE1Fv1b3LiESXN1X2xBzDNNjQofDWIDowSZWiVcHyEz%2F61dW8GsGXOqjfY%2BYwOYXxFgyMTP0ULTADlOyI4E52aJEmU9qSyTUUsywMngzFhxVnn3kiFlyPlMP1huHHhQUCziOJ9BkkktkmeR6yn0a9rCvfd%2Ba%2FEMNJ5uqZSUnnFtL5LRK1ANGYhNq1kq4wI0aLHAt7k9lDKYA15KfdUeMeaMnnwBSgWSJsh1Ai9s8gszTljq8VMYcZGR5UrjMt3bLDL0U1cQYlMrOlYHCUetmAV8dzJV12nFWvFE%2Bih4MhCCzooSmr8juoCXlaQQMCpD%2B2qBN1QLM7RVu8PlBvMAfckvWB2z1GCwftilNwx7TiwQD8AH9CwdpBeM2LrIlzuM2r9mDjAZ41aVSA89LQB4Ao0ltWT7NhjwPiWj6hPv7mlgdLrclPNjc39%2F7soffVoduQF8bXDf83N9lL%2F%2Fu7k7XLXw7eBfp71XZkl7%2BAVPL6HotBgAA). 

I pushed a fix in v4.3.7, @kotvasili @paulo2703 - please test and let me know how it works.

**Comment by kotvasili** [comment]
For me startReached works properly now. 
Thank you!

**Comment by paulo2703** [comment]
@petyosi amazing!

We also tested the startReached prop once more and had the same issue as @kotvasili, **but both are now resolved!**

Thank you for the amazing speed and support!

**Comment by petyosi** [comment]
@paulo2703 @kotvasili thank you both for the confirmation. I believe it's a good moment to plug a recommendation for a monthly project sponsorship, up to your capabilities. Those help a lot. 

Don't get me wrong, next.js is hugely popular, but it's not technically a choice I've forced on you with react-virtuoso. Or, in other words, this was not a problem in react-virtuoso or any of its direct dependencies. I could have deferred this to the swc package, where the issue might eventually be addressed, with an unknown timeline.

Investigating and solving such "fun" issues is a huge mental energy drain; I can only do it sustainably if there's enough support from the underlying commercial users of the library. 

Cheers,
