### ISSUE TITLE
[BUG] Virtuoso renders nothing between 2 box if height is unset

### ISSUE THREAD

**Issue by horprogs** [petyosi/react-virtuoso#903]
Many thanks for the library!

**Describe the bug**
By default Virtuoso renders nothing if `height` is not set. It makes it impossible to render some list in the middle of screen.
For example we have a page:

|       1 Block with content    |
|---------------------------|

|       Virtuoso renders 5 items    |
|-------------------------------|

|       2 Block with content    |
|---------------------------|

If we don't set height for Virtuoso it will render nothing, if we set `height: 100%` it will push `2 Block with content` to the bottom. I thought that setting `totalCount` or `initialItemCount` would do the job and render elements without setting height, but it doesn't work.

**Reproduction**
Please check here https://codesandbox.io/s/jovial-payne-xo09ko?file=/App.js

**To Reproduce**
Open the link and see that block with Virtuoso is not rendered between grey and green blocks.

**Expected behavior**
List should be rendered without setting height, as it's unknown

**Comment by petyosi** [comment]
How would you expect the component to create a scroller and contain its contents if it does not have a constraining height?

**Comment by horprogs** [comment]
I understand, but thought maybe `initialItemCount` could render the initial amount of rows and define the initial height.
Let's say we set `initialItemCount = 5`, it renders the list with initial height is equal to 5 rows, instead of empty.
But not sure if it's even possible. Anyways seems my case is quite rare, sorry

**Comment by petyosi** [comment]
I've seen (well, technically, not seen, but heard from) people who successfully use the `totalListHeightChanged` for similar use cases. You can give it a try. 

Closing this, it's more of a discussion I guess.
