### ISSUE TITLE
[BUG] startReached doesn't work with VirtuosoGrid if initialItemCount has passed

### ISSUE THREAD

**Issue by studentIvan** [petyosi/react-virtuoso#910]
**Describe the bug**

In the example code below everything works well

```tsx
<VirtuosoGrid
        ref={ref}
        data={items}
        overscan={0}
        className={style.categoryGrid}
        rangeChanged={rangeCallback}
        startReached={startReached}
        endReached={endReached}
        useWindowScroll
        totalCount={category.totalHits}
       //...
/>
```

But if I add

```
initialItemCount={category.hitsPerPage}
```

startReached never fire, works well for endReached though. Thanks :)

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Browser: latest chrome
 - react 18.2.0 + next.js 13.4.2
 - react-virtuoso 4.3.6 (latest)

**Comment by petyosi** [comment]
Can you test with [this branch](https://github.com/petyosi/react-virtuoso/tree/grid-enhancements)?

**Comment by studentIvan** [comment]
@petyosi thanks! Is good that you supporting the grid. I see the initialTopMostItemIndex there also. Without this feature its a bit complex to work with the endless reverse scrolling. Will test it soon.

**Comment by sydneyjodon-wk** [comment]
I ran into a similar issue with `endReached` not working if `initialItemCount` is set on `Virtuoso` ([sandbox example](https://codesandbox.io/s/react-virtuoso-endreached-with-initialitemcount-fyjhc2?file=/App.js))

**Comment by petyosi** [comment]
@sydneyjodon-wk what you have is not a valid configuration and not related to this thread. There are several threads that discuss a setup similar to yours.

**Comment by studentIvan** [comment]
@petyosi the stable branch (what is now the grid enhancement) still has this bug

**Comment by petyosi** [comment]
@studentIvan this discussion has gone through several iterations. Can you please help me by reproducing the current problem you experience in a sandbox? Thanks.
