### ISSUE TITLE
[BUG] Scroll out of control in TableVirtuoso on Chrome/Edge/Firefox

### ISSUE THREAD

**Issue by eywin** [petyosi/react-virtuoso#911]
We use TableVitruoso to render a huge grid in our system. We have a lot of columns and around 10000 rows.
A few weeks ago we started noticing a bug where if you scroll down a bit, the grid goes into freefall and scrolls to the bottom.

**It only happends if you horizontally scroll the first column out of view.**

I've recreated the bug here: [https://stackblitz.com/edit/stackblitz-starters-cub9gb?file=src%2FTableComponent.tsx](https://stackblitz.com/edit/stackblitz-starters-cub9gb?file=src%2FTableComponent.tsx)

To trigger the bug: 
- scroll a bit to the right so the **entire** "first"-column is out of view
- scroll down

I'm not sure if our way of using the TableVirtuoso component is wrong or if this simply is a bug in the component.

The bug is most porminent in Chrome in my tests (scrolls to the bottom), in Firefox it only partially scrolls out of controll (jumps down a bit then stops). I have not been able to trigger it in Safari. Tested on both Windows and Macos.

The bug is also possible to trigger on the [Mui-example](https://virtuoso.dev/mui-table-virtual-scroll/#material-ui-table-virtualized-with-table-virtuoso) in the docs. Just add a few more columns and set width to a small enough size that you can scroll the first column out of view.

Any help would be greatly appreciated!

**Comment by petyosi** [comment]
Duplicate: https://github.com/petyosi/react-virtuoso/issues/609

**Comment by eywin** [comment]
thanks!
