### ISSUE TITLE
[BUG]: changing groupCounts in GroupedVirtuoso seems to cause height calculation to mess up

### ISSUE THREAD

**Issue by genepaul** [petyosi/react-virtuoso#917]
**Describe the bug**
We have a component using GroupedVirtuoso that changes the groups based on a user input (like filtering the items). We do the same thing with Virtuoso and don't seem to have any issues, but in GroupedVirtuoso we see strangeness with the height calculation, which can cause scrolling problems in more complex components. I'm not sure if this is a usage issue, but I was able to recreate something like the situation in a codesandbox.

**Reproduction**
https://codesandbox.io/s/wizardly-maxwell-y8qvx5?file=/App.js

If you type into the input a value that reduces the number of items below the height of the list, you'll notice the list still has a scrollbar and the height is taller than the actual list of items. 

**To Reproduce**
1. Use a state value to modify the groupCounts and items that GroupedVirtuoso draws from
2. Observe that when you filter the items down to less than the height of the list, the height of the scroll window doesn't seem to update.

**Expected behavior**
When the number of items is less than the height, no scrollbar should appear.

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/66479/6c1ad9ee-ca4c-47b9-b73a-212fd384c633)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

**Comment by petyosi** [comment]
Thanks @genepaul , that's a valid issue for a common use case. Apparently reducing the group count does not trim the internal size structure correctly. There's [a workaround](https://codesandbox.io/s/vigorous-microservice-gvmkg0?file=/App.js:912-968), but it blinks. 

I will look into that.

**Comment by petyosi** [comment]
This is fixed in v4.3.9, [check the fork of the sandbox](https://codesandbox.io/s/festive-haze-9t2kx2).
