### ISSUE TITLE
[BUG] Endless Scrolling does not work on all elements on the page

### ISSUE THREAD

**Issue by apupchenko** [petyosi/react-virtuoso#919]
**Describe the bug**
After loading the first lines, lazy load stops. The use Window Scroll prop is used. You can only re-provoke by changing the size

**Reproduction**
https://codesandbox.io/s/load-bug-x3yf4t?file=/App.js

**To Reproduce**
1. Use the link 
2. Try to use the scroll

**Expected behavior**
Continue loading new rows until the user is able to use the scroll

**Additional context**
I used a template from [this page
](https://virtuoso.dev/endless-scrolling/)

**Comment by petyosi** [comment]
This is due to the data set not being big enough. For better or worse, I've designed the component to not invoke the event handlers immediately on load, as it may cause an endless, or near endless loop. 

If you use a page size of 200, the example works as expected.
