### ISSUE TITLE
When can we change scroll position manually?

### ISSUE THREAD

**Issue by lesha1201** [petyosi/react-virtuoso#92]
I need to restore scroll position manually by setting `scrollTop` to scroll container element. But everything I tried has effect of seeing first element and then jumps to certain position. Also it looks like there is code that runs asynchronously in Virtuoso so sometimes scroll doesn't restore and I don't know when I should modify `scrollTop`

Example of what I'm trying to do:
https://stackblitz.com/edit/react-kn82nn-ohhw1t

**Comment by petyosi** [comment]
Hey, 

you can use the [initial index](https://virtuoso.dev/initial-index/) property to restore the scroll state.

**Comment by lesha1201** [comment]
@petyosi `initial index` doesn't fit for my case because I need to restore scroll in exact place where user stopped scrolling. For example if user stopped between two elements I need to restore scroll to be also between two elements

**Comment by petyosi** [comment]
I see. This is not supported currently, although it can piggyback the implementation of the initial index. I am not sure how reliably that would work with different screen sizing for example - something to have in mind in such case.

If you are interested in exposing such property, I can help with directions on a PR.

**Comment by lesha1201** [comment]
I'll look into code and think about API. After that I'll write my ideas if I have free time. But this is probably going to be on weekends. Thanks anyway

Can you please point me to the code where initial index logic calls `scrollTo` or setting scroll position manually on a scroll element?

**Comment by lesha1201** [comment]
@petyosi I don't think I'll be able to implement this because it's hard for me to follow the flow of all observables so I can miss something.

This is how I imagine API:

```ts
export interface VirtuosoMethods {
  scrollToIndex(location: TScrollLocation): void
  // add method `scrollToPosition` or `scrollTo` to virtuoso ref
  scrollToPosition(options: ScrollToOptions): void
  adjustForPrependedItems(count: number): void
}
```

Usage example:

```tsx
useEffect(() => {
  const { current: virtuosoInstance } = virtuosoRef

  if (!virtuosoInstance) {
    return
  }

  virtuosoInstance.scrollToPosition({ top: 2000 })
}, [])
```

Also we can add prop `initialScrollPosition`:

```ts
export interface VirtuosoProps {
  ...
  initialScrollPosition?: { left?: number; top?: number }
  // or
  initialScrollPosition?: { x?: number; y?: number }
}
```

I think it can be implemented as `scrollToIndex` via calling `scrollTo$.next`

The difference between calling `scrollToPosition` and calling native `scrollTo` method on scroll container element is that `scollToPosition` will work when Virtuoso is probing item height

**Comment by petyosi** [comment]
Agreed, this part of the code is quite complex. I will try to get to that soon.

**Comment by petyosi** [comment]
I posted some thoughts on the problem in #168, will close this one in favor of it.
