### ISSUE TITLE
[BUG] <Virtuoso style={{overflow: 'visible'}} /> breaks

### ISSUE THREAD

**Issue by An-Huynh-Certivity** [petyosi/react-virtuoso#923]
**Description**
When setting `overflow: visible;` or `overflowY: visible` in the style prop of the `Virtuoso` component, scrolling will no longer render new items from the bottom. 

**Reproduction**
[Code Sanbox](https://codesandbox.io/s/condescending-noether-d8nsrk?file=/App.js)

**To Reproduce**
Go to any of the code examples, and set `overflow: visible;` or `overflowY: visible` in the `<Virtuoso />` style prop.

**Expected behavior**
Should render as usual.

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/100586735/1c49803f-0666-4444-b821-961f158373e7)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - PopOS (ubuntu based).
 - Browser: Firefox & Chrome

**Comment by reana-ovo** [comment]
any update?
