### ISSUE TITLE
[BUG] Fixed header with customScrollParent property

### ISSUE THREAD

**Issue by oneznamov** [petyosi/react-virtuoso#926]
**Describe the bug**
I find this in case when i use [collapsable MUI Table](https://mui.com/material-ui/react-table/#collapsible-table)(parent table) and  [Virtuoso + Mui table](https://mui.com/material-ui/react-table/#virtualized-table)(child table) as inner content of parent table. Key factor which break sticky header(it just stop being sticky) is using `customScrollParent`.

**Reproduction**
_Reproduction_ - https://codesandbox.io/s/fixed-header-bug-zkm482?file=/collaps.tsx
_Reproduction description:_ As a base for reproduction i use mui example of collapsable (`collaps.tsx`) & virualized(`demo.tsx`) tables with minimal changes. 

**To Reproduce**
1. Go to Sandbox
2. Expand row with name 'Basic Table'
3. Scroll down until table of inner header will sticky (Expected behavior)
4. Expand row with name 'Virtualized Table'
5. Scroll some down, 
6. See error ( inner table header wont be sticky)

**Expected behavior**
Header of inner table should be sticky when use Virtualized table in parent table (like Basic table in [Sandbox](https://codesandbox.io/s/fixed-header-bug-zkm482?file=/collaps.tsx)) 

**Screenshots**
Video - https://github.com/petyosi/react-virtuoso/assets/100121487/c2fe8778-6eba-40c7-b0dc-9f3d319ecb11

Broken header
<img width="1067" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/100121487/3cb1ff53-2f8c-4877-9a00-d20962ba3e50">
vs
Sticky header
<img width="914" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/100121487/90566d76-044c-4e11-b21a-5cae04f9f506">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - MacOs Ventura 13.4
 - Browser: ARC,  Version 0.107.0 (39372), Chromium Engine Version 114.0.5735.106

**Additional context**

**Comment by oneznamov** [comment]
Hello, @petyosi  i will be glad if you comment this one, or maybe can told me which way to dig to fix it.

**Comment by petyosi** [comment]
@oneznamov this seems like a fairly specific integration scenario. I am happy to prioritize it if you decide to sponsor the project. Will re-open the issue once you do so.

**Comment by Pedroor** [comment]
I had the same problem, using grouped virtuous when fixing a header with customScrollParent, what is rendered by groupContent is no longer fixed.

**Comment by mateusvini13** [comment]
Having the same problem, but it is not integration related at all. Just using a customScrollParent breaks the fixedHeader, as the sticky position is in relation to the table parent, but the table itself extends outside the view since it is not wrapping anymore.

**Comment by kachi1227** [comment]
Were any of you guys able to come up with a fix for this w/o hacking together a custom solution @Pedroor @mateusvini13? I can attest that this is not an integration issue and is fairly easy to recreate.

Understandable if you don't want to fix the issue w/o someone sponsoring it, but it may be worth documenting somewhere that users who use `GroupedVirtuoso` with the `customScrollParent` property may run into unexpected behavior @petyosi
