### ISSUE TITLE
[BUG] warning “ResizeObserver loop limit exceeded” in react-virtuoso@4.3.8 

### ISSUE THREAD

**Issue by WHF293** [petyosi/react-virtuoso#927]
use TableVirtuoso  component
Android and iOS have this error that ResizeObserver loop limit exceeded
PC does not have this issue

like this issue https://github.com/petyosi/react-virtuoso/issues/875

**Comment by petyosi** [comment]
Yes, it's a duplicate of #875, same stuff.
