### ISSUE TITLE
computeItemKey has invalid typing

### ISSUE THREAD

**Issue by lesha1201** [petyosi/react-virtuoso#93]
Currently `computeItemKey` expects number as returned type but React allows `key` to be string as well. Is it done for some reason or it should accept string as well?

Current type for `computeItemKey`

```ts
export interface VirtuosoProps {
  // ...otherPropTypes
  computeItemKey?: (index: number) => number
}
```

React type for `key`

```ts
type Key = string | number;

interface Attributes {
  key?: Key;
}
```

**Comment by petyosi** [comment]
This looks more like a mistake on my side (or the contributor) - PR welcome!
