### ISSUE TITLE
[BUG] missing 'children' prop types for TableHead and TableFoot interfaces inside TableComponents

### ISSUE THREAD

**Issue by mocantimoteidavid** [petyosi/react-virtuoso#932]
**Describe the bug**
I'm using the TableVirtuoso with it's `components` prop and I noticed that the [`TableComponents` interface](https://virtuoso.dev/api/interfaces/TableComponents/) (more specifically, the TableHead and the TableFoot interfaces there) seems to be a bit off compared to reality. 

What do I mean?

If I use the `TableHead` or the `TableFoot` components like so:
```
<TableVirtuoso
  data={...}
  totalCount={...}
  fixedHeaderContent={() => (
    <>{/* content of the header */}</>
  )}
  fixedFooterContent={() => (
    <>{/* content of the footer */}</>
  )}
  components={{
    TableHead: ({ style, children }) => <thead style={style}>{children}</thead>,
    TableFoot: ({ style, children }) => <tfoot style={style}>{children}</tfoot>,
  }}
  itemContent={<>{/* component to render each item */}</>}
  endReached={loadMore}
/>
```

It works just fine, but TypeScript complains with this error: 

```
Property 'children' does not exist on type 'Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "ref" | "style"> & { ...; }'. ts(2339)
```

Same for `TableHead` & `TableFoot`.

I find this weird because the children are really there. You even need them to be able to customise the table fully.

**Reproduction**
Here is the issue reproduced where it's using only the `TableHead`: https://codesandbox.io/s/great-booth-3znswg?file=/src/App.tsx

**Expected behaviour**
I expected the Types of [TableHead](https://virtuoso.dev/api/interfaces/TableComponents/#tablehead) and [TableFoot](https://virtuoso.dev/api/interfaces/TableComponents/#tablehead) to include the default `children` too.

**Additional context**
- I know the example I wrote above doesn't really customise the table in any way... I just simplified it to be easier to read.
- I'm more than willing to create a PR with the fix too (including a typo I found in the docs 😬)
- I also notice the console error popping up in the basic reproduction code... so I'm aware that this might be more complex than I simply imagine to just change the types 😓

**Comment by petyosi** [comment]
This might date back to the type changes in React 18. Should not be hard to fix I believe. Happy to accept a PR!

**Comment by mocantimoteidavid** [comment]
I will try to do it today! 👍 Thank you for taking the time to looking into the issue 🙂
