### ISSUE TITLE
Virtuoso for chat

### ISSUE THREAD

**Issue by kusik16** [petyosi/react-virtuoso#933]
Hello.  I want to use your library for chat.  And I want to use the grouping of groups as dates for chats, and when loading new elements up (from the server), I can get the same message dates that were in the previous pagination.  And I understood a little bit that I need to recalculate them every time, but won't the layout jump at the same time?  And I did not quite understand how I need to set the exact number of my elements?  Because in the element examples it is always greater than firstItemIndex.

**Comment by petyosi** [comment]
I don't provide free support over GitHub. If you need help from me, contact me over the email in my profile, so that we can discuss the scope of the work you need. I will give you a quote.
