### ISSUE TITLE
[BUG] VirtuosoGrid works incorrect on the wide screens (1798px and wider)

### ISSUE THREAD

**Issue by studentIvan** [petyosi/react-virtuoso#936]
**Describe the bug**
VirtuosoGrid blinks/crashes/loose items on the resolution wider than 1798px

**Reproduction**
[The codesandbox link](https://codesandbox.io/s/compassionate-wescoff-v755zj?file=/src/App.js)

**To Reproduce**
1. open codesandbox
2. click "preview in the new window"
3. set the screen width wider 1798px (e.g. 2560px resizing the browser window or with the chrome devtools "Responsive" mode
4. scroll down

**Expected behavior**
Items scrollable normally

**Videos explaining the problem**

See 1440px - works normally

https://github.com/petyosi/react-virtuoso/assets/1205208/7f68b7f3-52f1-41fe-aa57-44eb5cf9422b

Now 2560px - items jump

https://github.com/petyosi/react-virtuoso/assets/1205208/5759b24c-adf5-4277-9b14-5bdb215a0063

**Desktop:**
 - OS: MacOS
 - Browser Chrome/Safari

**Additional context**
react 18

**Comment by studentIvan** [comment]
I would test it on the grid-enhancements branch - can you create a tag so we can use it on the codesandbox?

**Comment by studentIvan** [comment]
Another or maybe related problem here - is the count of the rendered items
<img width="1777" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/1205208/effdebb7-de6f-497f-8db4-289d5886d0d9">

**Comment by studentIvan** [comment]
Update: same problem with the flex. Not related to CSS Grid.

**Comment by petyosi** [comment]
I don't think that the resolution itself breaks the grid. This has something to do with the way items are styled in this particular example - probably the fractional numbers.  

As far as I can tell, [the website example](https://codesandbox.io/s/z3k6ul?file=/App.js&utm_medium=sandpack) works as expected in that resolution. I may suggest that you start from this working version and gradually add your customization until you figure out what's causing the miscalculation. 

P.S. I see that you're sponsoring the project with a $1 per month. I appreciate the gesture, but I'm afraid I can't troubleshoot your project for such amount. If you this does not meet your expectations, cancel the sponsorship and send me a paypal account - I will refund you in full.

**Comment by studentIvan** [comment]
@petyosi sent you a email check pls
