### ISSUE TITLE
[BUG] When using firstItemIndex to create a invert chat list, strange things happened.

### ISSUE THREAD

**Issue by Porianesu** [petyosi/react-virtuoso#942]
**Describe the bug**
I create a invert list with Virtuoso, bug i find there is two problem with property 'firstItemIndex'.

1.Since this is a chat list, when a new message arrives, an item is added to the bottom of the list. In this moment,if the view port is in the middle of the list (as long as it's not at the bottom), the list will automatically scroll up a bit(Exactly the height of the new item). By not setting the firstItemIndex property, we don't have this problem, the list doesn't scroll when a new message arrives.
2.Even if i set followOutput to 'smooth' when isAtBottom is true.There is still no animation when the list is scrolled because a new message has arrived。

**Reproduction**
Use https://codesandbox.io/s/keen-chatterjee-cmzg9d?file=/src/App.tsx:606-616 to reproduct the problem

**To Reproduce**
1. Click the link above.
2. Scroll to the middle of the list, click 'Add a item to bottom' button, you will find the problem 1
3. Disabled the property 'firstItemIndex',scroll to the bottom of the list, click the button again, compare with step 1, you will find the problem 2

**Expected behavior**
For problem1, in the same situation, make the list don't scroll
For problem2, in the same situation, make the list scroll with animation

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome 114.0.5735.199 (Official Build) (64-bit)

**Comment by Porianesu** [comment]
By the way, we used Virtuoso 4.3.6

**Comment by petyosi** [comment]
Your property calculating logic is incorrect. I don't understand why you're following this approach. 

I don't provide free support and consulting over GH issues. If you need me to fix your project, you can sponsor the project.
