### ISSUE TITLE
[BUG] Focus stealing with next.js app router / SSR

### ISSUE THREAD

**Issue by cprussin** [petyosi/react-virtuoso#943]
**Describe the bug**
When using the next.js app router, with a layout.js containing an input that drives a URL search parameter which is used by a page.js to filter contents to place in a Virtuoso, Virtuoso removes focus from the input on each update.

**Reproduction**
[Codesandbox here](https://codesandbox.io/p/github/cprussin/virtuoso-issue-repro/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljw4dqqd000b2v6jao4cxtza%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljw4e91000go2v6jg87tnti1%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljw4ernl00tk2v6jezyxn7aj%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljw4ernl00tj2v6j9c1rdzxa%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljw4dqqd000b2v6jao4cxtza%2522%253A%257B%2522id%2522%253A%2522cljw4dqqd000b2v6jao4cxtza%2522%252C%2522activeTabId%2522%253A%2522cljw4ojwk01dc2v6jyg706g64%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljw4dqqc000a2v6j7prwafbw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.js%2522%252C%2522id%2522%253A%2522cljw4ojwk01dc2v6jyg706g64%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljw4ernl00tk2v6jezyxn7aj%2522%253A%257B%2522id%2522%253A%2522cljw4ernl00tk2v6jezyxn7aj%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cljw4e4ae00cz2v6jr0feu2e1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cljw4e90z00gm2v6ja5o0dl2o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljw4e90z00gm2v6ja5o0dl2o%2522%257D%252C%2522cljw4ernl00tj2v6j9c1rdzxa%2522%253A%257B%2522id%2522%253A%2522cljw4ernl00tj2v6j9c1rdzxa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljw4eagv00lg2v6jwggigx04%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljw4eagv00lg2v6jwggigx04%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Github repo here](https://github.com/cprussin/virtuoso-issue-repro)

**To Reproduce**
1. Load codesandbox (or clone repo / `npm install` / `npm start` / navigate to `localhost:3000`)
2. Type in input box
3. Notice the focus is lost on each character input

**Expected behavior**
No focus stealing

**Screenshots**
Not sure screenshots would help here but I'm happy to paste some if needed

**Additional context**
- I'm not able to reproduce the issue if I move the input from the `layout.js` to the `page.js`.
- The issue seems to go away if I wrap the `Virtuoso` component in a `<div>` (which perhaps explains the prior point).
- Virtuoso is definitely the cause of the focus being lost, because if I replace the Virtuoso component with a simple list (i.e. `<div style={{ overflowY: 'auto', ... }}>{items.map(...)}</div>`) the issue does not happen.
- I feel certain there's a more minimal reproduction here and this is a symptom of some more fundamental issue, but I don't know enough about Virtuoso's internals to have a strong hunch of where to poke, so I figured I'd start by putting in this issue in case it points to something obvious that I'm not aware of.  I'm guessing this has to do with something Virtuoso does when initializing, and that using next's app router is triggering that init code on each change since the data filtering & re-rendering happens server side instead of client side.
- I'm happy to do more investigating and contribute a fix, but like I said I figured I'd start here in case there something obvious I don't know about.

**Comment by cprussin** [comment]
FWIW I also tried the following to see if I could confirm that the issue had to do with something that runs while initializing the Virtuoso component:

```js
"use client";

import { useState } from "react";
import { Virtuoso } from "react-virtuoso";

export default () => {
  const [value, setValue] = useState("");

  return (
    <>
      <input value={value} onChange={(e) => setValue(e.target.value)} />
      <p>{value}</p>
      {value.length > 2 && (
        <Virtuoso
          style={{
            width: "400px",
            height: "200px",
            border: "1px solid black",
            marginTop: "2rem",
          }}
          data={value.split("")}
          itemContent={(index, item) => `${index}: ${item}`}
        />
      )}
    </>
  );
};
```

This did not reproduce any issue, so my hunch is that whatever it is is something specific to SSR

**Comment by petyosi** [comment]
By default, Virtuoso renders `tabindex=0` attribute to its scroller element. This enables scrolling with the keyboard. For some reason, this breaks your case. You can reproduce the same by replacing Virtuoso with:

```tsx
  <div tabindex={0}>
    Foo
  </div>
```

One possible solution is to overwrite the tab index:

```tsx
  <Virtuoso
    tabIndex={null}
```

FWIW, this seems more like an oddity of NextJS than a bug of Virtuoso. You'll probably find more help in their GH repo, given that there's a clear reproduction without Virtuoso.

**Comment by cprussin** [comment]
Ah super helpful, thanks @petyosi !
