### ISSUE TITLE
[BUG] Maximum call stack size exceeded since v4.3.11

### ISSUE THREAD

**Issue by lucassardois** [petyosi/react-virtuoso#946]
**Describe the bug**
When scrolling in a React Virtuoso it may throw the `Maximum call stack size exceeded` error. 

**Reproduction**
See https://codesandbox.io/s/gifted-silence-m4h479 for reproduction

**To Reproduce**
1. Go to the code sandbox
2. In the list on the right scroll down and up (using the scrollbar for faster scrolling) frenetically.
3. The error appears
![image](https://github.com/petyosi/react-virtuoso/assets/11078371/bc276451-6987-41dd-87d4-bf58e5ab5f50)

**Expected behavior**
No error should be throw.

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/11078371/a60a54ec-1459-4bf0-a221-81cf9af8a659)

**Desktop (please complete the following information):**
 - OS: Linux - Fedora Linux 38 (Workstation Edition) and Windows 10
 - Browser: Reproduced on Chromium Version 114.0.5735.198 (Official Build) Fedora Project (64-bit) AND various users Chrome version (I don't know exactly the version number)

**Additional context**
I don't know if it may matters but my guess is that the issue **seems to appears** when we change the overscan value. 
Indeed removing it from the sandbox and the list no longer crash. In the context of our application the `overscan` value is equal to the number of element that would be added to the list once the end of the list is reached.

**Comment by petyosi** [comment]
This seems to be some old sandbox with react-virtuoso 1.9.1 and React 17. As far as I can tell, [everything works as expected with the current versions](https://codesandbox.io/s/cranky-goodall-f67pyl?file=/src/index.js)?

**Comment by petyosi** [comment]
@lucassardois I will reopen the issue once we clarify that.

**Comment by mihkeleidast** [comment]
I'm currently investigating something very similar, we are using React 17 and react-virtuoso 4.5.0. Haven't been able to reproduce in a Codesandbox, but it definitely happens in our production app. The Virtuoso instance it happens on also has `overscan` applied, if I remove that prop, it no longer crashes. We also use it with a custom scroll parent, if that can make a difference.

I tried to debug this a bit as well. It seems there is a loop between `listStateSystem` and `sizeRangeSystem`:
1. `sizeRangeSystem` uses listBoundary to calculate visibleRange
2. `listStateSystem`  uses visibleRange to calculate list state
3. `listStateSystem` updates listBoundary
4. ... rinse and repeat

It seems to loop between to values and directions. It's not easy to read the following screenshot, but it should show the loop - every time `sizeRangeSystem` calculates visibleRange, listTop and listBottom switch between 1984/1472 and 3704/3192:
![image](https://github.com/petyosi/react-virtuoso/assets/1892091/74644abf-7665-4317-84ac-bb3fe96bf179)

Went back minor versions until 4.0, it happens with all of these minors.

**Comment by petyosi** [comment]
The loop is fine, eventually it should settle down. Can it be due to the weird `197.74...` float? You should be able to fix that by using round numbers.

**Comment by mihkeleidast** [comment]
The floats come from scrollTop etc measurements directly from DOM, it's not something I can really change. I tried rounding them, but does not seem to affect anything.

**Comment by petyosi** [comment]
I will try to use React 17 + overscan.

**Comment by mvachhar** [comment]
FWIW, we are seeing this issue as well.  I haven't been able to reproduce it in a sandbox but haven't tried very hard either.  We are also using overscan and infinite scroll, but even after all the data has been loaded, rapid scrolling up and down causes the issue.  Hopefully this confirmation helps a bit.  Glad to provide more information if you want.

**Comment by petyosi** [comment]
@mvachhar No, this does not help. A sandbox would. I suspect that it's related to React 17 and its legacy rendering.

**Comment by mvachhar** [comment]
We are on React 18, so if it is React 17 related, it would have to carry over into 18.  I have some other things to get done this coming week, but maybe I can take a closer look and get more information after that.

**Comment by MikeYermolayev** [comment]
Hello,
I'm experiencing this as well. We are using react 18.2.0 + react-virtuoso 4.6.0. 

Here is a link to updated [sandbox](https://codesandbox.io/p/sandbox/long-wood-4748mh?file=%2Fsrc%2FApp.js%3A11%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqm9dcny00063b6ecgl1he80%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqm9dcny00023b6e50q3rqbi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqm9dcny00033b6eyqgpdbi9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqm9dcny00053b6esxcz0nen%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B66.13330932543255%252C33.86669067456745%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqm9dcny00023b6e50q3rqbi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqm9dcnx00013b6eo3r873q9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqmacp6n00023b6kappj9cen%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqm9dcny00023b6e50q3rqbi%2522%252C%2522activeTabId%2522%253A%2522clqmacp6n00023b6kappj9cen%2522%257D%252C%2522clqm9dcny00053b6esxcz0nen%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqm9dcny00043b6eqw111zsx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqm9dcny00053b6esxcz0nen%2522%252C%2522activeTabId%2522%253A%2522clqm9dcny00043b6eqw111zsx%2522%257D%252C%2522clqm9dcny00033b6eyqgpdbi9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqm9dcny00033b6eyqgpdbi9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

And the video 

https://github.com/petyosi/react-virtuoso/assets/8783498/cd3a1164-6ebd-4dff-b99e-39405fd2c970

**Comment by MikeYermolayev** [comment]
Oh, seems like the issue is related to the value of `overscan` property. Does it expect pixels or amount of items? 

Documentation says `The property accepts pixel values.` so I assumed I should put there pixels. Is it correct?

**Comment by petyosi** [comment]
@MikeYermolayev - I fail to reproduce the problem in the sandbox you've posted in Chrome/mac. Notice that, as far as I can see, your setup is incorrect, though. You pass fixedItemHeight and defaultItemHeight as 20, but the items are 20 + the border size tall. 

Is there something I'm missing?

**Comment by MikeYermolayev** [comment]
@petyosi oh, missed the borders, fixed sandbox the aforementioned sandbox.

For me it can be easily reproduced when I set `overscan={200}` and manually drag scrollbar 

https://github.com/petyosi/react-virtuoso/assets/8783498/19e40884-1700-488b-a419-f15d0075571b

Tried in incognito window as well

**Comment by petyosi** [comment]
Thank you, that helped. Dragging the scrollbar fast seems to be the key here, I'm on a trackpad.

**Comment by petyosi** [comment]
Use the workaround from https://github.com/petyosi/react-virtuoso/issues/946#issuecomment-1869492230.

**Comment by mstykow** [comment]
Could we please re-open this issue until a proper fix is provided? This is a critical bug (because it can crash an application on production unexpectedly) for which a non-documented workaround is hardly a fix.

**Comment by petyosi** [comment]
@mstykow it's great that you want to help. Should I expect a PR from you? Thank you in advance!

**Comment by isair** [comment]
If we are expecting a PR doesn't this mean it's a valid issue that should be open? Who will implement the fix is moot. It does crash production apps for a non-negligible portion of users - we have analytics from over 200k accounts. We should be discussing things without passive aggression.
