### ISSUE TITLE
[BUG] VirtuosoGrid footer renders outside of the boundaries of the html tag with useWindowScroll prop

### ISSUE THREAD

**Issue by Demianeen** [petyosi/react-virtuoso#948]
**Describe the bug**
When using the `useWindowScroll` prop on the `VirtuosoGrid` component, `data-virtuoso-scroller` does not include the footer in height measurement, causing it to be pushed outside of the boundaries of the `html` tag.

**Reproduction**
[Codesandbox](https://codesandbox.io/s/kind-lovelace-w8hkwk?file=/src/App.js)

**To Reproduce**
1. Add footer to `VirtuosoGrid` component
2. Use `useWindowScroll` prop on the `VirtuosoGrid` component
3. Scroll down to the bottom
4. See footer that is pushed outside

**Expected behavior**
The footer is being included into height measurement and does not being pushed outside of the boundaries of the `html` tag.

**Screenshots**
Grid
![CleanShot 2023-07-15 at 15 10 40@2x](https://github.com/petyosi/react-virtuoso/assets/51330172/a9b3301a-9ebc-4d16-a52b-3cdcf07943bb)
List
![CleanShot 2023-07-15 at 15 12 47@2x](https://github.com/petyosi/react-virtuoso/assets/51330172/5f52a8c5-3302-4671-b05b-158c7f7533b7)

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Browser: Chrome

**Comment by petyosi** [comment]
That should be easy to fix, you can also give it a try. 

On a side note, unless I am missing something, you don't really need a footer if you use window scrolling - just put the component contents after the grid.

**Comment by Demianeen** [comment]
Thanks, @petyosi. I didn't think about that.

**Comment by engin-can** [comment]
> That should be easy to fix, you can also give it a try.
> 
> On a side note, unless I am missing something, you don't really need a footer if you use window scrolling - just put the component contents after the grid.

I tried this, it's not working, it starts flickering (re-renders?) like crazy...
@Demianeen did you have luck with this?
