### ISSUE TITLE
[BUG] MUI Tabs renders only the first Tab

### ISSUE THREAD

**Issue by Caliimon** [petyosi/react-virtuoso#949]
**Describe the bug**
Virtuoso only passes one child element to MUI Tabs component and thus only renders one Tab.

**Reproduction**
[CodeSandBox](https://codesandbox.io/s/mystifying-fermat-gcyw7k?file=/src/App.js)

**To Reproduce**
1. Create virtualized React component with Virtuoso
2. Pass MUI Tabs to 'List' component key
3. Pass MUI Tab to 'Item' component key

**Expected behavior**
All Tabs should be rendered, not just the first.
If you uncomment lines 42 - 46, wait for the List to render correctly, then comment lines 42 - 46 again, all Tabs should render correctly.

**Desktop:**
 - OS: Windows 11, Ubuntu 20.04
 - Browsers: Chrome@114.0.5735.199, Firefox@115.0.2
 - (Electron@23.0.0)

**Comment by petyosi** [comment]
The two components are not compatible with each other. You can compare what you have with the rendering of the normal virtuoso component to see why.

**Comment by Caliimon** [comment]
Thanks for your response, appreciate it! 
Is any other Virtuoso component compatible with MUI Tabs?
