### ISSUE TITLE
[BUG] restoreStateFrom not always restoring correctly

### ISSUE THREAD

**Issue by prankymat** [petyosi/react-virtuoso#951]
**Describe the bug**
The `restoreStateFrom` property doesn't always restore the scroll position correctly despite the data hasn't changed.

I followed the example in (https://github.com/petyosi/react-virtuoso/blob/master/examples/state.tsx), and created a [CodeSandbox example](https://codesandbox.io/s/gifted-raman-24hyx8?file=%2Fsrc%2FApp.tsx) to test it out. When I repeatedly click on the `Log State`, the list sometimes fails to restore the state and goes back to the start of the list.

**Reproduction**
[CodeSandbox](https://codesandbox.io/s/gifted-raman-24hyx8?file=%2Fsrc%2FApp.tsx)

**To Reproduce**
1. Scroll down in the list to an item (e.g. Item 28)
2. Click on the `Log State` button multiple times

**Expected behavior**
The list should remain the same scroll position after each click of the `Log State` button, but instead sometimes it fails to restore the scroll position and resets the scroll position to the top of the list.

**Screenshots**
![CleanShot 2023-07-19 at 16 49 02](https://github.com/petyosi/react-virtuoso/assets/2998111/fa150ac5-c3e0-4378-9843-c9a5b3b20d29)

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome, Firefox, Safari

**Additional context**
I believe the same issue also affects the [chat example](https://github.com/petyosi/react-virtuoso/blob/master/examples/chat.tsx) where repeatedly switching between chat-rooms will lose the scroll position at some point.

**Comment by petyosi** [comment]
Confirming - I managed to reproduce it on my side, though it took me a while. Thank you for the sandbox.
