### ISSUE TITLE
Height Calculation wrong when margin is used on virtualized elements

### ISSUE THREAD

**Issue by hipstersmoothie** [petyosi/react-virtuoso#952]
**Describe the bug**

When my virtualized elements use mergin to add spacing the height calculation is wrong. Notice how some foos aren't blue. blue is the className on Virtuouso.

![CleanShot 2023-07-21 at 10 52 20](https://github.com/petyosi/react-virtuoso/assets/1192452/444380ee-a22b-4ad1-a3cf-0ced11eab824)

If I switch to padding the height is correct. Notice how all foos are contained

![CleanShot 2023-07-21 at 10 52 27](https://github.com/petyosi/react-virtuoso/assets/1192452/aeed69d1-4940-42d7-ac6a-22ce402411ba)

**Reproduction**

Add margin to any virtualized element

**Expected behavior**

I can use margin or it's called out in the docs

**Comment by petyosi** [comment]
It's right there, [on the homepage](https://virtuoso.dev/#gotchas). There's other good stuff in the docs too.

**Comment by hipstersmoothie** [comment]
Sorry for missing that!
