### ISSUE TITLE
[BUG] The dragged item is not displayed outside the virtualized list

### ISSUE THREAD

**Issue by Hartaithan** [petyosi/react-virtuoso#958]
**Describe the bug**
I am trying to use dnd-kit together with react-virtuoso and everything works, except that the dragged item is not displayed outside the virtualized list

How to make the dragged item appear outside the virtualized list? High z-index on the dragged item doesn't work.

And when you start dragging an item inside a virtualized list a horizontal scroll appears, that's not good either.

**Reproduction**
Sandbox - https://codesandbox.io/s/dnd-kit-board-virtuoso-7yzcwj

**To Reproduce**
1. Go to sandbox link
2. Start dragging any item

**Expected behavior**
The dragged item should be displayed even outside the virtualized list.

**Desktop:**
 - OS: Windows.
 - Browser: Chrome

**Comment by petyosi** [comment]
An unsuccessful attempt to integrate with an arbitrary third-party library is not a bug of react-virtuoso. 

If you want me to do such integration for you, sponsor the project. Alternatively, figure it out and submit a PR / example.

**Comment by danieljmann96** [comment]
> **Describe the bug**
> I am trying to use dnd-kit together with react-virtuoso and everything works, except that the dragged item is not displayed outside the virtualized list
> 
> How to make the dragged item appear outside the virtualized list? High z-index on the dragged item doesn't work.
> 
> And when you start dragging an item inside a virtualized list a horizontal scroll appears, that's not good either.
> 
> **Reproduction**
> Sandbox - https://codesandbox.io/s/dnd-kit-board-virtuoso-7yzcwj
> 
> **To Reproduce**
> 1. Go to sandbox link
> 2. Start dragging any item
> 
> **Expected behavior**
> The dragged item should be displayed even outside the virtualized list.
> 
> **Desktop:**
>  - OS: Windows.
>  - Browser: Chrome
> 

Did you manage to fix this? Facing the same issue
