### ISSUE TITLE
[FEATURE] Able to style viewport

### ISSUE THREAD

**Issue by nadenf** [petyosi/react-virtuoso#963]
**Describe the bug**
Related to https://github.com/petyosi/react-virtuoso/issues/522.

When Virtuoso is used within Flex container it fails to scroll because the viewport height should be undefined or set to a fixed value.

It would be useful even without this issue to be able to set the style of the viewport e.g. add additional padding.

Could we allow viewPort to be a component that can be passed in to customise ?

**Comment by nadenf** [comment]
Happy to submit PR if you think it's worth it.

**Comment by petyosi** [comment]
> When Virtuoso is used within Flex container it fails to scroll 
Can you show me an example of that?

> Related to https://github.com/petyosi/react-virtuoso/issues/522.
Can you elaborate?

**Comment by joelworsham** [comment]
Absolutely think this is worth it. I need to have the layout of header, content, and footer in a flex container, but I cannot style the viewport

**Comment by Sushant-Rana** [comment]
Can we pls get this fixed , facinf the very same issue of using virtuoso under a popover and failing to render the list

**Comment by smalltalk80** [comment]
I have a similar wish for a different reason. I have a horisontal list with a Footer element. The Footer renders below the list instead of to the right. This could have been fixed by adding display:flex to the styling of the viewport but that is not possible.
