### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications. 

### ISSUE THREAD

**Issue by zebieksts** [petyosi/react-virtuoso#965]
Hi, 
I am getting a lot of '_ResizeObserver loop completed with undelivered notifications.' errors when using react-virtuoso.
Issue is same as https://github.com/petyosi/react-virtuoso/issues/254.
'RAF' fix, which you later reverted https://github.com/petyosi/react-virtuoso/commit/5475a10d873811b056d059c85fa419e764b70181 actually helps. I tried it and indeed errors went away. You mentioned that it was reverted because of scroll issues, but I have not noticed any. Long time has passed and perhaps scroll issues got fixed somehow.
Please consider re-applying 'RAF' fix. 
Another idea to consider is making RAF optional via config option. Like:
`options.useRafCallback ? requestAnimationFrame(() =>callback(element)) : callback(element);`

**Comment by petyosi** [comment]
Time heals many things, but I'm afraid this problem is not one of them. If, however, the performance with RAF is acceptable for your case, feel free to maintain a fork - the project is fairly stable, so you're unlikely to have a hard time keeping up.
