### ISSUE TITLE
Issues when filtering a source (array of objects)

### ISSUE THREAD

**Issue by toonvd** [petyosi/react-virtuoso#97]
Hi

I might be approaching this incorrectly, but I am attempting to filter list items based on a condition.
When the amount of data gets smaller, the lib tries to render too much (more keys than the totalcount).

Is my approach here wrong?
https://stackblitz.com/edit/react-mjiema

**Comment by toonvd** [comment]
Update:

The issue does not exist in v0.12.6.
This might be related to #87

**Comment by petyosi** [comment]
Looks like a bug to me. I will leave a modified version [of the example](https://stackblitz.com/edit/react-mjiema-5mhnbp?file=example.js) here for further examination.

**Comment by toonvd** [comment]
> Looks like a bug to me. I will leave a modified version [of the example](https://stackblitz.com/edit/react-mjiema-5mhnbp?file=example.js) here for further examination.

Hi, yes, I have started debugging in listEngine since it gives back an empty array after filtering.

**Comment by toonvd** [comment]
Reminder for myself to narrow it down: broke in v0.13.4
