### ISSUE TITLE
[BUG] After changing data - adding/deleting one item from the array, the table automatically re-renders.

### ISSUE THREAD

**Issue by will-yjn** [petyosi/react-virtuoso#978]
**Describe the bug**
I am using the the `TableVirtuoso` component. After changing data, say, adding or deleting one item from the array, the table automatically re-renders. And the table starts from row one.

**Expected behavior**
The view stays where the data is deleted.

**Desktop (please complete the following information):**
MacOS/Chrome

**Comment by petyosi** [comment]
The table has no concept of tracking the data item identity across data prop changes. You should be handling this by yourself.
