### ISSUE TITLE
How to use .scrollToIndex with a prepending list?

### ISSUE THREAD

**Issue by alii** [petyosi/react-virtuoso#979]
<div type='discussions-op-text'>

<a href="https://github.com/petyosi/react-virtuoso/discussions/977"><sup>Originally posted by **alii** September  8, 2023</sup></a>
It's not trivial to find out the index of an item anymore because the index changes when new messages are loaded in etc. How can we calculate what the index should be when we start with something like `10000`?

As an idea, would it be possible to have `.scrollToIndex` take a callback with each item in `data`? That way the index wouldn't need to be known but internally virtuoso could track it. Note that this would have performance implications.

```ts
// Example: scroll to message where id is `id`
virtuoso.current.scrollToIndex({
      index: m => m.id === id,
      align: 'center',
      behavior: 'auto',
});
```

</div>
<br />
<p>
Would it make sense to have this implemented? I'm implementing a "jump to id" and can't without knowing the index. Alternatively exposing the indexes when calling `handle.getState()` so you can find the right one yourself (might be faster) could also work!</p>

**Comment by petyosi** [comment]
Your problem statement does not make sense to me, I'm afraid - there's no private indexing, you have everything you need to calculate the right index. I'm also absolutely lost at your suggestions, unfortunately. 

At any case, feel free to fork and maintain the conveniences you need. The library is in fairly stable state, so you should not have troubles doing that.
