### ISSUE TITLE
[BUG] RestoreStateFrom not implemented in TableVirtuoso

### ISSUE THREAD

**Issue by ru-van-urk** [petyosi/react-virtuoso#982]
**Describe the bug**
In the api-reference (https://virtuoso.dev/table-virtuoso-api-reference/) the restoreStateFrom is mentioned but currently this is not implemented. Is there a reason for it not being implemented? This feature would perfectly fix my use-case. I can not sponsor project due to using it for a hobby project but would love to help out if you can point me in a few directions.

**Comment by petyosi** [comment]
This is a bug in the docs, indeed. 

The Virtuoso and TableVirtuoso share a common state manager, but I am not sure if there's anything more to be handled in the table component when it comes to state. You can start by finding the commit that implements it for the Virtuoso component and see what's missing in the Table. Maybe it's something very simple (a matter of exporting the API), but it needs testing. 

I will close this, as unfortunately more often than not, these feature requests end up with no response on the opener's side (hopefully this is not the case here), and the original thing kinda piles up on my personal todo list.
