### ISSUE TITLE
[BUG] RB DND + Window Scroller

### ISSUE THREAD

**Issue by max-orca** [petyosi/react-virtuoso#990]
RB DND list + Virtuouso fails
looks like items that aren't in the viewport unmount and triggers DND error:
**Invariant failed: Cannot find droppable entry with id [droppable]**  
even the doc example is not working

<img width="1073" alt="Screenshot 2023-10-03 at 14 59 37" src="https://github.com/petyosi/react-virtuoso/assets/75951146/33a0d21d-eb75-47d4-a186-76e84571b371">

**Comment by petyosi** [comment]
Yes, I'm afraid that this is the case. I will remove that example at some point, it is not helpful.  https://github.com/petyosi/react-virtuoso/issues/967.

**Comment by max-orca** [comment]
@petyosi could you please guess how to avoid it?
